carbon-design-system/ibm-products

packages/automation/config.js, packages/automation/src/Dummy/Dummy.stories.js, packages/cdai/config.js, packages/cdai/src/Dummy/Dummy.stories.js, packages/common-services/config.js, packages/common-services/src/Dummy/Dummy.stories.js, packages/security/config.js, packages/security/src/ComboButton/ComboButton.stories.js
**New**
- add `sectionTitle` in `packages/<section>/config.js`
**Changed**
- replaced hardcoded section titles with the string from the config
- moved dummy stories into dummy component folders
=> docs(storybook): add sectionTitle configs to move components easily

packages/experimental-package/src/components/PageHeader/PageHeader.stories.js, packages/experimental-package/src/components/PageHeader/PageHeaderCopy.stories.js, packages/experimental-package/src/components/PageHeader/_storybook-styles.scss
Makes all the stories for the PageHeader component scrollable, to demo the header collapse functionality.
M       packages/experimental-package/src/components/PageHeader/PageHeaderCopy.stories.js
M       packages/experimental-package/src/components/PageHeader/_storybook-styles.scss
=> Make PageHeader stories scrollable to demo header collapse

packages/core/.storybook/addon-carbon-theme/components/Panel.js, packages/experimental-package/src/components/PageHeader/PageHeader.mdx, packages/experimental-package/src/components/PageHeader/PageHeader.stories.js, packages/experimental-package/src/components/PageHeader/_storybook-styles.scss
Progresses #59
Creates a custom docs page in storybook for the PageHeader
M       packages/core/.storybook/addon-carbon-theme/components/Panel.js
A       packages/experimental-package/src/components/PageHeader/PageHeader.mdx
M       packages/experimental-package/src/components/PageHeader/_storybook-styles.scss
**New**
- Custom docs page for PageHeader
=> First pass at docs page for PageHeader component

packages/experimental-package/src/components/PageHeader/_page-header.scss
Relates to  #59
Correct -ve spacing which despite being deemed "valid" by Chrome equates to 0
=> fix: negative spacing use

packages/experimental-package/src/components/ExampleComponent/ExampleComponent.js, packages/experimental-package/src/components/PageHeader/ActionBarItem.js, packages/experimental-package/src/components/PageHeader/ActionBarItem.stories.js, packages/experimental-package/src/components/PageHeader/PageActionItem.js, packages/experimental-package/src/components/PageHeader/PageActionItem.stories.js, packages/experimental-package/src/components/PageHeader/PageHeader.stories.js
Part of  #59
Utility components PageAction and ActionBarItem simplified to wrap button. These are restricted UI types specified by the design.
removed files.
M       packages/experimental-package/src/components/ExampleComponent/ExampleComponent.js
M       packages/experimental-package/src/components/PageHeader/ActionBarItem.js
A       packages/experimental-package/src/components/PageHeader/ActionBarItem.stories.js
A       packages/experimental-package/src/components/PageHeader/PageActionItem.js
A       packages/experimental-package/src/components/PageHeader/PageActionItem.stories.js
Verified still working in the storybook. …
=> feat: header to simpler wrapped buttons

packages/experimental/src/components/EmptyState/EmptyState-test.js, packages/experimental/src/components/EmptyState/EmptyState.js, packages/experimental/src/components/EmptyState/EmptyState.mdx
Contributes to #54 
This is a follow up PR to #159 and adds more test coverage as @davidmenendez had suggested. As well as adding the other component variations to the `.mdx` file as suggested by @lee-chase.
**Changed**
`/packages/experimental/src/components/EmptyState/EmptyState.mdx`
`/packages/experimental/src/components/EmptyState/EmptyState-test.js`
`/packages/experimental/src/components/EmptyState/EmptyState.js`
Run `yarn test` to see tests.
And visit storybook doc page for `<EmptyState />` component to see the different previews/variations of this component.
=> PR for #54: Add additional tests and mdx examples

.stylelintrc.js, package.json
Allow SCSS comments so that we can generate SCSS that does not publish comments
Currently this
```scss
// stylelint-disable xxx
content: ''; /* disabled stylelint because */
```
generates
```css
content: ''; /* disabled stylelint because */
```
Where as the following does not
```scss
// stylelint-disable xxx
content: ''; // disabled stylelint because
```
=> chore: allow scss comments

lerna.json
**Changed**
Skip CI when the release step commits and pushes to the default branch
=> chore: skip CI after publish step pushes

package.json, packages/cloud-cognitive/package.json, packages/experimental/package.json, packages/security/package.json
**Changed**
Move `@carbon/rollup-plugin` private dependency to dependent packages, similarly to https://github.com/carbon-design-system/carbon/search?l=JSON&q=test-utils
=> build(rollup-config): move reference to dependents

packages/experimental/src/components/TagSet/_tag-set.scss
Contributes to #32 
Corrects styling issues with tags in an overflow/tooltip.
m  packages/experimental/src/components/TagSet/_tag-set.scss
=> fix: overflow tag styling

packages/experimental/src/components/AboutModal/index.js, packages/experimental/src/components/Tearsheet/_index.scss, packages/experimental/src/components/Tearsheet/index.js, packages/experimental/src/components/_index.scss, packages/experimental/src/components/index.js, packages/experimental/src/index.js
Publicly export PageHeader and Tearsheet components.
M       packages/experimental/src/components/index.js
=> fix: add Tearsheet and PageHeader to index.js

packages/cdai/src/components/IdeAPIKeyGeneration/_IdeAPIKeyGeneration.scss, packages/cdai/src/components/IdeCard/_IdeCard.scss, packages/cdai/src/components/IdeCreate/_ide-create.scss, packages/cdai/src/components/IdeDataTable/_IdeDataTable.scss, packages/cdai/src/components/IdeEmptyState/_IdeEmptyState.scss, packages/cdai/src/components/IdeFilter/_IdeFilter.scss, packages/cdai/src/components/IdeHTTPErrors/_IdeHTTPErrors.scss, packages/cdai/src/components/IdeHome/_IdeHome.scss, packages/cdai/src/components/IdeNavigation/_IdeNavigation.scss, packages/cdai/src/components/IdeRemove/_IdeRemove.scss, packages/cdai/src/components/IdeSaving/_IdeManualSave.scss, packages/cdai/src/components/IdeSlideOverPanel/_IdeSlideOverPanel.scss, packages/cdai/src/components/IdeTableToolbarSearch/_IdeTableToolbarSearch.scss, packages/cdai/src/globals/scss/_carbon-settings.scss
dont force consumers to have to update their webpack configuration so that the SCSS import can be resolved
=> fix: use tilde for node_module imports

packages/experimental/src/components/Tearsheet/Tearsheet.stories.js, packages/experimental/src/components/Tearsheet/TearsheetNarrow.stories.js, packages/experimental/src/components/Tearsheet/TearsheetShell.stories.js, packages/experimental/src/components/Tearsheet/TearsheetStacking.stories.js, packages/experimental/src/components/Tearsheet/TearsheetStackingNarrow.stories.js
Contributes to #183 
Simply reorganises the tearsheets in the storybook nav.
M       packages/experimental/src/components/Tearsheet/Tearsheet.stories.js
M       packages/experimental/src/components/Tearsheet/TearsheetNarrow.stories.js
M       packages/experimental/src/components/Tearsheet/TearsheetShell.stories.js
M       packages/experimental/src/components/Tearsheet/TearsheetStacking.stories.js
M       packages/experimental/src/components/Tearsheet/TearsheetStackingNarrow.stories.js
=> chore: reorg stories for tearsheets

packages/cdai/src/components/IdeNavigation/PageHeader/_IdePageHeader.scss
an extra "margin-top" rule has appeared in the move over from CDAI, this break compatibility
=> fix spacing in IdePageHeader

.prettierignore, package.json
Resolves #225 
**New**
Added `CHANGELOG.md` to `.prettierignore` - Because this is generated and updated by Lerna, I couldn't see the value in formatting with Prettier as these files should never need to be touched by anyone working on the project
=> build(Prettier): ignore CHANGELOGs from formatting

packages/automation/package.json, packages/babel-preset-ibm-cloud-cognitive/package.json, packages/cdai/package.json, packages/cli/package.json, packages/cli/src/commands/sync/packageJson.js, packages/cloud-cognitive/package.json, packages/common-services/package.json, packages/core/package.json, packages/experimental/package.json, packages/jest-config/package.json, packages/rollup-config/package.json, packages/security/package.json, packages/storybook-addon-carbon-theme/package.json
Contributes to #
Some repository links are computed wrongly and e.g. include the package subdirectory when pointing to issues or PRs.
**Changed**
- `packages/cli/src/commands/sync/packageJson.js`: use extended repository information that includes the directory instead of a concatenated string (see https://docs.npmjs.com/cli/v6/configuring-npm/package-json)
- ran `yarn sync`
=> chore(release): correct repository information in package.jsons

packages/experimental/src/components/ExportModal/ExportModal-test.js, packages/experimental/src/components/ExportModal/ExportModal.js, packages/experimental/src/components/ExportModal/ExportModal.mdx, packages/experimental/src/components/ExportModal/ExportModal.stories.js, packages/experimental/src/components/ExportModal/_export-modal.scss, packages/experimental/src/components/ExportModal/_index.scss, packages/experimental/src/components/ExportModal/_storybook-styles.scss, packages/experimental/src/components/ExportModal/index.js
Contributes to #31 
Adds the export modal
A       packages/experimental/src/components/ExportModal/ExportModal-test.js
A       packages/experimental/src/components/ExportModal/ExportModal.js
A       packages/experimental/src/components/ExportModal/ExportModal.mdx
A       packages/experimental/src/components/ExportModal/ExportModal.stories.js
A       packages/experimental/src/components/ExportModal/_export-modal.scss
A       packages/experimental/src/components/ExportModal/_index.scss
A       packages/experimental/src/components/ExportModal/_storybook-styles.scss
A       packages/experimental/src/components/ExportModal/index.js
**New**
Export modal
=> feat: export modal

packages/experimental/src/components/ImportModal/ImportModal.js
Contributes to #30 
When a file is added to the import modal the upload container will now be disabled since only one file is allowed at a time.
M       packages/experimental/src/components/ImportModal/ImportModal.js
=> fix: import continer disabled after file added in import modal

packages/experimental/src/global/styles/_carbon-settings.scss
There is an undeclared dependency on the Carbon grid package . This will move it to use the scss which is shipped in the core carbon-components project
=> Remove undeclared dependency

packages/experimental/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js, packages/experimental/src/components/PageHeader/ButtonSetWithOverflow.js, packages/experimental/src/components/PageHeader/PageHeader.js, packages/experimental/src/components/PageHeader/PageHeader.stories.js, packages/experimental/src/components/PageHeader/_page-header.scss, packages/experimental/src/components/PageHeader/_storybook-styles.scss
- Removed a number of runtime key/ref errors where ReactResizeDetector could not place a ref on a functional component.
- Moved pageActions in breadcrumb next to actionBarItems as per review
- Added a pageHeaderOffset property to allow use with a Global Header. A more elegant solution that passing an offset could be raised as a new issue.
- Added story TemplatePageHeaderWithCarbonHeader
removed files.
M       packages/experimental/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js
M       packages/experimental/src/components/PageHeader/ButtonSetWithOverflow.js
M …
=> fix: reiew updates

packages/experimental/src/components/Card/Card.js, packages/experimental/src/components/Card/Card.stories.js, packages/experimental/src/components/Card/_card.scss, packages/experimental/src/components/Card/_storybook-styles.scss
Contributes to #301
* updates to allow different media positioning (https://pages.github.ibm.com/cdai-design/pal/components/card/expressive/style#3.-media-(optional))
* adds `pictogram` option
* changes how `media` in consumed. previously assumed a url and provided an `<img />` tag for that url, but now the consumer will provide the media in component form.
M       packages/experimental/src/components/Card/Card.js
M       packages/experimental/src/components/Card/Card.stories.js
M       packages/experimental/src/components/Card/_card.scss
M       packages/experimental/src/components/Card/_storybook-styles.scss
=> fix: card updates

packages/experimental/scripts/generate/templates/DISPLAY_NAME.js
Contributes to #349
@AlexanderMelox noticed that the build was breaking it and appears to be caused by 
**Changed**
`packages/experimental/scripts/generate/templates/DISPLAY_NAME.js`
=> fix: script to generate component shell using correct prefix now

packages/experimental/src/global/js/utils/__tests__/unwrap-if-fragment.test.js, packages/experimental/src/global/js/utils/unwrap-if-fragment.js
Contributes to #356
Fixed - unwrapIfFragment failed for a single, non-fragment item.
Also added tests for unwrapIfFragment.
packages/experimental/src/global/js/utils/__tests__/unwrap-if-fragment.test.js
packages/experimental/src/global/js/utils/unwrap-if-fragment.js
=> fix: unwrap if fragment

.github/workflows/codeql.yml
Fix CodeQL GitHub Action warning per https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/troubleshooting-the-codeql-workflow#warning-git-checkout-head2-is-no-longer-necessary
=> build(codeql): fix GitHub Action warning

packages/experimental/src/components/AboutModal/_about-modal.scss
Contributes to #390
On the containing div there was an `overflow-y: auto` that was causing a spurious and unusable scrollbar to appear when the height was very small.
Removed this.
In storybook, verified that the remaining scroll and scrollbar behaviours are still good.
=> fix: remove spurious scrollbar when available height is very small

packages/experimental/src/components/Card/Card.js, packages/experimental/src/components/Card/Card.stories.js, packages/experimental/src/components/Card/_card.scss, packages/experimental/src/components/Card/_storybook-styles.scss
Contributes to #380 
handles all the feedback listed here https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/380#issuecomment-788403005
Updates to the `Card` component
Run the storybook and verify the changes align with the design feedback and doesn't break anything
=> fix: card design revisions v1

packages/experimental/src/components/SidePanel/SidePanel.js, packages/experimental/src/components/SidePanel/SidePanel.stories.js, packages/experimental/src/components/SidePanel/_side-panel.scss
Contributes to #399 
This prevents the `slideIn` prop from showing in the controls section in storybook. As this prop requires the `pageContentSelector` prop to be set as well, I have ensured that there is another story that displays this version of the component. I have also refactored the class names to follow our new guidelines.
`slideIn` is removed as a control in storybook for the SidePanel.
It no longer appears in the storybook controls for this component.
=> fix(SidePanel): remove slideIn prop from storybook, refactor classnames

packages/core/.storybook/index.scss, packages/experimental/src/components/AboutModal/AboutModal.js, packages/experimental/src/components/AboutModal/AboutModal.mdx, packages/experimental/src/components/AboutModal/AboutModal.stories.js, packages/experimental/src/components/AboutModal/_about-modal.scss
Contributes to #384
Remove the theme property and respond to Carbon theme instead
Removed theme prop, and added className prop to AboutModal. Removed scss related to theme prop. Updated stories to use classes instead to control theme.
Built, linted, examined result with Storybook.
=> Remove AboutModal theme prop and respond to Carbon theme

packages/experimental/src/components/WebTerminal/WebTerminal.stories.js
Contributes to #405 
I moved `<WebTerminal />` from `Experimental` to `Canary`.
Moved this story from `experimental` to `canary` in our storybook
Verified that this component is now inside of `canary` and there are no additional components inside `experimental` within storybook.
=> fix(WebTerminal): move from experimental to canary in storybook

packages/experimental/src/components/PageHeader/PageHeader.mdx
Contributes to #413 
Adds correct id prefix so that story previews load correctly on PageHeader docs tab.
Changed experimental to canary in `id`s
Previews are visible and load correctly again
=> fix(PageHeader): story previews show correctly again in docs

packages/experimental/package.json
core is not a dependency, and flagging it made a loop in the dependency tree causing it to build twice.
package.json in experimental
built experimental
=> chore: core is no longer a dependency of experimental

packages/security/package.json
core is not a dependency, and flagging it made a loop in the dependency tree causing it to build twice.
package.json in core
built security
=> chore: core is no longer a dependency of security

packages/experimental/src/components/SidePanel/SidePanel.js
Contributes to #432 
Allow classname to be passed to side panel component.
=> fix(SidePanel): add classname prop to side panel

packages/experimental/package.json, packages/experimental/src/__tests__/settings.test.js, packages/experimental/src/enable-all.js, packages/experimental/src/global/js/package-settings.js, packages/experimental/src/settings.js
Contributes to #462 
Experimental was outputting canary warnings during test, these have now been suppressed.
- babel config to ignore enable-all and disable-all
- settings.test to disable warnings
- enable-all to disable warnings
- package-settings to facilitate warning suppression and fix prefix update
- settings to correctly export package-settings
=> fix: canary component warnings

packages/experimental/src/components/AboutModal/AboutModal.js, packages/experimental/src/components/AboutModal/AboutModal.test.js, packages/experimental/src/components/AboutModal/_about-modal.scss
Contributes to #393
AboutModal failed an accessibility check for not labelling the dialog, which is actually behaviour inherited from ComposedModal. It turns out ComposedModal will label the dialog automatically from a `label` but not from a `title`. I don't understand the logic of that, but switching to use `label` is a simple way to resolve that accessibility issue.
AboutModal.js and .scss and .test.js
Ran all tests.
=> Fixed AboutModal accessibility test failure and re-enable test

packages/experimental/src/__tests__/settings.test.js, packages/experimental/src/enable-all.js, packages/experimental/src/global/js/package-settings.js
Contributes to #462 
Experimental was still outputting canary warnings during test, these have now been suppressed even more. Shallow copies of package-settings, such as that made by settings.js, did not inherit the proxy behaviour. I've made the silencer into a method instead, and optimised the structures a bit since it's now (hopefully) in a final form.
package-settings.js
Ran the tests.
=> fix: shallow copies of settings were losing proxy behaviour

packages/experimental/src/__tests__/index-all-disabled.test.js, packages/experimental/src/__tests__/index-all-enabled.test.js, packages/experimental/src/__tests__/index.test.js, packages/experimental/src/__tests__/settings.test.js
Contributes to #462
The index tests instantiate a stack of components (well, at the moment, only ExampleComponent, but even that has two required props) with no props to test the Canary behaviour. Missing off required props causes console errors, expected but not relevant to the tests. Suppressing these cleans up the test output a bit more.
index-all-disabled.test.js, index-all-enabled.test.js, index.test.js and settings.test.js
Ran all the tests.
=> fix: suppress console errors from required props during index tests

packages/cloud-cognitive/src/global/js/utils/__tests__/wrap-focus.test.js, packages/cloud-cognitive/src/global/js/utils/wrapFocus.js
Contributes to #434 
This will _hopefully_ fix the side panel focus trap bug that @AlexanderMelox found. Thanks @joshblack for the help 🙏 
Line [63-66 from wrapFocus](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/packages/cloud-cognitive/src/global/js/utils/wrapFocus.js#L63-L66) is trying to convert an array like node list to an array using `Array.slice.call`, but it should have been `Array.prototype.slice.call`, which can also be achieved by using the static method `Array.from`.
- Everything still functions as expected in the storybook for the side panel, however this bug has only been able to be reproduced when using the packaged version of the component.
- New tests for `wrapFocus.js` pass, `jest /utils/`
=> fix(SidePanel): should fix focus trap which is breaking the side panel

packages/cloud-cognitive/src/settings.js, packages/experimental/.babelrc.js, packages/experimental/index.js, packages/experimental/index.scss, packages/experimental/package.json, packages/experimental/scripts/import.js
Contributes to #363
Add an experimental package as a simple passthrough to ibm-cloud-cognitive
added experimental package and files within in
We're doing that right now.
=> Recreate experimental as a passthrough

packages/cloud-cognitive/src/components/EmptyStates/EmptyState.js
Contributes to #507 
Since the empty states are sharing some default props, there were some components that used them but they are not necessary. 
Removed default props not shared by all components, because they end up getting spread onto the outer most element as an html attribute.
Ran `jest /EmptyStates/` and `jest /Notifications/`, no longer any console errors.
=> fix(EmptyState): fix error logs by not having defaults for shared props

packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
Contributes to #370 
Adds pre-collapse/toggle collapse feature to PageHeader. 
Adds space to right of tags when on narrower screens
Viewed in storybook, ran tests.
=> feat: add header pre and toggle collapse features

packages/cloud-cognitive/src/components/HTTPErrors/_http-errors.scss
Contributes to #542 
When putting together the code sandbox for the HTTPErrors component I noticed that the content was not properly centered, this will fix that issue.
Add missing css properties needed to center the HTTPError content.
=> fix(HTTPErrors): fix centering issue with HTTPError content

packages/cloud-cognitive/src/components/Notifications/Notifications.test.js
Contributes to #507 
Switch to the preferred `userEvent.click` rather than `fireEvent`. I also refactored some of the tests to remove `querySelector`s in preference of `getByText`/`getByRole` when possible. I also adopted the new rendering approach for the tests based on the example component.
`Notifications.test.js`
`jest /Notifications/`
=> chore(Notifications): rework some of the notificaitons tests

.github/CODE_GUIDELINES.md, packages/cloud-cognitive/scripts/generate/templates/DISPLAY_NAME.js, packages/cloud-cognitive/src/components/AboutModal/AboutModal.js, packages/cloud-cognitive/src/components/ExampleComponent/ExampleComponent.js, packages/cloud-cognitive/src/components/_Canary/Canary.js
Contributes to #393
`cx({ [className]: className })` turns out to be a tadge unnecessary, so `cx(blockClass, className, ...)` is simpler and cleaner.
CLI, ExampleComponent, AboutModal, and Canary
Ran build and tests.
=> Update code guidelines to simpler handling of className

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss, packages/cloud-cognitive/src/components/SidePanel/utils.js
Contributes to #490 
This preps the side panel for review. Restructured class names usage based on our guidelines, sass updates (for `import-once`), forward ref capability added, tests to ensure props spreading and passing a ref work.
`SidePanel.js`
`utils.js`
Everything still works in storybook and all tests for this component pass `jest /SidePanel/`
=> chore(SidePanel): update per review guidance to prep for review

packages/cloud-cognitive/scripts/generate/templates/_STYLE_NAME.scss, packages/cloud-cognitive/src/components/AboutModal/_about-modal.scss, packages/cloud-cognitive/src/components/ExampleComponent/_example-component.scss, packages/cloud-cognitive/src/components/_Canary/_canary.scss, packages/cloud-cognitive/src/components/_index.scss, packages/core/.storybook/index.scss
There were some style oddities following our storybook build changes. This should straighten them out.
storybook master index.scss, plus some tweaks to individual style files.
Ran storybook.
=> Put styles back in order after storybook updates

README.md
Contributes to #394 
This change adds steps on how to install the package, include the styles, and how to enable canary components via config.js.
I added 3 new sections to the `README.md`. Installation, usage, and Enabling canary components
=> docs: added installation & canary usage

packages/cloud-cognitive/src/components/ActionSet/ActionSet.js, packages/cloud-cognitive/src/components/ActionSet/ActionSet.stories.js, packages/cloud-cognitive/src/components/ActionSet/ActionSet.test.js, packages/cloud-cognitive/src/components/ActionSet/_action-set.scss, packages/cloud-cognitive/src/components/ActionSet/_index.scss, packages/cloud-cognitive/src/components/ActionSet/_storybook-styles.scss, packages/cloud-cognitive/src/components/ActionSet/index.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.stories.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss, packages/cloud-cognitive/src/components/SidePanel/constants.js, packages/cloud-cognitive/src/components/SidePanel/utils.js, packages/cloud-cognitive/src/components/_index.scss
Contributes to #487
Creates a new ActionSet component based on the primary actions logic from SidePanel. This lays out action buttons, and also provides validation logic for the structured prop. I also looked through the layout logic and streamlined it a little. NB I have left most of the style rules in SidePanel, as I am not sure how many of them will be general and how many are specific to the SidePanel design: I may move some of those style rules into the ActionSet when I investigate how to use the ActionSet for the TearSheet action buttons.
SidePanel files, including tests and stories. Also created ActionSet files, including tests, and added action-set scss to main component roll-up.
Ran build, tests, and ran storybook and checked multiple configurations. I may not have checked every …
=> Create ActionSet to do action button layouts

packages/cloud-cognitive/config.js, packages/cloud-cognitive/src/__tests__/index.test.js, packages/cloud-cognitive/src/components/ActionBar/ActionBar.stories.js, packages/cloud-cognitive/src/components/EmptyStates/EmptyStates.stories.js, packages/cloud-cognitive/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/index.js, packages/cloud-cognitive/src/components/HTTPErrors/index.js, packages/cloud-cognitive/src/components/index.js, packages/cloud-cognitive/src/global/js/package-settings.js
Contributes to #487
The stories for ActionSet don't seem to belong in 'Canary', and certainly don't belong in 'Released', so this PR makes a third category 'Internal' for stories for non-public components. The stories for TearsheetShell are in there too. There may be other stories for internal-only components that could go there. It would be nice to hide this category in an externally-published storybook -- if anyone knows how to do that we can make that happen :-)
Added methods to package-settings to find out whether a component is known to the package settings at all, and updated config to return a third category for non-public components. Also tidied up exports from several components, and made sure they were getting their storybookPrefix using the right component name so they appeared …
=> Make an internal category for stories for non-public components

packages/cloud-cognitive/package.json, packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/__tests__/index-all-disabled.test.js, packages/cloud-cognitive/src/__tests__/index-all-enabled.test.js, packages/cloud-cognitive/src/__tests__/index.test.js, packages/cloud-cognitive/src/__tests__/settings.test.js, packages/cloud-cognitive/src/__tests__/styles.test.js, packages/cloud-cognitive/src/components/_index-released-only.scss, packages/cloud-cognitive/src/index-full-carbon.scss, packages/cloud-cognitive/src/index-without-carbon-released-only.scss, packages/cloud-cognitive/src/index-without-carbon.scss
Contributes to #577
Create multiple built and minimised CSS outputs with no/needed/all carbon styles included. This includes a "released only" no-carbon CSS build. Added a test as proposed by @SimonFinney in #571 for the released only no-carbon CSS output. This keeps a snapshot of the released component CSS and will be sensitive to any changes that may inadvertently be introduced there.
cloud-cognitive index.scss, export tests, package.json
Ran build, ran tests. Made a small change to _about-modal.scss and verified that it caused the tests to fail until the snapshot was updated. Reverted the change.
=> test(styles): add styles public API test

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to #594 
To adapt to height changes in the actions container, the resize detector component was added to make sure that the main content always has the correct amount of bottom padding.
`SidePanel.js`
Storybook
=> fix(SidePanel): add resize detector to adapt to new actions height

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to #64 
This adds an animation to the title divider line during the scroll animation. Previously this was a border bottom that just appears immediately once the user started scrolling. This was causing a slight jump and also appeared quite abruptly. This is now implemented through a pseudo element that changes opacity as the scroll animation is progressed.
`SidePanel.js`
Storybook
=> fix(SidePanel): add transition to divider appearing during animation

packages/cloud-cognitive/src/components/ActionSet/ActionSet.js, packages/cloud-cognitive/src/components/ActionSet/ActionSet.test.js, packages/cloud-cognitive/src/components/ActionSet/_action-set.scss, packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js
Contributes to #555
Pass any additional fields in each action object to the Button as props. This includes className and ref (with forwardRef). Any other fields are passed directly to the Button, which can consume them as props or pass them to the HTML element as HTML attributes.
Also a minor SCSS tweak to use BEM better, and complete the set of sizes.
ActionSet.js, also added tests and tweaked scss.
Ran build, tests, storybook
=> Pass additional action fields to action buttons as props or HTML attrs

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/NotificationsPanel/NotificationsPanel.js, packages/cloud-cognitive/src/components/NotificationsPanel/NotificationsPanel.test.js, packages/cloud-cognitive/src/components/NotificationsPanel/_notifications-panel.scss, packages/cloud-cognitive/src/components/_index-released-only.scss, packages/cloud-cognitive/src/global/js/package-settings.js
Contributes to #574 
Tests now are at 100%, and component has been marked as released with this PR.
css snapshot
`NotificationsPanel.js`
`NotificationsPanel.test.js`
`_notifications-panel.scss`
`_index-released-only.css`
`package-settings.js`
`jest /NotificationsPanel/ --coverage`
and verified in Storybook
*Note: I learned that testing default props that are functions you can write a test that renders the component _without_ those props passed in and target the element/s that trigger those handlers. This ensures that those default props are used. This was part of the reason function testing coverage wasn't at 100% before.
=> chore(NotificationsPanel): add tests and mark as released

packages/cloud-cognitive/src/components/ActionSet/ActionSet.js, packages/cloud-cognitive/src/components/ActionSet/ActionSet.stories.js, packages/cloud-cognitive/src/components/ActionSet/_action-set.scss, packages/cloud-cognitive/src/components/ActionSet/_storybook-styles.scss, packages/cloud-cognitive/src/components/ActionSet/actions.js, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.js, packages/experimental/package.json
Contributes to #546
The carbon ButtonSet only applies full bleed styling when placed into a modal footer, and does not have any other way to request full bleed style. So replicate the full bleed style into ActionSet to ensure the correct styles are used: heights, and alignment. Also enabled Tearsheet to request extra large buttons, and improved the stories a little.
ActionSet, also SidePanel styles (changed way button heights are set), and Tearsheet.
Ran build, ran tests, ran storybook.
=> Fix styling on ActionSet to ensure SidePanel and Tearsheet buttons match design

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.stories.js, packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.stories.js, packages/cloud-cognitive/src/components/Tearsheet/_storybook-styles.scss, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss, packages/cloud-cognitive/src/global/js/package-settings.js
Resolves #339 
Modal styles override input fields to use $field-02 over $ui-01. However, in wide Tearsheets, the main content background is set to $ui-02 to create a gray 'layer', so we need to revert the input fields to use $field-01 over this to match.
Also, mark TearsheetNarrow as released, which was accidentally missed.
Tearsheet styles and stories, plus package-settings and the global css snapshot.
Ran build, tests, storybook.
=> Ensure input fields on Tearsheets have correct colours

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.stories.js, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.test.js, packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.stories.js, packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js, packages/cloud-cognitive/src/components/Tearsheet/_storybook-styles.scss, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Resolves #546 (hopefully properly this time :-) @andrea-gm)
Add a `headerActions` prop to allow actions to be inserted into the header. Adjust some margins and padding. Fix the stories to align with the recommended design to, and rework the stories to make a more useful set of scenarios.
Tearsheet files. NB this PR changes the SCSS for released components (Tearsheet/TearsheetNarrow).
Ran build, tests, storybook. Verified that Tearsheet test coverage remains at 100%.
=> Align Tearsheet to updated design

packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js, packages/cloud-cognitive/src/global/js/utils/Wrap.js, packages/cloud-cognitive/src/global/js/utils/Wrap.test.js
Contributes to #546
Move the `DivIf` component out as a global utility component, as it may be useful more widely.
Created new component, and updated Tearsheet.
ran build, tests, storybook.
=> move DivIf out as a new global 'Wrap' component

packages/cloud-cognitive/src/components/NotificationsPanel/NotificationsPanel.js, packages/cloud-cognitive/src/components/NotificationsPanel/NotificationsPanel.test.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js
Contributes to #574 
I was able to remove some `istanbul-ignore`s after learning how to properly test animations with RTL, I also did some refactoring to cleanup side panel tests after adding a default arg value for SidePanel children in `renderSidePanel()` in  `SidePanel.test.js` (thanks @sydrosa for catching this).
`NotificationsPanel.js`
`NotificationsPanel.test.js`
`jest /NotificationsPanel/ --coverage`
`jest /SidePanel/ --coverage`
=> chore(Notifications): remove istanbul ignores, refactor side panel tests

packages/cloud-cognitive/src/components/ActionSet/ActionSet.js, packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.js, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.js, packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.js, packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js
Use Button propTypes as the basis for button-shaped array props in ActionSet, Tearsheet, ButtonSetWithOverflow. This makes a more complete set of type constraints, and is less error-prone and ensures we stay in sync with Button props if/when they change.
ActionSet, Tearsheet files, ButtonSetWithOverflow
ran build, tests, storybook
=> Use Button propTypes to creating matching prop shapes

packages/cloud-cognitive/src/global/js/utils/props-helper.js, packages/cloud-cognitive/src/global/js/utils/props-helper.test.js
Simplifies the signature of prepareProps, and makes it more general -- any sequence of objects and blocklists can be provided to merge and block as required. All existing calls and arguments work as before.
props-helpers.js and the tests
Ran tests
=> Generalise prepareProps a bit further

packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js, packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/_breadcrumb-with-overflow.scss, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
Contributes to #627 
This adds a back button on smaller viewports that replaces the breadcrumbs in the PageHeader. If no breadcrumbs are present, the bread
`BreadcrumbWithOverflow.js`
`_breadcrumb-with-overflow.scss`
`_page-header.scss`
Storybook
=> feat(PageHeader): back button to replace breadcrumbs on small viewport

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.stories.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to #691 
This PR cleans up the side panel behavior when `animateTitle={false}` is provided to the component. The subtitle text becomes fixed, as well as the action toolbar buttons if they are provided.
`SidePanel.js`
`SidePanel.stories.js`
Storybook
Verified test coverage is still at 100%
=> PR for #691: side panel animate title prop updates

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Resolves #699 
The header bottom padding was being reversed by a negative margin on the navigation, to try to bring the navigation aligned with the bottom of the header. This was fragile, and broke, perhaps by a change in Carbon. Instead, just remove the bottom padding from the header when there is a navigation item. Fixed, and should be more robust.
TearsheetShell
NB this PR changes published styles for a released component.
Storybook
=> Fix Tearsheet navigation position in header

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Resolves #700
The header action buttons should have an 8px gap. Fixed.
Tearsheet styles
NB this PR changes published styles for a released component.
Storybook
=> Fix Tearsheet header action button spacing

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Resolves #701
The header for a wide Tearsheet should have a 24px padding top and bottom, 32px left and right. A narrow Tearsheet should have 16px all round. Fixed.
Tearsheet styles
NB this PR changes published styles for a released component.
Storybook
=> Fix Tearsheet heading padding

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to #719
This PR adds a shadow to panels that do not have an overlay.
`SidePanel.js`
Storybook
=> chore(SidePanel): add shadow to panels without overlay

packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js, packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/_breadcrumb-with-overflow.scss, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
The padding above the back arrow was causing the breadcrumb row to grow in height.
The overflow button in the breadcrumb was 2 pixels taller than the specified breadcrumb size and center alignment was causing a small jump when the overflow appeared.
The breadcrumb storybook was not showing the / contained in the ::after
- Fixed page header width measurement
- Removed some breadcrumb styling from PageHeader component
- Fixed breadcrumb responsive behavior.
- In the breadcrumb storybook check following slash shown.
- In the breadcrumb storybook check the width based behaviour
- In the page header storybook check the breadcrumb responsive behaviour down to showing of back arrow.
=> fix: breadcrumb styling

packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
Contributes to #630
Adds space to the right of the actionBarItems column when there are no tags or navigation. This prevents the collapse button from covering the action bar items.
Page Header
Storybook and ci-check
=> fix: prevent collapse button over action bar items

packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss, packages/cloud-cognitive/src/components/SidePanel/_storybook-styles.scss
Contributes to #727 
Side panel now gives form fields a background color by default.
`_storybook-styles.scss`
Storybook
=> chore(SidePanel): form fields receive default background color now

packages/cloud-cognitive/src/components/ActionBar/ActionBar.js, packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.js, packages/cloud-cognitive/src/components/ButtonSetWithOverflow/_button-set-with-overflow.scss, packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
Closes #658
- Fixed subtitle to max 60% from the medium breakpoint up (as per title) and clamp at two lines.
- Addressed responsivity of pageActcions by using ButtonSetWithOverflow. To persist with the pageActions in 40% width when space is restricted causes either the page to be too wide or wrap. Neither sit well with the move into the breadcrumb row.
- Added a right alight property to the ButtonSetWithOverflow to keep the buttons on the right.
Ran tests and storybook.
=> fix: title and subtitle row responsivity

packages/security/src/ComboButton/ComboButton.js
Contributes to #749
Add a deprecation warning to ComboButton, which we'll shortly remove in favour of ButtonMenu.
ComboButton.js
Ran storybook and test.
=> Add a deprecation warning to ComboButton

packages/cloud-cognitive/src/components/ModifiedTabs/ModifiedTabs.js
ModifiedTabs is setting a deprecated prop `href` on carbon-react Tab component, and this is causing console noise during test runs. As it is only setting the prop to its default value, removing these should not make any functional difference and will help clean up the test runs.
Just ModifiedTabs.js
Ran all ModifiedTabs tests. There aren't any, so that didn't take long.
=> Don't use deprecated Tab prop href

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
Contributes to #734 
Change `onRequestClose` prop from required to not required.
`SidePanel.js`
Storybook and all tests still pass with 100% coverage
=> chore(SidePanel): remove required from onRequestClose prop

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.js, packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.stories.js, packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.test.js, packages/cloud-cognitive/src/components/_index-released-only.scss, packages/cloud-cognitive/src/global/js/package-settings.js
Contributes to #570 
Test coverage for `UserProfileImage` is now at 100% and this component will be marked as released with this PR.
`UserProfileImage.test.js`
`UserProfileImage.js`
`UserProfileImage.stories.js`
`package-settings.js`
`_index-released-only.scss`
Updated snapshot
Storybook and ensured that all tests pass with 100% coverage
`jest /UserProfileImage/ --coverage`
Great job on this one @qbi11y! 👏
=> chore(UserProfileImage): test coverage to 100 and mark as released

packages/cloud-cognitive/src/components/EmptyStates/EmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/EmptyStateContent.js, packages/cloud-cognitive/src/components/EmptyStates/EmptyStates.stories.js, packages/cloud-cognitive/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.stories.js, packages/cloud-cognitive/src/components/EmptyStates/_empty-state.scss
Contributes to #752 
I updated stories for EmptyState components so that a title / subtitle always display. I also renamed the `illustrationSize` prop to just `size` because there are typography changes when the smaller size version is used which have also been added in now too.
Empty state components and story files
Storybook
All tests still pass and coverage is still at 100%
=> fix(EmptyStates): update stories and rename size prop

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
This is directly related to #339.
We added two missing classes to the list of selectors that need to be "un-overridden" to get back to the correct look inside the wide tearsheet main area. 
Copied the list of selectors from https://github.com/carbon-design-system/carbon/blob/ce0662896cb8919f1f11b70a1f4351750b6d7e07/packages/components/src/components/modal/_modal.scss#L49-L50 to add the missing classes.
=> Fix background of pagination inside wide tearsheet

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js
Contributes to #490 
Adds an optional `onUnmount` function prop that is called after the side panel exit animation but before the panel is removed from the DOM that can be used for any necessary cleanup.
`SidePanel.js`
Storybook and updated tests
`jest /SidePanel/ --coverage`
=> feat(SidePanel): add optional onUnmount prop for cleanup

packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js
Remove use of wibble in story sample
PageHeader.stories.js
Storybook.
=> fix: remove wibble from example story

packages/cdai/src/components/IdeFilter/IdeFilter.js, packages/cdai/src/components/IdeFilter/IdeFilter.spec.js, packages/cdai/src/components/IdeImporting/IdeImporting.js, packages/cdai/src/components/IdeImporting/IdeImporting.test.js, packages/cloud-cognitive/src/components/APIKeyDownloader/APIKeyDownloader.test.js, packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.test.js
resolves #741
Clean up some of the CDAI tests, and in a couple of places adjust the component itself, to ensure the tests run cleanly with no noise in the console log.
Selected CDAI components.
Ran the tests. None of these changes should functionally affect the components themselves.
=> Ensure clear console during test runs

packages/cloud-cognitive/src/global/styles/_imported-carbon-modules.scss, packages/cloud-cognitive/src/index-without-carbon-released-only.scss, packages/cloud-cognitive/src/index-without-carbon.scss
Contributes to #839 
Separated `$imported-modules` into global partial for application team usage.
No regressions running:
- `storybook`
- `test`
=> feat(styles): export used Carbon style modules

packages/cdai/src/components/IdeSlideOverPanel/IdeSlideOverPanel.js
Contributes to #848
This fixes the CDAI `IdeSlideOverPanel.js` component. In the recent package updates, the `fallbackFocus` value needs to be provided. Previously, the story named `With state manager` was breaking, with this changed everything works as expected again.
`IdeSlideOverPanel.js`
Storybook
=> fix: add fallback selector for focus trap (CDAI Legacy IdeSlideOverPanel)

packages/cloud-cognitive/src/components/ActionSet/_action-set.scss
Contributes to #858 
This makes sure that the ActionSet buttons do not receive a `max-width` as this will cause layout issues in larger scenarios, such as Tearsheets, CreateTearsheets, and max size side panels.
`_action-set.scss`
Storybook
=> fix(ActionSet): ensure action set buttons have max width none

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
Contributes to #887 
BUG FIX: @lily-peng discovered that if a `subtitle` is _not_ provided to the side panel, the title scrolling animation breaks. Adding a default subtitle height value, when the subtitle does not exist, fixes this issue.
`SidePanel/SidePanel.js`
Storybook
=> PR for #887: fix(SidePanel): add default subtitle height value

packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.test.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js, packages/cloud-cognitive/src/components/PageHeader/PageHeaderDemo.stories.js, packages/cloud-cognitive/src/components/PageHeader/PageHeaderUtils.js, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss, packages/cloud-cognitive/src/components/PageHeader/_storybook-styles.scss
Closes #890 
Simplifies sticky scroll behaviour based on https://codepen.io/lee-chase/pen/rNyZrRm
Also makes a couple of story updates to remove modal glitch.
Replaces space below title with use of margin above available row or last row buffer.
I'd recommend turning off whitespace for diff.
PageHeader.js structure to allow breadcrumb row and navigation row to scroll, this includes scrolling off the tags when there is no navigation.
Storybook
=> feat: update page header sticky again

packages/cloud-cognitive/src/components/PageHeader/_page-header.scss, packages/cloud-cognitive/src/components/TagSet/TagSet.js
Possibly due to the weight of CSS or storybook we get some CSS load glitches. This looks at the modal shown by the page header tag set and the button set when shown in the action bar area.
- Only renders TagSet modal if required removing storybook glitch showing briefly showing the modal on 'long-values-many-items'
- Only animates opacity removing a positional artefact.
Storybook.
=> fix: page header performance glitches

packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js, packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.stories.js
Closes to #882
Simplify breadcrumb title and href access and add the option of supplying a value via title or data-title.
BreadcrumbWithOverflwo.js and story
Storybook.
=> feat: breadcrumb overflow title and href updates

packages/cloud-cognitive/src/components/HTTPErrors/HTTPErrorContent.js
Contributes to #899 
The HTTP error content component should not check if it is canary, this is used to render content and does not need to have a canary check since it is an internal component and is also never exported for end users to consume.
`HTTPErrorContent.js`
Storybook
=> fix(HTTPErrors): remove canary check on http error content component

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.test.js, packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Contributes to #773
Per design, a right-aligned influencer should sit over the action buttons instead of pushing them in. This means a right-aligned influencer is structurally different from a left-aligned influencer, so they are rendered separately.
TearsheetShell and tearsheet SCSS
Note that this PR updates styles for released components.
Ran storybook.
=> Tearsheet navigation buttons always right aligned

packages/cloud-cognitive/src/components/ComboButton/ComboButton.stories.js, packages/cloud-cognitive/src/components/index.js, packages/cloud-cognitive/src/global/js/package-settings.js, packages/core/.storybook/preview.js
Contributes to #749
We're holding off deprecating ComboButton pending the outcome of the button pattern workgroup, and publishing ButtonMenu until a design is published, but in the mean time they are slightly randomly placed in our Storybook which may cause some confusion. ComboButton we have moved into C&CS package in order to remove the dependency on the legacy/security package, but this ComboButton is still showing in legacy/security in the storybook where it clashes with the component from the legacy/security package itself! MenuButton is causing some distraction by showing in our canary list, but it's only internal (used by PageHeader) for now pending the design outcome. This PR moves both components into the 'Internal' section of C&CS on storybook.
NB this leaves ComboButton as a …
=> Move ButtonMenu and ComboButton into 'Internal' folder on Storybook

packages/cloud-cognitive/src/components/CreateTearsheet/_create-tearsheet.scss
Contributes to #923 
Removed overflow styles that are preventing scrolling, this was temporarily added to fix an issue found with the styles from Carbon's radio button
https://github.com/carbon-design-system/carbon/issues/8932
`_create-tearsheet.scss`
Storybook
=> fix(CreateTearsheet): remove overflow styles

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js, packages/cloud-cognitive/src/components/CreateTearsheet/_create-tearsheet.scss, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Closes #925 
Repair main content scroll behaviour for tearsheets. Also fix the influencers which were 1px too narrow.
Also fix the scroll behaviour on create tearsheet when the viewport is too short to display the full side nav.
Tearsheet and CreateTearsheet styles.
NB this PR changes styles for released components.
In Storybook.
=> Fix issue #925 re scrolling in tearsheets

package.json
`lerna version` does not update versions of packages in the root package.json. I do not know why this is, but it appears to be a designed and intentional behaviour. This means that you cannot list one of the monorepo packages as a dependency in the root package.json, because if you do then this version becomes stale after the next version bump takes place.
Removed jest-config-ibm-cloud-cognitive from root package.json
Ran `yarn install`
=> Remove jest config package from root package.json dependencies

packages/cloud-cognitive/src/components/Card/CardFooter.js
Card prop `action` has a prop-types declaration that looks wrong and generates warnings. I think what was meant might be `PropTypes.oneOfType([PropTypes.array, PropTypes.node])`. @davidmenendez fyi
prop-types declaration for Card prop `action`.
Ran storybook.
=> Fix proptypes one-of-type for Card

packages/cloud-cognitive/src/components/AboutModal/AboutModal.js, packages/cloud-cognitive/src/components/AboutModal/AboutModal.stories.js, packages/cloud-cognitive/src/components/AboutModal/AboutModal.test.js
closes #663 
Add a `closeIconDescription` prop to AboutModal and make it required, to ensure users provide all translatable text.
AboutModal, tests and stories.
Ran storybook.
=> feat: add closeIconDescription required prop to AboutModal

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js
Contributes to #849 
Addresses issue in side panel title animation where if the amount of scrollable area is smaller than the length of the scrolling animation, the animation would not complete (you could potentially see the initial title and collapsed title at the same time). With this change, the length of the scroll animation is shortened to avoid this issue.
_To see this bug see the second screen recording [here](https://ibm-casdesign.slack.com/archives/CQGR0HC05/p1624050878118800)_
`SidePanel.js`
=> fix(SidePanel): allow animation to complete when scroll length is short

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.stories.js, packages/cloud-cognitive/src/components/Tearsheet/_storybook-styles.scss, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
closes #977
The default 100% width was being applied to all tearsheets, and should only have applied to wide tearsheets. Fixed this, and also tidied up a couple of story oddities.
Tearsheet styles and stories.
Ran tests and storybook
=> Set correct widths for narrow tearsheets

packages/cloud-cognitive/src/components/CreateSidePanel/CreateSidePanel.stories.js, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js
Contributes to #980 
I removed the `closeIconDescription` prop from the CreateTearsheet component since the create flows do not include the close icons. I also added some `id`s that were missing in CreateSidePanel stories which were causing prop type errors in the console.
`CreateSidePanel.stories.js`
Storybook
=> chore(CreateTearsheet): remove closeIconDesc as there is no close icon

packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js
Contributes to #991 
Adds logic to prevent the bottom divider line between CreateTearsheetSection components from rendering on the last section of the last step component. See screenshot in #991 
Storybook
=> chore(CreateTearsheet): add divider line render logic

packages/core/.storybook/main.js
Contributes to #1004
This will enable us to use storybook to check for react strict mode warnings and deprecations.
storybook main.js
Ran storybook, selected SidePanel story, opened the side panel, and verified the following warning now appears in the console:
=> Enable react strict mode in storybook

packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.js, packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.stories.js
The hook pattern (`useResizeDetector`) is lighter weight than the full class object pattern (`<ResizeDetector>`) and fits better with our general hook-based component approach.
@lee-chase please check that this still works as intended
Also, the ButtonSetWithOverflow stories were not supplied the now-required `key` field, generating stacks of console errors, so I fixed that and also improved the way omitted `key` prop is handled by the component.
ButtonSetWithOverflow and stories
Storybook
=> switch ResizeDetector in ButtonSetWithOverflow to hook pattern

packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
The hook pattern (`useResizeDetector`) is lighter weight than the full class object pattern (`<ResizeDetector>`) and fits better with our general hook-based component approach.
@lee-chase please check that this still works as intended
PageHeader
Storybook
=> switch ResizeDetector in PageHeader to hook pattern

packages/cloud-cognitive/src/components/CreateTearsheet/_storybook-styles.scss
Contributes to #921
The view all toggle on the CreateTearsheet had an incorrect amount of padding/margin around it. This is fixed now, it should have a total of `1.5rem` surrounding it. I also removed some styles that were added in to fix a Carbon related issue with the RadioButton and RadioButtonGroup components that has now been fixed.
_Incorrect spacing_ (bottom margin has been removed)
`CreateTearsheet/_storybook-styles.scss`
Storybook
=> fix(CreateTearsheet): toggle spacing is correct now

packages/cloud-cognitive/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.js
Contributes to #1000 review comment from @davidmenendez 
Move shared className into it's own variable and use cx package on the elements that use the shared classname.
`CreateTearsheetNarrow.js`
Storybook
=> chore(CreateTearsheetNarrow): refactor shared classname usage

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/AboutModal/_about-modal.scss
Resolves #1035 
Align `AboutModal` copyright and legal text color with [design](https://pages.github.ibm.com/cdai-design/pal/patterns/about-modal/usage/#anatomy).
=> fix(about-modal): align copyright and legal text color with design

cspell.json, package.json, packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.stories.js, packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.test.js, packages/cloud-cognitive/src/components/Card/Card.js, packages/cloud-cognitive/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.stories.js
Add spellcheck to commit-lint and ci-check so spelling is checked before repo is updated.
Excluded CHANGELOG.md files from the spellcheck, as these are auto-updated from PR names and so may inadvertently contain spelling/grammar errors that are not the fault of subsequent submitters. Care with forming good PR names is still important, but is not enforced through the spellcheck!
Fixed a few remaining spelling issues to ensure the repo is currently clean.
Also, discovered that the commit-lint was taking a lot longer than it needed to: the lint tasks were in several cases linting the entire project folder rather than the staged files. This also meant that if errors existed in files that were not currently added for commit, the commit could still fail, wrongly, because of linter errors in …
=> Add spellcheck to commit-lint and ci-check

packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.js
Contributes to #1041 
Adds new prop type util for conditionally required props in UserProfileImage component.
Removed custom prop type validator and replaced with `.if` prop type util.
Storybook
=> chore(UserProfileImage): add prop type util for conditional props

packages/cloud-cognitive/src/components/EmptyStates/EmptyState.js
Contributes to #1043 
Adds the new prop type util for conditionally required props.
`EmptyState.js`
Storybook
=> chore(EmptyState): use prop type util for conditional props

cspell.json
`cspell` is parsing files from Yarn's offline mirror — this change proposes to ignore the  `.yarn` directory from its configuration (in addition to my muscle memory accidentally formatting the configuration file):
=> build(cspell): ignore `.yarn` directory

.github/CODE_GUIDELINES.md, .github/CODE_OF_CONDUCT.md, .github/VARIANT_COMPONENT_GUIDELINES.md, .github/stale.yml, cspell.json, cspell.packages.txt, package.json
Hidden files (beginning with .) are not included in `yarn spellcheck`, but they are still spellchecked when commitlint asks specifically for them, which could be inconvenient as we haven't cleared them of spellcheck errors.  This PR adds all hidden files in any directories, including root, to the ignore list, so that they are not spellchecked during commit either.
Files in hidden folders (beginning with .) are also not included in `yarn spellcheck`, but can still be spellchecked when commitlint asks specifically for them. We have already added '.yarn' to the ignore list to ensure that files in the offline mirror are not spellchecked during commit. This PR adds '.vscode' to the ignore list so that updates to files in that folder don't get spellchecked during commit, but adds '.github' to …
=> Add .github folder to spellcheck and exclude hidden files

cspell.json, package.json, packages/core/.storybook/preview.js, packages/core/package.json
The "Show info" button is a relic of a deprecated addon-info, which we have already dropped in favour of the replacement addon-docs. Remove the unused decorator.
Storybook preview.js, also added some spellcheck fixes, and removed an unnecessary dependency core->ccs (the files are accessed directly, not via a dependency chain).
Ran storybook.
=> chore: remove really annoying blue "Show Info" button that gets in the way on all the storybook pages

packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/PageHeader/PageHeaderUtils.js
Contributes to #996
Not all the dependencies were listed for the toggleCollapse function, leading to it not being called e.g. if the metrics were calculated *after* the `collapseHeader` prop was applied, which happened if the prop was set true on initial render.
Changed the toggle function to a set function, to avoid it 'bouncing' as the collapse state changed. Moved the function into utils file and ensured all callers listed all dependencies.
Ran storybook
=> fix(PageHeader): ensure all dependency changes trigger header collapse

packages/core/.storybook/index.scss
There used to be a DIV inserted around our stories, and David added these styles to prevent that inserted DIV mucking up our modals. That DIV is no longer inserted since I removed the addon-info, so the styles are getting randomly applied to top-level DIVs in our stories, causing mayhem. End the mayhem.
storybook index.scss
Ran storybook. Again. And looked a bit more thoroughly.
=> chore(Storybook): remove styles that fixed a div that's no longer inserted

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
Contributes to #1056 
The problem here was that `sidePanelSubtitleElementHeight` was being assigned a negative number if the panel did not have scrolling content. But if the browser was resized, that value never got updated. In the case that it receives a negative number, the scrolling animation stops working so we simply needed to give it a default value.
`SidePanel.js`
Storybook
=> fix(SidePanel): title animation bug addressed, missing default value

packages/cloud-cognitive/src/components/CreateSidePanel/_create-side-panel.scss, packages/cloud-cognitive/src/components/SidePanel/_side-panel-variables.scss, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to https://ibm-casdesign.slack.com/archives/G01PUCL3V8R/p1627365838044100
Looks like the title and subtitle on the create side panel were not getting the proper padding, I have made some updates so this behaves as expected. Because of the positioning of the title/subtitle, the previous implementation was calculating 20% of the window, not of the panel.
`_create-side-panel.scss`
`_side-panel-variables.scss`
Storybook
_Incorrect_
_Correct_
=> fix(CreateSidePanel): title and subtitle padding is correct now

packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js, packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js, packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepWithSectionsTearsheet.js
Contributes to #1085 
Addresses 2 of the items in #1085 regarding the handling of optional form fields and removing an example label from the tearsheet.
`CreateTearsheet/preview-components/MultiStepTearsheet.js`
`CreateTearsheet/preview-components/MultiStepWithSectionsTearsheet.js`
Storybook
=> fix(CreateTearsheet): story component updates

packages/core/.storybook/manager.js
This PR adds the ability to turn on a "Canary" marker tag in storybook component titles by including "#canary" on the end of the generated title. NB this is not currently used, and the detail may be adjusted before it is, but it sets up the ability ready for when we do use it.
storybook config in `manager.js`
Ran storybook. It makes no difference to the current storybook, but can be seen by adding #canary onto the end of an existing story file `title` field in the default export.
=> chore: add storybook title canary tag

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
Contributes to #1056 
This PR addresses the issue @lily-peng found in #1056 where if the panel is open larger than the scrolling content, is then resized to include scrolling, the title animation would not behave as expected. This was because we needed a way to get the current panel height (not the panel height when it opened/first rendered).
I added a `panelHeight` state variable that receives it's value from the `useResizeDetector` hook, added this value to the useEffect that is animating the title as a dependency and now we always have the _current_ height of the side panel.
`SidePanel.js`
Storybook
=> fix(SidePanel): add panel height to useEffect dependencies

packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.test.js
Contributes to #954 
also in regards to `downloadFileName/Type` not being included in the testing those props are being handled in `APIKeyDownloader`
=> fix: added additional apikeymodal tests

config/jest-config-ibm-cloud-cognitive/setup/setupFilesAfterEnv.js
I should really have included an explanatory comment for this otherwise mysterious config setting which affects how our tests need to use `getByTestId` and related queries.
Just added a comment to setupFilesAfterEnv.js.
This change does not have any functional effect.
=> chore: add commentary for 'data-test-id' config setting

packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.test.js, packages/cloud-cognitive/src/components/CreateTearsheet/_create-tearsheet.scss
Contributes to #1085 
Adds microinteraction to the `CreateTearsheet` when you turn the "View all" toggle on and off. The progress indicator component and SideNav (from Carbon UI shell) will animate in and out respectively.
`_create-tearsheet.scss`
Storybook
https://user-images.githubusercontent.com/10215203/128032919-faaf5ffc-f879-4f6b-a941-591224554ab3.mov
=> feat(CreateTearsheet): add microinteraction to influencer menus

packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.js, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js, packages/cloud-cognitive/src/global/js/use/useCreateComponentStepChange.js, packages/cloud-cognitive/src/global/js/use/usePreviousValue.js, packages/cloud-cognitive/src/global/js/use/useResetCreateComponent.js, packages/cloud-cognitive/src/global/js/use/useValidCreateStepCount.js, packages/cloud-cognitive/src/global/js/utils/getFocusableElements.js
Contributes to #1123 
Extracts code from both CreateTearsheet and CreateFullPage components to both reduce the size of these components and to start creating shared logic between these components.
`packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.js`
`packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js`
`packages/cloud-cognitive/src/global/js/use/useCreateComponentStepChange.js`
`packages/cloud-cognitive/src/global/js/use/usePreviousValue.js`
`packages/cloud-cognitive/src/global/js/use/useResetCreateComponent.js`
`packages/cloud-cognitive/src/global/js/use/useValidCreateStepCount.js`
`packages/cloud-cognitive/src/global/js/utils/getFocusableElements.js`
Storybook and ran tests for both CreateTearsheet and CreateFullPage
=> chore(CreateComponents): add custom hooks to reduce size

packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.test.js
Contributes to #1124
Generalise the tearsheet common tests so that they can be applied to CreateTearsheetNarrow, and include that in the tests. This covers testing of a number of CreateTearsheetNarrow props which are inherited from the TearsheetNarrow. Note that a similar extension could be made to include CreateTearsheet into this test, but that hasn't been included into this PR.
Extended tearsheet tests to include CreateTearsheetNarrow.
Ran tests.
=> chore: extend tearsheet tests to include CreateTearsheetNarrow

packages/cloud-cognitive/src/components/CreateModal/CreateModal.js, packages/cloud-cognitive/src/components/CreateModal/CreateModal.test.js
Closes #1137 
Added an onClose handler to CreateModal.js to suppress the automatic closing of the modal and notify the onRequestClose handler.
Ran storybook
=> fix(CreateModal): ensure closing the modal calls onRequestClose handler

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/HTTPErrors/_http-errors.scss
Contributes to #1150 
This PR explicitly sets the text color for the HTTPError label, title, and description.
`_http-errors.scss`
Storybook and ran `yarn jest styles -u`
=> fix(HTTPErrors): explicitly set text color and update snapshot

packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.js, packages/cloud-cognitive/src/components/CreateInfluencer/CreateInfluencer.js, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.stories.js, packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js, packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepWithSectionsTearsheet.js, packages/cloud-cognitive/src/components/CreateTearsheet/utils/isValidChildren.js, packages/cloud-cognitive/src/global/js/use/useCreateComponentFocus.js, packages/cloud-cognitive/src/global/js/use/useCreateComponentStepChange.js
Contributes to #1123
Extracts more logic out of CreateTearsheet and CreateFullPage so that it can be shared across these two components.
`packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js`
`packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.stories.js`
`packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js`
`packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepWithSectionsTearsheet.js`
`packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.js`
`packages/cloud-cognitive/src/components/CreateInfluencer/CreateInfluencer.js`
`packages/cloud-cognitive/src/global/js/utils/hasValidChildType.js`
`packages/cloud-cognitive/src/global/js/use/useCreateComponentFocus.j …
=> chore: #1123 create components custom hook

packages/cloud-cognitive/src/settings.js
The `checkComponentEnabled` helper function applied to components was correctly rendering components as themselves if the component was flagged as released and as a canary placeholder if the component was flagged as not yet released (canary). However, if the component was not an exported component at all, it was wrongly rendering it as a canary placeholder. This PR fixes this so that internal components can include a `checkComponentEnabled` without becoming canaries.
Just the one function in `settings.js`
Ran tests and storybook. I also commented out the enable-all-components from storybook, so I could see the BreadcrumbWithOverflow and ActionBar becoming canary placeholders in the PageHeader stories, and checked that this PR fixes that.
=> fix: ensure internal components don't render as canary placeholders

packages/cloud-cognitive/src/components/CreateTearsheet/_create-tearsheet.scss
The main content of the create tearsheet should remain left aligned, this PR removes the margin from the grid component that was previously preventing this.
`_create-tearsheet.scss
Storybook
=> fix(CreateTearsheet): remove grid margin

packages/cloud-cognitive/src/components/CreateInfluencer/CreateInfluencer.js, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.test.js, packages/cloud-cognitive/src/global/js/hooks/useResetCreateComponent.js
Contributes to #1076 
This PR adds a new prop, `initialStep`, that allows for opening the create tearsheet to a custom step.
`CreateTearsheet.test.js`
`CreateInfluencer.js`
`useResetCreateComponent.js`
Storybook, `yarn test /CreateTearsheet/`
=> feat(CreateTearsheet): #1076 create tearsheet custom step

packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.stories.js
Contributes to #1180 
Sets a default action set to use for the story titled `Narrow tearsheet with all header items`.
`TearsheetNarrow.stories.js`
Storybook
=> chore(Tearsheet): set default action set for narrow story

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Fixes the placement of the close svg within the close button of the side panel
Storybook and updates styles snapshot
=> fix(SidePanel): center close svg in close button

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.stories.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js
Contributes to #1177 
Adds some flexibility to the action toolbar buttons in the side panel and properly displays the tooltip via `hasIconOnly` prop on buttons.
`SidePanel.js`
`SidePanel.stories.js`
Storybook and updated tests
=> feat(SidePanel): allow actionToolbarButtons to be a bit more flexible

packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.js, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js, packages/cloud-cognitive/src/global/js/utils/hasValidType.js
Contributes to #1123 
Adds another utility that can be used in both CreateTearsheet and CreateFullPage to cut down on the logic in those two components (I have held off adding it to CreateFullPage for now since it is currently being reviewed).
`cloud-cognitive/src/global/js/utils/hasValidType.js`
Storybook
=> chore(CreateTearsheet): add utility for checking type of child components

packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
The PageHeader is hosted in a grid but was missing properties influencing the width of the grid "narrow" and "fullWidth". This PR adds the props "narrowGrid" and "fullWidthGrid".
Storybook and additional tests for grid width classes.
=> feat: page header props to influence grid width

docs/reviews/RELEASE_REVIEW_GUIDELINES.md, packages/cloud-cognitive/scripts/generate/templates/DISPLAY_NAME.test.js, packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.js, packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.test.js, packages/cloud-cognitive/src/components/AboutModal/AboutModal.test.js, packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.js, packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.test.js, packages/cloud-cognitive/src/components/CreateModal/CreateModal.js, packages/cloud-cognitive/src/components/CreateModal/CreateModal.test.js, packages/cloud-cognitive/src/components/CreateSidePanel/CreateSidePanel.js, packages/cloud-cognitive/src/components/CreateSidePanel/CreateSidePanel.test.js, packages/cloud-cognitive/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.js, packages/cloud-cognitive/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.test.js, packages/cloud-cognitive/src/components/EmptyStates/EmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/EmptyState.test.js, packages/cloud-cognitive/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.js, packages/cloud-cognitive/src/components/ExportModal/ExportModal.js, packages/cloud-cognitive/src/components/ExportModal/ExportModal.test.js, packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.js, packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.test.js, packages/cloud-cognitive/src/components/HTTPErrors/HTTPError403/HTTPError403.js, packages/cloud-cognitive/src/components/HTTPErrors/HTTPError404/HTTPError404.js, packages/cloud-cognitive/src/components/HTTPErrors/HTTPErrorOther/HTTPErrorOther.js, packages/cloud-cognitive/src/components/HTTPErrors/HTTPErrors.test.js
Contributes to #1178 
PR to add Devtools support and tests to numerous released components:
- `APIKeyModal`
- `CreateFullPage`
- `CreateModal`
- `CreateSidePanel`
- `CreateTearsheetNarrow`
- `EmptyState`
- `ErrorEmptyState`
- `ExportModal`
- `ExpressiveCard`
- `HTTPError403`
- `HTTPError404`
- `HTTPErrorOther`
- Add Devtools guidance to release documentation
- Update Devtools test description to better reflect DOM attributes instead of props
=> feat(devtools): add support to released components (1 / 3)

packages/cloud-cognitive/src/components/EmptyStates/EmptyState.test.js, packages/cloud-cognitive/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.js, packages/cloud-cognitive/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.js, packages/cloud-cognitive/src/components/ImportModal/ImportModal.js, packages/cloud-cognitive/src/components/ImportModal/ImportModal.test.js, packages/cloud-cognitive/src/components/NotificationsPanel/NotificationsPanel.js, packages/cloud-cognitive/src/components/NotificationsPanel/NotificationsPanel.test.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js, packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.js, packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.test.js, packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.js, packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.test.js, packages/cloud-cognitive/src/components/Saving/Saving.js, packages/cloud-cognitive/src/components/Saving/Saving.test.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js
- Blocked by #1220 
- Contributes to #1178 
PR to add Devtools support and tests to numerous released components:
- `ImportModal`
- `NotificationsPanel`
- `NoDataEmptyState`
- `NoTagsEmptyState`
- `NotFoundEmptyState`
- `NotificationsEmptyState`
- `PageHeader`
- `UnauthorizedEmptyState`
- `ProductiveCard`
- `RemoveModal`
- `Saving`
- `SidePanel`
Add test to `ErrorEmptyState` overlooked in #1220
=> feat(devtools): add support to released components (2 / 3)

packages/cloud-cognitive/src/components/StatusIcon/StatusIcon.js, packages/cloud-cognitive/src/components/StatusIcon/StatusIcon.test.js, packages/cloud-cognitive/src/components/TagSet/TagSet.js, packages/cloud-cognitive/src/components/TagSet/TagSet.test.js, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.js, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.test.js, packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.js, packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.js, packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.test.js
Contributes to #1178 
PR to add Devtools support and tests to remaining released components:
- `StatusIcon`
- `TagSet`
- `Tearsheet`
- `TearsheetNarrow`
- `UserProfileImage`
Remove duplicate `ref` test for `TagSet`
=> feat(devtools): add attribute to numerous released components (3 / 3)

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
Bug that was reported via slack, regarding content scrolling behind the panel. With this change, the content behind the panel, will not be able to scroll anymore.
https://ibm-casdesign.slack.com/archives/C013ZTX0N6B/p1630682475035300
`SidePanel.js`
Storybook
=> fix(SidePanel): add overflow hidden to body if includeOverlay exists

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/CreateFullPage/_create-full-page.scss
In working on adding theme switching capabilities to the code sandboxes, I noticed that the CreateFullPage was not setting the background color of the main content area so when I changed themes the background remained white.
`_create-full-page.scss`
Update snapshot
Storybook
_Unexpected background color behavior in code sandbox_
=> fix(CreateFullPage): explicitly set bg color for page content

packages/cloud-cognitive/package.json, packages/core/package.json, yarn.lock
We previously avoided upgrading sass, as from v1.33 onwards it produced a large number of deprecation warnings in Carbon. Carbon have now fixed these warnings, and their fix *requires* v1.33 or later, so this PR relaxes the version restriction on sass so that tomorrow's version update can bring in the latest sass and the updated Carbon together.
package.json in cloud-cognitive and core
This doesn't actually change anything yet -- the testing (and fixing, if needed) will be done on tomorrow's version-update PR.
=> chore: relax restriction on sass version

packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.js
Contributes to #1125 
updates `inputLabelText` in `RemoveModal` to use `node` proptype instead of `string`, which is what carbon does for the text input label.
=> fix: use node instead of string for remove modal input label

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/ActionSet/_action-set.scss, packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.js, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Addresses theming issue with the tearsheet description.
https://ibm-cloud.slack.com/archives/C013ZTX0N6B/p1632124708127100
Also, added a background color on the action set component to avoid issues with ghost buttons when switching themes. See screenshot below from `CreateFullPage` code sandbox
`_tearsheet.scss`
`_action-set.scss`
Snapshot
Storybook
=> fix(Tearsheet): set text color so theming works as expected

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.mdx, packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss, packages/cloud-cognitive/src/components/PageHeader/_storybook-styles.scss
Contributes to #1271
Page content set to `position: relative` was appearing over the top of the PageHeader on scroll. This PR uses the Carbon SCSS function `z('header')` to set the PageHeader to a z-index of 8000. 
In addition it fixes an issue where the 'style' attribute was being thrown away by the PageHeader.
PageHeader, test and styles.
Storybook and addition of a new test for the 'style' attribute.
=> fix: keep page header above content on scroll

packages/cloud-cognitive/src/components/EmptyStates/assets/ErrorIllustration.js, packages/cloud-cognitive/src/components/EmptyStates/assets/NoDataIllustration.js, packages/cloud-cognitive/src/components/EmptyStates/assets/NoTagsIllustration.js, packages/cloud-cognitive/src/components/EmptyStates/assets/NotFoundIllustration.js, packages/cloud-cognitive/src/components/EmptyStates/assets/NotificationsIllustration.js, packages/cloud-cognitive/src/components/EmptyStates/assets/UnauthorizedIllustration.js
Contributes to #1289 
Fixes #1289, ensures that svg elements have unique ids.
Empty state illustration components
Storybook
=> fix(EmptyStates): give svg elements unique ids to avoid display issues

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.stories.js
Contributes to #1314 
If a subtitle is not provided, the scrolling title animation's duration gets set to the entire scrolling content of the panel. By default, the duration of the scrolling animation is set to the height of the subtitle, but in this case when there is no subtitle the scrolling animation needs a set value.
`SidePanel.js`
`SidePanel.stories.js`
Ran tests and verified via storybook
=> fix(SidePanel): give default scroll height if no subtitle

packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.stories.js, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.test.js, packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js, packages/cloud-cognitive/src/global/js/utils/test-helper.js
Closes #1332
This PR:
- adds tearsheets to the modal exit selector list so that stacking tearsheets do not "trap" the focus in the first tearsheet.
- catches focus entry into a non-topmost tearsheet and transfers focus to the topmost tearsheet.
- checks as each tearsheet becomes topmost that focus is within the tearsheet, and if not claims focus.
This should avoid the focus trap issue and also clean up the handling of focus when multiple tearsheets are being opened and closed.
Tearsheet.js, also added to the stacked tearsheet stories so the issue can be verified. Also updated the tests to expect warnings from Carbon -- these should eventually be removed (see https://github.com/carbon-design-system/carbon/issues/10000).
Ran storybook.
=> Fix(Tearsheet): avoid focus traps with stacked tearsheets

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
Contributes to #1358 
Allow actionToolbarButtons prop to use rest props. This allows for users to more easily target these elements for testing, as requested in #1358.
I also updated the `subtitle` prop to just check for `PropTypes.node` like @SimonFinney and @lee-chase had suggested in a previous PR.
`SidePanel.js`
Storybook
=> feat(SidePanel): add rest props to actionToolbarButtons prop

packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
Contributes to #1311 
A number of page header property tests looked like
```js
prop === undefined
prop2 !== undefined
```
The intent appears to have been to simply test for the existence of a property that is falsy or truthy. Changed to
```js
!prop
!!prop2
```
A number of tests for undefined
Ran tests, lint and checked scroll behaviour of pageActions in context when there are no action bar itgems.
=> fix(pageHeader): breadcrumb scroll without actionbar

cspell.json
cspell wasn't actually doing anything at all during `yarn lint`, but was working properly during commit-lint. It was caused by a dodgy glob in the cspell.json. I'm not sure why, but removing the glob sorts it so whatevs.
cspell.json
Ran `yarn lint` after making a spelling error.
=> chore: fix cspell for linting

config/jest-config-ibm-cloud-cognitive/index.js, package.json
Since we switched to running tests on a per-package basis the coverage paths need to be updated. This PR does that. `yarn test:c4p --coverage` will now work.
=> chore: fix coverage inclusion

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
- Previously the page header had a background that appeared (opacity: 0 to $ui-01). This did not work when the background was turned off (on is the default). Changed this to transition between $ui-background and $ui-01.
- The Breadcrumb was only 60% of 60% of 100% width when shown with a pageAction, corrected to 60% of 100%;
- The breadcrumb was not quite wide enough to cover the row background (excluding pageActions, without actionBar) due to grid margins. Corrected.
- The pageActions when stuck to top (no action bar) did not cover the background. Updated to do so.
Storybook, lint and tests
=> fix: page header background over lays

package.json, packages/cloud-cognitive/package.json
Closes #1432 
Add sideEffects to main package.json to avoid tree shaking issue as seen in #1432 
`package.json`
=> fix: add side effect for props-helper to package.json

packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.stories.js
Contributes to #1445
This workaround for https://github.com/storybookjs/storybook/issues/11554 was suggested on that thread by shilman. It means there is no source code shown for the story, but that seems to stop Storybook trying to format the code which is where the error seems to happen that causes error messages and infinite loop crashes.
APIKeyModal.stories.js
Ran storybook.
=> chore: avoid storybook code formatting errors

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Card/Card.js, packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.js, packages/cloud-cognitive/src/components/ProductiveCard/_productive-card.scss
Contributes to #1243 
changes `primaryButtonText` propType in `ProductiveCard` to node to allow svg support.
=> feat: adds svg support to buttons in productive card

.github/workflows/update.yml
We want the versions update PR to include a release bump, so that any package affected by the updates gets a release the next time the release workflow runs. Up to now, this has been a `feat` bump, but this seems excessive: it generates a minor version each time the most trivial dependency changes, and taking on board the latest versions is not really a feature update. Change the workflow to set up a `fix` bump, so only a patch release will be generated (unless there are other `feat` items in the release, of course).
update workflow
Will be seen in action tonight
=> chore: reduce the versions update to a patch release bump

.github/workflows/update.yml, package.json
This PR separates the version updates into two tasks, one of which updates the dev-dependencies and the other updates Carbon versions. This will create two PRs. The dev-dependency PR can be readily merged as soon as all tests and CI checks pass. The Carbon-updates PR will do a version bump, and should be carefully tested before merging. This means that when there are no Carbon updates there will not be an unnecessary version bump.
top-level package.json, and the update yaml.
Will do a test run once merged.
=> chore: separate carbon and dev-dependency updates

examples/carbon-for-ibm-products/example-gallery/src/GalleryCard.scss, examples/carbon-for-ibm-products/example-gallery/src/_storybook-styles.scss, examples/carbon-for-ibm-products/example-gallery/src/example-gallery.stories.js, packages/core/.storybook/main.js, packages/core/docs/getting-started.stories.mdx, packages/core/story-structure.js
Create a new 'Overview' section in the storybook, and move the 'Getting Started' page into it, and also add the examples gallery into it. We can also add multi-component playgrounds etc into this section.
storybook config, and added a new story to the examples gallery
Ran storybook.
=> chore: add the examples gallery to the storybook

.yarnrc, package.json
Our `yarn` version is locked in to our repo, but hasn't been updated recently. Update to the latest `yarn` as part of the regular dependencies upgrades.
package.json, plus yarn config
Ran `yarn` and builds.
=> chore: update yarn version as part of dependencies upgrade

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/StatusIcon/_status-icon.scss
Contributes to #1567 
This allows the StatusIcon component to receive the correct fill color when used inside of an icon only carbon button.
```
packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
packages/cloud-cognitive/src/components/StatusIcon/_status-icon.scss
```
Verified via the StatusIcons used in the component playground
=> fix(StatusIcon): allow status icons to receive fill inside of icon only buttons

packages/cloud-cognitive/src/components/ExportModal/ExportModal.js, packages/cloud-cognitive/src/components/ExportModal/ExportModal.stories.js, packages/cloud-cognitive/src/components/ExportModal/ExportModal.test.js
Contributes to #1573 
adds the option to use a password field instead of a text field in the `ExportModal` component.
=> feat: password input option for export modal

config/babel-preset-ibm-cloud-cognitive/package.json, config/cli/package.json, config/jest-config-ibm-cloud-cognitive/package.json, config/storybook-addon-carbon-theme/package.json, package.json, packages/cdai/package.json, packages/cloud-cognitive/package.json, packages/core/package.json, packages/security/package.json
Our weekly dependency updates were updating the yarn lock and offline mirror, ensuring that we were always building alongside the latest versions of carbon, but `npm-check-updates` by default does NOT update the peerDependencies field, so our peer dependencies were sometimes lagging behind, meaning that some of our users might be using our library alongside older Carbon versions -- something we don't recommend. This update ensures that our peer dependencies are pulled up to the latest versions at the same time.
package.json update scripts
Ran the various update processes and checked the outputs.
=> chore: ensure dependency updates bring peer dependencies up to latest

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Card/Card.js, packages/cloud-cognitive/src/components/ProductiveCard/_productive-card.scss
Contributes to #1580 and #1571
* removes unnecessary margin from productive card icon buttons that were causing an incorrect size
* adds `{...rest}` to the action icons in productive cards so that users can pass additional props like `disabled` to the buttons
=> fix: productive card button size and props spread

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to #1117 
Allows for the side panel to incorporate usage with `prefers-reduced-motion`. This update consists of not animating the entrance and exit animations, as well as preventing the scrolling title animation.
`SidePanel.js`
Storybook (turning prefers reduced motion on and off)
=> feat(SidePanel): add prefers-reduced-motion support for SidePanel animations

packages/cloud-cognitive/src/components/AddSelect/AddSelect.js, packages/cloud-cognitive/src/components/AddSelect/_add-select.scss, packages/cloud-cognitive/src/components/SingleAddSelect/SingleAddSelect.stories.js
Contributes to #1582 
* the code now checks for a `children` attribute in the items array to distinguish the hierarchy of the list and adds a chevron to indicate that you can drill down further. just the start of the implementation as this PR shifted focus while I was working on this.
* i refactored the way the search filter work and how custom filtering works. now it appropriately uses a hook to filter the data and now the user only needs to provide a filter function instead of maintaining the state. clearly the initial implementation was done hastily on my part. this should represent a more polished version.
=> fix(AddSelect): refactor custom filter and init navigation

package.json
The package.json version used in the root was out of date and would never get updated by lerna.
Changed to asterisk, which should install any version found.
Ran yarn.
=> chore: ensure yarn stylelint config can be loaded

packages/cloud-cognitive/package.json
I noticed that our source-maps on the built CSS files were problematic, as they referred to source in the `/src` folder but this folder is not included in our published package. All the SCSS files *are* included, but in a '/scss' folder. Adjusted the build scripts so that the SCSS files are copied into the '/scss' folder first and then the sass compile is done from there, so that the source-maps refer back to the source in that folder and thus are valid at run time.
Also allow source-maps to be built for our minimised CSS -- there seems no real reason not to, as it adds no overhead when dev tools are not used, won't be included into production bundles, and may occasionally be helpful.
package.json
ran build
=> fix: fix source links in source-maps for built CSS files

packages/core/story-structure.js
InlineEdit is not an internal component, but is one of the edit and update flows. We already have that section in the storybook, so move InlineEdit into that section (also drop the word "flows" to align with PAL site).
storybook structure config
ran storybook
=> chore(InlineEdit): move into edit and update section of storybook

packages/cloud-cognitive/scripts/generate/templates/_storybook-styles.scss, packages/cloud-cognitive/src/components/CancelableTextEdit/_storybook-styles.scss, packages/cloud-cognitive/src/components/CreateTearsheetNarrow/_storybook-styles.scss, packages/cloud-cognitive/src/components/EditSidePanel/_storybook-styles.scss, packages/cloud-cognitive/src/components/InlineEdit/_storybook-styles.scss, packages/cloud-cognitive/src/components/LoadingBar/_storybook-styles.scss, packages/cloud-cognitive/src/components/OptionsTile/_storybook-styles.scss
Remove a few instances of storybook styles files importing `./index`, as this causes duplicated styles in the storybook pack -- harmless but pointless. Also remove redundant comments with an old approach to checking specificity (not needed now the CSS import order has been set in the storybook) or prompting to add code that is now there. Also update the template generator page which wrongly includes the import of `./index`.
PS this will conflict with #1622 but it seemed better not to leave it incomplete -- we'll resolve the conflict after whichever one merges first.
several _storybook-styles.scss
Ran storybook
=> chore: tidy up storybook styles files

packages/cloud-cognitive/src/components/ActionSet/ActionSet.js, packages/cloud-cognitive/src/components/ActionSet/ActionSet.test.js, packages/cloud-cognitive/src/components/ButtonMenu/ButtonMenu.js
Closes #1643 
A number of Carbon functional components have recently switched from using `defaultProps` to using ES6 default values for prop parameters on the component function. This causes a number of test failures where we are accessing those default prop values for use in our components. This is now the recommended way to provide default prop values, so this PR removes all dependency on `defaultProps` in carbon components.
ActionSet and ButtonMenu
Ran tests
=> fix: avoid relying on defaultProps in carbon components (issue #1643)

.prettierrc.js
Removes prettier config now deprecated, but still specified by Carbon from our usage.
Just the prettier config.
Committing code from within VSCode. No problems were encountered, other than the report, at the command line.
=> chore: this prettier setting fails VSCode commits

packages/cloud-cognitive/src/components/InlineEdit/_inline-edit.scss
Contributes to #1492 
Ensures the placeholder does not block editable content clicks.
Improved the CSS hiding of the placeholder.
Storybook
=> fix(inline edit): placeholder blocking input click

packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.stories.js
Contributes to #1492 
The validation would occasionally fall over if the story parameter was undefined.
Storybook.
=> fix(InlineEdit): make story validation more robust

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Contributes to #1682 
Fix Tearsheet heading border being cut by margin-right by replace margin with padding
Replaced margin right by adding same space to padding right
Loaded storybook up locally to test
BEFORE
AFTER
=> fix: Using padding instead of margin to prevent border to being cut

packages/cloud-cognitive/src/components/InlineEdit/_inline-edit.scss
Contributes to #1492 
Remove the reserved space for the invalid/warn icons.
Inline edit styles adding space for the invalid/warn icon if needed.
Storybook.
=> fix: remove reserved space for invalid icon

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetBody.js, packages/cloud-cognitive/src/components/DataSpreadsheet/_data-spreadsheet.scss, packages/cloud-cognitive/src/components/DataSpreadsheet/createActiveCellFn.js
Contributes to #1701 
This PR addresses #1701, where if a cell selection is created then the second point of the selection is moved back to the active cell, the cell selection should be removed.
See attached screen recording for updated behavior:
https://user-images.githubusercontent.com/10215203/156089049-21a93c18-3897-43d6-8dcb-8362bcf3af99.mov
```
packages/cloud-cognitive/src/components/DataSpreadsheet/createActiveCellFn.js
```
=> feat(DataSpreadsheet): remove cell selection in certain case

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js
Fixed outside click functionality, `coords.row` need a check to make sure it exists before look at it's value.
`DataSpreadsheet.js`
Storybook
=> fix(DataSpreadsheet): prevent check on coords that do not exist

.github/workflows/ci.yml
Hi there! 👋 This PR adds a setting to the CI workflow to cancel existing jobs for a given PR when a new commit is added. This option helps to reduce the number of runners used across repos as the org is limited to only 20 runners.
I updated the `.github/workflows/ci.yml` workflow with the `concurrency` option from: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
We are currently using this config over on the Design System monorepo to reduce the number of runners being used by actions.
=> ci: add concurrency option to CI workflow

packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.js, packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.test.js
Contributes to #1722, #1725
- `props.lockedText` is shown as fallback if no summary is set but tile is locked
- summary is hidden when not in validation state and disabled (as per design)
Automated testing, Storybook
=> fix(options-tile): fix summary behaviour

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetBody.js
Cleans up some of the event handlers based on video shared by @davidmenendez yesterday 😄 
Old
```jsx
onMouseDown={event => handler(event, arg1, arg2)}
```
New
```jsx
onMouseDown={handler(arg1, arg2)}
```
Then the handler function contents are wrapped in a function that returns the event itself, ie:
```jsx
const handler = (arg1, arg2) => {
return event => {
// handler logic here
}
}
```
`DataSpreadsheetBody.js`
Storybook
=> chore(DataSpreadsheet): add curried functions for event handlers

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.test.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetBody.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetHeader.js, packages/cloud-cognitive/src/components/DataSpreadsheet/_data-spreadsheet.scss
Contributes to #1731 
With these changes, whenever the active cell changes the row and column header cells that match the coordinates of the active cell receive a different `background-color`.
See example below:
https://user-images.githubusercontent.com/10215203/156691417-02d82e38-47fd-404c-b235-48d8b0560cc6.mov
```
packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.test.js
```
Storybook, added to tests
=> feat(DataSpreadsheet): highlight row/column header on active cell change

packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.js, packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.stories.js, packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.test.js, packages/cloud-cognitive/src/components/InlineEdit/_inline-edit.scss
Contributes to #1649 
Removes "warn" state following design review.
Validation now only supports the 'invalid' state.
InlineEdit component, styles, story and tests.
Storybook and test
=> chore: design review remove warn state

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetBody.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetHeader.js, packages/cloud-cognitive/src/components/DataSpreadsheet/checkActiveHeaderCell.js
Contributes to #1731 
Part 2 of #1731: whenever the cell selection areas change the row/column headers will receive the active highlight background color at the appropriate time.
See example below:
https://user-images.githubusercontent.com/10215203/156810371-e6518963-42ef-4558-bc07-5477f4912e11.mov
```
```
Storybook
=> feat(DataSpreadsheet): #1731 add active highlight to column/row headers

packages/cloud-cognitive/src/components/TagSet/TagSet.js, packages/cloud-cognitive/src/components/TagSet/TagSet.stories.js
Contributes to #1307 
Adds allTagsModelTarget to allow users to specify an alternative to the default document body.
Storybook.
=> feat(TagSet): add allTagsModalTarget prop

packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.js, packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.mdx, packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.stories.js, packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.test.js, packages/cloud-cognitive/src/components/OptionsTile/_index.scss, packages/cloud-cognitive/src/components/OptionsTile/_options-tile.scss, packages/cloud-cognitive/src/components/OptionsTile/_storybook-styles.scss, packages/cloud-cognitive/src/components/OptionsTile/index.js
Contributes to #1656
- Updated copyright year in all file headers to include 2022
- Import Carbon toggle component scss
- Renamed props
- `props.heading` -> `props.title`
- `props.headingId` -> `props.titleId`
- Render component as child of `<main>` element for automated a11y test
- Improve responsive behaviour in storybook
- Annotated why certain spacings don't use tokens but `rem`
- Fix chevron rendering on iOS Safari
- Storybook
- Tests
=> refactor(options-tile): implement release review feedback

packages/cloud-cognitive/src/components/AddSelect/AddSelect.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectSidebar.js, packages/cloud-cognitive/src/components/AddSelect/add-select-utils.js, packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.stories.js, packages/cloud-cognitive/src/components/SingleAddSelect/SingleAddSelect.stories.js
just some cleanup for add select
* moves some functions to a new utils file to reduce file bloat
* adds a submit handler
* adds some additional comments to help readability
* moves the flattened sidebar items to `AddSelect` and inside the `useEffect` so that that function only needs to run once
=> fix: add select cleanup

packages/security/src/components/SummaryCard/SummaryCardContainer/__tests__/SummaryCardContainer-test.js
Skip a11y test for summary card container
Added a test skip
Ran test.
=> chore: skip a11y test for summary card container

packages/component-usage-report/package.json
It appears that the release from yesterday evening failed because the `@carbon/component-usage-report` was never published, I think the publish step was possibly skipped because the `publishConfig` key in the package.json was missing. I re-ran the release workflow, if it fails again with the same message, I'm hoping this will fix it.
`packages/component-usage-report/package.json`
=> fix: add publishConfig to component usage package.json

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/TagSet/_tag-set.scss
The text alignment of the TagSet overflow was based on the alignment of the popup. Changed to always align the text to the left.
CSS targeting the text in the overflow and related snapshot.
Storybook.
=> fix: text alignment in tagset overflow

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/_data-spreadsheet.scss
Contributes to #1759 
This PR adds the `body-short-01` type token to all spreadsheet cells, the active cell, and the cell editor (text area). Previously, the text area font size was slightly larger than the font size of the body cells.
I also updated the calculation of the paddingTop value of the cellEditor, it was off by 1px. Now, going into edit mode, the contents of the cell being edited does not move or jump anymore.
```
```
Storybook
=> fix(DataSpreadsheet): use type token for cells/cell editor/active cell

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.stories.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.test.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetBody.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetHeader.js, packages/cloud-cognitive/src/components/DataSpreadsheet/utils/handleHeaderCellSelection.js
Contributes to #1757 
Adds a new prop, `onSelectionAreaChange`, that sends data back to the consumer detailing each selection area. This function prop is called whenever new selection areas are created either from the spreadsheet body or from selecting a row or column header.
The structure of the data sent back is as follows:
```js
[
{
rows: {
start: 0,
end: 0
},
columns: {
start: 0,
end: 2
},
cells: [
[0, 0],
[0, 1],
[0, 2],
]
}
]
```
You can also see the return value of this prop by looking at the actions tab in storybook after selecting an area.
```
packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.stories.js
packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.test.js …
```
=> feat(DataSpreadsheet): add `onSelectionAreaChange` prop

packages/cdai/src/components/IdeButton/IdeButton.spec.js, packages/cdai/src/components/IdeCreate/ide-create.test.js, packages/cdai/src/components/IdeDataTable/IdeDataTable.spec.js, packages/cdai/src/components/IdeHome/IdeHome.spec.js, packages/cdai/src/components/IdeTableToolbarSearch/IdeTableToolbarSearch.spec.js
Contributes to #1387
Changed some tests to use settings.prefix from carbon-components.  This is in preparation for Carbon 11 which will move away from the 'bx' prefix.
Ran the tests.
=> chore: remove cdai bx in testss

packages/core/src/component-playground/ComponentPlayground.js
In one of the previous carbon prefix PRs, the settings import was incorrect which caused the netlify build to fail.
=> fix(ComponentPlayground): fix carbon settings import

packages/cloud-cognitive/src/components/AddSelect/AddSelectList.js, packages/cloud-cognitive/src/components/AddSelect/_add-select.scss, packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.stories.js, packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.js, packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.test.js
Contributes to #1850 and #1851
this PR accomplishes two things.
1. it allows `UserProfileImage` to accept an optional icon to display in lieu of the built in ones. i also included an additional utility to add a random background color if one is not provided.
2. adds avatar support to add select.
=> fix: add select avatar and userprofileimage update

packages/cloud-cognitive/src/components/ActionBar/ActionBar.js, packages/cloud-cognitive/src/components/ActionBar/ActionBar.test.js, packages/cloud-cognitive/src/components/ActionBar/ActionBarOverflowItems.js, packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js
Contributes to #1789
Fixes A11y issues raised in #1789 that can be addressed directly. The right/left scroll buttons which can be shown by tabs needs an update to Carbon https://github.com/carbon-design-system/carbon/issues/11109
- Added `icon-description` properties to match `aria-label` when creating overflows for breadcrumb and action bar items.
- Wrapped aria-hidden buttons with an inner aria-hidden={false} as suggested by a11y checker.
- Corrected label id used by hidden action bar items
Storybook, a11y checker and tests.
=> fix(PageHeader): issue1789 a11y issues BreadcrumbWithOverflow & ActionBar

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useSpreadsheetOutsideClick.js
Contributes to #1858 
This fixes the issues preventing cell edits in Safari and Firefox. Also removes a duplicate `removeCellSelections` function. Lastly, after submitting cell edits the selection area was not being updated, that was fixed as well.
```
packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useSpreadsheetOutsideClick.js
```
Storybook
=> fix(DataSpreadsheet): browser fix, update selectionArea on cell updates

examples/carbon-for-ibm-products/example-gallery/package.json, examples/carbon-for-ibm-products/example-gallery/src/index.js
Example gallery broken in V11, reverted to v10 pending assessment.
=> chore: fix example gallery to v10

examples/carbon-for-ibm-products/example-gallery/src/gallery-config/index.js, packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
Closes #1737
Moves the title down 2px to allow for editable title outline when no ActionBar is used. Use of an ActionBar changes the position of the title meaning no intervention is necessary.
Added a transition to PageHeader styles
Storybook and tests
=> fix: issue 1737 page header example

packages/cloud-cognitive/src/components/TagSet/TagSet.js
Attempt to address SSR issue with TagSet.
Move use of document.body (default target for allTagsModalTarget) into useEffect.
Tests and storybook. 
Asked nextJS user to supply SSR sample, but none so far.
=> fix: ssr maybe - moves document.body inside useEffect

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/_data-spreadsheet.scss
Contributes to #1882 
This PR fixes the placement of the text area cursor in Safari. Previously, the cursor was placed at the beginning of the content in the text area, now it is placed at the end of the content of the cell being edited.
```
```
Storybook
=> fix(DataSpreadsheet): correct cursor placement

cspell.json, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetBody.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetHeader.js, packages/cloud-cognitive/src/components/DataSpreadsheet/_data-spreadsheet.scss, packages/cloud-cognitive/src/components/DataSpreadsheet/utils/handleHeaderCellSelection.js
Contributes to #1907 
This allows you to select multiple columns/rows via header cells. To do this, it is the same interaction as in the body of the spreadsheet, command + click or shift + arrow key.
```
cspell.json
packages/cloud-cognitive/src/components/DataSpreadsheet/utils/handleHeaderCellSelection.js
```
Storybook
=> feat(DataSpreadsheet): add support for multi row/column selections

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useMultipleKeyTracking.js, packages/cloud-cognitive/src/components/DataSpreadsheet/utils/handleMultipleKeys.js
Contributes to #1912 
If the user agent is not `Macintosh`, some of the keyboard shortcuts needed to be updated. For example, `CMD+A` should become `CTRL+A`. I updated the `useMultipleKeyTracking` hook to return a `usingMac` boolean variable so we can correctly set the keyboard shortcuts.
```
packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useMultipleKeyTracking.js
packages/cloud-cognitive/src/components/DataSpreadsheet/utils/handleMultipleKeys.js
```
To test this you can:
1. open the browser devtools
2. Click the overflow menu on the right (next to the close icon)
3. Hover over `More tools`
4. Click on `Network conditions`
5. Scroll down to `User agent` section
6. Uncheck `Use browser default` and …
=> feat(DataSpreadsheet): support shortcuts when user agent is not mac

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.stories.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.test.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetBody.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetHeader.js, packages/cloud-cognitive/src/components/DataSpreadsheet/_data-spreadsheet.scss, packages/cloud-cognitive/src/components/DataSpreadsheet/utils/generateData.js, packages/cloud-cognitive/src/components/DataSpreadsheet/utils/getSpreadsheetWidth.js
Contributes to #1928 
This adds support for horizontal scrolling within the spreadsheet, along with adding position sticky to the row header cells when there is horizontal scrolling. The total width of the spreadsheet gets determined by the new prop `totalVisibleColumns`.
The width of the cells within the spreadsheet were also not correct based on the value they were supposed to be, they now match the designs and the custom size you can optionally provide.
```
packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.stories.js …
```
=> feat(DataSpreadsheet): support horizontal scrolling/add sticky headers

packages/cloud-cognitive/src/components/ExportModal/ExportModal.js
Contributes to #1946 
fixes a very silly and easy bug where default props were being improperly used to set the default state of the filename and extension. since `useEffect` was not being used changes to those props where not properly being updated in the component.
=> fix: filename and extension default state

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to #1941 
Fixes the panel height when there are no action buttons provided and `animateTitle` is set to false. I also noticed some spacing issues when the label text is provided which I addressed here as well.
```
packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
```
Storybook
=> fix(SidePanel): fix static panel height without actions

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.stories.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetBody.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetHeader.js, packages/cloud-cognitive/src/components/DataSpreadsheet/_data-spreadsheet.scss, packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useSpreadsheetEdit.js, packages/cloud-cognitive/src/components/DataSpreadsheet/utils/createCellSelectionArea.js
Contributes to #1944 
Adds support for variable column width, this can be done by adding a `width` property to the column you wish to give the custom width to, via the columns prop. Updates were also made to `createCellSelectionArea.js` so that when you create a selection area, it works with different column widths. Similarly, `useSpreadsheetEdit.js` was also updated so that the dynamic size of the cell editor is set according to the size of the next column.
Previously, cell selections and the dynamic sizing of the cell editor both assumed the width of all columns were the same.
See interaction below:
https://user-images.githubusercontent.com/10215203/165186520-90a1410d-c564-402d-a3c5-13e762625621.mov
``` …
```
=> feat(DataSpreadsheet): support variable column width

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useSpreadsheetEdit.js
Contributes to #1961 
Similar to #1960, there was one more place where the DataSpreadsheet component was getting a value based on the original order of the columns and not the new reordered version of the columns.
FYI @mitchellbernstein this will fix the two bugs you noticed earlier today 😅 
`DataSpreadsheet.js`
`useSpreadsheetEdit.js`
Storybook
=> fix(DataSpreadsheet): address cell editing after reorder

packages/security/src/components/Header/Header.js, packages/security/src/components/Header/__tests__/Header-test.js
Contributes to #1978
Fix for accessibility issue with the profile button in the Security Header Shell.
Switch from using aria-label to using aria-describedby + accessibility text.  aria-label requires the aria-label matches the button text.  In this case we want the assistive text to be different than the username/initials used in the button.
- Ran IBM accessibility checker and verified no accessibility issues.
- Verified unit tests passed.
=> fix: a11y issue profile-button (#1978)

packages/cloud-cognitive/src/components/AddSelect/AddSelect.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectList.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectMetaPanel.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectSidebar.js, packages/cloud-cognitive/src/components/AddSelect/_add-select.scss, packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.stories.js
Contributes to #1982
when an item has a `meta` attribute and you hover over it in the list you should now see an icon that when clicked will open up the metal data panel.
=> fix: add select meta panel

.github/workflows/update.yml
Contributes to #1984 
Change cron syntax in github action so that dependency update PRs occur on the 1st and 15th of every month.
```
```
Checked cron syntax [here](https://crontab.guru/#0_4_1,15_*_*)
=> chore: change frequency of dependency github action

packages/cloud-cognitive/src/components/ExportModal/ExportModal.js
small bug brought to my attention in the pal-dev channel. when a user edits the input and closes it via submit or cancel and then re-opens the modal the previous input still persists. this should reset it properly when the modal closes.
=> fix: when export modal closes the input should be reset

packages/cloud-cognitive/src/components/DataSpreadsheet/_data-spreadsheet.scss
Updates the border colors depending on the state of the header cell (default vs active).
`_data-spreadsheet.scss`
Storybook
=> fix(DataSpreadsheet): update header cell border colors

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetHeader.js, packages/cloud-cognitive/src/components/DataSpreadsheet/utils/getCellSize.js
Contributes to #1995 
Changes `cellSize` prop to match the sizes from Carbon's data table.
```
packages/cloud-cognitive/src/components/DataSpreadsheet/utils/getCellSize.js
```
Storybook
=> feat(DataSpreadsheet): rename cellSize props to match carbon data table

packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useSpreadsheetMouseMove.js, packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useSpreadsheetMouseUp.js, packages/cloud-cognitive/src/components/DataSpreadsheet/utils/moveColumnIndicatorLine.js
Addresses issues where if you have a spreadsheet with horizontal scrolling the placement of elements during/after column reordering was incorrect because it wasn't accounting for the amount scrolled horizontally. Now the cloned selection element as well as the indicator line are positioned correctly.
```
packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useSpreadsheetMouseMove.js
packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useSpreadsheetMouseUp.js
packages/cloud-cognitive/src/components/DataSpreadsheet/utils/moveColumnIndicatorLine.js
```
Storybook, with the story named `With many columns`
=> fix(DataSpreadsheet): support reordering columns with horizontal scroll

.github/workflows/release.yml
Contributes to #2011 
Upon the last PR addressing this issue, I tried running the release workflow and noticed the same behavior. I realized that running `yarn` was required _before_ the publish of the legacy package, not _after_ actually renaming it. I think this will fix all of the release issues after the yarn upgrade.
`release.yml`
Will test after merging by running the release workflow
=> fix(ReleaseAction): run yarn before publsh, not after rename

.github/workflows/release.yml
Contributes to #2011 
Created a separate step to install dependencies after renaming package to support the legacy name to help narrow down what may still be causing release flow to not finish successfully.
`release.yml`
The last release workflow failed so I believe breaking the install into it's own separate step will help
=> fix(ReleaseAction): #2011 release fix attempt 3

packages/cloud-cognitive/src/components/AddSelect/AddSelect.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectList.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectSidebar.js, packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.stories.js
Contributes to #2018 
adds modifier functionality to add select multi select. now when the user passes in a modifier object, onMount the existing modifiers will be added to state in `appliedModifiers` which looks like `[{ id: some_id, [modifier_attribute]: some_value }]`
when `onSubmit` is called it now checks for these modifiers and instead of just sending an array of id's it will send an array of objects with the id's and the modifier values.
=> fix: Add select modifier functionality

packages/cloud-cognitive/src/components/ComboButton/ComboButton.js
Contributes to ComboButton import still causing build issues.
You can see that [this code sandbox](https://codesandbox.io/s/practical-meadow-c1sgm0?file=/src/App.js) is still have issues starting up because of the import of `setupGetInstanceId` from `carbon-components-react/lib/tools/setupGetInstanceId`. To make sure that we don't run into this issue again, I just replaced `setupGetInstanceId` with our own internal uuid utility.
`ComboButton.js`
Storybook
=> fix(ComboButton): remove getInstanceId and use our internal uuid util

packages/cloud-cognitive/src/components/Datagrid/styles/datagrid.scss
When doing horizontal scrolling in datagrid, header row would not scroll;
In certain datagrid stories(eg., Empty State, Infinite Scroll, Ten Thousand Entries) , the style of scroll bar is set to browser's default style instead of IBM's scrollbar style.
`datagrid.scss` 
Changed overflow and display configs so that header row can scroll properly when overflow occurs.
Added selectors to change the scrollbar style of stories to improve consistency
verified visually in storybook.
=> fix: header row horizontal scroll and scrollbar style

packages/cloud-cognitive/src/components/index.js
Contributes to #2035 
The hooks provided by the Datagrid component will now be exported with this change, making them available to consumers of the Datagrid component. Without exporting these hooks there is no possible way to use the Datagrid component because the component relies on these hooks to create the data table.
```
```
=> fix(Datagrid): export datagrid hooks

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridSelectAllWithToggle.js
Contributes to #2035 
There seems to be errors when importing the `InlineCheckbox` from within the Datagrid component. I replaced it with the standard Checkbox to avoid these issues.
Fixes the error below:
`DatagridSelectAllWithToggle.js`
Storybook
=> fix(Datagrid): use checkbox in place of inline checkbox

.github/workflows/release.yml, .github/workflows/update.yml
Contributes to #2040 
Our `update` and `release` workflows have been failing after the yarn upgrade because of lock file changes. These lock file changes are intended, using the yarn env variable `YARN_ENABLE_IMMUTABLE_INSTALLS` should help in the actions that we have that require lock file changes.
```
.github/workflows/release.yml
```
Thanks @joshblack and @tay1orjones for the tips here 🥳
=> build(GithubActions): avoid lockfile issues with yarn env variable

.github/workflows/release.yml, .github/workflows/update.yml
Contributes to #2040 
I think because the yarn environment variables were not initialized correct within the workflow file, they didn't work as expected. I changed it to follow the guidance from github on [setting env variables](https://docs.github.com/en/actions/learn-github-actions/environment-variables#about-environment-variables) within a workflow file
`update.yml`
`release.yml`
=> build(actions): update how env variable is instantiated

packages/cloud-cognitive/src/components/Datagrid/Datagrid.mdx, packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories/StickyActionsColumnStory.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/Datagrid/utils/makeData.js
Contributes to #1609 
Adds a story for sticky row actions. Also fixed the docs tab for the Datagrid which wasn't loading previously. Lastly, the `makeData` function was being exported inside of the `.stories.js` file which made it appear in storybook as a story. I moved it, along with a few other utilities, into it's own separate file so it can be used for the stories and for testing.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories/StickyActionsColumnStory.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js
packages/cloud-cognitive/src/components/Datagrid/utils/makeData.js
```
Storybook
See overflow menu from sticky row …
=> chore(Datagrid): add sticky actions example, fix docs page

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/TagSet/TagSet.js, packages/cloud-cognitive/src/components/TagSet/TagSet.stories.js, packages/cloud-cognitive/src/components/TagSet/_tag-set.scss
Contributes to #2078
TagSet with multiline attribute
Add a multiline attribute to TagSet
Open storybook and open the TagSet > multiline story
Result:
=> feat: add multiline attribute to tagset

packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.js
Contributes to #2071 
Carbon v11 icons are now a function instead of an object. Changed proptypes to reflect this
packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.js
=> fix(user-profile-image): changed prop types to pass test

packages/cloud-cognitive/src/components/AddSelect/AddSelectMetaPanel.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectMetaPanel.test.js
Contributes to #2090 
adds tests for `AddSelectMetaPanel`
=> chore: add select metal panel testing

packages/cloud-cognitive/src/components/AddSelect/AddSelectBody.test.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectBreadcrumbs.test.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectColumn.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectList.js
Contributes to #2124 
adds additional testing to finish up `AddSelect` coverage.
note- the coverage isn't 100% because an error caused by carbon is preventing me from creating passing tests
=> chore: finish up add select testing

packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js
I noticed that our release workflow failed earlier this week, stemming from an issue in the Datagrid StickyActionColumn tests. There was logic to hide some of the overflow menu items based on the data that is randomly generated. Unfortunately, because this data is random, we can't always know for certain which overflow menu item we're clicking on in the test. To fix this I just removed the `shouldHideMenuItem` prop from the array of menu items.
After we review/merge this, I'll run the release workflow again.
`Datagrid.test.js`
Ran tests and ci-check locally
=> fix(Datagrid): fix issue in StickyActionColumn tests

packages/cloud-cognitive/src/components/AddSelect/AddSelectColumn.js
Contributes to #2131 
fixes an issue where if you selected an item in a column and then clicked select all it would add duplicate entries of that item.
=> fix: select all duplicates in add select columns

packages/cloud-cognitive/src/components/ModifiedTabs/ModifiedTabs.js
This fixes the `index-all-enabled.test.js` tests because `ModifiedTabs` needs a default value for the `tabs` prop.
`ModifiedTabs.js`
Confirmed by running the tests in `index-all-enabled.test.js`.
=> fix(ModifiedTabs): add back default tabs value

packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.test.js, packages/cloud-cognitive/src/components/AboutModal/AboutModal.test.js, packages/cloud-cognitive/src/components/ActionBar/ActionBar.test.js, packages/cloud-cognitive/src/components/ActionBar/ActionBarItem.test.js, packages/cloud-cognitive/src/components/ActionSet/ActionSet.test.js, packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.test.js, packages/cloud-cognitive/src/components/ButtonMenu/ButtonMenu.test.js, packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.test.js, packages/cloud-cognitive/src/components/Card/Card.test.js, packages/cloud-cognitive/src/components/Card/CardFooter.test.js, packages/cloud-cognitive/src/components/CreateSidePanel/CreateSidePanel.test.js, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.test.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/EditSidePanel/EditSidePanel.test.js, packages/cloud-cognitive/src/components/ExampleComponent/ExampleComponent.test.js, packages/cloud-cognitive/src/components/ExportModal/ExportModal.test.js, packages/cloud-cognitive/src/components/ImportModal/ImportModal.test.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js, packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.test.js, packages/cloud-cognitive/src/components/TagSet/TagSet.test.js, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.test.js, packages/cloud-cognitive/src/components/Toolbar/Toolbar.test.js, packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.test.js, packages/cloud-cognitive/src/global/js/utils/__tests__/wrap-focus.test.js, packages/cloud-cognitive/src/global/js/utils/wrapFocus.js
Contributes to https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2093
Removes hard coded `cds` from tests that needed to check specific cases against the carbon prefix.
Test files
Ran tests to make sure the same number of tests pass as before this change
=> chore: use carbon prefix from settings file

packages/cloud-cognitive/scripts/generate/index.js, packages/cloud-cognitive/scripts/generate/templates/_STYLE_NAME.scss, packages/cloud-cognitive/scripts/generate/templates/_carbon-imports.scss, packages/cloud-cognitive/scripts/generate/templates/_index-with-carbon.scss, packages/cloud-cognitive/src/components/ActionBar/_index.scss
Contributes to #2122 
With the refactored component sass structure, the `generate` script needed to be updates so that new components will receive the same structure. I've made sure that the output from this script is what is expected from the generated component files to the exporting of the component styles.
`generate` script
Ran `yarn generate TestComponent` locally and confirmed the correct output
=> fix: update generate script to use new sass structure

.github/workflows/sync-main.yml
Contributes to #2134 
Creates (hopefully) a PR from `main` to `carbon-v11` branch — currently set for Mondays 4:30am but open to changing the timing if we prefer not to do this before releases on Tuesdays.
Adds GitHub action for opening a PR to merge `main` to `carbon-v11`
Partly via [Act](https://github.com/nektos/act) and partly on forked repo. This will be the real test though. 🤞
Note: Examples didn’t always show needing a token for checkout action, but testing locally via Act required a personal access token. Used the lerna token here since usage seemed similar but can create a new token for this if it doesn’t work / we prefer.
=> chore: add action to sync v11 with main

packages/core/.storybook/manager.js
To prevent any confusion now that we have a v11 storybook site, I removed the version from the `brandTitle` until we have created our first release candidate supporting Carbon v11.
```
packages/core/.storybook/manager.js
```
Ran storybook locally and confirmed that the brand title was updated
=> chore: remove version number from storybook brand title until one exists

packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss
Issue brought up over [slack](https://ibm-cloud.slack.com/archives/C013ZTX0N6B/p1659968138799829), we had some styles that were changing Carbon data tables. The styles from our components should always be scoped to our components only to avoid these types of issues in the future.
`_datagrid.scss`
Storybook
=> fix(Datagrid): fix style issues between Datagrid and Carbon data table

packages/cloud-cognitive/src/components/InlineEdit/_inline-edit.scss
Issue brought up [over slack](https://ibm-casdesign.slack.com/archives/C013ZTX0N6B/p1659982921891409), Carbon tokens inside of `calc` need to be interpolated in order to compile correctly.
`_inline-edit.scss`
Ensured that sass still compiled and focus outline styling still works
=> fix(InlineEdit): fix sass calc issue with carbon token

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/Datagrid/useActionsColumn.js, packages/cloud-cognitive/src/components/Datagrid/useStickyColumn.js
Contributes to #
1609
Implements actions buttons extensions for Datagrid component
`useActionsColumn.js` - added logic that shows individual buttons when number of actions are less than 3
`useStickyColumn.js` - added logic that removes the datagrid resizer element found in the sticky column. This also affects the Sticky Action Columns story, see https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1783
`Datagrid.stories.js` - added RowActionButton story
storybook
=> feat: Add Row Action Buttons

.github/workflows/release-v11.yml, cspell.json
Contributes to #2163 
It appears that if you want to run the action via `workflow_dispatch` it needs to exist on the branch you're running the action against. Because #2167 included these changes on the `main` branch, we are unable to run this action on the `carbon-v11` branch.
Same changes as #2167 
[Sample project](https://github.com/matthewgallo/releases-test)
=> feat: add release action in v11 branch to run with workflow_dispatch

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/AboutModal/_about-modal.scss
I was confirming the v2 release worked ok in a sample application and when I imported the styles I was getting an error in the build along the lines of
```
"+" and "-" must be surrounded by whitespace in calculations.
```
which led me to find an issue in the `_about-modal.scss` styles.
`_about-modal.scss`
Adding the whitespace inside of the calc fixes breaking build
=> fix(AboutModal): fix spacing issue causing build to break

.github/workflows/release-v11.yml, yarn.lock
Contributes to #2163 
Initial `2.0.0-rc.0` release has been created, this changes the publish script so that it no longer uses `premajor` (which would cause another major release to be created).
I kept the `--ignore-changes` flag because those other packages will be released from our release action that will continue to run from `main` branch.
Removed `premajor` from v11 publish script
Sample project
=> chore: update v2 publish script

.github/workflows/release-v11.yml
Contributes to #2163 
Now that we've made the first release candidate and the first release candidate version bump, I think it makes sense for us to now be able to run this release action on a weekly basis. It will run at the same time as the other version updates (Tues 4:30am).
`.github/workflows/release-v11.yml`
Uses the same cron scheduling as our `main` branch releases
=> chore(v11): add weekly release for v11

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss, packages/cloud-cognitive/src/components/Datagrid/useDefaultStringRenderer.js, packages/cloud-cognitive/src/components/Datagrid/utils/makeData.js
Contributes to #2173 
Adds the option to specify `multiLineWrap` on a per column basis. There is an example added to the basic usage story on the last column.
```
packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss
packages/cloud-cognitive/src/components/Datagrid/useDefaultStringRenderer.js
```
Storybook
=> feat(Datagrid): add multi line wrap option

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/Datagrid/index.js, packages/cloud-cognitive/src/components/Datagrid/useColumnOrder.js, packages/cloud-cognitive/src/components/index.js
Contributes to issue brought up over [slack](https://ibm-cloud.slack.com/archives/C013ZTX0N6B/p1661229457777809).
The main issue here is that `useColumnOrder` is coming from `react-table` so in our stories we just import it from that package. However, our consumers shouldn't need to install `react-table` so I created `useColumnOrder` within the Datagrid component and exported that so it is available to import from our package.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js
packages/cloud-cognitive/src/components/Datagrid/index.js
packages/cloud-cognitive/src/components/Datagrid/useColumnOrder.js
```
Storybook
Removed `import { useColumnOrder} from …
=> fix(Datagrid): export useColumnOrder hook

config/stylelint-config-ibm-products/package.json, package.json, yarn.lock
Updates the token linter to the released version
stylelint-plugin-carbon-tokens from v2.0.0-beta.0 to v2.0.0
Ran stylelint and verified no new warnings were raised.
=> chore: update stylelint plugin to released version

packages/cloud-cognitive/src/components/ImportModal/ImportModal.js
Contributes to #2126 
This PR fixes a bug where the user would pass `accept={[]}` and would always return as an invalid type. Also changed the extension variable to re-add a period in front to align with [HTML's accept attribute standards](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept) of having the filetype with a period in front. 
packages/cloud-cognitive/src/components/ImportModal/ImportModal.js
1. Added another OR statement to return false when the accept is empty (if the user passes an empty accept array that means that it accepts all file types so isInvalidFileType should return false for this case.
2. Currently the extension doesn't have a period in the front, so I added it back in to align with HTML's accept list.
=> fix(ImportModal): empty accepts array and changed extension variable to include period

packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.js, packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.stories.js
Contributes to #2107 
fixes an issue where if no value was supplied to inline edit it causes the placeholder text to not show.
i'll be honest, i'm not as familiar with the need for so much need of `ref`'s in this component. the problem appeared to be related to the fact that `refInput` wasn't being set until the user clicked inside the input when no value prop was supplied. this fix changes that check to use `value` instead of `refInput`. @lee-chase i know you have a lot of experience with this component. perhaps you should review this change and let me know if this works or not since it appears to be a different approach.
you can verify this behavior by going to `InlineEdit.stories.js` and in the template props setting `value: ''` and adding a `placeholder` prop (assuming you're on the …
=> fix: Inline edit 2107

packages/cloud-cognitive/src/components/Datagrid/useSelectRows.js, packages/cloud-cognitive/src/components/Datagrid/useStickyColumn.js
Contributes to #2240 
We needed to check against a value in `datagridState` to know when to change the `left` position value. I added it to `useSelectRows` and then was able to check for `withSelectRows` in `useStickyColumns`.
Before
https://user-images.githubusercontent.com/10215203/187460664-05dd72b5-f441-4e67-b8a6-422398b47195.mov
After
https://user-images.githubusercontent.com/10215203/187460698-26bae5b0-8326-4915-9c0d-80c60c4ca2af.mov
```
packages/cloud-cognitive/src/components/Datagrid/useSelectRows.js
packages/cloud-cognitive/src/components/Datagrid/useStickyColumn.js
```
Storybook
=> fix(Datagrid): add withSelectColumns when using useSelectRows

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to #2185
Title truncation does not occur on strings with no spaces
- Updated the style for title to resolve the issue
- Tests & Storybook
=> fix(SidePanel): style update for title truncation issue

packages/cdai/package.json, yarn.lock
Contributes to #2231
See title.
I'm assuming that CI will bear this out.
=> fix: Remove `@carbon/elements` from `@carbon/ibm-cloud-cognitive-cdai`'s peer dependencies

packages/cdai/src/components/IdeNavigation/Navigation/IdeNavigation.js, packages/cdai/src/components/IdeNavigation/Navigation/__snapshots__/IdeNavigation.spec.js.snap
Contributes to #2215
Previously, `<IdeNavigation>`'s prop `ariaAttributes` incorrectly required *both* `aria-labelledby` *and* `aria-label` to be specified. Now, only one or the other of `aria-labelledby` and `aria-label` is required. If both are supplied, there is no prop type error, so we will have backwards compatibility. (However, this will still cause the same accessibility issue mentioned in #2215.)
The default `ariaAttributes` prop now only specifies `aria-label`, not `aria-labelledby`. The example value of `aria-labelledby` was `'Example Aria Labeled by'` which was never [a meaningful value for this](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) in any case.
Manually... also CI will go a long way here I hope.
=> fix: Require only one of `arial-label` or `aria-labelledby` in `<IdeNavigation>`

.github/workflows/release-v11.yml, .github/workflows/release.yml, yarn.lock
This will hopefully fix the npm auth issues we've been seeing in release actions over the past week which have prevented updates being published to the npm registry. Carbon seems to have also experienced the same issue, see [here](https://github.com/carbon-design-system/carbon/commit/e3dd10d84c03e4ab1e4ae67f9c667c1f24aff040).
Moved `--no-verify-access` in publish script.
Will test after merging by running release action again.
=> fix(release): move no verify access flag in lerna publish command

.github/workflows/release-v11.yml
Best to put the weekly v11 releases on pause until we can better manage upgrading the v11 branch.
`release-v11.yml`
Removing the cron schedule will prevent the action from running weekly.
=> chore: remove scheduled v11 releases

packages/cloud-cognitive/src/components/Datagrid/Datagrid.mdx, packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridSelectAllWithToggle.js, packages/cloud-cognitive/src/components/Datagrid/Extensions/Header/Header.stories.js, packages/cloud-cognitive/src/components/Datagrid/Extensions/RowActionButtons/RowActionButtons.stories.js, packages/cloud-cognitive/src/components/Datagrid/Extensions/Settings/Settings.stories.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useActionsColumn.scss, packages/cloud-cognitive/src/components/Datagrid/styles/_useStickyColumn.scss, packages/cloud-cognitive/src/components/Datagrid/useActionsColumn.js, packages/cloud-cognitive/src/components/Datagrid/useSelectAllToggle.js, packages/cloud-cognitive/src/components/Datagrid/utils/DatagridActions.js, packages/cloud-cognitive/src/components/Datagrid/utils/DatagridPagination.js, packages/cloud-cognitive/src/components/Datagrid/utils/Wrapper.js, packages/cloud-cognitive/src/components/Datagrid/utils/getArgTypes.js, packages/cloud-cognitive/src/global/js/utils/story-helper.js, packages/core/story-structure.js
Contributes to #2270 
This adds a folder structure to some of the Datagrid stories, with the purpose of organizing Datagrid stories based on the Data table extensions found on the [PAL site](https://pages.github.ibm.com/cdai-design/pal/components/data-table/overview/).
See below:
I also setup the stories that are inside of `Datagrid/Extensions/` such that there are some controls that you can now use to change the component. This was not originally done for the other Datagrid stories. I have only done three extensions (Header, Row action buttons, Settings) to start off, to reduce the amount of changes being reviewed. Also, started on some documentation in the `mdx` file. The majority of these changes involved adding new stories files and creating shared components that are used across …
=> chore(Datagrid): start storybook reorganization for Datagrid

examples/carbon-for-ibm-products/example-gallery/src/gallery-config/index.js, packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useMultipleKeyTracking.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js
I noticed after #2269 was merged, it broke the sticky behavior of the sticky columns because of the extra div required for the `useMultipleKeyTracking` hook. I'll make a separate update to allow for sticky columns while using `useInlineEdit`.
```
examples/carbon-for-ibm-products/example-gallery/src/gallery-config/index.js
packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useMultipleKeyTracking.js
```
Storybook
=> fix(Datagrid): allow sticky columns to stick again

packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useMultipleKeyTracking.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js
**Corresponding PR for #2281 for v11 branch**
Allows sticky columns to stick again, see #2281 for further detail.
```
packages/cloud-cognitive/src/components/DataSpreadsheet/hooks/useMultipleKeyTracking.js
```
Storybook
=> fix(Datagrid): allow sticky column to stick again (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js
Contributes to #2280 
The row settings menu should be right aligned to the trigger button that opens it.
`RowSizeRadioGroup.js`
Storybook
=> fix(Datagrid): row size drop down alignment

packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.js, packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.test.js
Contributes to #2030 
I was able to fix this by using `textContent` instead of `innerText`. i have been unable to find a reason as to why this interaction occurs in firefox, which is unfortunate because i think it's beneficial to understand these limitations. either way this seems to work better.
=> fix: inline edit newline fix

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/Datagrid/Extensions/ColumnAlignment/ColumnAlignment.stories.js, packages/cloud-cognitive/src/components/Datagrid/utils/makeData.js, packages/core/story-structure.js
Contributes to #2270 
Adds a new Datagrid extension directory specifically for column alignment. I also added new data to match the usage example for right and center aligned columns from the PAL site, see [here](https://pages.github.ibm.com/cdai-design/pal/components/data-table/column-alignment/usage).
Added new Datagrid extension directory, only storybook presentational change
Storybook
=> chore(Datagrid): add column alignment story extension

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridRow.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useInlineEdit.scss
_Includes @Ratheeshrajan's review feedback fixes for `carbon-v11` branch_
Contributes to #1924
- The row should also receive its hover effect (light gray background) when using keyboard navigation.
- The row should still have its hover effect (light gray background) when a cell is in editing mode
- The dropdown icons are baseline-aligned, should be center-aligned
`DatagridRow.js`
`_useInlineEdit.scss`
Storybook
=> fix(Data Grid): review feedback fix (v11)

packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.js, packages/cloud-cognitive/src/components/OptionsTile/_options-tile.scss
Contributes to #2271 
Options tile truncation bug
- updated [_options-tile.scss](https://github.com/carbon-design-system/ibm-cloud-cognitive/compare/main...punnoosewilson:ibm-cloud-cognitive:%232271?expand=1#diff-42e245e72364e425d798cee3d103d4124ff0bf9b29dd85091ed08f956881004a) for style updates.
- updated [OptionsTile.js](https://github.com/carbon-design-system/ibm-cloud-cognitive/compare/main...punnoosewilson:ibm-cloud-cognitive:%232271?expand=1#diff-1bb9a3a5b36cb4ef9a3b9a80486898a350caeb9cd2db507f03051dda722b1272) for previewing the truncated text on hover.
- Storybook
=> fix: update option title truncation issue

packages/cloud-cognitive/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.js
Contributes to #2278 
Need to make the `formTitle` prop as optional.
- Updated the `formTitle` prop as optional. 
Storybook
=> fix(CreateTearsheetNarrow): Update formTitle prop as optional

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/InlineEdit/handleGridKeyPress.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useInlineEdit.scss, packages/cloud-cognitive/src/components/Datagrid/utils/getInlineEditColumns.js
Contributes to #1924 
@Ratheeshrajan I took over from where you had left off since you're looking at https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1923 right now.
This change adds validation to the text and number types for Datagrid inline edit (`useInlineEdit`). In order for the component to know whether a field is invalid, there is a `validator` function that is included in the column inline editing configuration. Also included according to [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/inline-editing/usage#validation), when in edit mode and input is invalid, `enter` and `tab` do not allow the cell to make new changes until the input is valid once again.
See example below:
```js
{
Header: 'Age',
accessor: 'age',
width: 120, …
```
=> feat(Datagrid): add validation to inline editing (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/InlineEdit/handleGridKeyPress.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useInlineEdit.scss, packages/cloud-cognitive/src/components/Datagrid/utils/getInlineEditColumns.js
Contributes to #1924 
@Ratheeshrajan I took over from where you had left off since you're looking at https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1923 right now.
This change adds validation to the text and number types for Datagrid inline edit (`useInlineEdit`). In order for the component to know whether a field is invalid, there is a `validator` function that is included in the column inline editing configuration. Also included according to [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/inline-editing/usage#validation), when in edit mode and input is invalid, `enter` and `tab` do not allow the cell to make new changes until the input is valid once again.
See example below:
```js
{
Header: 'Age',
accessor: 'age',
width: 120, …
```
=> feat(Datagrid): add validation to inline editing

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/InlineEdit/_inline-edit.scss
Contributes to #2283 (v11)
Carbon tokens inside of calc needed to be interpolated in order to build correctly
`_inline-edit.scss`
`styles.test.js.snap`
Styling still works correctly and after carbon token is interpolated correctly
=> fix(InlineEdit): fix calc interpolation issue (v11)

packages/security/src/components/Nav/Nav.js, packages/security/src/components/Nav/NavList/NavList.js, packages/security/src/components/__tests__/__snapshots__/public-api-test.js.snap
Contributes to #2333
Fix for NavList throwing error when using production build.
Swap from using type.name to type.displayName.   
type.name is not safe to use with production builds which may minify symbol names.
- verified unit tests pass
- verified component functions correctly in storybook
=> fix(NavList): use type.displayName

packages/cloud-cognitive/src/components/AddSelect/AddSelectBody.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectBody.test.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js, packages/cloud-cognitive/src/components/Datagrid/Extensions/InlineEdit/InlineEdit.stories.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useInlineEdit.scss, packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.mdx, packages/core/story-structure.js
Contributes to #2270
This PR adds a new extension directory in storybook for the datagrid component for `InlineEdit`. While working on this, I found a few css issues with the focus region outlines which I've also provided fixes for.
```
packages/cloud-cognitive/src/components/Datagrid/Extensions/InlineEdit/InlineEdit.stories.js
packages/cloud-cognitive/src/components/Datagrid/styles/_useInlineEdit.scss
packages/core/story-structure.js
```
Storybook
=> chore(Datagrid): add inline edit extension directory for story organization (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js, packages/cloud-cognitive/src/components/Datagrid/Extensions/InlineEdit/InlineEdit.stories.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useInlineEdit.scss, packages/core/story-structure.js
Contributes to #2270
This PR adds a new extension directory in storybook for the datagrid component for `InlineEdit`. While working on this, I found a few css issues with the focus region outlines which I've also provided fixes for.
```
packages/cloud-cognitive/src/components/Datagrid/Extensions/InlineEdit/InlineEdit.stories.js
packages/cloud-cognitive/src/components/Datagrid/styles/_useInlineEdit.scss
packages/core/story-structure.js
```
Storybook
=> chore(Datagrid): add inline edit extension directory for story organization

packages/cloud-cognitive/src/components/AddSelect/_add-select.scss, packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/ButtonWrapper.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsModal.js, packages/cloud-cognitive/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js, packages/cloud-cognitive/src/components/Datagrid/_storybook-styles.scss, packages/cloud-cognitive/src/components/Datagrid/styles/addons/_CustomizeColumnsModal.scss, packages/cloud-cognitive/src/components/Datagrid/utils/getArgTypes.js, packages/core/story-structure.js
Contributes to #2270 
Adds column customization storybook directory for datagrid component.
```
packages/cloud-cognitive/src/components/AddSelect/_add-select.scss
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/ButtonWrapper.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsModal.js
packages/cloud-cognitive/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js
packages/cloud-cognitive/src/components/Datagrid/_storybook-styles.scss …
```
=> chore(Datagrid): create customize columns storybook extension (v11)

config/jest-config-ibm-cloud-cognitive/setup/setupFiles.js, config/jest-config-ibm-cloud-cognitive/setup/setupFilesAfterEnv.js, packages/cloud-cognitive/package.json, packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/CreateSidePanel/CreateSidePanel.test.js, packages/cloud-cognitive/src/components/EditSidePanel/EditSidePanel.test.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.stories.js, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss, packages/cloud-cognitive/src/components/SidePanel/_storybook-styles.scss, packages/cloud-cognitive/src/components/SidePanel/motion/variants.js, packages/cloud-cognitive/src/global/js/utils/getBezierValues.js, packages/cloud-cognitive/src/global/js/utils/motionConstants.js, yarn.lock
Contributes to #2304 
Same changes as https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2312 but for v11 branch.
This is a refactor of the entrance/exit animation for the SidePanel component using framer motion, in replace of the current approach. Because of the animation issue brought up in #2304 it seemed like a good time to take a look at refactoring the motion here. Especially because of the cross browser issues that have been brought up.
I started off just by replacing the entrance/exit animation/micro-interaction with framer motion. I think we could potentially at some point in the future replace the title animation with framer motion as well, but wanted to for now just focus on the entrance/exit.
```
config/jest-config-ibm-cloud-cognitive/setup/setupFiles.js …
```
=> fix(SidePanel): motion refactor using framer motion (v11)

packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.js, packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.mdx, packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.test.js
Contributes to #2341 
adds tests for inline edit v2. code coverage is at 100%
=> chore: add inline edit v2 tests

packages/cloud-cognitive/package.json, scripts/updateSourceMaps.js
Contributes to #1864 
This PR includes a script that changes the relative path to the `node_modules` directory in each of the sass source maps (ie `.css.map` files) which fixes the path used within the map files themselves.
```
packages/cloud-cognitive/package.json
scripts/updateSourceMaps.js
```
To test this change, I ran the build script from `packages/cloud-cognitive` which now includes a new script `"build-css-update-maps": node ../../scripts/updateSourceMaps.js` which is run after the source maps are created. This script changes the path to `node_modules` inside of each map file. After that was run, I copied over the generated `css` directory into a sample app that uses our package. Then I ran `react-scripts build` in the sample app and no longer see source map errors anymore.
=> fix(builds): add script to fix `node_modules` path in sass source maps (v11)

packages/cloud-cognitive/src/components/EditUpdateCards/EditUpdateCards.js, packages/cloud-cognitive/src/components/EditUpdateCards/EditUpdateCards.mdx, packages/cloud-cognitive/src/components/EditUpdateCards/EditUpdateCards.stories.js, packages/cloud-cognitive/src/components/EditUpdateCards/EditUpdateCards.test.js, packages/cloud-cognitive/src/components/EditUpdateCards/_carbon-imports.scss, packages/cloud-cognitive/src/components/EditUpdateCards/_edit-update-cards.scss, packages/cloud-cognitive/src/components/EditUpdateCards/_index-with-carbon.scss, packages/cloud-cognitive/src/components/EditUpdateCards/_index.scss, packages/cloud-cognitive/src/components/EditUpdateCards/_storybook-styles.scss, packages/cloud-cognitive/src/components/EditUpdateCards/index.js, packages/cloud-cognitive/src/components/_index-with-carbon.scss, packages/cloud-cognitive/src/components/_index.scss, packages/cloud-cognitive/src/components/index.js, packages/cloud-cognitive/src/global/js/package-settings.js, packages/core/story-structure.js
Contributes to #1259 
Editable cards allow a quick way to update assets in C&CS products.
- Included the edit and update feature for the "Productive Card".
PS: We are waiting for "Expressive Card" edit and update design.
- Storybook
=> feat(EditUpdateCards): Edit and update cards - v11

examples/carbon-for-ibm-products/APIKeyModal/package.json, examples/carbon-for-ibm-products/AboutModal/package.json, examples/carbon-for-ibm-products/Cascade/package.json, examples/carbon-for-ibm-products/CreateTearsheet/package.json, examples/carbon-for-ibm-products/CreateTearsheetNarrow/package.json, examples/carbon-for-ibm-products/Datagrid/package.json, examples/carbon-for-ibm-products/EmptyStates/package.json, examples/carbon-for-ibm-products/ExportModal/package.json, examples/carbon-for-ibm-products/ExpressiveCard/package.json, examples/carbon-for-ibm-products/OptionsTile/package.json, examples/carbon-for-ibm-products/ProductiveCard/package.json, examples/carbon-for-ibm-products/RemoveModal/package.json, examples/carbon-for-ibm-products/Saving/package.json, examples/carbon-for-ibm-products/SidePanel/package.json, examples/carbon-for-ibm-products/StatusIcon/package.json, examples/carbon-for-ibm-products/TagSet/package.json, examples/carbon-for-ibm-products/Tearsheet/package.json, examples/carbon-for-ibm-products/UserProfileImage/package.json, examples/carbon-for-ibm-products/WebTerminal/package.json, examples/carbon-for-ibm-products/ccs-base-react-16/package.json, examples/carbon-for-ibm-products/ccs-base-react-17/package.json, examples/carbon-for-ibm-products/example-gallery/package.json, examples/carbon-for-ibm-products/prefix-example/package.json
Contributes to #2379 
Removes eslint config since it's no longer needed with react-scripts
All package.json inside of `examples/`
=> chore: removes eslint config to fix errors

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
Contributes to #2371 
Adds new property that can be passed inside of the `useDatagrid` hook to customize the height of the virtual table body (used with `useInfiniteScroll` hook).
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
```
Storybook
=> feat(Datagrid): allow for customizable virtual height (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
Contributes to #2371 
Adds new property that can be passed inside of the `useDatagrid` hook to customize the height of the virtual table body (used with `useInfiniteScroll` hook).
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
```
Storybook
=> feat(Datagrid): allow for customizable virtual height

packages/cdai/src/components/IdeCard/_IdeCard.scss, packages/security/src/components/FilterPanel/LEGACY_FilterPanel/FilterSubcategory/_index.scss, packages/security/src/components/FilterPanel/LEGACY_FilterPanel/FilterSubcategory/_mixins.scss, packages/security/src/components/IconButton/_mixins.scss, packages/security/src/globals/grid/vendor/css-gridish/scss/_functions.scss, packages/security/src/globals/grid/vendor/css-gridish/scss/_mixins.scss, packages/security/src/globals/grid/vendor/css-gridish/scss/_sass-list-maps.scss, packages/security/src/globals/grid/vendor/css-gridish/scss/_utilities.scss
Contributes to #2393 
We have had a lot of sass deprecation warnings in our local development server regarding `/` outside of a `calc()`. The changes in this PR remove all of the warnings. Some instances have been addressed by simply multiplying instead of dividing (ie multiplying by ` * 0.5` in cases of `/ 2`) and some instances where that is not possible the sass:math built in module has been used (ie `math.div()`).
_**Note**_: this is only currently possible on the `carbon-v11` branch because it uses the module system. Because `main` is not using the module system yet, we can't `@use "sass:math";`.
```
packages/cdai/src/components/IdeCard/_IdeCard.scss
packages/security/src/components/FilterPanel/LEGACY_FilterPanel/FilterSubcategory/_index.scss …
```
=> chore: address sass deprecation warnings

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to #2394 
Fixes the positioning of the title, subtitle, and action bar when used in static version of panel. I don't remember the reasoning for the extra spacing being added here, but I checked this change in Chrome, Firefox, and Safari and everything looks to be rendering as expected now.
The issue can be seen [here](https://v11-carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-side-panel-sidepanel--with-static-title).
Storybook and updated styles snapshot
=> fix(SidePanel): address positioning in static version (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js
Contributes to #2399 
This PR fixes an issue where we were not using the [new onChange prop signature](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md#checkbox) for the Carbon checkbox. This was causing the checkboxes in the customize columns modal to not work as expected. After using the new signature, where the checkbox state is returned in the second callback argument, it is working again.
Issue can be seen [here](https://v11-carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-columncustomization--column-customization-usage-story) and after opening the customize columns modal you'll notice that the checkboxes do not work.
_**Note**_: This is only a v11 issue
``` …
```
=> fix(Datagrid): customize columns checkbox fix

packages/cloud-cognitive/carbon.yml, packages/security/carbon.yml
Contributes to https://github.com/carbon-design-system/carbon-platform/issues/1380
- Adds `externalDocsUrl`s to the index, so the IBM Products library’s assets have `View asset docs` in Carbon Platform.
- Replaces Storybook links with v11 equivalents
- add external docs urls
- clean up ibm security carbon yml formatting
- fix smart quote in description
- replace v1/v10 Storybook links with v2/v11 Storybook links
Storybook
=> docs: add external docs urls for v11

packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
Contributes to #2400 
This addresses the scrolling issue in the PageHeader. The only portion of the PageHeader that scrolls the page is from a utility called `utilSetCollapsed` that is called from inside of a `useEffect`. I think the issue here is that the previous check to run this function only look to see if `collapseHeader` was a `boolean` type. But we only want to ever run this utility if `collapseHeader` is true.
```
packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
```
Haven't been able to fully reproduce this issue, but `utilSetCollapsed` should only ever be called when `collapsed` is true. So I think the useEffect containing `utilSetCollapsed` is being run when it shouldn't be which is causing the scrolling.
=> fix(PageHeader): restrict useEffect logic to prevent scrolling

packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
Contributes to #2400 
This addresses the scrolling issue in the PageHeader. The only portion of the PageHeader that scrolls the page is from a utility called `utilSetCollapsed` that is called from inside of a `useEffect`. I think the issue here is that the previous check to run this function only look to see if `collapseHeader` was a `boolean` type. But we only want to ever run this utility if `collapseHeader` is true.
```
packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
```
Haven't been able to fully reproduce this issue, but `utilSetCollapsed` should only ever be called when `collapsed` is true. So I think the useEffect containing `utilSetCollapsed` is being run when it shouldn't be which is causing the scrolling.
=> fix(PageHeader): restrict useEffect logic to prevent scrolling (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js
Contributes to #2345 
This should resolve the issue initially brought up in #2345, specifically the warning about a change in the order of react hooks.
I also noticed this react warning when starting up a sample application using the Datagrid. Thanks @johannwagner for adding details around this issue.
```
```
Storybook, component still renders as expected.
=> fix(Datagrid): render pagination as component

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js
Contributes to #2345 
This should resolve the issue initially brought up in #2345, specifically the warning about a change in the order of react hooks.
I also noticed this react warning when starting up a sample application using the Datagrid. Thanks @johannwagner for adding details around this issue.
```
```
Storybook, component still renders as expected.
=> fix(Datagrid): render pagination as component (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid.mdx, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js
Contributes to #2407 
Added Datagrid documentation around column alignment and inline editing.
```
```
Viewed in Storybook docs tab for Datagrid component
=> docs(Datagrid): add column alignment and inline edit docs (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js
Contributes to #2417 
Fixes an issue where if you search in a table with selectable rows, then select a row and clear the batch action toolbar the search is cleared but the filtered rows are not reset. The `globalFilter` value from `react-table` just needed to be reset in the batch action toolbar `onCancel`.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js
```
Storybook
=> fix(Datagrid): #2417 datagrid select rows filter issue (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js
Contributes to #2417 
Fixes an issue where if you search in a table with selectable rows, then select a row and clear the batch action toolbar the search is cleared but the filtered rows are not reset. The `globalFilter` value from `react-table` just needed to be reset in the batch action toolbar `onCancel`.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js
```
Storybook
=> fix(Datagrid): #2417 datagrid select rows filter issue

packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridRow.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useExpandedRow.scss, packages/cloud-cognitive/src/components/Datagrid/useRowExpander.js
Contributes to #1607 
Contributes to overall accessibility to the Datagrid component, specifically the row expanders. Previously it was not possible to interact with this element via keyboard. I changed the expander element from a `span` to a `button` to fix this issue.
See preview story with expandable rows [here](https://deploy-preview-2434--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-expandablerow--expandable-row-story)
```
packages/cloud-cognitive/src/components/Datagrid/styles/_useExpandedRow.scss
packages/cloud-cognitive/src/components/Datagrid/useRowExpander.js
```
Storybook
=> fix(Datagrid): allow keyboard interaction with row expander

packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridRow.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useExpandedRow.scss, packages/cloud-cognitive/src/components/Datagrid/useRowExpander.js
Contributes to #1607 
Contributes to overall accessibility to the Datagrid component, specifically the row expanders. Previously it was not possible to interact with this element via keyboard. I changed the expander element from a `span` to a `button` to fix this issue.
See preview story with expandable rows [here](https://deploy-preview-2435--v11-carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-expandablerow--expandable-row-story)
```
packages/cloud-cognitive/src/components/Datagrid/styles/_useExpandedRow.scss
packages/cloud-cognitive/src/components/Datagrid/useRowExpander.js
```
Storybook
=> fix(Datagrid): allow keyboard interaction with row expander (v11)

.github/workflows/release-v11.yml, .github/workflows/release.yml
Contributes to #2427 
Changes the current npm access token we use to publish packages to one that was created by the `carbon-bot` account.
`github/workflows/release.yml`
`github/workflows/release-v11.yml`
I made sure that the new token has correct privileges to publish our packages.
=> chore: use new carbon-bot token for releases (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useNestedRows.scss, packages/cloud-cognitive/src/components/Datagrid/useNestedRowExpander.js
Contributes to #2291 
This PR adds some styling so that the border of the last nested row extends the full width of the row. I also added keyboard support for this expander, similar to `useRowExpander`.
```
packages/cloud-cognitive/src/components/Datagrid/styles/_useNestedRows.scss
packages/cloud-cognitive/src/components/Datagrid/useNestedRowExpander.js
```
Storybook
_Before_
_After_
=> fix(Datagrid): #2291 extend last nested row border (v11)

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/ActionSet/ActionSet.js, packages/cloud-cognitive/src/components/ActionSet/ActionSet.test.js, packages/cloud-cognitive/src/components/ActionSet/_action-set.scss
Contributes to #2437 
This PR allows for ActionSet buttons to not always be expressive (ie from the `isExpressive` prop). Prior to this change, we hard coded each button in the action set to be expressive.
```
packages/cloud-cognitive/src/components/ActionSet/ActionSet.js
packages/cloud-cognitive/src/components/ActionSet/ActionSet.test.js
packages/cloud-cognitive/src/components/ActionSet/_action-set.scss
```
Storybook and added to ActionSet tests
=> fix(ActionSet): allow for non expressive buttons (v11)

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/ActionSet/ActionSet.js, packages/cloud-cognitive/src/components/ActionSet/ActionSet.test.js, packages/cloud-cognitive/src/components/ActionSet/_action-set.scss
Contributes to #2437 
This PR allows for ActionSet buttons to not always be expressive (ie from the `isExpressive` prop). Prior to this change, we hard coded each button in the action set to be expressive.
```
packages/cloud-cognitive/src/components/ActionSet/ActionSet.js
packages/cloud-cognitive/src/components/ActionSet/ActionSet.test.js
packages/cloud-cognitive/src/components/ActionSet/_action-set.scss
```
Storybook and added to ActionSet tests
=> fix(ActionSet): allow for non expressive buttons

packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.js, packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.stories.js, packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.test.js, packages/cloud-cognitive/src/global/js/hooks/index.js, packages/cloud-cognitive/src/global/js/hooks/useControllableState.js
Contributes to #1540 
Incorporates the `useControllableState` hook from Carbon into the `OptionsTile` component and adds an `onChange` prop which is a callback function that will be called whenever the `OptionsTile` is either closed or opened.
```
packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.js
packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.stories.js
packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.test.js
packages/cloud-cognitive/src/global/js/hooks/index.js
packages/cloud-cognitive/src/global/js/hooks/useControllableState.js
```
Storybook and ran tests for OptionsTile
=> feat(OptionsTile): add onChange prop and useControllableState hook (v11)

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/PageHeader/PageHeaderTitle.js, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
Contributes to #2409
Update h1 tag to truncate page title (v11)
`_page-header.scss`
`PageHeaderTitle.js`
`styles.test.js.snap`
Updated snapshot tests and checked styling shows as expected
=> fix(PageHeader): Page header title truncation v11

packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/cloud-cognitive/src/components/DataSpreadsheet/utils/handleCellDeletion.js
Small update to cell deletion interaction (`handleCellDeletion`) to prevent deletion from any row or column header cells. The row/column needs to be selected first, and then deletion is allowed.
```
packages/cloud-cognitive/src/components/DataSpreadsheet/utils/handleCellDeletion.js
```
Storybook, prior to this change there was an error in the browser console when pressing the `Delete` key while the active cell was in a column or row header.
=> fix(DataSpreadsheet): prevent delete error from header cells (v11)

scripts/audit.js
Contributes to issue with CI lint step hanging.
`yarn audit` from yarn 1 is renamed to `yarn npm audit` in yarn berry.
https://yarnpkg.com/getting-started/migration#renamed
`yarn audit` becomes `yarn npm audit` in our audit script
`yarn ci-check:lint` now completes locally.
=> chore: fix yarn audit

packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridRow.js, packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss, packages/cloud-cognitive/src/components/Datagrid/useNestedRows.js
Contributes to #2291 
This PR adds the indicator line for nested rows that are also parent rows (ie they have sub rows within them). See attached screen recording for example:
https://user-images.githubusercontent.com/10215203/204433944-a31c5e75-f4d4-47d6-acc4-04a4916bf2ef.mp4
```
packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss
packages/cloud-cognitive/src/components/Datagrid/useNestedRows.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js
```
Storybook and ran tests for Datagrid
=> chore(Datagrid): add nested row indicator for child rows (v11)

packages/cloud-cognitive/src/components/ActionBar/ActionBarOverflowItems.js
Contributes to #2510
forward the action's onClick handler to the OverflowMenuItem
verified in storybook, with and without a click handler
=> fix(ActionBar): overflow menu item onClick

packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.js
Contributes to #2438 
Modal not opening after closing it with outside click
Added onClose function with a state change(onClose={()=>setModalIsOpen(false)})
Storybook
=> fix(create full page): modal close issue fixed

packages/cloud-cognitive/src/components/InlineEditV1/InlineEditV1.js, packages/cloud-cognitive/src/components/InlineEditV1/InlineEditV1.test.js
Contributes to #2526 
This PR moves the v1 InlineEdit deprecation warning inside of the component so that it only logs the warning when using this component.
`InlineEditV1.js`
Storybook, confirmed that the warning is only showing when using this component.
=> fix(InlineEdit): move warning inside component

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
These changes were reflected in the v11 PR for FilterFlyout and FilterSummary #2525. This PR just adds those changes here too for v10.
- Fixed where Checkbox on change wasn't being called correctly
- Removed children from Proptypes
- Adds the `selectedItem` prop to Dropdown to sync with state
=> fix(Datagrid): fixed some issues in filter flyout

packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.test.js
i forgot to include the test for using `primaryButtonDisabled` for `RemoveModal`
=> fix: adds primaryButtonDisabled test to RemoveModal v11

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js
Contributes to #2545 
Allows the selection inline edit type in Datagrid to now use either an array of strings or array of objects. I tested this by passing an array of strings in `getInlineEditColumns.js` to the column that supports the `selection` type after I made the changes and confirmed that the interaction still worked as expected.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js
```
Storybook
=> fix(Datagrid): update inline edit selection type to support string items (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridEmptyBody.js, packages/cloud-cognitive/src/components/Datagrid/utils/getArgTypes.js
Adds empty state type property, allowing for error empty state to be used.
FYI @holmansze 
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridEmptyBody.js
packages/cloud-cognitive/src/components/Datagrid/utils/getArgTypes.js
```
=> feat(Datagrid): add empty state type option

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridRow.js
Contributes to #2498 
This PR resolves the React hooks error that has been observed from the Datagrid component. This was stemming from the DatagridRow component which is conditionally rendered and then uses `useContext`, so we'll have to find another way to add the `${blockClass}__carbon-row-hover-active` class (this is something that is specific to the inline editing extension).
```
```
Storybook
=> fix(Datagrid): resolve react hook error from datagrid row (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridRow.js
Contributes to #2498 
This PR resolves the React hooks error that has been observed from the Datagrid component. This was stemming from the DatagridRow component which is conditionally rendered and then uses `useContext`, so we'll have to find another way to add the `${blockClass}__carbon-row-hover-active` class (this is something that is specific to the inline editing extension, fyi @Ratheeshrajan).
```
```
Storybook
=> fix(Datagrid): resolve react hook error from datagrid row

packages/cloud-cognitive/src/components/Datagrid/Extensions/InlineEdit/InlineEdit.stories.js, packages/cloud-cognitive/src/components/Datagrid/_storybook-styles.scss, packages/cloud-cognitive/src/components/Datagrid/utils/getInlineEditColumns.js
Contributes to #2506 
Adds a note about which columns have validation on the storybook example.
```
packages/cloud-cognitive/src/components/Datagrid/Extensions/InlineEdit/InlineEdit.stories.js
packages/cloud-cognitive/src/components/Datagrid/_storybook-styles.scss
packages/cloud-cognitive/src/components/Datagrid/utils/getInlineEditColumns.js
```
Storybook
=> chore(Datagrid): provide context for columns using validation (v11)

packages/cloud-cognitive/src/components/Datagrid/Extensions/InlineEdit/InlineEdit.stories.js, packages/cloud-cognitive/src/components/Datagrid/_storybook-styles.scss, packages/cloud-cognitive/src/components/Datagrid/utils/getInlineEditColumns.js
Contributes to #2506 
Adds a note about which columns have validation on the storybook example.
```
packages/cloud-cognitive/src/components/Datagrid/Extensions/InlineEdit/InlineEdit.stories.js
packages/cloud-cognitive/src/components/Datagrid/_storybook-styles.scss
packages/cloud-cognitive/src/components/Datagrid/utils/getInlineEditColumns.js
```
Storybook
=> chore(Datagrid): make note about validation on storybook example

packages/cloud-cognitive/src/components/Datagrid/Datagrid.mdx, packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js, packages/cloud-cognitive/src/components/Datagrid/Extensions/Filtering/Filtering.stories.js, packages/cloud-cognitive/src/components/Datagrid/utils/DatagridActions.js, packages/cloud-cognitive/src/components/Datagrid/utils/getArgTypes.js
Contributes to #2523 
This adds documentation for filter flyout and adds a story file for data table filtering.
- Changed filtering stories from `Datagrid.stories.js` and moved it to `Filtering.stories.js`
- Fixed typo with `SelectAllWithToggle` import and updated path to fix error
- Adds Filtering docs to `Datagrid.mdx`
=> feat(Datagrid): makes seperate story file and adds docs for FilterFlyout (v11)

examples/carbon-for-ibm-products/example-gallery/package.json, examples/carbon-for-ibm-products/prefix-example/src/Example/Example.js
Corrects package.json in the `example-gallery` and location of prefix in `prefix-example`;
Built and ran examples locally.
=> chore: fix v10 examples

examples/carbon-for-ibm-products/example-gallery/src/gallery-config/index.js, examples/carbon-for-ibm-products/gallery-examples.test.js, scripts/example-gallery-builder/gallery-config.js
Adds comment to `examples/carbon-for-ibm-products/gallery-examples.test.js` as to why a test or import is skipped.
=> chore: add gallery test skip comment

examples/carbon-for-ibm-products/.babelrc, examples/carbon-for-ibm-products/gallery-examples.test.js, scripts/example-gallery-builder/gallery-config.js
Add a `.babelrc` to examples/carbon-for-ibm-products for `gallery-examples.test.js` as well.
Remove skipped test for CarbonV11Template since the import gets skipped (so it’s undefined in the test even if skipped).
There might be a better approach, but this seemed simplest for now. This should still allow skipped tests if we need but not create tests for skipped imports.
`examples/carbon-for-ibm-products/.babelrc`
`scripts/example-gallery-builder/gallery-config.js`
`examples/carbon-for-ibm-products/gallery-examples.test.js` (generated in precommit)
During commit/precommit 😅
=> chore: fix example gallery tests

packages/cloud-cognitive/src/components/ButtonMenu/ButtonMenu.js, packages/cloud-cognitive/src/components/ButtonMenu/ButtonMenu.test.js
Contributes to #2508
Current version of `ButtonMenu` uses the incorrect prop for Carbon buttons.
The `lg` props maps to 64px height button in v10, but our designs use the 48px button (`default`).
Since the `lg` prop will map to the correct 48px in v11, we accept `lg` and map it to `default` in v10.
This also allows us to pass `size` to OverflowMenu so that the item sizes match the button size, as shown in the [design guidance](https://pages.github.ibm.com/cdai-design/pal/components/button-guidance/menu-and-combo-buttons/).
Have not opened a v11 PR since ButtonMenu is out of sync on v11 — FYI @qbi11y 
`ButtonMenu.js`
- Map `lg` to `default` for v10
- Pass `size` to OverflowMenu
`ButtonMenu.test.js`
- Change the checked prop from `lg` to `md` since that behaves consistently
- Storybook
=> fix(ButtonMenu): update lg size

packages/cloud-cognitive/src/components/TagSet/TagSetOverflow.js
Fixes to #1677 Focus Issue in TagSet component when tooltip is opened for first time
Updates the handleChange method to check the event type as indicated in the related Carbon issue.
1. In storybook change looking at the many tags story for TagSet. 
2. Change the width of the container until there are fewer than 10 items in the overflow.
3. Click the over flow.
Previously the tip only opened if the overflow already had focus (before the click). It should now correctly open and close as expected.
=> fix: tagset overflow first open

packages/cloud-cognitive/src/components/ButtonMenu/ButtonMenu.js
Pass `size` to OverflowMenu so that menu items match the button size, as shown in the [design guidance](https://pages.github.ibm.com/cdai-design/pal/components/button-guidance/menu-and-combo-buttons/).
Contributes to #2508
`ButtonMenu.js`
Storybook
=> fix(ButtonMenu): menu size

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss, packages/cloud-cognitive/src/components/Datagrid/utils/DatagridActions.js
~**DO NOT MERGE UNTIL #2612 IS MERGED.** Marking as draft until until v11 ButtonMenu fix is merged.~
Contributes to #2508
Fixes for datagrid actions dropdown.
- Use `ChevronDown` instead of `Add` in examples
- Add className to DatagridActions ButtonMenu menu options to change background color*
- Update story name to ActionsDropdown for easier discovery
*`light` prop is deprecated in favor of `Layer` but need to investigate whether/how to effectively leverage `Layer`s in components or if using CSS is the preferred option for now.
Storybook
=> chore(Datagrid): fix actions dropdown styles v11

packages/cloud-cognitive/src/components/index.js
Contributes to #2630
Fix missing export from Datagrid extensions.
Add `useColumnCenterAlign` to exports in 
```
```
=> fix(Datagrid): export useColumnCenterAlign v11

packages/cloud-cognitive/src/components/index.js
Contributes to #2630 
Fix missing export from Datagrid extensions.
Add `useColumnCenterAlign`
```
```
=> fix(Datagrid): export useColumnCenterAlign

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Contributes to #2637 
Fix wrapping of text mid-word in tearsheet descriptions.
Replaces `word-break: break-all` in 
```
packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
```
Storybook
=> fix(Tearsheet): prevent description breaking

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Contributes to #2637 
Fix wrapping of text mid-word in tearsheet descriptions.
Replaces `word-break: break-all` in 
```
packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
```
Storybook
=> fix(Tearsheet): prevent description breaking v11

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js, packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss
Contributes to #2585 
The filter summary has two height options. The 48 px height should be used with the medium, large, and extra-large row heights. The 32px height should be used with extra small and small row heights. 
`styles/_datagrid.scss`
`DatagridToolbar.js`
Storybook
=> fix(DataGrid): filter summary add heights options v11

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js, packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss
Contributes to #2585 
The filter summary has two height options. The 48 px height should be used with the medium, large, and extra large row heights. The 32px height should be used with extra small and small row heights. 
`styles/_datagrid.scss`
`DatagridToolbar.js`
Storybook
=> fix(DataGrid): filter summary add heights options

packages/cloud-cognitive/src/components/AddSelect/AddSelect.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectBody.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectBody.test.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectColumn.js, packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.stories.js
fixes a small bug in `AddSelectColumn`. also attempts to add additional coverage, but unfortunately it looks like tests are failing due to carbons `OverflowMenu`
=> chore: add select column coverage

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DraggableElement.js, packages/cloud-cognitive/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js, packages/cloud-cognitive/src/components/Datagrid/styles/_draggableElement.scss, packages/cloud-cognitive/src/components/Datagrid/styles/addons/_CustomizeColumnsTearsheet.scss
Contributes to #2504
Includes spacing and styling fixes from design review and fixes to draggable styles styles based on drag and drop guidance.
To keep review manageable, excluded the enhancement for fixed columns in column customization from this PR.
Fix tokens and spacing from design review plus broken classnames and specificity for drag and drop.
Some minor styling differences from v10 since we already use `$icon-disabled` in v11, decided not to switch to `$icon-on-color-disabled` based on the color usage descriptions.
Storybook
=> fix(Datagrid): column customization styles v11

packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridEmptyBody.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridHead.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridRow.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridSelectAll.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridSimpleBody.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridVirtualBody.js, packages/cloud-cognitive/src/components/Datagrid/useSelectRows.js, packages/cloud-cognitive/src/components/Datagrid/utils/DatagridActions.js
Contributes to #2610 
Should fix the DatagridContent invalid import bug? Not really sure but someone hinted that this might be a fix.
All files that destructure from `Datatable`
=> feat: imports all DataTable pieces from `@carbon/react` (v11)

packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.js, packages/cloud-cognitive/src/components/OptionsTile/OptionsTile.stories.js
Closes to #2329 
(v11 only change)
- Wrap OptionsTile content in `<Layer>`
- Remove `props.light` from demo components in storybook
Storybook
=> fix(options-tile): use layer

packages/cdai/package.json, packages/cdai/src/components/IdeFilter/IdeFilter.js, yarn.lock
Contributes to #2695
Removed `react-highlighter` as a dependency, replacing it with a very small inline component `<Highlight>` which fulfills all of the functionality we use.
I'm relying on CI to do this... this code has also worked locally for us.
=> fix: Replace `react-highlighter`

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/hooks/index.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useShouldDisableButtons.js
Simple PR, all it does is it encapsulates the logic for disabling the ActionSet buttons into a custom hook and uses it for FilterFlyout too.
=> feat(Datagrid): Custom hook to handle `ActionSet` disabled state for `FilterPanel` & `FilterFlyout `(v11)

packages/cloud-cognitive/src/components/Datagrid/Extensions/RowHeightSettings/RowHeightSettings.stories.js, packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss, packages/cloud-cognitive/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss, packages/cloud-cognitive/src/components/Datagrid/utils/DatagridActions.js
Contributes to #2503
Design review fixes for row height settings. v11 version.
- Reorder and add row height options from smallest to largest, including`xs` through `xl`
- Fix settings button color on activate/open menu
- Move row height settings button to first icon left of any CTAs
Storybook and ci checks
=> fix(Datagrid): row height settings style fixes v11

packages/cloud-cognitive/README.md
Contributes to #2378 
Add documentation on adding support for ESM in Webpack 4. (Commonly asked with relation to `AnimatePresence` in `framer-motion`).
@lee-chase Not sure if you think there’s a better spot for this (maybe its own section?), but added to package-specific README under the building locally section.
README within `ibm-cloud-cognitive` package.
Markdown Preview
=> chore: add detail on ES modules v11

packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss
Contributes to #2710 
Datagrid title alignment is off if there is only grid title supplied.
`styles/_datagrid.scss`
Storybook
Check `useDenseHeader` true
Remove value from `gridDescription`
=> fix(DataGrid): dense header alignment fix v11

packages/cloud-cognitive/src/components/Card/CardFooter.js, packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.stories.js
Contributes to #2728 
fixes small issue where `CardFooter` was using the wrong prop type for `primaryButtonIcon`
=> fix: cardfooter button icon props update

packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
Contributes to #2485
Exposes the `tooltipPosition` and `tooltipAlignment` props for the SidePanel action toolbar buttons. Users will no longer be locked into bottom, centered tooltips for action toolbar buttons and can change them for their uses.
`tooltipPosition` and `tooltipAlignment` are now exposed props under `actionToolbarButtons`
So far I have tested by setting the props' values in `actionToolbarButtons` and see the correct change in Storybook.
I also tested with `yarn test:c4p` and it passed all tests.
=> feat(SidePanel): expose tooltip props

.github/workflows/sync-commit.yml
Contributes to #2726
Use a test branch to resolve [issue where token triggered from forked repo is not passed](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow).
=> chore: use sync workflow on test branch

packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.js
Contributes to #2784
**Not a regression** as doesn't exist in `v1`.
=> fix(create-full-page): focus modal secondary button

packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.js
=> fix(create-full-page): focus modal secondary button (#2790)

packages/security/achecker.js
Contributes to https://github.com/carbon-design-system/ibm-cloud-cognitive/actions/runs/4599572575/jobs/8126960915?pr=2803
`security` fails recent `accessibility-checker` rule deployment — this pins to last passing until addressed.
=> build(security): pin `accessibility-checker` rules

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/CreateFullPage/_create-full-page.scss
Contributes to #2784
Removed grid margin override in #2807 causing `CreateFullPage` regression at `max` breakpoint — this reverts that.
=> fix(create-full-page): revert `max` grid regression

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js
Contributes to #2801
A change to one of the property names in the object passed to the `handleGridKeyPress` function caused the inline editing to stop working. I changed the property name back and things are now working again.
```
```
Storybook
=> fix(Datagrid): address bug with keyboard interaction for inline edit

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
Contributes to #2820 
Addresses issue where the checkbox to select a row was getting re-ordered in the incorrect place after customizing the column ordering. The filtering of the action columns needs to happen in the `<Columns />` component otherwise the row selection column gets placed as the last column instead of the first, see @youngjunekoh's screenshots in #2820.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
```
Storybook
=> fix(Datagrid): filter action columns from `Columns` component to prevent ordering issues (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
Contributes to #2820 
Addresses issue where the checkbox to select a row was getting re-ordered in the incorrect place after customizing the column ordering. The filtering of the action columns needs to happen in the `<Columns />` component otherwise the row selection column gets placed as the last column instead of the first, see @youngjunekoh's screenshots in #2820.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
```
Storybook
=> fix(Datagrid): filter action columns from `Columns` component to prevent ordering issues

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridVirtualBody.js, packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss, packages/cloud-cognitive/src/components/Datagrid/styles/_useSortableColumns.scss, packages/cloud-cognitive/src/components/Datagrid/useSortableColumns.js
Contributes to #2825 
This PR includes some styling fixes for virtual data grids (can be seen when using infinite scroll option), as well as an issue where the width of the grid was not updating if the window resized at all.
Width issue can be seen below (this only occurs with the virtual data grid)
_Before_
_After_
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss
packages/cloud-cognitive/src/components/Datagrid/styles/_useSortableColumns.scss
packages/cloud-cognitive/src/components/Datagrid/useSortableColumns.js
```
Storybook
=> fix(Datagrid): add background to virtual body header, fix svg scoping

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridVirtualBody.js, packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss, packages/cloud-cognitive/src/components/Datagrid/styles/_useSortableColumns.scss, packages/cloud-cognitive/src/components/Datagrid/useSortableColumns.js
Contributes to #2825 
This PR includes some styling fixes for virtual data grids (can be seen when using infinite scroll option), as well as an issue where the width of the grid was not updating if the window resized at all.
Width issue can be seen below (this only occurs with the virtual data grid)
_Before_
_After_
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss
packages/cloud-cognitive/src/components/Datagrid/styles/_useSortableColumns.scss
packages/cloud-cognitive/src/components/Datagrid/useSortableColumns.js
```
Storybook
=> fix(Datagrid): add background to virtual body header, fix svg scoping (v11)

packages/cloud-cognitive/src/components/Datagrid/Extensions/ClickableRow/ClickableRow.stories.js, packages/cloud-cognitive/src/components/Datagrid/useOnRowClick.js
Contributes to #2843 
Pass click event to `onRowClick` callback to allow consumers to prevent row click behaviors for cells with interactive elements.
```
packages/cloud-cognitive/src/components/Datagrid/Extensions/ClickableRow/ClickableRow.stories.js
packages/cloud-cognitive/src/components/Datagrid/useOnRowClick.js
```
Storybook
=> chore(Datagrid): pass event to `onRowClick` callback

packages/cloud-cognitive/src/components/Datagrid/Extensions/ClickableRow/ClickableRow.stories.js, packages/cloud-cognitive/src/components/Datagrid/useOnRowClick.js
Contributes to #2843 
Pass click event to `onRowClick` callback to allow consumers to prevent row click behaviors for cells with interactive elements.
```
packages/cloud-cognitive/src/components/Datagrid/Extensions/ClickableRow/ClickableRow.stories.js
packages/cloud-cognitive/src/components/Datagrid/useOnRowClick.js
```
Storybook
=> chore(Datagrid): pass event to `onRowClick` callback (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid.mdx, packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/index.js, packages/cloud-cognitive/src/components/Datagrid/utils/getAutoSizedColumnWidth.js, packages/cloud-cognitive/src/components/index.js
Contributes to #2045 
Added an auto size utility function that will be exported for consumers to use on columns they wish to be auto sized and not receive a custom width or the default column width of 150px. Added some usage docs to the Datagrid.mdx file as well.
```
packages/cloud-cognitive/src/components/Datagrid/index.js
packages/cloud-cognitive/src/components/Datagrid/utils/getAutoSizedColumnWidth.js
```
Storybook
=> feat(Datagrid): add auto size column support (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js
Contributes to #2856 
When using row height settings with customize columns the open value for the `RowSizeDropdown` component does not update (see this [code sandbox](https://codesandbox.io/s/epic-fire-q8c41o?file=/src/Example/Example.js)), this prevents the overflow menu from opening at all. I think setting it with a function that gives us a reliable previous state value will help to fix this.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js
```
Storybook
=> fix(Datagrid): fix how `RowSizeDropdown` open state value is set (v11)

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/TearsheetWrapper.js, packages/cloud-cognitive/src/components/Datagrid/styles/addons/_CustomizeColumnsTearsheet.scss, packages/cloud-cognitive/src/components/Datagrid/useSortableColumns.js
Contributes to #2837 
Fixes issue when using `useSortableColumns` and `useCustomizeColumns` together there were issues with the customize columns tearsheet.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/CustomizeColumns/TearsheetWrapper.js
packages/cloud-cognitive/src/components/Datagrid/styles/addons/_CustomizeColumnsTearsheet.scss
packages/cloud-cognitive/src/components/Datagrid/useSortableColumns.js
```
Storybook
=> fix(Datagrid): sortable and customizable columns work together now (v11)

cspell.json, packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js, packages/cloud-cognitive/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
Contributes to #2868 
The tooltip for the row height settings was previously displayed incorrectly, now it is aligned `bottom` by default. I did some refactoring to `RowSizeDropdown` to use `ToggleTip` from Carbon since this tooltip has interactive elements inside of it, so this will help with a11y too.
```
cspell.json
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js
packages/cloud-cognitive/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
```
Storybook
=> fix(Datagrid): tooltip placement change for row height settings

packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
Contributes to #2677 
Before when you clear the number input the empty string would still render an empty tag. This fix removes it from the filter's list and doesn't render the empty tag anymore.
`packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js`
1. Go to Filtering > Filter flyout - instant
2. Add a number in the visits filter, and remove it. The tag should disappear
=> fix(Datagrid): filtering number empty tag bug

packages/cloud-cognitive/src/components/Card/Card.js, packages/cloud-cognitive/src/components/Card/CardHeader.js, packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.js, packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.js
Contributes to #2728
to add more flexibility, this PR allows `Card` to accept node and object for additional props
=> fix: allow nodes to be passed to additional card props v11

packages/cloud-cognitive/src/components/Card/Card.js, packages/cloud-cognitive/src/components/Card/CardHeader.js, packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.js, packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.js
Contributes to #2728
to add more flexibility, this PR allows `Card` to accept node and object for additional props
[v11 PR](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2886)
=> fix: allow nodes to be passed to additional card props

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridEmptyBody.js
Contributes to #2861 
Adds ability to use NotFound empty state in the Datagrid
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridEmptyBody.js
```
Storybook
=> feat(Datagrid): add support for NotFound empty state

packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridEmptyBody.js
Contributes to #2861 
Adds ability to use NotFound empty state in the Datagrid
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridEmptyBody.js
```
Storybook
=> feat(Datagrid): add support for NotFound empty state (v11)

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/ActionBar/_action-bar.scss, packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js, packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
Fixes #2830
Previous changes addressed size of icon buttons.
This change addresses remaining issues identified in 2830
- Fix collapse button location/styling (Carbon breaking change of IconButton).
- Fix incorrect conversion from 'field' to 'lg' in action bar story.
- Remove styling no longer needed in action bar causing icon to not be centered.
- Storybook
- Ran tests
=> fix: styling issues found in 2830

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/TagSet/_tag-set.scss
Contributes to #2557
Reopening on behalf of @qbi11y. v1 version of this PR is #2707.
Previously, descenders would get cut off around the edge of tags listed in the overflow due to `border-radius` coming from the Carbon tag. This removes the `border-radius` in the TagSet popover to prevent this from happening.
Storybook
=> fix(TagSet): remove tag radius in overflow

packages/cloud-cognitive/package.json, packages/cloud-cognitive/src/components/AboutModal/AboutModal.js, packages/cloud-cognitive/src/components/ActionBar/ActionBar.js, packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js, packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridVirtualBody.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.js, packages/cloud-cognitive/src/components/TagSet/TagSet.js, packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js, packages/cloud-cognitive/src/global/js/hooks/useResizeObserver.js, packages/cloud-cognitive/src/global/js/hooks/useWindowResize.js, packages/cloud-cognitive/src/global/js/hooks/useWindowScroll.js, yarn.lock
Contributes to #2744 
V7 of ReactResizeObserver can result in the error shown in #2744 but the error appears to be a timing issue of some description.
The author fixed a similar looking issue in V8, but it persists in our storybook. In V9 there were more extensive changes that stopped our current usage working.
This PR removes ReactResizeObserver in favor of wrapping ResizeObserver (now standard) in a hook.
- Removed react-resize-detector
- Created useResizeObserver hook.
- Checked it functioned as a replacement for all useResizeDetector hook
- Storybook changing the size of things and adding new elements
- Ran tests
NOTE: Storybook 6 reports the following error which would appear to be related this issue fixed only in Storybook 7. https://github.com/storybookjs/storybook/issues/18716
=> feat: Remove react resize detector

packages/cloud-cognitive/src/components/Datagrid/Datagrid.mdx
Contributes to #2917 
This PR adds missing documentation for roughly half of the hooks listed in #2917. I will include the other half in a separate PR to reduce the size for reviewing.
Hooks included in this PR:
`useColumnCenterAlign`
`useColumnRightAlign`
`useActionsColumn`
`useColumnOrder`
`useCustomizeColumns`
`useDisableSelectRows`
`useInfiniteScroll`
`Datagrid.mdx`
Storybook
=> docs(Datagrid): add missing hook documentation, part 1

packages/cloud-cognitive/src/components/Datagrid/Datagrid.mdx, packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridSelectAllWithToggle.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useSelectAllToggle.scss, packages/cloud-cognitive/src/components/Datagrid/useSelectRows.js
Contributes to #2917 
Adds documentation for the remaining hooks listed in #2917. I additionally, made some small fixes as I was reviewing `useSelectRows` and `useSelectAllToggle`.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridSelectAllWithToggle.js
packages/cloud-cognitive/src/components/Datagrid/styles/_useSelectAllToggle.scss
packages/cloud-cognitive/src/components/Datagrid/useSelectRows.js
```
Storybook
=> docs(Datagrid): docs update part 2 (v2)

packages/cloud-cognitive/src/components/Datagrid/Datagrid.mdx, packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridSelectAllWithToggle.js, packages/cloud-cognitive/src/components/Datagrid/styles/_useSelectAllToggle.scss, packages/cloud-cognitive/src/components/Datagrid/useSelectRows.js
Contributes to #2917 
Adds documentation for the remaining hooks listed in #2917. I additionally, made some small fixes as I was reviewing `useSelectRows` and `useSelectAllToggle`.
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridSelectAllWithToggle.js
packages/cloud-cognitive/src/components/Datagrid/styles/_useSelectAllToggle.scss
packages/cloud-cognitive/src/components/Datagrid/useSelectRows.js
```
Storybook
=> docs(Datagrid): docs update part 2

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/InlineEditV1/_inline-edit-v1.scss, packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.js, packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.stories.js, packages/cloud-cognitive/src/components/InlineEditV2/_inline-edit-v2.scss
Contributes to #2871
There are a number of differences between V1 and V2 Inline edit outlined in the issue.  This addresses some of them.
- Invalid state shows even without focus
- rename invalidLabel to invalidText inline with Carbon TextInput
- added option to make edit button always visible.
- update snapshots
- added size to v2
- added option to allow InlineEditV2 to inherit type (allows use in PageHeader title).
Storybook.
=> feat: update InlineEditV2

packages/cloud-cognitive/src/components/EditInPlace/EditInPlace.js, packages/cloud-cognitive/src/components/EditInPlace/EditInPlaceV1.stories.js, packages/cloud-cognitive/src/components/EditInPlace/EditInPlaceV2.stories.js, packages/cloud-cognitive/src/components/EditInPlace/index.js, packages/cloud-cognitive/src/components/InlineEditV1/InlineEditV1.js, packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.js, packages/cloud-cognitive/src/components/index.js, packages/cloud-cognitive/src/global/js/package-settings.js, packages/cloud-cognitive/src/settings.js, packages/core/story-structure.js
Contributes to #2866 
Allows V1 users to switch to V1
- Added Editable field and stories. 
- Changed some of the messaging around deprecation of 'InlineEditV1' to be consistent with other message. 
- Added deprecation message regarding switch to EditableField
Viewed in Storybook.
Not yet tested.
=> feat: Rename inline edit (V1)

packages/cloud-cognitive/src/components/Datagrid/useOnRowClick.js
Contributes to #2910 
Adds keyboard support to the `useOnRowClick` hook.
`useOnRowClick.js`
Storybook
=> feat(Datagrid): add keyboard support for clickable rows (v2)

packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap, packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.js, packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.stories.js, packages/cloud-cognitive/src/components/InlineEditV2/_inline-edit-v2.scss, packages/cloud-cognitive/src/components/InlineEditV2/_storybook-styles.scss
Contributes to #1649 
Inline edit v2 is missing an ellipsis when not in edit mode and overflowing it's container.
Add an ellipsis in when needed and not editing to inline edit v2.
Storybook
=> feat: add ellipsis to inline-edit v2 pkg v1

packages/cloud-cognitive/src/__tests__/index-all-enabled.test.js, packages/cloud-cognitive/src/components/AboutModal/AboutModal.test.js, packages/cloud-cognitive/src/components/ActionBar/ActionBar.test.js, packages/cloud-cognitive/src/components/ActionBar/ActionBarItem.test.js, packages/cloud-cognitive/src/components/AddSelect/AddSelect.test.js, packages/cloud-cognitive/src/components/AddSelect/AddSelectBody.test.js, packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.test.js, packages/cloud-cognitive/src/components/CreateSidePanel/CreateSidePanel.test.js, packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.test.js, packages/cloud-cognitive/src/components/Datagrid/Datagrid.test.js, packages/cloud-cognitive/src/components/EditSidePanel/EditSidePanel.test.js, packages/cloud-cognitive/src/components/EditTearsheet/EditTearsheet.test.js, packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js, packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js, packages/cloud-cognitive/src/components/TagSet/TagSet.test.js, packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.test.js, packages/security/src/__tests__/scss/__snapshots__/styles-test.js.snap
Contributes to #2878
Remove `restoreAlMocks()`[^1] in c4p tests.
This also includes an update to the one of the security snapshots but does not yet resolve failed tests in `security` package.
Only removed `restoreAllMocks()` where we were seeing failure.
`yarn ci-check:test:c4p` passes
[^1]: https://stackoverflow.com/questions/69330455/jest-fn-inside-jest-mock-returns-undefined/70270857#70270857
=> chore: update tests for dev dependencies

packages/cloud-cognitive/src/components/Datagrid/index.js, packages/cloud-cognitive/src/components/Datagrid/useEditableCell.js, packages/cloud-cognitive/src/components/Datagrid/useInlineEdit.js, packages/cloud-cognitive/src/components/index.js
Contributes to #2889 
Renamed `useInlineEdit` to `useEditableCell`. Both hooks are available to use but if `useInlineEdit` is used, there is a deprecation warning that will be logged.
```
packages/cloud-cognitive/src/components/Datagrid/index.js
packages/cloud-cognitive/src/components/Datagrid/useEditableCell.js
packages/cloud-cognitive/src/components/Datagrid/useInlineEdit.js
```
Storybook
=> chore(Datagrid): add deprecation warning for `useInlineEdit` hook, will be renamed in v2 to `useEditableCell`

packages/ibm-products/src/config.scss
This feels wrong
`@use "@carbon/ibm-products/scss/index" as config;` to be able to do `config.$pkg-prefix'
It forwards way more than is needed.
Might I suggest a `config.scss` file as per Carbon thus allowing...
With
@use "@carbon/ibm-products/scss/config"
enabling
config.$pkg-prefix
config.$carbon-prefix
=> feat: expose scss config file

packages/ibm-products/src/components/Datagrid/useActionsColumn.js
Contributes to #2966 
Add support for `shouldHideMenuItem` to row actions with less than three items.
```
packages/cloud-cognitive/src/components/Datagrid/useActionsColumn.js
```
Storybook
=> fix(Datagrid): `shouldHideMenuItem` works with less than 3 row actions (v2)

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/EmptyStates/EmptyState.js, packages/ibm-products/src/components/EmptyStates/EmptyState.test.js, packages/ibm-products/src/components/EmptyStates/EmptyStateContent.js, packages/ibm-products/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.js, packages/ibm-products/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.js, packages/ibm-products/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.js, packages/ibm-products/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.js, packages/ibm-products/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.js, packages/ibm-products/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.js, packages/ibm-products/src/components/EmptyStates/_empty-state.scss
Contributes to #2963 
adds an `illustrationPosition` option to empty state. on a separate note, there's a lot of redundancy in the empty state components. this should be looked at to reduce some code bloat.
=> fix: give empty state illustration position

packages/ibm-products/package.json, yarn.lock
DataGrid has an undeclared dependancy on lodash, this PR adds it.
=> fix: Carbon v11 lodash dependency

examples/carbon-for-ibm-products/AboutModal/src/Example/Example.jsx, examples/carbon-for-ibm-products/AboutModal/src/Example/_example.scss
Contributes to #2604 
Example styling seen here https://stackblitz.com/github/carbon-design-system/ibm-cloud-cognitive/tree/carbon-v11/examples/carbon-for-ibm-products/AboutModal?file=src%2FExample%2FExample.jsx
shows the SVG icons with no constraint on size. This fixes the size of the icons.
Applied changes to stackblitz example and checked they worked.
=> fix: Carbon v11 about modal example

.github/workflows/release.yml, package.json
This should fix the ci-check on the new main branch, ie will skip over cdai/security tests/build
=> fix(build): use v2 ci check script

README.md, examples/carbon-for-ibm-products/ccs-base-react-16/src/Example/Example.js, examples/carbon-for-ibm-products/ccs-base-react-17/src/Example/Example.js, packages/core/.storybook/manager-head.html, packages/ibm-products/README.md, packages/ibm-products/carbon.yml, packages/ibm-products/src/components/Datagrid/utils/makeData.js, packages/security/carbon.yml, packages/security/src/components/Card/Card-story.js, packages/security/src/components/DataDecorator/DataDecorator-story.js, packages/security/src/components/ErrorPage/ErrorPage-story.js, packages/security/src/components/Panel/Panel-story.js, packages/security/src/components/PanelV2/PanelV2-story.js, packages/security/src/components/Pill/Pill-story.js, packages/security/src/components/ProfileImage/ProfileImage-story.js, packages/security/src/components/SummaryCard/SummaryCard-story.js, packages/security/src/components/TrendingCard/TrendingCard-story.js, packages/security/src/components/Wizard/Wizard-story.js
Closes #3011
Contributes to #2884 
Replace Netlify links.
In Security `carbon.yml` and Stories, these will point to https://v1-ibm-products.carbondesignsystem.com/.
Replace links with https://ibm-products.carbondesignsystem.com/ or https://v1-ibm-products.carbondesignsystem.com/
Find and replace and <kbd>option</kbd> + click
=> docs: update Storybook links v1

examples/carbon-for-ibm-products/CreateTearsheet/gallery.config.json, examples/carbon-for-ibm-products/example-gallery/src/gallery-config/index.js
Contributes to #3016
Fixed CreateTearsheet example label
```
examples/carbon-for-ibm-products/CreateTearsheet/gallery.config.json
examples/carbon-for-ibm-products/example-gallery/src/gallery-config/index.js
```
Ran example gallery locally
=> fix: use create tearsheet label in examples

config/storybook-addon-carbon-theme/react.js, config/storybook-addon-carbon-theme/register.js, config/storybook-addon-carbon-theme/vue.js
An attempt to update storbyook to v7 highlighted this use of require which will not be compatible with V7.
Changed to use import/export. Verified storybook still works.
=> fix: errors raised by the storybook addon

.github/workflows/release-v1.yml, .github/workflows/release.yml
Turns cron for v2 release back on.
~*Still looking into why v1 release action failed.~ Thanks @matthewgallo 
- Remove commented cron
- Also renamed for easier navigation in actions list
🤐
=> chore: turn on v2 release

config/storybook-addon-carbon-theme/package.json, yarn.lock
Removes `"private": true` from storybook-addon-theme package. This unfortunately prevents yarn.lock from updating when it needs. We will need to find another way to prevent this package from publishing in both the `release-v1.yml` and `release.yml` actions.
=> fix: private true prevents lock file from updating

.github/workflows/release-v1.yml
Legacy package name publish failed because we're still referencing the `cloud-cognitive` directory, this should update the legacy publish script to use `ibm-products` instead.
`release-v1.yml`
=> fix: use correct directory name for legacy package name in v1 release action

packages/ibm-products/src/components/NonLinearReading/NonLinearReading.mdx, packages/ibm-products/src/components/NonLinearReading/NonLinearReading.stories.js
Contributes to #3001
Storybook examples under the Docs tab are now loading.
Stories updates
1. Removed `defaultProps` as they were overridden in every example.
2. _Wanted to_ remove `args` from each template, but there seems to be a bug where if `args` is missing as a template argument, then in the Docs tab the "Show code" button changes to the "No code available" button. (!?) I left `args` in along with a `TODO` comment explaining the problem.
Docs updates
1. Updated example titles.
2. Replaced old "Embedded" story with "With Gradient" story.
1. Loaded [Storybook for Non-Linear Reading](https://deploy-preview-3002--v1-carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-novice-to-pro-nonlinearreading-canary--single-level) component.
2. Switched to Docs tab.
3. Saw that the …
=> fix(non-linear): update stories and mdx

packages/ibm-products/src/components/Datagrid/_storybook-styles.scss, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss
Contributes to #2724 
`.#{c4p-settings.$carbon-prefix}--body--with-modal-open
.#{$block-class}__grid-container {
overflow: hidden;
height: 100vh;
}`
The above style caused the issue. This is added as part of toolbar responsiveness and affected other modals inside Datagrid. 
The changes are only required in the storybook demo to override `#root` element padding. This is managed to add styles in `_storybook-styles.scss`.
Storybook.
Toolbar mobile modal now
Customize column modal now
=> fix(DataGrid): header misalignment when modal open - v1

packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/TearsheetWrapper.js
Contributes to [ibm-products](https://github.com/carbon-design-system/ibm-products)
when using tearsheet isTableSortable prop is undefined and since it is a required prop it causes error
i added default value false for prop
checked it in storybook and my production version of my project
=> fix(Datagrid): prevent undefined value for isTableSortable prop

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js, packages/ibm-products/src/components/Datagrid/styles/addons/_FilterFlyout.scss, packages/ibm-products/src/components/Datagrid/styles/addons/_FilterPanel.scss, packages/ibm-products/src/components/Datagrid/utils/DatagridActions.js
Contributes to #2725 
I was able to narrow down the re-rendering issues with the `FilterFlyout` button, which caused the trigger to have to be clicked twice before opening the flyout. From what I can tell so far, it stems from the `renderIcon` prop from Carbon's `Button` component. I simply changed from using `Button` with the `renderIcon` prop to `IconButton` and the issue is gone.
I'm going to continue doing some investigating, because things like the ButtonMenu still have this problem.
I also made a small change to the `tabIndex` of the containing element for the Datagrid to remove a console error.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js …
```
=> chore(Datagrid): address rerender issues with filter flyout button

config/storybook-addon-carbon-theme/package.json, packages/core/package.json, yarn.lock
Contributes to #2846 
Before publishing a theme add-on with storybook 7 support, make the storybook 6 support v1.
Just the version number of the theme switching package.
Built the software and ran CI-Check.
=> chore: publish storybook 6 theme addon to v1

packages/ibm-products/src/components/Datagrid/Extensions/EditableCell/EditableCell.stories.js
I noticed that the `useEditableCell` and `useInlineEdit` hooks were mislabeled in the stories and this was causing some issues with properly setting the feature flag for these extensions.
Updating naming in editable cell Datagrid story file
Storybook, component behaves as expected now
=> fix(Datagrid): address useEdtiableCell and useInlineEdit feature flag issue

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAllWithToggle.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.js, packages/ibm-products/src/components/Datagrid/_storybook-styles.scss
Contributes to #3045 
Addresses issue where items are preselected across multiple pages. The batch action toolbar would only render when you changed to the page containing the selected item/s. This behavior can be seen from the code sandbox provided by @K-Markopoulos (thank you!).
The story `Select Items in All Pages` also was breaking after the storybook 7 merge because `onSelectAllRows` was called before being defined.
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAllWithToggle.js
packages/ibm-products/src/components/Datagrid/_storybook-styles.scss
```
Storybook
=> fix(Datagrid): use `selectedRowIds` to set selected rows

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.js
Contributes to #3045 
Addresses issue where items are preselected across multiple pages. The batch action toolbar would only render when you changed to the page containing the selected item/s. This behavior can be seen from the code sandbox provided by @K-Markopoulos (thank you!).
The story `Select Items in All Pages` also was breaking after the storybook 7 merge because `onSelectAllRows` was called before being defined.
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAllWithToggle.js
packages/ibm-products/src/components/Datagrid/_storybook-styles.scss
```
Storybook
=> fix(Datagrid): use `selectedRowIds` to set selected rows (v1)

.github/workflows/release-v1.yml, .github/workflows/release.yml, .github/workflows/update-v1.yml, .github/workflows/update.yml, CODEOWNERS, cspell.packages.txt
Closes to #3112 and #3113
- Update to `actions/checkout@v3`
- Fix naming in v2 update action
- Add v1 update action for Carbon dependencies
-  Commented out other dependencies updates for now to limit workload and will look into whether dependabot can support multiple branches
**Note:** v1 dependency updates will be once a month offset from the v2 dependency updates 2x a month
👀
=> chore: update dependency and release actions

.github/workflows/release-v1.yml, .github/workflows/release.yml
Both release actions seem to be attempting to run after every commit. The screenshot below shows it with Lee's storybook docs PR, but I also noticed it with https://github.com/carbon-design-system/ibm-products/pull/3136 as well.
Not sure if it is happening because of the indentation of the `run` block that commits the lock file, github actions vscode plugin seems to want it indented, as opposed to directly below the step (ie `- name`).
`release.yml` and `release-v1.yml`
😱 after merging this
=> fix: scope `run` block to step when committing lock file

packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/handleGridKeyPress.js
Contributes to #3135 
Moving `saveCellData` before it is used somehow caused it to be called in some sort of loop which ended up causing the component to fall over. Because storybook complained about that function being defined after it was used, I created a `saveCellData` variable with `let` and assigned it a value where it was initially given one prior to the storybook change.
There also appeared to be an issue in `handleGridKeyPress` which I addressed as well (`!!` will only convert `'true'` to `true` but will not convert `'false'` to `false`).
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/handleGridKeyPress.js
```
Storybook
=> fix(Datagrid): address `saveCellData` loop, crashes Datagrid editable cell stories

.github/workflows/release-v1.yml, .github/workflows/release.yml, .github/workflows/update-v1.yml, .github/workflows/update.yml, packages/core/package.json, yarn.lock
Contributes to #3151
Addresses issues outlined in #3151, primarily removing the lock file step in `release.yml` and upgrading `packages/core` version. `packages/core` (ie `@carbon/ibm-cloud-cognitive-core`) will end up with `1.1.0` the next time `release.yml` is run but since it is a private package that seems ok.
```
.github/workflows/release.yml
.github/workflows/update-v1.yml
packages/core/package.json
```
Will test in github
=> fix: update release actions and `packages/core` version

packages/core/package.json
Contributes to #3151 #3154
Bump `core` version to 2.0.0.
`core/package.json`
🥸
=> chore: `packages/core` version bump

packages/ibm-products/src/global/js/hooks/useResizeObserver.js
Contributes to #3172 
Resize observer was incorrectly setting up based on the target ref and not it's current value.
Updated the useLayoutEffect dependencies in useResizeObserver.
Storybook stacked tearsheets.
=> fix: resize observer infinite perspective issue

examples/carbon-for-ibm-products/gallery-examples.test.js, examples/carbon-for-ibm-products/prefix-example/src/index.scss, packages/ibm-products/README.md
Contributes to #3173
The prefix example and documentation did not reflect how the prefix can be modified in V2 with `@use`. 
- Updated the prefix example 
- Added a prefix section to the documentation.
Checked prefix example on codesandbox.
=> chore: update prefix documentation and example

packages/core/.storybook/_prefix-index.scss, packages/core/.storybook/index.scss, packages/core/.storybook/preview.js
Contributes to #1154 
Propose changing all development storybook stories to use a custom prefix.
Core storybook preview and styling to set a prefix when in development mode.
- yarn storybook
- Viewed in storybook and inspected the DOM and noted prefix
- yarn build
- npx serve packages/core/storybook-static and checked the prefix in the DOM
=> chore: always use prefix in dev storybook

packages/core/story-structure.js, packages/ibm-products/src/components/Datagrid/Extensions/Skeleton/Skeleton.stories.js, packages/ibm-products/src/components/Datagrid/utils/getArgTypes.js
Contributes to #3120 
Adds a loading/skeleton story for Datagrid as requested during design review.
```
packages/core/story-structure.js
packages/ibm-products/src/components/Datagrid/Extensions/Skeleton/Skeleton.stories.js
packages/ibm-products/src/components/Datagrid/utils/getArgTypes.js
```
Storybook
=> chore(Datagrid): add skeleton story (v1)

packages/core/story-structure.js, packages/ibm-products/src/components/Datagrid/Extensions/Skeleton/Skeleton.stories.js, packages/ibm-products/src/components/Datagrid/utils/getArgTypes.js
Contributes to #3120 
Adds a loading/skeleton story for Datagrid as requested during design review.
```
packages/core/story-structure.js
packages/ibm-products/src/components/Datagrid/Extensions/Skeleton/Skeleton.stories.js
packages/ibm-products/src/components/Datagrid/utils/getArgTypes.js
```
Storybook
=> chore(Datagrid): add skeleton story (v2)

packages/ibm-products/src/components/Datagrid/Extensions/ClickableRow/ClickableRow.stories.js, packages/ibm-products/src/components/Datagrid/_storybook-styles.scss
Contributes to #2608 
Address quick fixes from clickable row design review.
- Add `title` to link
- Align numerical data
- Use sentence case in headers
- Add **View details** in side panels
Clickable row stories
Storybook
=> fix(Datagrid): clickable row stories

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js
Contributes to #3227 
Always adding the class for `__sortableColumn` in header rows even when the useSortableColumns hook is not included.
`__sortableColumn` class is conditionally added when `isTableSortable` is `true`. 
Storybook
=> fix(Datagrid): remove sort styles hook not in use v1

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/ClickableRow/ClickableRow.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/RowActionButtons/RowActionButtons.stories.js, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/useOnRowClick.js
Contributes to #3226 and #2607
Adds batch actions to the clickable row with panel story to provide a more detailing use case. I also fix the alignment of the batch action buttons in this PR as well.
- Added batch actions to clickable with panel story
- Removed styling causing batch action layout issues
Storybook
Also discovered a storybook config option to allow for non story exports within `*.stories.js` files. I've utilized it here for `getBatchActions` which reduces our overall footprint.
=> fix(Datagrid): add batch actions to clickable row with panel story (v1)

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/useActionsColumn.js
Contributes to #3334
This PR allows row actions to become disabled when a row is selected with batch actions. There was some logic in place already, but wasn't correctly setup to disable the row actions as expected.
```
packages/ibm-products/src/components/Datagrid/useActionsColumn.js
```
Storybook, via BatchActions story (I added some row actions to this story in order to verify that the row actions become disabled when selecting the row)
=> fix(Datagrid): address row action disabled state logic (v1)

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/useActionsColumn.js
Contributes to #3334
This PR allows row actions to become disabled when a row is selected with batch actions. There was some logic in place already, but wasn't correctly setup to disable the row actions as expected.
```
packages/ibm-products/src/components/Datagrid/useActionsColumn.js
```
Storybook, via BatchActions story (I added some row actions to this story in order to verify that the row actions become disabled when selecting the row)
=> fix(Datagrid): address row action disabled state logic (v2)

lerna.json
Closes #3342 
`--frozen-lockfile` arg is causing release action to break due to a contraction with `update-lockfle` in the yarn.cjs
Remove `--frozen-lockfile` from lerna.json args.
Compared against main branch `lerna.json` (minus Lerna 7 changes in main).
=> chore: remove `--frozen-lockfile`

packages/ibm-products/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js
After reviewing the CreateTearsheet with Turbo team, noticed that the checkbox used to dynamically include an additional step was not updated to use the new `onChange` callback signature that changed from Carbon v10 to v11.
```
packages/ibm-products/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js
```
Storybook
=> fix(CreateTearsheet): use new onChange callback signature in v11

packages/ibm-products/src/components/CreateTearsheet/CreateTearsheetStep.js, packages/ibm-products/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js
Contributes to #3345 
Allows nodes to be passed to `CreateTearsheetStep` description.
```
packages/ibm-products/src/components/CreateTearsheet/CreateTearsheetStep.js
packages/ibm-products/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js
```
Storybook
=> feat(CreateTearsheet): allow node to be passed to description prop

packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/TearsheetWrapper.js, packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js, packages/ibm-products/src/components/Datagrid/styles/_useColumnCenterAlign.scss, packages/ibm-products/src/components/Datagrid/useDefaultStringRenderer.js, packages/ibm-products/src/components/Datagrid/useSortableColumns.js
Contributes to #2837 
This PR adds some logic to `DraggableItemsList` that will allow for use of `useCustomizeColumns` with one or more hooks that manipulate the column header (such as `useSortableColumns` or `useColumnCenterAlign`). This also allowed for refactoring how we get the column title if there is a hook being used which manipulates the column header structure.
We previously attempted to support customizable columns with `useSortableColumns` by passing down a prop called `isTableSortable` but this did not get at the root of the problem which is, the use of one or more extensions which may manipulate the structure of the column header. I added a function (`getNestedTitle`) which recursively checks for the title so this should account for instances when one or more hooks are used …
=> fix(Datagrid): add support for other extensions with customizable columns (v2)

packages/core/package.json, packages/ibm-products/package.json, yarn.lock
We were not able to pin to a version prior to `1.65.0` because we are using `yarn dlx sass` in one of the build scripts from `packages/core` which pulls in the latest sass version (thus explaining why we kept seeing the issue).
I changed `yarn dlx sass` to just `sass` and everything seems to be working ok now.
```
packages/core/package.json
yarn.lock
```
Ran build scripts and confirmed that storybook server starts as expected
=> build: pin current sass version and remove `yarn dlx` to prevent rem issue

packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.js, packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.test.js, packages/ibm-products/src/components/CreateTearsheet/CreateTearsheetStep.js, packages/ibm-products/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js, packages/ibm-products/src/global/js/hooks/useCreateComponentStepChange.js, packages/ibm-products/src/global/js/hooks/useRetrieveStepData.js, packages/ibm-products/src/global/js/utils/StoryDocsPage.js
Contributes to #3340 
Adds an optional `onPrevious` prop to the `CreateTearsheetStep` component. There were also remnants of an old version of this component when you could view all the steps together, `shouldViewAll`, inside the custom hook that contains the step changing logic, so I cleaned that up as well.
```
packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.js
packages/ibm-products/src/components/CreateTearsheet/CreateTearsheetStep.js
packages/ibm-products/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js
packages/ibm-products/src/global/js/hooks/useCreateComponentStepChange.js
```
Storybook
=> feat(CreateTearsheet): add optional `onPrevious` handler to step

packages/ibm-products/src/components/ActionSet/ActionSet.stories.js
Contributes to #3131 
The ActionSet story uses a display box but it does not allow it to be resized as per ActionBar.
- The `containerWidth` prop was included to enable the resize capabilities of the display-box within the story.
Storybook
=> feat(ActionSet): Include containerWidth prop inside the story

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/useDatagrid.js
Contributes to #1923 and #2507
Took another look at adding keyboard support for resizable columns. This time around i discovered that we can pass a [custom stateReducer](https://github.com/TanStack/table/blob/v7/docs/src/pages/docs/api/useTable.md) to `useTable` that will allow us to manually track the resize events via the `dispatch` function they provide to us in the table state, giving us the ability to add the missing keyboard support.
I kept the same approach of using a slider input and changed the visual representation of the resizer, as the previous version felt a bit clunky.
New focus state of the resizer can be seen below:
Resizing with both mouse and key events enforce a minimum width so at least one character from the column header is displayed.
``` …
```
=> feat(Datagrid): add keyboard support for col resizing

packages/ibm-products/src/components/Datagrid/Datagrid.mdx, packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js
Contributes to #1923 and #2507 
@paul-balchin-ibm suggested adding a callback to allow consumers to optionally save the column widths that have been resized as opposed to us saving the updated column sizes. This definitely feels more appropriate, so I have included that new resize end callback in this PR, `onColResizeEnd`.
```
```
Storybook
=> feat(Datagrid): add column resize callback

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/pr.yml
If I remember correctly from Taylor's share this morning, we need to add the `merge_group` event to the workflows that run during PR checks
```
.github/workflows/codeql.yml
.github/workflows/pr.yml
```
=> build: add `merge_group` event to PR workflows

.github/workflows/add-to-merge-queue.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .kodiak.toml, cspell.contributors.txt, cspell.json
Thanks @tay1orjones for sharing this with us.
Add new action so we can continue to use `status: ready to merge` as is our typical workflow today.
- **Note** — we kept the 🎉 and updated our label already because we deserve to celebrate each merge/win 😤 
Also updated CodeQL/CI actions to run on merge group and removed Kodiak after some discussion with Taylor. If we hate this, we can always put it back but feel like we should try it out first and see how it goes before that.
In Taylor we trust — but really, adopted from Carbon’s working version. How to _actually test_ actions eludes us still.
=> chore: add merge queue to actions

.github/workflows/pr.yml
Adds some logic to skip PR title validation in the merge queue, while still requiring in the actual PR.
=> fix: skip PR title validation in `merge_group` queue

config/jest-config-ibm-cloud-cognitive/package.json, packages/ibm-products/package.json, yarn.lock
This week's v2 release failed because of the jest config package being published from both our v1 and v2 release actions which caused a clash in versioning. Moving it to `v1.0.0` on `main` should solve this problem.
=> fix(build): move jest config package to v1 to prevent version clashes

packages/core/.storybook/index.scss, packages/ibm-products/src/components/CreateSidePanel/CreateSidePanel.stories.js, packages/ibm-products/src/components/CreateSidePanel/_storybook-styles.scss, packages/ibm-products/src/components/DataSpreadsheet/_storybook-styles.scss, packages/ibm-products/src/components/Datagrid/_storybook-styles.scss, packages/ibm-products/src/components/EditSidePanel/EditSidePanel.stories.js, packages/ibm-products/src/components/EditSidePanel/_storybook-styles.scss, packages/ibm-products/src/components/EditTearsheetNarrow/_storybook-styles.scss, packages/ibm-products/src/components/ExportModal/ExportModal.stories.js, packages/ibm-products/src/components/SidePanel/SidePanel.js, packages/ibm-products/src/components/SidePanel/SidePanel.stories.js, packages/ibm-products/src/components/SidePanel/_storybook-styles.scss, packages/ibm-products/src/components/Tearsheet/Tearsheet.stories.js, packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.stories.js, packages/ibm-products/src/global/decorators/_side-panel-decorator.scss, packages/ibm-products/src/global/decorators/sidePanelDecorator.js, packages/ibm-products/src/global/js/utils/StoryDocsPage.js, packages/ibm-products/src/global/js/utils/_story-as-full-page.scss
Some stories are poorly formatted or present badly on the docs page. This is because Storybook has changed the way in which the stories are hosted on the docs page. 
We should as a result try to ensure
- All stories reserve the space they need to present themselves (some stories have no content or only content that does not reserve vertical space.
- Have the stories, not common CSS, specify the size of the viewport on the docs page.
e.g. 
- Wrapped side panel stories to reserve the full height of the page.
- Removed the 50vh common minimum height in storybook styling.
- Added `layout: 'fullscreen'` to stories which should be full screen.
- Fixed CreateSidePanel, Datagrid, DataSpreadsheet, EditSidePanel, EditTearsheetNarrow, SidePanel and Tearsheet stories.
- Partially fixed ExportModal …
=> fix: some full screen docs pages

packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss
Contributes to #3158 
Adds some missing styles to allow for handling text overflow in the Datagrid title and descriptions.
```
```
Storybook, was able to use the controls in the `Header` Datagrid story to confirm the expected behavior
=> fix(Datagrid): add text overflow styling to title/desc

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss
Contributes to #3430 
Adds some missing styles in order to render the new column resizer as expected across browsers.
```
```
Referenced Storybook in Firefox
=> fix(Datagrid): add firefox style fixes to new column resizing

.github/workflows/codeql.yml
I have observed that the `codeql` action fails during the merge queue because v1 is now deprecated. I've moved our usage of it to v2 in `codeql.yml`.
`github/codeql-action/init@v2`
and
`github/codeql-action/analyze@v2`
`.github/workflows/codeql.yml`
Followed upgrade guidance [here](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/)
=> fix: upgrade to v2 codeql

packages/ibm-products/src/components/FilterSummary/FilterSummary.js, packages/ibm-products/src/components/FilterSummary/FilterSummary.stories.js, packages/ibm-products/src/components/TagSet/TagSet.js, packages/ibm-products/src/components/TagSet/TagSet.stories.js
Possible starting point for #3402
Strictly speaking the Tagset was defined with 'filter' prohibited at the request of the designer. Rather than create a second Tagset component, this PR undoes that restriction.
- Tagset to allow 'filter' and 'onClose' properties.
- Added to FilterSummary story.
Storybook.
=> feat(TagSet): enable filter property on tags

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js, packages/ibm-products/src/global/js/hooks/useClickOutside.js
Contributes to #3397 
clicking the flyout button was causing the outside click detector to be called. this refactors the `useOutsideClick` hook to provide the ref and fixes the aforementioned bug by applying the hook correctly to the container.
=> fix: filter flyout outside click

packages/ibm-products/src/components/InlineTip/InlineTip.js, packages/ibm-products/src/components/InlineTip/InlineTip.stories.js, packages/ibm-products/src/components/InlineTip/InlineTip.test.js, packages/ibm-products/src/components/InlineTip/InlineTipButton.js, packages/ibm-products/src/components/InlineTip/InlineTipLink.js
Contributes to #3422
Reviewed code and styling to meet accessibility guidelines.
Nothing related to accessibility; it's a very simple component out of the box.
Removed `InlineTipButton` and `InlineTipLink` as exportable components.
=> fix(InlineTip): accessibility review changes

packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js, packages/ibm-products/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
=> fix: datagrid row size accessibility v1

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridEmptyBody.js, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss
Contributes to #3483
Removed `<td>` bottom border when table shows an empty state.
Added a class to the `<td>`; updated SCSS.
Verified in Storybook.
=> fix(DataGrid): remove td bottom border when state is empty

packages/ibm-products/src/components/Datagrid/Extensions/RowActionButtons/RowActionButtons.stories.js, packages/ibm-products/src/components/Datagrid/useActionsColumn.js
Contributes to #3470
Allow developer to set the tooltip alignment of a row action button.
The developer can now pass a `align` property to a `rowActions` object. E.g. (see last line in code sample below):
```
rowActions: [
{
id: 'delete',
itemText: 'Delete',
icon: TrashCan,
isDelete: true,
onClick: action('Clicked row action: delete'),
align: 'top-right', // <-- add this
},
],
```
The same `align` values as Tooltip and Popover options are available.
=> fix(DataGrid): set row action button tooltip alignment

packages/ibm-products/src/components/index.js, packages/ibm-products/src/global/js/package-settings.js
The `EditTearsheetForm` component was never exported even though it is described in the `EditTearsheet` docs as a component that can be used alongside the `EditTearsheet`. I've exported it in this PR, making it available to be used.
```
packages/ibm-products/src/components/index.js
packages/ibm-products/src/global/js/package-settings.js
```
Ensured that `EditTearsheetForm` is exported and added to `package-settings.js`
=> fix(EditTearsheet): export edit tearsheet form component

packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss
Contributes to #3483, is an addendum to PR #3498
Removed <td> bottom border when table shows an empty state _and the user mouseovers the table row_.
Updated SCSS
=> fix(DataGrid): remove td bottom border when state is empty and tr hover

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/styles/_useExpandedRow.scss
Contributes to #3506 
Small styling update to address the layout of the row expander, used for both nested and expandable rows. I also included a fix for a console error we've had about how we've specified a `role` attribute.
```
packages/ibm-products/src/components/Datagrid/styles/_useExpandedRow.scss
```
Storybook
=> chore(Datagrid): address layout of expander icon button

examples/carbon-for-ibm-products/react-16-example/yarn.lock, examples/carbon-for-ibm-products/react-17-example/yarn.lock, scripts/example-gallery-builder/update-example/templates-react-16/yarn.lock, scripts/example-gallery-builder/update-example/templates-react-17/yarn.lock
Closes #3493 and #3494
Bump semver from 6.3.0 to 6.3.1 in gallery-builder templates
=> chore(deps): bump semver from 6.3.0 to 6.3.1 in templates

package.json, packages/ibm-products/package.json, packages/ibm-products/src/components/Datagrid/Datagrid/DraggableElement.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js, packages/ibm-products/src/components/Datagrid/styles/_draggableElement.scss, packages/ibm-products/src/global/js/hooks/useWindowScroll.js, yarn.lock
Contributes to https://github.com/carbon-design-system/ibm-products/issues/3478
Using dnd-kit.
Probably chopped out more than needed to make sense of this, need to understand if it is working and if we've lost any features.
This works really nice, fewer issues than react-beautiful-dnd and less code. Looks correct on scrolling compared to react-beautiful-dnd.
Only niggle(s)
- Keyboard movement is 25px at a time, not sure why as I think it should be `cell height / 2` reading the code, but I must be missing a rounded pixel somewhere. This is noticeable on longer lists.
- Not visible if dragged out of modal (to be expected).
Datagrid customisable columns
Storybook
=> feat: with dnd kit

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridEmptyBody.js, packages/ibm-products/src/components/EmptyStates/EmptyState.js, packages/ibm-products/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.js, packages/ibm-products/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.js, packages/ibm-products/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.js, packages/ibm-products/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.js, packages/ibm-products/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.js, packages/ibm-products/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.js, packages/ibm-products/src/components/EmptyStates/assets/ErrorIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/NoDataIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/NoTagsIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/NotFoundIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/NotificationsIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/UnauthorizedIllustration.js
Contributes to #3243 
mostly just addresses some testing. to help facilitate testing I added specific class names to all the empty state variants, which honestly should have been done from the start haha
there was a point in the issue to mention how to set the error type, but i think there needs to be a bigger discussion about prop types and that documentation for datagrid. so i opted to skip it for now.
=> fix: datagrid empty state fixes

packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js
Contributes to https://github.com/carbon-design-system/ibm-products/issues/3478
We can safely remove the warning notification we added on the ColumnCustomization story for the Datagrid now that we have the `dnd-kit` approach merged. Thanks to @lee-chase! 🥳 🎉 
Removed notification from ColumnCustomization story
Storybook
=> chore(Datagrid): remove warning about drag and drop rework

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridEmptyBody.js, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss
v1 accompanying PR from @paul-balchin-ibm's initial work to fix this issue
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridEmptyBody.js
```
Storybook
=> fix(DataGrid): remove td bottom border when state is empty (v1)

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridExpandedRow.js, packages/ibm-products/src/components/Datagrid/styles/_useExpandedRow.scss
Contributes to #3324 
Adds background color to expanded area when hovering on the expanded row.
```
packages/ibm-products/src/components/Datagrid/styles/_useExpandedRow.scss
```
Storybook
=> fix(Datagrid): expandable row add background on row hover

packages/ibm-products/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.js
Contributes to #3543 
Addresses an issue of duplicate id's coming from the `ButtonSetWithOverflow` component because the button set used for measuring available space is using the same id as the visible button.
```
packages/ibm-products/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.js
```
Storybook
=> fix(ButtonSetWithOverflow): fix duplicate id issue

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/ActionSet/_action-set.scss, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/styles/addons/_CustomizeColumnsTearsheet.scss, packages/ibm-products/src/components/Datagrid/styles/addons/_FilterFlyout.scss, packages/ibm-products/src/components/Datagrid/styles/addons/_FilterPanel.scss, packages/ibm-products/src/components/FilterSummary/_filter-summary.scss
Moves away from use of `rem` function in favour of `to-rem` the former being a problem for current versions of SASS.
=> fix: Should our CSS use of carbon rem be to-rem

packages/ibm-products/src/components/Datagrid/Datagrid.mdx, packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.js, packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js, packages/ibm-products/src/components/Datagrid/useRowExpander.js, packages/ibm-products/src/components/Datagrid/utils/getArgTypes.js
Contributes to #3561
Properly assigns a more logical value to the row expander `title` and `aria-label` attributes, as opposed to using the default value that `react-table` provides via `{...row.getToggleRowExpandedProps()}`.
This change has been applied to both expanded and nested rows.
```
packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.docs-page.js
packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.stories.js
packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.js
packages/ibm-products/src/components/Datagrid/styles/_useExpandedRow.scss …
```
=> fix(Datagrid): expander title / aria-label updates (v1)

.github/stale.yml, .github/workflows/stale.yml
Contributes to #3523 
Runs weekly on issues with the labels https://github.com/carbon-design-system/ibm-products/labels/status%3A%20needs%20reproduction or https://github.com/carbon-design-system/ibm-products/labels/status%3A%20waiting%20for%20author%20%F0%9F%92%AC
Should close issues with 30 https://github.com/carbon-design-system/ibm-products/labels/stale%20%F0%9F%8D%9E + 14 days https://github.com/carbon-design-system/ibm-products/labels/status%3A%20won%E2%80%99t%20fix%20%F0%9F%94%9A of no activity but excludes PRs.
Add new GitHub action[^1] and remove old stalebot
🤫
[^1]: https://github.com/actions/stale
=> chore: add stale action

packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/styles/addons/_FilterFlyout.scss, packages/ibm-products/src/components/Datagrid/styles/addons/_FilterPanel.scss, packages/ibm-products/src/components/FilterSummary/_filter-summary.scss
Fix usage of to-rem in some CSS files. Problem seems to suggest Carbon export `rem` but not `to-rem` in some SCSS.
=> fix: to rem usage

packages/ibm-products/package.json
Issue brought up via slack from @dbrugger. Appears that `dnd-kit` dependencies were listed as dev dependencies by accident.
```
```
Will verify build passes
=> fix: move dnd kit packages out of dev dependencies

README.md
Closes #3472
Updates README with v1 links and adds version support/compatibility info.
README content
=> docs: add version support to README

README.md, packages/ibm-products/src/components/EditTearsheet/EditTearsheet.js, packages/ibm-products/src/components/EditTearsheet/EditTearsheet.test.js, packages/ibm-products/src/components/EditTearsheet/EditTearsheetForm.js, packages/ibm-products/src/components/EditTearsheet/preview-components/MultiFormEditTearsheet.js, packages/ibm-products/src/global/js/hooks/useRetrieveFormTitles.js
Contributes to #3554
Replace hardcoded implementation of influencer with one derived from form titles.
Currently, the EditTearsheet component uses a hardcoded sample influencer rather than a dynamic or user provided one.
- Removed hardcoded nav item definitions
- Created state variable `formTitles`
- Created custom hook `useRetrieveFormTitles` to set form titles used for influencer nav items
- Added unit tests
- Added usage in storybook sample
- Also replaced influencer prop from component API with onFormChange handler
https://github.com/carbon-design-system/ibm-products/assets/12387334/24e1ff19-2492-4051-847e-b273fdde13d4
_Observe how the influencer nav item responds to the change made to the form title. Also observe how the new onFormChange handler is fired on click._
Passing.
=> fix(EditTearsheet): Derive influencer nav items from form titles

packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
Contributes to #3454 
Fixes a bug where the column order does not reset to the default if the CustomizeColumns tearsheet is closed, instead it maintains the new sorting order.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
```
Storybook
=> fix(Datagrid): reset column order in CustomizeColumns onClose handler

packages/ibm-products/src/components/Saving/Saving.js
Contributes to #2849
Reversed the the icons shown for  default state and success state to save and checkmark icons respectively.
storybook
=> fix(Saving): reversed icons for default state (save) and success state (checkmark)

packages/ibm-products/src/components/Tearsheet/Tearsheet.js, packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.js, packages/ibm-products/src/components/Tearsheet/TearsheetShell.js
Contributes to #3620 
Fixes issue with `portalTarget` prop type, `instanceOf(Element)` does not work with SSR apps because `Element` does not exist.
```
packages/ibm-products/src/components/Tearsheet/Tearsheet.js
packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.js
packages/ibm-products/src/components/Tearsheet/TearsheetShell.js
```
Storybook, confirmed there are no prop type errors
=> fix(Tearsheet): address `Element` type issue with portalTarget prop type

packages/ibm-products/src/components/Datagrid/Datagrid/DraggableElement.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js, packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js
Contributes to #3455 
Adds back the functionality to:
1. Prevent dragging of columns that are disabled
2. Prevent items to be dropped/reordered to positions that are disabled
```
packages/ibm-products/src/components/Datagrid/Datagrid/DraggableElement.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js
packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js
```
Storybook
=> fix(Datagrid): add disabled/locked col drag functionality back

packages/ibm-products/src/components/Datagrid/Datagrid/Datagrid.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterProvider.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/constants.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js, packages/ibm-products/src/components/Datagrid/useFiltering.js, packages/ibm-products/src/components/FilterSummary/FilterSummary.js, packages/ibm-products/src/components/FilterSummary/FilterSummary.stories.js, packages/ibm-products/src/components/TagSet/TagSet.js, packages/ibm-products/src/components/TagSet/TagSet.stories.js
Contributes to #3402 
This PR adds functionality to remove individual filter tags from the filter summary component used in the Datagrid. This change works with both the flyout and panel variants.
Note: In order to achieve this, I had to include updates to the `FilterSummary` and `TagSet` components that I did not make in the corresponding v2 PR because @lee-chase had already done this on the `main` branch/v2.
```
packages/ibm-products/src/components/Datagrid/Datagrid/Datagrid.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterProvider.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Fi …
```
=> feat(Datagrid): remove filter tags individually from `FilterSummary`

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/Card/_card.scss
Fixes typo `#{$block-class}...` to `.#{$block-class}...`. Prepended a dot.
=> fix: Card CSS typo

config/storybook-addon-carbon-theme/.babelrc
In the current version 2.0.4, the dist directory contains files in ES modules format. However, the declared format of the bundle is traditional CommoJS. This causes usage issues:
```
WARN   Failed to load preset: {"type":"presets","name":"/redacted/node_modules/@carbon/storybook-addon-theme/dist/preset.js"} on level 1
./node_modules/@carbon/storybook-addon-theme/dist/preset.js:11
export default {
^^^^^^
SyntaxError: Unexpected token 'export'
at internalCompileFunction (node:internal/vm:73:18)
at wrapSafe (node:internal/modules/cjs/loader:1178:20)
at Module._compile (node:internal/modules/cjs/loader:1220:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
at Object.newLoader (./node_modules/esbuild-register/dist/node.js:2262:9)
at extensions..js …
```
=> fix(storybook-addon-carbon-theme): build storybook addon as CommonJS

packages/ibm-products/src/global/js/utils/StoryDocsPage.js
Contributes to #3591 and #3592 
Fixes console errors in Storybook.
Updated two `propTypes`.
=> fix: Storybook errors 'Invalid argument ... oneOf(...), oneOfType(…)'

packages/ibm-products/src/components/Datagrid/utils/DatagridActions.js
Fixes a console error in Storybook.
Changed a prop name from `placeHolderText` to `placeholder`
=> fix: Storybook error "placeHolderText is not a DOM element"

packages/ibm-products/src/components/Datagrid/utils/DatagridActions.js
Fixes a console error in Storybook.
Removed a prop.
=> fix: Storybook error "renderIcon is not a DOM element"

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js
Fixes a console error in Storybook.
Removed a prop.
=> fix: Storybook error "isDelete is not a DOM element"

packages/ibm-products/src/components/Datagrid/useActionsColumn.js
Contributes to #3595 
Removed a prop.
=> fix: Storybook warning "light prop is deprecated"

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridEmptyBody.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRefBody.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSimpleBody.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
Fixes console errors in Storybook.
Changed value assignment from a `boolean` to the correct `string`.
=> fix: Storybook console error 'role=boolean'

packages/ibm-products/src/components/Datagrid/useDisableSelectRows.js, packages/ibm-products/src/components/Datagrid/useSelectRows.js
Renamed an object property.
**Issue**
`Datagrid/useDisableSelectRows.js`: `getRowProps()` appends `{selectDisabled: true or false}`.
But `Datagrid/DatagridRow.js` (line 114) and `DataSpreadsheet/DataSpreadsheetBody.js` (line 469) use object spreading to apply **all** properties of `getRowProps()` to a tag as attributes, e.g. 
```
<div {...row.getRowProps({ style })} />
```
```
<TableRow {...row.getRowProps({ role: false })} />
```
...resulting in `selectDisabled` being added like this: `<div selectDisabled=true />`
`selectDisabled` is not recognized as a valid prop on a DOM element: the console throws an error.
**Solution**
Renamed `selectDisabled` to `disabled`.
=> fix: Storybook warning "selectDisabled is not a valid prop for a DOM element"

packages/ibm-products/src/global/js/hooks/useCreateComponentStepChange.js
Contributes to #3676 
Fixes the back/previous button in the CreateFullPage component, functionality stopped working after optional handler for back button was added for `CreateTearsheet`.
```
packages/ibm-products/src/global/js/hooks/useCreateComponentStepChange.js
```
Storybook
=> fix(CreateFullPage): fix back button in full page

packages/ibm-products/src/components/ComboButton/ComboButton.stories.js, packages/ibm-products/src/components/CreateFullPage/CreateFullPage.stories.js, packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.stories.js, packages/ibm-products/src/components/EditFullPage/EditFullPage.stories.js, packages/ibm-products/src/components/EditTearsheet/EditTearsheet.stories.js, packages/ibm-products/src/components/EmptyStates/EmptyStates.stories.js, packages/ibm-products/src/components/PageHeader/PageHeader.stories.js, packages/ibm-products/src/components/Tearsheet/Tearsheet.stories.js, packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.stories.js, packages/ibm-products/src/components/Toolbar/Toolbar.stories.js
Contributes to #3667 
Removed `subcomponents` property from Storybook settings.
=> fix: Remove 'subcomponents' from Storybook settings

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js
Contributes to #3680 
Adds support for a custom `renderLabel` function in the filterProps that can be used to customizing the rendering/display of the filter tags from the `FilterSummary` component.
```
```
Storybook
=> feat(Datagrid): add `renderLabel` support to v1 filtering

packages/core/.storybook/preview.js
Contributes to #3590
Removes an unnecessary console log in Storybook.
Removed an component export
=> fix: Storybook console log: "Unknown key Style"

packages/ibm-products/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.stories.js, packages/ibm-products/src/components/EditTearsheetNarrow/EditTearsheetNarrow.stories.js
Contributes to #3697 
Fixes a console error in Storybook.
Removed a prop.
=> fix: Storybook error "multiForm is not a valid prop for a DOM element"

packages/ibm-products/src/components/Datagrid/_datagrid.scss, packages/ibm-products/src/components/_index.scss
Contributes to #3688 
Discovered that the Datagrid does not import the FilterSummary styles, which causes some visual issues since the FilterSummary is an internal component.
Discovered as I was building a [code sandbox](https://codesandbox.io/p/sandbox/datagrid-filter-panel-lj7rn7?file=%2Fsrc%2Findex.scss%3A4%2C39) for Datagrid, filter panel
_Expected layout_
Imported FilterSummary styles from Datagrid
Verified that filter summary styles are now included in the built css
=> fix(Datagrid): import filter summary styles from datagrid

packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js
Contributes to #3691
Enabled the feature flag in the Storybook story.
=> fix: Storybook warning "feature Datagrid.useActionsColumn not enabled" in ColumnCustomization.stories.js

packages/ibm-products/src/components/PageHeader/PageHeader.js
Contributes to #3575
Changed PageHeader prop `subtitle` from `string` to `node`. This will allow passing in jsx to customize the rendering of the subtitle without any prop type errors.
```
packages/ibm-products/src/components/PageHeader/PageHeader.js
```
Storybook
=> chore(PageHeader): update subtitle prop type

packages/ibm-products/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
Contributes to #3508 
This PR will top align cell content when row size is extra large.
```
packages/ibm-products/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
```
Storybook
=> fix(Datagrid): top align cell content for extra large row height (v1)

packages/ibm-products/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
Contributes to #3508 
This PR will top align cell content when row size is extra large.
```
packages/ibm-products/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
```
Storybook
=> fix(Datagrid): top align cell content for extra large row height

packages/ibm-products/src/components/TagSet/TagSet.test.js
Noticed that a `.only` was left in the TagSet tests after https://github.com/carbon-design-system/ibm-products/pull/3646 was merged.
=> fix(TagSet): remove `.only` from tag set tests
