packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/FilterSummary/FilterSummary.js, packages/ibm-products/src/components/TagSet/TagSet.js, packages/ibm-products/src/components/TagSet/TagSet.stories.js, packages/ibm-products/src/components/TagSet/TagSet.test.js, packages/ibm-products/src/components/TagSet/TagSetOverflow.js, packages/ibm-products/src/components/TagSet/_tag-set.scss
Contributes to #3627
This PR adds the ability to specify a `overflowType` prop on the `TagSet`. This will render the items in the `TagSetOverflow` either as they have been or as actual tag components. This change allows filters to be removed from the `TagSetOverflow` which was previously not possible.
```
packages/ibm-products/src/components/FilterSummary/FilterSummary.js
packages/ibm-products/src/components/TagSet/TagSet.js
packages/ibm-products/src/components/TagSet/TagSet.stories.js
packages/ibm-products/src/components/TagSet/TagSet.test.js
packages/ibm-products/src/components/TagSet/TagSetOverflow.js
packages/ibm-products/src/components/TagSet/_tag-set.scss
```
=> feat(TagSet): allow for tag rendering in overflow (v1)

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js
Contributes to #3721 
This PR semantically hides the spacer column used to allow the last visible column to be resized. The spacer column was also getting a class name specifically only for sortable columns, that's been fixed as well.
```
```
Storybook and added new test to check we render the expected number of column headers.
=> fix(Datagrid): semantically hide spacer col

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/OverflowCheckboxes.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js
Contributes to #3724 
Fixes the number of items displayed when viewing all checkbox filters. Also added `autoHideFilters` to filterProps which provides a way to opt out of the view all/view less checkbox filter functionality.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/OverflowCheckboxes.js
```
Storybook
=> fix(Datagrid): correct number of items displayed when viewing all checkbox filters

packages/ibm-products/src/global/js/hooks/index.js, packages/ibm-products/src/global/js/hooks/usePrefix.js
Contributes to #3711 
In an effort to align better with Carbon's approach to providing their prefix to consumers, this addition creates a new `usePrefix` hook and exports it for use.
```
packages/ibm-products/src/global/js/hooks/index.js
packages/ibm-products/src/global/js/hooks/usePrefix.js
packages/ibm-products/src/index.js
```
Used the hook internally to check that it returned the expected prefix.
=> feat: add custom hook returning library prefix

packages/ibm-products/src/components/CreateFullPage/CreateFullPage.docs-page.js, packages/ibm-products/src/components/CreateFullPage/CreateFullPage.stories.js, packages/ibm-products/src/components/CreateFullPage/CreateFullPage.test.js, packages/ibm-products/src/components/CreateFullPage/CreateFullPageStep.js, packages/ibm-products/src/components/CreateInfluencer/CreateInfluencer.js, packages/ibm-products/src/components/CreateInfluencer/CreateInfluencer.test.js, packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.docs-page.js, packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.stories.js, packages/ibm-products/src/components/CreateTearsheet/CreateTearsheetStep.js, packages/ibm-products/src/components/CreateTearsheet/preview-components/MultiStepWithStepInErrorState.js, packages/ibm-products/src/global/js/hooks/useRetrieveStepData.js
Contributes to #2930
The Carbon ProgressIndicator component already supports the "invalid" prop, although it was unused in both the CreateInfluencer for the CreateFullPage and the CreateTearsheet components. These changes involve incorporating the use of this prop.
- I Added the invalid optional prop support to the CreateInfluencer, CreateFullPageStep, CreateTearsheetStep and the useRetrieveStepData hook
- I added storybook examples to show this error state for both the CreateFullPage and the CreateTearsheet
- Added unit-tests
- I tested my changes on storybook new examples that I added in this PR
- introduced more unit-tests
=> fix(CreateTearsheet & CreateFullPage): Influencer step error indicator extension

packages/ibm-products/src/components/Datagrid/useActionsColumn.js
Contributes to #3470 
Change alignment from 'top-right' to 'left'. The previous 'top-right' fix still induced an "oscillation" of the table's container size when the tooltip appeared. Changing the tooltip's alignment to 'left' fixes this problem.
There is no mechanism at this time to allow the developer to change the alignment of the overflow menu's trigger button via a prop without some refactoring.
A single string value.
=> fix(Datagrid): change overflow menu's tooltip alignment to 'left'

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/useSortableColumns.js
Contributes to #3704 
Sortable columns were not adhering to the `minWidth` property in the column definitions while resizing. This PR checks if there is a `minWidth` before defaulting to a min width of 90 for sortable columns so that the sorting icons have room to still display.
```
packages/ibm-products/src/components/Datagrid/useSortableColumns.js
```
Storybook
=> fix(Datagrid): adhere to min width in column definition if one exists

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/useSortableColumns.js
Contributes to #3704 
Sortable columns were not adhering to the `minWidth` property in the column definitions while resizing. This PR checks if there is a `minWidth` before defaulting to a min width of 90 for sortable columns so that the sorting icons have room to still display.
```
packages/ibm-products/src/components/Datagrid/useSortableColumns.js
```
Storybook
=> fix(Datagrid): adhere to min width in column definition if one exists (v1)

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js
Contributes to #3737
Fixes a column resize bug in the Datagrid where if you resized a column focusable items outside of the Datagrid seemed to lose focus. There was some extra logic in the resize end action to prevent this behavior.
While working on this issue, I discovered that we don't need to handle all of the custom logic to handle mouse events with resizing, `react-table` will still take care of that even if we want custom control over the key events so that we have keyboard support with resizing columns. Because of this, I was able to remove some code from `DatagridHeaderRow.js`.
```
```
Storybook
=> fix(Datagrid): address resize end issues (v1)

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/styles/_useInlineEdit.scss
Contributes to #3462 
just does a little classname cleanup. the issue also mentions a small coverage fix required, but i also noticed in storybook that the datagrid inline edit was being deprecated, so i chose to skip it initially because i don't know if the coverage is needed.
=> fix: datagrid header review fixes

packages/ibm-products/src/components/CoachmarkBeacon/_coachmark-beacon.scss
Contributes to #3728
The CSS class this svg issue belongs to (`...-ring`) seems to have been a work in progress that was never finished being developed. There is no story showcasing this feature, and this class is not referenced anywhere else in the code. 
Removing the class entirely.
=> fix(Coachmark): remove malformed svg code

packages/ibm-products/src/components/CreateFullPage/CreateFullPage.test.js, packages/ibm-products/src/components/EditTearsheet/EditTearsheet.js, packages/ibm-products/src/components/EditTearsheet/EditTearsheet.test.js, packages/ibm-products/src/components/EditTearsheet/preview-components/MultiFormEditTearsheet.js
Contributes to #3744
Assign the correct handlers to each of their respective buttons.
Currently, the 2 action buttons on the `EditTearsheet` component refer to the same event handler property. This prohibits the user from distinguishing behavior _and_ closing the modal.
- Distinguished event handler assignment
- Changed 'Cancel' button from type secondary to ghost
- Renamed and repurposed `onHandleModalClick` to `onRequestSubmit`
- Updated prop description
- Updated storybook
- Changed references
- Added actions to handlers
- Added handlers definitions
https://github.com/carbon-design-system/ibm-products/assets/12387334/69bed889-bd83-44ca-aa98-7867c4ee5900
_Observe how action buttons are now associate with the correct handlers._
=> fix(EditTearsheet): Correctly assign action handlers to associated buttons

packages/ibm-products/src/components/Datagrid/Extensions/ColumnAlignment/ColumnAlignment.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js, packages/ibm-products/src/components/Datagrid/_storybook-styles.scss
Contributes to #3467 
Updates storybook usage examples to match design guidance for icon only columns, they should be center aligned. I also added a tooltip to the status icons so that there is still a way to know what the label associated with the status icon is.
```
packages/ibm-products/src/components/Datagrid/Extensions/ColumnAlignment/ColumnAlignment.stories.js
packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js
packages/ibm-products/src/components/Datagrid/_storybook-styles.scss
```
Storybook
=> chore(Datagrid): fix alignment of icon only columns to match guidance

packages/ibm-products/src/components/Guidebanner/Guidebanner.js, packages/ibm-products/src/components/Guidebanner/GuidebannerElement.js, packages/ibm-products/src/components/Guidebanner/GuidebannerElementButton.js, packages/ibm-products/src/components/Guidebanner/GuidebannerElementLink.js, packages/ibm-products/src/components/InlineTip/InlineTipButton.js, packages/ibm-products/src/components/InlineTip/InlineTipLink.js, packages/ibm-products/src/components/index.js, packages/ibm-products/src/global/js/package-settings.js
Contributes to #3759
Add `GuideBanner` and `InlineTip` sub components as exportable.
```
packages/ibm-products/src/components/Guidebanner/Guidebanner.js
packages/ibm-products/src/components/Guidebanner/GuidebannerElement.js
packages/ibm-products/src/components/Guidebanner/GuidebannerElementButton.js
packages/ibm-products/src/components/Guidebanner/GuidebannerElementLink.js
packages/ibm-products/src/components/InlineTip/InlineTipButton.js
packages/ibm-products/src/components/InlineTip/InlineTipLink.js
packages/ibm-products/src/components/index.js
packages/ibm-products/src/global/js/package-settings.js
```
=> fix: GuideBanner and InlineTip - export sub components

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/useColumnCenterAlign.js, packages/ibm-products/src/components/Datagrid/useColumnRightAlign.js
Contributes to #3467 
Refactored the existing test for right aligned columns and added a new test for center aligned columns.
```
packages/ibm-products/src/components/Datagrid/useColumnCenterAlign.js
packages/ibm-products/src/components/Datagrid/useColumnRightAlign.js
```
Ran tests locally
=> chore(Datagrid): add/refactor col alignment tests

packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js, packages/ibm-products/src/components/Datagrid/useRowExpander.js
Contributes to #3749 
Click event from row expanders was bubbling up, causing the `onRowClick` to be called unexpectedly. Thanks @dsav-eng for the detailed issue!
```
packages/ibm-products/src/components/Datagrid/useRowExpander.js
```
Storybook, temporarily added `useOnRowClick` to both `useNestedRows` and `useExpandableRows` and confirmed the expander click does not trigger the `onRowClick`.
=> fix(Datagrid): stop propagation of row expander click event

packages/ibm-products/src/components/CreateSidePanel/CreateSidePanel.stories.js, packages/ibm-products/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js, packages/ibm-products/src/components/EditSidePanel/EditSidePanel.stories.js, packages/ibm-products/src/components/EditTearsheetNarrow/EditTearsheetNarrow.stories.js, packages/ibm-products/src/components/Toolbar/Toolbar.stories.js
Contributes to #3685
Some Carbon components have deprecated their `ariaLabel` props with the now-standard `aria-label` props.
These fixes remove the console logs created by some components: 
```
Warning: This prop syntax has been deprecated. Please use the new `aria-label`.
```
Note: The replacements of `ariaLabel` with `aria-label` was not global. Only those that were found to be generating the error were changed. (A previous attempt to "search and replace all (40 files)" broke a `Datagrid` test for no apparent reason.)
```
packages/ibm-products/src/components/CreateSidePanel/CreateSidePanel.stories.js
packages/ibm-products/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.stories.js …
```
=> fix: replace prop from 'ariaLabel' to 'aria-label'

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRefBody.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSimpleBody.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
Contributes to #3679
I _think_ this finally solves the unique key prop console errors we've been seeing in Datagrid. Found [this discussion](https://github.com/TanStack/table/discussions/2647) helpful, with others stating that destructing the key from `row.getRowProps()` fixes the issue.
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRefBody.js
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.js
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSimpleBody.js
```
Storybook
=> fix(Datagrid): destructure key to fix eslint unique key error

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/Extensions/RowActionButtons/RowActionButtons.stories.js, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/useActionsColumn.js
Contributes to #3557
This PR fixes some behavior in the row action buttons (ie `useActionButtons`). According to the design guidance, if the action column is frozen/sticky, the row action buttons will _always_ display in an overflow menu. If the action column is not frozen/sticky then it should display as icon buttons for 1 or 2 actions, anything greater than 2 will be displayed in an overflow menu. Lastly, if a row is not frozen, the actions should only show on row hover/focus of icon buttons.
I also fixed an issue where the action column included the column resizer but should not have and removed the background color change on hover of the action column header.
``` …
```
=> fix(Datagrid): match designs, frozen/non frozen action button behavior (v1)

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/Extensions/RowActionButtons/RowActionButtons.stories.js, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/useActionsColumn.js
Contributes to #3557
This PR fixes some behavior in the row action buttons (ie `useActionButtons`). According to the design guidance, if the action column is frozen/sticky, the row action buttons will _always_ display in an overflow menu. If the action column is not frozen/sticky then it should display as icon buttons for 1 or 2 actions, anything greater than 2 will be displayed in an overflow menu. Lastly, if a row is not frozen, the actions should only show on row hover/focus of icon buttons.
I also fixed an issue where the action column included the column resizer but should not have and removed the background color change on hover of the action column header.
``` …
```
=> fix(Datagrid): match designs, frozen/non frozen action button behavior

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridExpandedRow.js, packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.stories.js
Contributes to #3782 
The way we were rendering the expandable row component was causing a hook error because it was not rendered as `jsx`. After rendering `ExpandedRowContentComponent` as jsx and adding in a test hook (`usePrefix()`) inside of the row expansion renderer component for testing, this error is no longer seen when multiple expandable rows are open.
```
packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.stories.js
```
Storybook
___
To view this error, see [this code sandbox](https://codesandbox.io/s/nervous-wright-hc6fdd?file=/src/Table.js) and attempt to open more than one expandable row
=> fix(Datagrid): properly render expandable row component via jsx

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRefBody.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSimpleBody.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
Contributes to #3679
I _think_ this finally solves the unique key prop console errors we've been seeing in Datagrid. Found [this discussion](https://github.com/TanStack/table/discussions/2647) helpful, with others stating that destructing the key from `row.getRowProps()` fixes the issue.
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRefBody.js
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.js
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSimpleBody.js
```
Storybook
=> fix(Datagrid): destructure key to fix eslint unique key error (v1)

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridExpandedRow.js, packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.stories.js, packages/ibm-products/src/global/js/hooks/index.js, packages/ibm-products/src/global/js/hooks/usePrefix.js
Contributes to #3782 
The way we were rendering the expandable row component was causing a hook error because it was not rendered as `jsx`. After rendering `ExpandedRowContentComponent` as jsx and adding in a test hook (`usePrefix()`) inside of the row expansion renderer component for testing, this error is no longer seen when multiple expandable rows are open.
```
packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.stories.js
```
Storybook
___
To view this error, see [this code sandbox](https://codesandbox.io/s/nervous-wright-hc6fdd?file=/src/Table.js) and attempt to open more than one expandable row
=> fix(Datagrid): render expanded component via jsx (v1)

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/useActionsColumn.js
Contributes to #3464
Adds and refactors existing tests for `useActionColumn` taking into consideration the most recent changes.
```
```
All Datagrid tests still pass
_Before_
_After_
_Before_
_After_
Something interesting I learned is you can use `within` from `@testing-library/dom` to query within a particular element rather than having to use `screen`, this helped in several places to avoid using `querySelector`s.
=> chore(Datagrid): add/refactor useActionColumn tests (v1)

packages/ibm-products/src/components/Datagrid/useStickyColumn.js
Contributes to #3466 
Updated copyright header and added a few istanbul ignores to functionality related to resizing, which we've done in other components ([`BreadcrumbWithOverflow`](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js#L200), [`ActionBar`](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/ActionBar/ActionBar.js#L195), [`PageHeader`](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/PageHeader/PageHeader.js)).
```
packages/ibm-products/src/components/Datagrid/useStickyColumn.js
```
Ran tests and reviewed coverage report for `useStickyColumn`
=> chore(Datagrid): frozen/sticky column testing, add istanbul ignore for resize

packages/ibm-products/src/components/Datagrid/useStickyColumn.js
Contributes to #3466 
Updated copyright header and added a few istanbul ignores to functionality related to resizing, which we've done in other components ([`BreadcrumbWithOverflow`](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js#L200), [`ActionBar`](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/ActionBar/ActionBar.js#L195), [`PageHeader`](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/PageHeader/PageHeader.js)).
```
packages/ibm-products/src/components/Datagrid/useStickyColumn.js
```
Ran tests and reviewed coverage report for `useStickyColumn`
=> chore(Datagrid): frozen column testing, add istanbul ignore for resize

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/useOnRowClick.js
Contributes to #3463 
addresses a single bug i found with the `onKeyDown` handler and fills out some test coverage.
=> fix: clickable row review fixes

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridExpandedRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js
Increases overall test coverage of the base Datagrid component, added a few `istanbul ignore`s but only for functionality either related to resizing or extensions that are not part of the base component.
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.js
```
Ran Datagrid tests and confirmed test coverage reaches at …
=> test(Datagrid): increase test coverage for base component

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss
Contributes to #3692 
Fixes an issue where there was a vertical scrollbar when resizing columns if pagination was included. Added `overflow-y: hidden` to the table when resizing.
```
```
Storybook
=> fix(Datagrid): fix visible scroll bar when resizing with pagination

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridExpandedRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js
Increases overall test coverage of the base Datagrid component, added a few `istanbul ignore`s but only for functionality either related to resizing or extensions that are not part of the base component. I also was able to remove `.skip` from the batch action test, the button menu selector was using a v11 class name which was causing it not to find the menu or menu items.
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.js …
```
=> test(Datagrid): increase base component test coverage (v1)

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/SidePanel/_side-panel.scss
Closes to #3817
Changes how the height of the side panel title is calculated
Stopped changing the container height, instead adding negative margin to the title-text.
Storybook following steps in issue.
=> fix: side panel scrolled height

packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js
Contributes to #3455 
{{Change to use updatedDragCols instead of using the column to get text}}
packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js
Storybook
=> fix: unhandling error that caused by extra columns for issue #3455

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss
Contributes to #3692 
Fixes an issue where there was a vertical scrollbar when resizing columns if pagination was included. Added `overflow-y: hidden` to the table when resizing.
```
```
Storybook
=> fix(Datagrid): fix visible scroll bar when resizing with pagination (v1)

packages/ibm-products/src/components/MultiAddSelect/MultiAddSelect.stories.js, packages/ibm-products/src/components/SingleAddSelect/SingleAddSelect.stories.js
Contributes to #3797 
Update storybook control `items` to use dropdown menu instead of node. Only addition is adding a state where no items are present. The rest of the work was restructuring the current examples in a dropdown menu.
`packages/ibm-products/src/components/SingleAddSelect/SingleAddSelect.stories.js`
`packages/ibm-products/src/components/MultiAddSelect/MultiAddSelect.stories.js`
Storybook
=> chore(Add Select): reconfigure items node to use dropdown menu

packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js, packages/ibm-products/src/components/Datagrid/useSelectRows.js
Contributes to #3818 
This enhancement adds `selectedRowData` to the state data returned from the datagrid state via the state reducer we have. We are able to do this by tapping into react table's reducer.
```
```
Verified that the new property `selectedRowData` is returning expected values, accessed from `datagridState.state.selectedRowData`. Matches the same data structure as `datagridState.state.selectedRowIds`.
=> feat(Datagrid): selectable rows return all row data selected via react-table `state`

packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js, packages/ibm-products/src/components/Datagrid/useSelectRows.js
Contributes to #3818 
This enhancement adds `selectedRowData` to the state data returned from the datagrid state via the state reducer we have. We are able to do this by tapping into react table's reducer.
```
```
Verified that the new property `selectedRowData` is returning expected values, accessed from `datagridState.state.selectedRowData`.
=> feat(Datagrid): selectable rows return all row data selected via react-table `state` (v1)

.github/workflows/release-preminor.yml, .github/workflows/release-scheduled.yml
Using implicit method[^1] of passing secrets first.
[^1]: [Passing inputs and secrets to a reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow)
=> fix: pass tokens in reusable workflow

packages/core/.storybook/carbon.scss, packages/core/.storybook/index.scss, packages/core/.storybook/main.js, packages/ibm-products/src/components/ActionBar/_storybook-styles.scss, packages/ibm-products/src/components/ActionSet/_storybook-styles.scss, packages/ibm-products/src/components/BreadcrumbWithOverflow/_storybook-styles.scss, packages/ibm-products/src/components/ButtonSetWithOverflow/_storybook-styles.scss, packages/ibm-products/src/components/CreateSidePanel/_storybook-styles.scss, packages/ibm-products/src/components/EditFullPage/_storybook-styles.scss, packages/ibm-products/src/components/EditInPlace/_storybook-styles.scss, packages/ibm-products/src/components/EditSidePanel/_storybook-styles.scss, packages/ibm-products/src/components/FilterSummary/_storybook-styles.scss, packages/ibm-products/src/components/InlineTip/_storybook-styles.scss, packages/ibm-products/src/components/SidePanel/_storybook-styles.scss, packages/ibm-products/src/components/TagSet/_storybook-styles.scss
Replaces `@carbon/ibm-products-styles` until package is actually published.
This should fix our broken builds. Once published, we can replace the URLs again.
=> chore: revert ibm-products-styles paths

packages/ibm-products/src/components/Datagrid/Datagrid.mdx, packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.js
Contributes to #3587 
Removed the hardcoded `More` string for the menu button in `DatagridToolbar` and added a callback that can be passed through to Carbon's `TableBatchActions` component to translate some of the strings related to that component.
```
```
Storybook
=> fix(Datagrid): remove hardcoded label, add cb fn for TableBatchActions (v1)

scripts/updateSourceMaps.js
Update `updateSourceMaps.js` based on error from prerelease actions.
Update path to `ibm-products-styles`.
`yarn build` no longer shows error.
=> chore: update styles path

packages/ibm-products-styles/package.json
The version between our core package and the styles package became out of sync, I think because the styles package failed during the prerelease action. I manually published the new version `2.17.0` to npm, adding this change here so that `lerna publish` will keep them synced for further releases.
```
packages/ibm-products-styles/package.json
```
Verified on npm that the new version was published succussfully
=> fix: manually bump styles package version

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/CreateTearsheet/_create-tearsheet.scss
Contributes to #3857 
This change allows the height of create tearsheet steps to fill the available space.
```
packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
packages/ibm-products-styles/src/components/CreateTearsheet/_create-tearsheet.scss
```
Storybook
=> fix(CreateTearsheet): fix step height to fill available space

packages/ibm-products/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js
Closes to #3865
Tiny fix ... would have let it slide but was reading and investigated so figured better to commit the fix since it took me long enough to remember that we had the preview components for Create ... 🙈 
Fixes an issue where changing `verticalPosition` in Create Tearsheet stories didn’t actually do anything. 🤔 
💤 
Storybook and CI
=> chore(CreateTearsheet): pass props to story

packages/ibm-products/src/global/js/hooks/useCreateComponentStepChange.js
Contributes to #3413
fixes small bug where when a user passes in an `onClose` function that doesn't close the tearsheet the content inside the tearsheet was disappearing.
=> fix: create tearsheet reset bug

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.stories.js, packages/ibm-products/src/components/Datagrid/useSelectRows.js
Contributes to #3808 
Previously, the row expander in some cases could be rendered after the row checkbox which is incorrect. With this change, the row expander will always be rendered first.
```
packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.stories.js
```
Storybook
=> fix(Datagrid): always force row expander to be first column

cspell.json, packages/core/story-structure.js, packages/ibm-products-styles/src/components/Carousel/_carbon-imports.scss, packages/ibm-products-styles/src/components/Carousel/_carousel.scss, packages/ibm-products-styles/src/components/Carousel/_index-with-carbon.scss, packages/ibm-products-styles/src/components/Carousel/_index.scss, packages/ibm-products-styles/src/components/Guidebanner/_carbon-imports.scss, packages/ibm-products-styles/src/components/Guidebanner/_guidebanner.scss, packages/ibm-products-styles/src/components/Guidebanner/_index-with-carbon.scss, packages/ibm-products-styles/src/components/Guidebanner/_index.scss, packages/ibm-products-styles/src/components/_index.scss, packages/ibm-products/src/components/Carousel/Carousel.docs-page.js, packages/ibm-products/src/components/Carousel/Carousel.js, packages/ibm-products/src/components/Carousel/Carousel.stories.js, packages/ibm-products/src/components/Carousel/Carousel.test.js, packages/ibm-products/src/components/Carousel/CarouselItem.js, packages/ibm-products/src/components/Carousel/_storybook-styles.scss, packages/ibm-products/src/components/Carousel/index.js, packages/ibm-products/src/components/Carousel/utils.js, packages/ibm-products/src/components/Guidebanner/Guidebanner.docs-page.js, packages/ibm-products/src/components/Guidebanner/Guidebanner.js, packages/ibm-products/src/components/Guidebanner/Guidebanner.stories.js, packages/ibm-products/src/components/Guidebanner/Guidebanner.test.js, packages/ibm-products/src/components/Guidebanner/GuidebannerElement.js, packages/ibm-products/src/components/Guidebanner/GuidebannerElementButton.js, packages/ibm-products/src/components/Guidebanner/GuidebannerElementLink.js, packages/ibm-products/src/components/Guidebanner/_storybook-styles.scss, packages/ibm-products/src/components/Guidebanner/index.js, packages/ibm-products/src/global/js/package-settings.js
Contributes to #3599
Guide banners are used to give a bird’s eye view of information users need to know before diving into the page’s workflow.
This is a new component.
`Carousel` has been added as an "internal" component. This is a common component used by other Novice to Pro components.
=> feat: port Guidebanner component w Carousel to v2

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/FilterSummary/FilterSummary.js, packages/ibm-products/src/components/FilterSummary/_filter-summary.scss, packages/ibm-products/src/components/TagSet/TagSet.js
Contributes to #3893 
Includes fixes so that the `Clear filters` button can be placed inline next to the filter tags and not spaced at the end of the filter summary component. This required changes/enhancements to the current `TagSet` component in order for it to measure available space from a given element opposed to it's own container element. To account for the width of the `Clear filters` button I also included a new prop, `measurementOffsetValue` otherwise the TagSet only measures based on the width of the entire FilterSummary as opposed to the FilterSummary minus the width of the `ClearFilter` button since that always needs to be visible.
```
packages/ibm-products-styles/src/components/FilterSummary/_filter-summary.scss
packages/ibm-products/src/components/FilterSummary/FilterSummary …
```
=> feat(FilterSummary): enable filter summary clear button to be placed inline (v1)

packages/ibm-products-styles/src/components/FilterSummary/_filter-summary.scss, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js, packages/ibm-products/src/components/FilterSummary/FilterSummary.js, packages/ibm-products/src/components/TagSet/TagSet.js
Contributes to #3893 
Includes fixes so that the `Clear filters` button can be placed inline next to the filter tags and not spaced at the end of the filter summary component. This required changes/enhancements to the current `TagSet` component in order for it to measure available space from a given element opposed to it's own container element. To account for the width of the `Clear filters` button I also included a new prop, `measurementOffsetValue` otherwise the TagSet only measures based on the width of the entire FilterSummary as opposed to the FilterSummary minus the width of the `ClearFilter` button since that always needs to be visible.
```
packages/ibm-products-styles/src/components/FilterSummary/_filter-summary.scss
packages/ibm-products/src/components/FilterSummary/FilterSummary …
```
=> feat(FilterSummary): enable filter summary clear button to be placed inline

packages/ibm-products-styles/src/components/Checklist/_carbon-imports.scss, packages/ibm-products-styles/src/components/Checklist/_checklist.scss, packages/ibm-products-styles/src/components/Checklist/_index-with-carbon.scss
This is a simple update. 
The Novice to Pro Checklist component was in development during the Carbon for IBM Products SCSS global update. This just brings the component inline with the other components.
Added Carbon-specific SCSS files
Built locally and verified no Carbon styles related to checklist.
=> fix(Checklist): add carbon scss import files

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid.stories/ColumnAlignment/ColumnAlignment.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid.stories/Header/Header.stories.js
Removes section added to storybook navigation, I'm guessing because the `Header` and `ColumnAlignment` changes removed the `title` from the story default export.
Added `title` porperty to story default export for Header and ColumnAlignment
Storybook
Removes section highlighted below:
=> chore: fix small issue with new datagrid story structure

packages/core/story-structure.js, packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid.stories/ColumnAlignment/ColumnAlignment.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid.stories/Header/Header.stories.js
Contributes to #3863
Initial work in reorganizing Datagrid stories.
For now, moving the `Header` and `Column alignment` stories out from Extensions to align with our current “base” v. “extension” structure.
Will continue to open more PRs for more reorganization in order to keep changes small and somewhat related. (Not prioritizing story order for now.)
- Move `Header` and `Column alignment` into main Datagrid section
- Rename stories
- `With pagination` ➡️ `Pagination`
- `With column alignment` ➡️ `Column alignment`
- Remove “unofficial” stories like `Is hover on row` and `Top alignment`
- Functionality _does_ exist but `#notsponsored` since it’s not explicitly discussed in our docs
Storybook and CI
=> chore: reorganize datagrid stories v1

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
Contributes to #3947 and #3867
This PR completely resets filtering history when the "Clear filters" button from the `FilterSummary` is used to reset the filters.
Emptied out `lastAppliedFilters` ref.
```
```
Storybook
1. I added two checkbox filters from the filter panel
2. Clicked `Clear filters` from `FilterSummary`
3. I selected another filter checkbox but did not click "Apply' and instead click "Cancel"
4. No new filters should be added to filter summary and it should just go back to the initial state
=> feat(Datagrid): clear out filter history on reset

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
Contributes to #3947 and #3867
This PR completely resets filtering history when the "Clear filters" button from the `FilterSummary` is used to reset the filters.
Emptied out `lastAppliedFilters` ref.
```
```
Storybook
1. I added two checkbox filters from the filter panel
2. Clicked `Clear filters` from `FilterSummary`
3. I selected another filter checkbox but did not click "Apply' and instead click "Cancel"
4. No new filters should be added to filter summary and it should just go back to the initial state
=> feat(Datagrid): clear out filter history on reset (v1)

packages/core/package.json, packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss, packages/ibm-products/package.json, packages/ibm-products/src/components/CreateSidePanel/CreateSidePanel.js, packages/ibm-products/src/components/CreateSidePanel/CreateSidePanel.stories.js, packages/ibm-products/src/components/EditSidePanel/EditSidePanel.js, packages/ibm-products/src/components/EditSidePanel/EditSidePanel.stories.js, packages/ibm-products/src/components/SidePanel/SidePanel.js, yarn.lock
Closes #3752
Updates to the side panel AI expanding it's usage to the patterns.
- SidePanel to add a type check to the slug and to mark the prop as `Experimental` as per Carbon/React.
- CreateSidePanel added feature
- EditSidePanel added feature
- Added design updates which included moving the 
Storybook.
=> feat: side panel for create and edit + type check

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
Contributes to #3945
This fixes an issue with Datagrid filtering where if the Datagrid is refreshed (`isFetching: true`) while the filter panel is open and if some filters have been deselected but not applied, those filters are removed unintentionally.
Added `useEffect` in `useFilters` to properly re-apply filters during `isFetching` state.
```
```
Changed panel story in storybook to include the ability to refresh table
=> fix(Datagrid): re-apply filters during fetching state (v1)

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Filtering.docs-page.js
Contributes to #3786 
Addresses situation where there can be duplicate `id`s with radio button filters in the Datagrid, stemming from the `Any`/default radio button. There is now a way to pass in values for the default radio button and if nothing is passed in then we handle it internally to ensure there is not a duplicate id for the default radio button.
```
packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Filtering.docs-page.js
```
Storybook, changed `status` filter to type of `radio` just to test
=> fix(Datagrid): address duplicate id with radio filters

packages/ibm-products/src/components/Datagrid/Datagrid.mdx, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
Contributes to #3786 
Addresses situation where there can be duplicate `id`s with radio button filters in the Datagrid, stemming from the `Any`/default radio button. There is now a way to pass in values for the default radio button and if nothing is passed in then we handle it internally to ensure there is not a duplicate id for the default radio button.
```
packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Filtering.docs-page.js
```
Storybook, changed `status` filter to type of `radio` just to test
=> fix(Datagrid): address duplicate id with radio filters (v1)

packages/ibm-products/src/components/Datagrid/useFiltering.js
Contributes to #3732 
This PR allows for other date formats to be used with filtering in the Datagrid. Prior to this, all date columns which used filtering had to be Date objects. To test this, I temporarily changed the `makeData` file to use `new Intl.DateTimeFormat('en-US').format(date)`.
```
packages/ibm-products/src/components/Datagrid/useFiltering.js
```
Storybook, with localized date format
=> feat(Datagrid): support timestamp date formats in filtering

packages/ibm-products/src/components/Datagrid/useFiltering.js
Contributes to #3732 
This PR allows for other date formats to be used with filtering in the Datagrid. Prior to this, all date columns which used filtering had to be Date objects. To test this, I temporarily changed the `makeData` file to use `new Intl.DateTimeFormat('en-US').format(date)`.
```
packages/ibm-products/src/components/Datagrid/useFiltering.js
```
Storybook, with localized date format
=> feat(Datagrid): support timestamp date formats in filtering (v1)

config/jest-config-ibm-cloud-cognitive/setup/setupFilesAfterEnv.js, packages/ibm-products/src/components/InlineTip/InlineTip.test.js, packages/ibm-products/src/components/InlineTip/InlineTipButton.js, packages/ibm-products/src/components/InlineTip/InlineTipLink.js, packages/ibm-products/src/components/index.js, packages/ibm-products/src/global/js/package-settings.js
Adds missing N2P components to list of exports
```
packages/ibm-products/src/components/index.js
```
=> fix: add missing N2P component exports

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/motion/variants.js
Contributes to #2689 
Allows the filter panel in the Datagrid to respond to the user's reduce motion setting.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/motion/variants.js
```
Storybook, toggled `Reduce motion` in my osx settings to confirm correct behavior
=> feat(Datagrid): add reduced motion support to filter panel (v1)

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/SidePanel/_side-panel.scss
Contributes to #3812 (v1)
Update actions container to be 100% wide at `2xl`.
```
packages/ibm-products/src/components/SidePanel/_side-panel.scss
```
=> fix(SidePanel): action buttons layout at 2xl (v1)

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
Contributes to #3812 (v1)
Update actions container to be 100% wide at `2xl`.
```
packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
```
=> fix(SidePanel): action buttons layout at 2xl (v2)

packages/ibm-products/src/components/Tearsheet/TearsheetShell.js
Fixes #3988.
Modified checkFocus() so it doesn't try to focus tearsheets that are closed.
Ran existing storybook test and also ran with my own app.
@dcwarwick maybe you can check and merge this?
=> fix(Tearsheet): stop trying to focus closed tearsheets

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/motion/variants.js
Contributes to #4006 
Updates the motion specs of the reduced motion filter panel in the Datagrid. 
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/motion/variants.js
```
Storybook, turned on `Reduced motion` in osx settings
=> fix(Datagrid): use correct motion specs for reduced motion filter panel (v1)

packages/ibm-products-styles/src/components/Datagrid/styles/addons/_FilterFlyout.scss, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
Contributes to #2696 
Adds responsive changes to the Filter Flyout so that it renders correctly on smaller viewport widths.
https://github.com/carbon-design-system/ibm-products/assets/10215203/5de28a40-62dc-43bc-82fe-38e669073f97
```
packages/ibm-products-styles/src/components/Datagrid/styles/addons/_FilterFlyout.scss
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
```
Storybook
=> feat(Datagrid): add responsive updates to filter flyout

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js, packages/ibm-products/src/components/Datagrid/styles/addons/_FilterFlyout.scss
Contributes to #2696 
Adds responsive changes to the Filter Flyout so that it renders correctly on smaller viewport widths.
https://github.com/carbon-design-system/ibm-products/assets/10215203/5de28a40-62dc-43bc-82fe-38e669073f97
```
packages/ibm-products-styles/src/components/Datagrid/styles/addons/_FilterFlyout.scss
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
```
Storybook
=> feat(Datagrid): add responsive updates to filter flyout (v1)

packages/ibm-products/src/components/SidePanel/SidePanel.js
Contributes to #4015
Prevents a type error from being thrown if `selectorPageContent` is passed a selector that does not match any element in the DOM. I also added a warning if we cannot find the `selectorPageContent` element and it is a `slideIn` panel.
```
packages/ibm-products/src/components/SidePanel/SidePanel.js
```
Storybook, temporarily passed in a selector that didn't exist and verified that the panel still renders, just as a slide over instead of slide in.
FYI @lee-chase
=> fix(SidePanel): check for element before proceeding, add warning

packages/ibm-products/scripts/generate/templates/DISPLAY_NAME.mdx, packages/ibm-products/scripts/generate/templates/_storybook-styles.scss
Addresses issues caught by @paul-balchin-ibm while using the generate script. Made some mdx fixes and updates path in the genereated `_storybook-styles.scss` file.
```
packages/ibm-products/scripts/generate/templates/DISPLAY_NAME.mdx
packages/ibm-products/scripts/generate/templates/_storybook-styles.scss
```
Ran `yarn generate TestComponent` and verified that storybook successfully included the new component
=> fix: update generate component script

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useShouldDisableButtons.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js, packages/ibm-products/src/components/Datagrid/utils/filterPropsForTesting.js, packages/ibm-products/src/components/FilterSummary/FilterSummary.js, packages/ibm-products/src/components/FilterSummary/FilterSummary.test.js, packages/ibm-products/src/components/SteppedAnimatedMedia/assets/index.js
Contributes to #3942 
Adds test coverage to at least 80% to the following Datagrid files related to filtering:
```
FilterPanel.js
FilterFlyout.js
FilterSummary.js
useSubscribeToEventEmitter.js
useShouldDisableButtons.js
constants.js
```
Most of the changes are in `Datagrid.test.js`, however, I did clean up a few spots where a prop had a default value but was a required prop so it didn't need a default value.
I also fixed a bug in the `FilterSummary` where we never used the provided `ref` from `forwardRef` if one was passed in, instead we accidentally always use our own. Also added tests for the `FilterSummary`.
``` …
```
=> test(Datagrid): beginning of filtering test coverage

packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
Contributes to #3966 
Changed padding to spacing-05 when there is no subtitle, if a subtitle is present then padding would be spacing-03
`packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss`
```
.#{$block-class}__title-container {
...
padding: $spacing-05;
...
&:has(~ .#{$block-class}__subtitle-text) {
padding-bottom: $spacing-03;
}
...
```
Manually tested in Storybook
=> fix(side panel): increase title spacing in side panel without subtitle

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/useOnRowClick.js
Contributes to #3758 
when user clicks on child row, the onRowClick event should be triggered and a corresponding css styling should be applied to that row.
Row selection updated to closest row.
`packages/ibm-products/src/components/Datagrid/useOnRowClick.js`
`packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss`
Storybook.
Add `useOnRowClick` hook in "Nested row story" as the following
```
const SingleLevelNestedRows = ({ ...args }) => {
const columns = React.useMemo(() => defaultHeader, []);
const [data] = useState(makeData(10, 2));
const datagridState = useDatagrid(
{
columns,
data,
onRowClick: (row, event) => {
action()(event);
},
DatagridActions,
...args.defaultGridProps,
},
useNestedRows,
useOnRowClick
);
return <Datagrid datagridState={{ ...datagridState }} />;
}; …
```
=> fix(DataGrid): nested rows on click on child row v1

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.js
Contributes to #3874
fixes all the accessibility violations in datagrid that were related to assigning roles unnecessarily
=> fix: remove unnecessary datagrid roles

packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js
Contributes to #3899 
This was something that only required storybook updates, since the `renderDateLabel` property uses `.toLocaleDateString()` to render the filter tags we need to also use a localized date format for the `DatePicker` in the filter panel/flyout (with the use of `navigator?.language`).
```
packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js
```
Storybook (changed my browsers preferred language list to test)
=> chore(Datagrid): use browser locale to avoid confusion in formatting (v1)

packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js
Contributes to #3899 
This was something that only required storybook updates, since the `renderDateLabel` property uses `.toLocaleDateString()` to render the filter tags we need to also use a localized date format for the `DatePicker` in the filter panel/flyout (with the use of `navigator?.language`).
```
packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js
```
Storybook (changed my browsers preferred language list to test)
=> chore(Datagrid): use browser locale to avoid confusion in formatting

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.js, packages/ibm-products/src/components/Datagrid/useNestedRows.js
Contributes to #3815 
Adds new support for initially expanded nested rows. I have added a new story in the Nested rows directory demonstrating this new behavior.
Simply provide an `expandedRowIds` object to the `initialState` object provided to the `useDatagrid` hook.
```jsx
const datagridState = useDatagrid(
{
columns,
data,
initialState: {
expandedRowIds: {
1: true,
3: true,
},
}
},
useNestedRows
);
```
```
packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.js
packages/ibm-products/src/components/Datagrid/useNestedRows.js
```
Storybook and added a new test
=> feat(Datagrid): add support for initially expanded nested rows

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.js, packages/ibm-products/src/components/Datagrid/useNestedRows.js
Contributes to #3815 
Adds new support for initially expanded nested rows. I have added a new story in the Nested rows directory demonstrating this new behavior.
Simply provide an `expandedRowIds` object to the `initialState` object provided to the `useDatagrid` hook.
```jsx
const datagridState = useDatagrid(
{
columns,
data,
initialState: {
expandedRowIds: {
1: true,
3: true,
},
}
},
useNestedRows
);
```
```
packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.js
packages/ibm-products/src/components/Datagrid/useNestedRows.js
```
Storybook and added a new test
=> feat(Datagrid): add support for initially expanded nested rows (v1)

packages/ibm-products/src/components/Tearsheet/Tearsheet.js, packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.js, packages/ibm-products/src/components/Tearsheet/TearsheetShell.js
Contributes to #4013
Added an optional 'ariaLabel' prop to Tearsheet/TearsheetNarrow modal components. When the 'ariaLabel' prop is provided, it will be used for the 'aria-label' attribute. If not provided, the 'title' content will be used as the default 'aria-label'.
packages/ibm-products/src/components/Tearsheet/Tearsheet.js
packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.js
packages/ibm-products/src/components/Tearsheet/TearsheetShell.js
storybook controls
=> feat(Tearsheet): support aria-label

packages/ibm-products/carbon.yml, packages/ibm-products/src/components/index.js
Contributes to #4132
Fixes an issue where we never actually exported ButtonMenu in our v1 when we added it as a canary component. 🙈 
Add to index.js and updated `carbon.yml` for good measure
c4p CI checks pass
=> fix(ButtonMenu): export as canary

packages/ibm-products/src/components/index.js, packages/ibm-products/src/global/js/package-settings.js
Follow up to #4132, this PR just exports the `ButtonMenuItem` so it can be used with the `ButtonMenu` in v1.
Export `ButtonMenuItem`
=> feat(ButtonMenu): export button menu item component (v1)

packages/ibm-products/src/components/Datagrid/Datagrid.test.js
Issue brought up via slack, the way the test to check the `renderDateLabel` was written could be incorrectly formatted given different locales, I explicitly set it now (ie `.toLocaleDateString('en-US')`) which will prevent this from happening moving forward.
`Datagrid.test.js`
Verified that all tests still pass
fyi @lee-chase
=> test(Datagrid): always set a locale to prevent date format changes in `renderDateLabel` test (v1)

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/SidePanel/_side-panel.scss
Contributes to #3966 
This is to change padding to spacing-05 when there is no subtitle, if a subtitle is present then padding would be spacing-03
`packages/ibm-products/src/components/SidePanel/_side-panel.scss`
```
.#{$block-class}__title-container {
padding: $spacing-05;
&:has(~ .#{$block-class}__subtitle-text) {
padding-bottom: $spacing-03;
}
```
Storybook
=> fix(sidePanel): adjust title spacing when there is no subtitle v1

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.js, packages/ibm-products/src/components/Datagrid/useRowIsMouseOver.js
Contributes to #3819
{{Fix the issue of Last hovered row stays in the datagrid table when not hovering using useRowIsMouseOver}}
=> fix(Datagrid): resolve useRowIsMouseOver issue V1

packages/ibm-products-styles/src/components/Datagrid/_datagrid.scss, packages/ibm-products-styles/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js
Contributes to #3725 
The pagination component when used in conjunction with the filter panel needed to be rendered with the table and not outside the table and filter panel. Because of the fact that the filter panel when open has a large height, previously the pagination component wasn't visible. It now renders below the last row of the table.
There was also a bug in the panel height when it was not open it was still causing content below the Datagrid to be pushed down the page, this should only occur when the panel is open.
```
packages/ibm-products-styles/src/components/Datagrid/_datagrid.scss …
```
=> fix(Datagrid): fix placement of pagination when used with filter panel

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/useActionsColumn.js, yarn.lock
Contributes to #3662 
We should use the `prepareProps` utility to remove the `isDelete` prop if there are either 1 or 2 column actions, 
`ibm-products/packages/ibm-products/src/components/Datagrid/useActionsColumn.js`
`ibm-products/packages/ibm-products/src/components/Datagrid/Datagrid.test.js`
Storybook
=> fix(DataGrid): use action column use isdelete prop V1

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/CreateSidePanel/_create-side-panel.scss, packages/ibm-products-styles/src/components/EditSidePanel/_edit-side-panel.scss, packages/ibm-products/src/components/CreateSidePanel/CreateSidePanel.stories.js, packages/ibm-products/src/global/js/hooks/useResizeObserver.js
Fixes #4177 #4176
Tidies up and removes styling differences between core SidePanel and CreateSidePanel/EditSidePanel. Some styling had no effect, other parts were no longer relevant.
Fixed the dependency lists in useResizeObserver.
NOTE: @matthewgallo @Laura-Marshall the only visible difference is the change of subtitle from `$text-secondary` to default. Does the SidePanel pattern need changing, I cannot make a case the CreateSidePanel not following the pattern. 
The SidePanel design does not include setting subtitle text color to $test-secondary. https://www.figma.com/file/Yz74b1hPqqYWwEtmcPqojq/(v10)-Gray-10---IBM-Products?type=design&node-id=8858-390242&mode=design&t=3fDSawd8fVykIuwe-0
- subtitle text in create is now default (was $text-secondary)
- Removed styles no longer needed from …
=> fix: side panel and tearsheet fixes

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/ibm-products/src/components/Datagrid/_datagrid.scss, packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss
Contributes to #3725 
The pagination component when used in conjunction with the filter panel needed to be rendered with the table and not outside the table and filter panel. Because of the fact that the filter panel when open has a large height, previously the pagination component wasn't visible. It now renders below the last row of the table.
There was also a bug in the panel height when it was not open it was still causing content below the Datagrid to be pushed down the page, this should only occur when the panel is open.
```
packages/ibm-products-styles/src/components/Datagrid/_datagrid.scss …
```
=> fix(Datagrid): fix placement of pagination when used with filter panel (v1)

packages/ibm-products/src/components/Datagrid/Datagrid/DraggableElement.js, packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js
Contributes to #3624 
This should prevent dropping into the locked column position in the customize column modal.
Transform styles are not being updated if the item is in locked condition.
`packages/ibm-products/src/components/Datagrid/Datagrid/DraggableElement.js`
Storybook
=> fix(DataGrid): customize column prevent disabled drop v1

packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js, packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js
Contributes to #4091 
In the datagrid component, when customizing the columns in the modal the compulsory columns can be deselected by the Select all button.
Filtered the locked column when select all works.
Storybook
=> fix(DataGrid): column customisation not unselect locked columns V1

packages/ibm-products/src/components/ButtonMenu/ButtonMenu.js, packages/ibm-products/src/components/ButtonMenu/ButtonMenu.stories.js, packages/ibm-products/src/components/ButtonMenu/ButtonMenu.test.js
Contributes to #3519 
Follow a11y guideline about "accessible label should contain or match the visible labels) or allow overrides
Provide the menuAriaLabel prop to be passed to the Button menu component. This optional label should contain or match the visible labels or it will automatically take button label
Verified in the storyboard using IBM Equal Access Accessibility Checker.
=> fix(Button menu): button menu accessibility issue - 3519

packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js
Contributes to #4203 
Adds `typeof` check before accessing `document.activeElement`, this prevents issues with SSR apps/nextjs.
```
```
Storybook
=> fix(Datagrid): address ssr bug in nested row hook (v2)

packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js
Contributes to #4203 
Adds `typeof` check before accessing `document.activeElement`, this prevents issues with SSR apps/nextjs.
```
```
Storybook
=> fix(Datagrid): address ssr bug in nested row hook (v1)

packages/core/.storybook/main.js, packages/core/package.json
for #4220
according to the storybook documentation, [usage of the `-s` flag in the build command is deprecated.](https://storybook.js.org/docs/api/cli-options#build). this PR updates the build command to remove some stuff that i don't *think* is necessary, but more importantly removes the flag and establishes the static directory in the `.storybook/main.js` file where the documentation says to put it.
after doing this i was able to run the build locally with success.
=> fix: storybook static build folder update

packages/ibm-products-styles/src/components/Datagrid/styles/addons/_FilterPanel.scss, packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterProvider.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/OverflowCheckboxes.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/constants.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilterContext.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useShouldDisableButtons.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useSubscribeToEventEmitter.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/index.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Filtering.docs-page.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js, packages/ibm-products/src/components/Datagrid/useFiltering.js, packages/ibm-products/src/global/js/package-settings.js
Contributes to #4156 
This PR mostly contains copyright header updates, some files were missing them altogether while some needed to be updated from WKC copyright header to ours. Carbon uses a rollup package (`rollup-plugin-strip-banner`) to enforce copyright header formatting which is included in the [typescript setup](https://github.com/carbon-design-system/ibm-products/pull/4172/files#diff-110b2eef5f7121d5dd4028f07e7ea48a6c7dc4d7861e69fb5e5640773c3a938aR149) PR.
I also removed the filtering feature flags after going through the release review checklist and double checking test coverage.
Filtering files, updated copyright headers and added a few comments.
Storybook
=> feat(Datagrid): update filtering copyright headers, review eslint disable rules, remove filter feature flags

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js
Contributes to #4235 
Add the onColResizeEndto onMouseup event 
On the storybook
=> feat(Datagrid): add mouseUp event for onColResizeEnd #4235

packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js
Contributes to #4248
Changes the first parameter passed to getRowId to the original property of row.
So now instead of passing the whole row object it will pass just the actual data.
This is for v1.
```
```
Storybook & run unit tests
=> fix(Datagrid): changes getRowId parameter to original row data (v1)

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/FilterSummary/_filter-summary.scss, packages/ibm-products-styles/src/components/ProductiveCard/_productive-card.scss, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Slug/DatagridSlug.js
Contributes to #4306 
Addresses autoprefixer warning about mixed support for `start` value with `align-items` property.
I have also included a small fix related to the `DatagridSlug` component needing to `return null`.
```
Error: ForwardRef(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```
```
packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
packages/ibm-products-styles/src/components/FilterSummary/_filter-summary.scss
packages/ibm-products-styles/src/components/ProductiveCard/_productive-card.scss
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Slug/DatagridSlug.js
```
Storybook
=> fix: use flex-start instead of start and update `DatagridSlug` return

packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js
Contributes to #4311 
Fixes a SSR bug caused by the `useSelectAllToggle` hook because there is no check before accessing the `window` object.
```
packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js
```
N/A
=> fix(Datagrid): ssr fix in `useSelectAllToggle` hook (v1)

packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js
Contributes to #4311 
Fixes a SSR bug caused by the `useSelectAllToggle` hook because there is no check before accessing the `window` object.
```
packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js
```
N/A
=> fix(Datagrid): ssr fix in `useSelectAllToggle` hook

packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js, packages/ibm-products/src/global/js/hooks/index.js, packages/ibm-products/src/global/js/hooks/useIsomorphicEffect.js
Contributes to #4319 
Includes Carbon's `useIsomorphicEffect` hook to help us catch and prevent SSR issues earlier on.
```
packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js
packages/ibm-products/src/global/js/hooks/index.js
packages/ibm-products/src/global/js/hooks/useIsomorphicEffect.js
```
Storybook
=> feat: add isomorphic hook to address ssr issues (v1)

packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js, packages/ibm-products/src/global/js/hooks/index.js, packages/ibm-products/src/global/js/hooks/useIsomorphicEffect.js
Contributes to #4319 
Includes Carbon's `useIsomorphicEffect` hook to help us catch and prevent SSR issues earlier on.
```
packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js
packages/ibm-products/src/global/js/hooks/index.js
packages/ibm-products/src/global/js/hooks/useIsomorphicEffect.js
```
Storybook
=> feat: add isomorphic hook to address ssr issues

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js
Contributes to https://github.com/carbon-design-system/ibm-products/issues/4248
- Fixes unselecting a single row -> `selectedRowData` did not update correctly when unselecting a row and when the id of the row doesn't correspond to the index
- Fixes cancel action not triggering the removal of the selected row(s) from  `selectedRowData`
```
```
Storybook and run unit tests
=> fix(Datagrid): fixes selectedRowData updating on cancel/unselecting

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js
Contributes to #4322 
This prevents any resizing from occurring during `isFetching` otherwise this can cause the app to crash, see #4322 for details.
```
```
Storybook
=> fix(Datagrid): disable resizing during fetching state

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js
Contributes to #4322 
This prevents any resizing from occurring during `isFetching` otherwise this can cause the app to crash, see #4322 for details.
```
```
Storybook
=> fix(Datagrid): disable resizing during fetching state (v1)

packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss, packages/ibm-products/src/components/SidePanel/SidePanel.js, packages/ibm-products/src/components/SidePanel/motion/variants.js
Contributes to #3998 
Includes reduced motion support for the `SidePanel`, similar to the FilterPanel this update only uses opacity when the panel is opened or closed. Along, with opacity transition and delay for the action set when reduced motion is enabled.
```
packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
packages/ibm-products/src/components/SidePanel/SidePanel.js
packages/ibm-products/src/components/SidePanel/motion/variants.js
```
Storybook
=> feat(SidePanel): initial reduced motion work for side panel opacity

packages/ibm-products-styles/src/components/FullPageError/_full-page-error.scss
Contributes to #4081 
Although this was implemented in previous issues #4211 and #4304 , i would like to utilize this pr to make fine adjustments and for cross browser compatibility.
packages/ibm-products-styles/src/components/FullPageError/_full-page-error.scss
storybook, chrome, firefox, safari.
=> fix(FullPageError): responsive behavior for full page errors

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid/Datagrid.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js, packages/ibm-products/src/components/Datagrid/utils/makeData.js, packages/ibm-products/src/components/FullPageError/FullPageError.mdx
=> fix: adds aria label to datagrid toolbar

packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheetBody.js, packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheetHeader.js, packages/ibm-products/src/components/DataSpreadsheet/utils/checkForHoldingKey.js
Contributes to #4188 
Reduce duplication with isHoldingCommandKey
Created a util method _checkForHoldingKey_ that will check if the key is holding. 
Method accept 2 arguments, event object and the key.
This method will isolate this logic , so that can be reused.
Tested locally
=> fix(Dataspreadsheet): Reduce duplication with isHoldingCommandKey #4188

packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.js, packages/ibm-products/src/components/Datagrid/useSelectRows.js
Contributes to #3887 
Add support for selected nested rows in the Datagrid.
Note: This PR only covers the selectable nested row part of #3887. The second acceptance criteria in [comment](https://github.com/carbon-design-system/ibm-products/issues/3887#issuecomment-1856319771) "Selecting parent should not select all children by default" is [coming from the React table ](https://github.com/TanStack/table/blob/v7/src/plugin-hooks/useRowSelect.js#L154-L177)and it's hard to override. If there is subRows then child rows get selected when parent row is selected.
`rowId` selection changed to a combination of `rowId` and `index` so the nested rows will have unique Id with depth
Storybook > With selectable nested rows
=> fix(DataGrid): add support for selectrow and nestedrow V1

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterProvider.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/constants.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/utils.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.js, packages/ibm-products/src/components/Datagrid/useFiltering.js
Contributes to #4356 
Adds `multiSelect` filter type to Datagrid filtering, which will render the `<MultiSelect />` carbon component as an available option be used in both the filter panel and filter flyout.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterProvider.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/constants.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/utils.js
packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js
packages/ibm-products/src/components/Datagrid/useFiltering.js
``` …
=> feat(Datagrid): add support for multi select filter type (v1)

packages/ibm-products/src/components/Datagrid/useSortableColumns.js
Contributes to #4339
remove the sort icon from action column
Add condition to check the header is the action column
using storybook
=> feat: sort icon appear in the Actions column on Datagrid #4339

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/Tearsheet/_tearsheet.scss
Contributes to #4362 
Fix position of AI gradient when influencer is on right. The gradient should be in the content area only.
CSS selector for ai gradeient
Storybook.
Correct visual
=> fix: move ai gradient to content

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/Tearsheet/_tearsheet.scss
Contributes to #4381 
The wide tearsheet header when displayed with an AI slug and close button had a gap bottom right of the header border. 
This PR addresses that gap.
Tearsheet styling
Storybook
=> fix: header border issue introduced with ai slug

package.json, yarn.lock
Fixes an issue with changed CDN
`chromedriver` (from `accessibility-checker`) was causing build failures in our CI[^1]. Temporarily added `chromedriver@1.220.1` to resolutions to update version in `yarn.lock`.
Add resolution to current latest version in `package.json` to update `yarn.lock`.
CI checks pass but ... also this _is_ the test.
[^1]: https://github.com/IBMa/equal-access/blob/master/accessibility-checker/package.json#L26
=> chore: update chromedriver resolutions

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/Tearsheet/_tearsheet.scss
Tearsheet was using an old version of the overlay color 161616 (gray 100).
Updated to use the $overlay tag and moved it and opacity to ::after. This also works with $ai-overlay.
Tearsheet styling
Storybook
=> fix: tearsheet overlay

packages/ibm-products/src/components/Datagrid/Datagrid.mdx, packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/useInitialColumnSort.js, packages/ibm-products/src/components/Datagrid/useSortableColumns.js
Contributes to #4301 
This PR adds the ability to specify a column to be sortable within the datagrid initial state, see following structure:
```jsx
initialState: {
sortableColumn: {
id: 'firstName', // column id
order: 'ASC' // sorting order, 'ASC' | 'DESC' included in docs update
}
}
```
I created a custom hook called `useInitialColumnSort` that calls `instance.toggleSortBy()`, which comes from `react-table`, and is what triggers the sorting.
```
packages/ibm-products/src/components/Datagrid/useInitialColumnSort.js
packages/ibm-products/src/components/Datagrid/useSortableColumns.js …
```
=> feat(Datagrid): add option to specify an initial sortable column (v1)

packages/ibm-products/src/components/Datagrid/Datagrid.docs-page.js, packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js, packages/ibm-products/src/components/Datagrid/useInitialColumnSort.js, packages/ibm-products/src/components/Datagrid/useSortableColumns.js
Contributes to #4301 
This PR adds the ability to specify a column to be sortable within the datagrid initial state, see following structure:
```jsx
initialState: {
sortableColumn: {
id: 'firstName', // column id
order: 'ASC' // sorting order, 'ASC' | 'DESC' included in docs update
}
}
```
I created a custom hook called `useInitialColumnSort` that calls `instance.toggleSortBy()`, which comes from `react-table`, and is what triggers the sorting.
```
packages/ibm-products/src/components/Datagrid/useInitialColumnSort.js
packages/ibm-products/src/components/Datagrid/useSortableColumns.js …
```
=> feat(Datagrid): add option to specify an initial sortable column

.github/CONTRIBUTING.md, packages/ibm-products/src/components/Toolbar/ToolbarButton.tsx
Contributes to #4276 
Converts ToolbarButton component to use typescript, no visual component changes just refactoring.
Small PR to begin contributing with, I'll add more types if this goes well.
Converted `ToolbarButton` component to typescript.
Updated contribution docs to include an up to date link.
Checked storybook and ran unit tests locally.
=> refactor: convert ToolbarButton to typescript

packages/ibm-products-styles/src/components/Datagrid/styles/addons/_FilterPanel.scss
Contributes to #4337
the button bar covers the last filter options for Datagrid filter panel 
Add the bottom padding 
Check on the storybook
=> feat: the button bar covers the last filter options for Datagrid filter panel #4337

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
Contributes to #4441 
Fixes an issue in some new logic added to Datagrid that reverts to the saved filter list when refreshing.
`useFilter.js`
Temporarily added fetching state to filter panel story, was able to reproduce the issue and fix.
=> fix(Datagrid): add safety checks for saved filters logic

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/TagSet/_tag-set.scss
Contributes to #4357 
In order to remove the color contrast violation that the accessibility checker was flagging, we have to explicitly set the color on the link/button element. We set the color for the `:visited` state of the link but not on the default state (even though it appears to always default to the `:visited` state which is why visually it looks correct), however, my guess is the accessibility checker is comparing the default state of the link against the background.
`_tag-set.scss`
Snapshot update
Storybook with accessibility checker
=> fix(TagSet): address color contrast issue in overflow link button

packages/core/package.json, packages/ibm-products-community/package.json, packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/AboutModal/_about-modal.scss, packages/ibm-products/package.json, packages/ibm-products/src/components/AboutModal/AboutModal.stories.js, packages/ibm-products/src/components/AboutModal/AboutModal.tsx, scripts/example-gallery-builder/update-example/templates-react-16/package.json, scripts/example-gallery-builder/update-example/templates-react-17/package.json, scripts/example-gallery-builder/update-example/templates/package.json, yarn.lock
Closes #4445 and contributes to #4359 
- Updates `@carbon/react` to 1.51.1, which fixes custom class on modal body.
- Removes redundant `hasScrollingContent` code
- Fixes about modal spacing with or without scroll gradient
- Also uses CSS logical properties in about modal body 🤷‍♀️ 
- Sets defaults in about modal story
Storybook and CI checks
=> fix: about modal layout

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/Datagrid/styles/_useStickyColumn.scss
Contributes to #4452 
The frozen column variant of the Datagrid had header cells that were missing borders if they were frozen. I've included them if it is a header cell that is sticky/frozen, see screenshot below:
```
packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
packages/ibm-products-styles/src/components/Datagrid/styles/_useStickyColumn.scss
```
Storybook
=> fix(Datagrid): add missing borders to frozen header cells

packages/ibm-products/src/components/Datagrid/useDisableSelectRows.js, packages/ibm-products/src/components/Datagrid/useSelectRows.js
Contributes to #4198
See also #3666 for more details when this was fixed in `v2`.
`getRowProps()`: renamed property `selectDisabled` to `disabled`.
```
packages/ibm-products/src/components/Datagrid/useDisableSelectRows.js
```
=> fix(Datagrid): invalid selectDisabled prop

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js
Contributes to #4059 
updates the selectable row story to demonstrate the new functionality to select all ignoring disabled rows
=> fix: update story for selectable row

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/Tearsheet/_tearsheet.scss, packages/ibm-products/src/components/Tearsheet/Tearsheet.stories.js, packages/ibm-products/src/components/Tearsheet/TearsheetShell.js
Contributes to #4066 
This change will prevent any stacking visual cue to tearsheets of different sizes. If the stacked tearsheets are all the same size, the behavior remains the same as it was before. However, if you now include a wide and a narrow, there is no scaling effect anymore.
```
packages/ibm-products-styles/src/components/Tearsheet/_tearsheet.scss
packages/ibm-products/src/components/Tearsheet/Tearsheet.stories.js
packages/ibm-products/src/components/Tearsheet/TearsheetShell.js
```
Storybook, added new stacking story
=> fix(Tearsheet): prevent stacking visual cue with different sizes

packages/ibm-products/src/components/Datagrid/Datagrid.docs-page.js
Contributes to #3803 
Adds clarifying docs regarding batch actions in Datagrid.
```
```
Storybook, Datagrid docs page
=> docs(Datagrid): add docs around specifics of batch actions

packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Filtering.docs-page.js, packages/ibm-products/src/components/Datagrid/Extensions/Slug/Slug.stories.js
Contributes to https://github.com/carbon-design-system/ibm-products/issues/4431
Adds some missing docs for multi select filter type and AI slug usage in Datagrid.
=> docs(Datagrid): include multiselect and slug docs

packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
Contributes to #4379 
now when customize column tearsheet is opened it won't sort the hidden columns to the bottom.
=> fix: remove sorting in custom column tearsheet

packages/ibm-products/src/components/Datagrid/Datagrid.mdx
Contributes to #3803 
Adds clarifying docs regarding batch actions in Datagrid.
```
```
Storybook, Datagrid docs page
=> docs(Datagrid): batch action docs update (v1)

packages/ibm-products/src/components/Datagrid/Datagrid.mdx, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js
Issue brought up via slack, if `disableResizing` is passed to `useDatagrid` hook it can cause the app to crash. Adding an optional chain to the logic that adds the resizing class within `DatagridContent` fixes this. I also removed the aria label property in the docs example for disable resizing because it's not applicable if resizing is disabled.
```
packages/ibm-products/src/components/Datagrid/Datagrid.mdx
```
Storybook
=> fix(Datagrid): add optional chain to prevent errors with `disableResizing` (v1)

packages/ibm-products/src/components/Datagrid/Datagrid.docs-page.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js
Issue brought up via slack, if `disableResizing` is passed to `useDatagrid` hook it can cause the app to crash. Adding an optional chain to the logic that adds the resizing class within `DatagridContent` fixes this. I also removed the aria label property in the docs example for disable resizing because it's not applicable if resizing is disabled.
```
```
Storybook
=> fix(Datagrid): add optional chain to prevent errors with `disableResizing`

.github/workflows/update.yml, package.json
Contributes to #4219 
Set version fails as part of the update workflow.
Noticed that when we run `yarn set version latest` locally, this passes but as part of the `upgrade` scripts, it fails. Thought it was worth a shot to separate it out although this makes it harder to test the whole action locally. 🥲 
Removed `yarn upgrade:dependencies:yarn` from package.json and instead put a separate line within the update.yml action.
🤫
=> chore: set yarn version in update action

docs/CODE_GUIDELINES.md, docs/MAINTAINER_GUIDELINES.md, package.json
while working with Paul on a review it came to my attention that he was unaware about the test coverage tooling. to alleviate this i thought it might help to add additional npm scripts to run the test coverage and open the results.
=> chore: add test coverage commands

packages/ibm-products/src/components/Datagrid/Datagrid.test.js
Contributes to #4244 
Adding a few test cases for column customization. Especially the actions in the column customization tearsheet.
Tests added for column search and unselecting column and hiding column.
run `yarn test:c4p`
=> fix(Datagrid): adding test for customize column

packages/ibm-products/src/components/FullPageError/FullPageError.stories.js
Contributes to #4564 
removed the redundant role="link" on .
packages/ibm-products/src/components/FullPageError/FullPageError.stories.js
IBM Equal accessibility checker.
=> fix: removed redundant role from Link

packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
Filterable column count includes the non-filterable spacer column.
Filterable column counts to account for this.
Storybook
=> fix: filterable column counts

packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js, packages/ibm-products/src/components/Datagrid/useRowSize.js
Contributes to #4528 
The radio buttons in the radio group from `RowSizeRadioGroup` were being given duplicate id's if there were multiple Datagrids on the same page, resulting in the first datagrid always getting the row size changes even if you were attempting to change the row size on the second datagrid. Fixing the duplicate id issue resolves this problem.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js
packages/ibm-products/src/components/Datagrid/useRowSize.js
```
Storybook
=> fix(Datagrid): address duplicate id issue in `RowSizeRadioGroup`

packages/ibm-products/src/components/Tearsheet/TearsheetShell.js
Contributes to #4543 
Focus issue in Tearsheet with navigation when state change (Only first time)
Removed `firstElement` from initial `useEffect` code
Added a new `useEffect` to focus first element in stacked Tearsheets 
storybook
=> fix(tearsheet): fix focus capturing issue when first state update

packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.js, packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheetBody.js, packages/ibm-products/src/components/DataSpreadsheet/hooks/useMoveActiveCell.js
Contributes to #4551 
Glitchy behaviour in spreadsheet while changing the cell selection. 
Previous cell value is been displayed in the new active cell for a glance.
Identified root-cause for this issue was , the active cell button element is getting created over the new active cell as expected , but by that time the new value is not updated as expected.There is a small delay in value updation. The new active cell is created by listening to the change of activeCellCoordinate state.
Fix: i changed that, to listen to the change of activeCellContent state.
Also some changes to pass cspell check in existing code
Tested locally in storybook
=> fix(Dataspreadsheet): glitchy behaviour issue 4551

packages/ibm-products/src/components/DescriptionList/DescriptionList.js, packages/ibm-products/src/components/DescriptionList/DescriptionListBody.js, packages/ibm-products/src/components/DescriptionList/DescriptionListCell.js, packages/ibm-products/src/components/DescriptionList/DescriptionListRow.js, packages/ibm-products/src/components/DescriptionList/index.js, packages/ibm-products/src/components/index.js, packages/ibm-products/src/global/js/package-settings.js
Contributes to  [4593](https://github.com/carbon-design-system/ibm-products/issues/4593)
I missed exporting the files from the components/index file 
Broke out the following components into their own files:
- DescriptionListBody
- DescriptionListRow
- DescriptionListCell
Modified the index file in the components directory to export ^ these 3 along with the DescriptionList
- Running CI check / test scripts
- Storybook
=> fix(Descriptionlist): Export sub components

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/handleGridKeyPress.js
Contributes to #4147 
We need to keep the focus on the dropdown/selectable cell while it is in edit mode, otherwise the focus moves to the overall grid and prevents interaction with just the dropdown itself. The second part of this fix included fixing a selector that checks if the dropdown is open/active.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/handleGridKeyPress.js
```
Storybook
=> fix(Datagrid): address keyboard support with selectable/dropdown editable cells

config/storybook-addon-carbon-theme/README.md, config/storybook-addon-carbon-theme/package.json, config/storybook-addon-carbon-theme/telemetry.yml, packages/ibm-products-styles/README.md, packages/ibm-products-styles/package.json, packages/ibm-products-styles/telemetry.yml, yarn.lock
Adds the config file and dependency necessary to start tracking telemetry data via [IBM Telemetry](https://github.com/ibm-telemetry/telemetry-js) for the packages:
- `@carbon/ibm-products-styles`
- `@carbon/storybook-addon-theme`
**New**
- Adds @ibm/telemetry-js dependency
- Adds telemetry.yml config file
- Adds readme telemetry notice
- Adds postinstall script to use the telemetry command
- Adds telemetry.yml as an exported file if the package specifies `files`
**Changed**
- N/A
**Removed**
- N/A
Please look through package.json config files and ensure all necessary modifications have been made so that the "telemetry.yml" config file is included in the release version of each package.
**PLEASE NOTE:** In order for IBM Telemetry to start collecting data for this project, a new build must …
=> chore: onboard @carbon/ibm-products-styles to IBM Telemetry 🚀 

packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx
=> chore: convert optionstile to typescript

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridEmptyBody.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRefBody.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSimpleBody.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
Contributes to #4583 
i have set the role to undefined, and aria-live to null, in order to remove them from tbody
as aria-live is a default attribute from TableBody component from core carbon 
and getTableBodyProps() includes the role="rowgroup" by default
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSimpleBody.js
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridEmptyBody.js
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRefBody.js
storybook, checking the attributes manually in dev tools.
=> chore(datagrid): remove role and aria-live attributes

e2e/components/Cascade/Cascade-test.avt.e2e.js
After some of the storybook refactoring, there were changes to story id's which included the Cascade component. This caused the Cascade e2e avt test to have an incorrect story id (essentially causing a 404). The test never failed however, so we might want to verify the component is on the page in addition to the `.toHaveNoACViolations()` check.
```
e2e/components/Cascade/Cascade-test.avt.e2e.js
```
Ran playwright locally and checked the output of `const html = await page.content()` to make sure it rendered the `Cascade` component.
=> fix(e2e): use updated path to cascade story

CODEOWNERS, cspell.contributors.txt
Contributes to #4638
Update CODEOWNERS to reflect team name change (long overdue 🫠)
CODEOWNERS
GitHub tells me the file is valid ;)
=> chore: update codeowners

packages/ibm-products/src/components/SidePanel/SidePanel.tsx
Contributes to #4468 
In https://github.com/carbon-design-system/ibm-products/pull/4471, I accidentally included `selectorPrimaryFocus` as the conditionally required prop for slide in panels instead of `selectorPageContent`. This PR changes it to use the correct one now.
`packages/ibm-products/src/components/SidePanel/SidePanel.tsx`
Storybook, locally
=> fix(SidePanel): replace incorrect prop in conditional prop types

e2e/test-utils/storybook.js, packages/core/.storybook/preview.js, playwright.config.js
Contributes to #4688 
I noticed that `Cascade` e2e avt test was passing even when it was being passed an incorrect story id which results in storybook's 404 page to display. This PR brings in similar changes @tay1orjones included in https://github.com/carbon-design-system/carbon/pull/16132 after we chatted about this issue.
```
e2e/test-utils/storybook.js
packages/core/.storybook/preview.js
playwright.config.js
```
- Ran playwright tests locally
- With an incorrect story id, fails
- And with a correct one, passes
=> test(playwright): check story has actually rendered before proceeding

packages/ibm-products/src/components/ImportModal/ImportModal.tsx, packages/ibm-products/src/custom-typings/index.d.ts
Contributes to #4507 
Converts `ImportModal` to TypeScript and added Carbon's `usePrefix` to our custom-typings declaration file.
```
packages/ibm-products/src/components/ImportModal/ImportModal.tsx
packages/ibm-products/src/custom-typings/index.d.ts
```
Locally, vscode and made sure component still functions the same in storybook
=> refactor(ImportModal): convert to typescript

packages/core/.storybook/main.js
Addresses #4780
Includes some webpack optimizations found in Storybook's repo/issues. This should hopefully prevent Netlify builds from running out of memory, thus causing our Netlify PR check to fail.
`packages/core/.storybook/main.js`
Build completes and storybook preview deploy works in this PR
=> build: include webpack optimization config

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/CreateFullPage/CreateFullPage.stories.js, packages/ibm-products/src/components/CreateFullPage/CreateFullPageStep.js
Fixes to #4778 
Changes CreateTearsheetStep description from string to node.
Updated a story and ran storybook to check function.
=> feat: full page step description as node to match tearsheet

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.js
Contributes to #4651 
Applied fade-out animation with "forwards" fill mode to prevent animation reset upon completion, resolving the issue.
packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.js
storybook
=> fix(NotificationsPanel): fixed glitchy animation after closing the panel

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/ProductiveCard/_productive-card.scss
Contributes to #4756 
alleviates styling issue where productive card wasn't flexing to match it's siblings
=> fix: productive card flex fix

.github/workflows/move-issue-to-project-and-set-fields.yml, .github/workflows/triage-labeled-issues.yml
Contributes to #4803 
Adds the prototype action I created [here](https://github.com/matthewgallo/ibm-products-vite-template/blob/main/.github/workflows/add-label-move-to-area.yml) into our repo. This action triages labeled issues by adding them to our project board and applying the specified field/field option values. In this case, issues labeled `area: typescript` will be moved into "Area: 🟦 TypeScript" in our project.
Discussed with @tay1orjones about potentially including the reusable workflow in a [shared repo](https://github.com/carbon-design-system/.github) for other teams to use as well, but want to make sure it works here first.
If we want to add this same thing for other labels we should be able to easily by updating `.github/workflows/triage-labeled-issues.yml`. The [Graphql API …
=> feat: create action for triaging labeled issues

packages/core/package.json
Contributes to #4780 
This PR includes the same node options that we specify for extra memory allocation that we use in `v1`. This likely was just unintentionally not included from v1 to v2. With all of the Netlify preview deploys not working because of memory issues, turns out we need to include this.
```
packages/core/package.json
```
We'll see if the Netlify build in this PR works 😄
=> fix: use same node options as v1 for storybook build script

.husky/commit-msg, .husky/pre-commit, package.json
Closes #4878 🤞 
- Update husky config and precommit
- Remove gallery update 
Port @szinta’s precommit fixes from #4746 to v1
Successful precommit run locally without extra gallery update commit
=> build: fix legacy rename

packages/ibm-products/src/components/InlineTip/InlineTip.tsx, packages/ibm-products/src/components/SteppedAnimatedMedia/SteppedAnimatedMedia.tsx
Contributes to #4287 
Migrates `InlineTip` and `SteppedAnimatedMedia` to TypeScript. One thing I found (well, TypeScript found it 😂) was that the `title` prop sets a default value to `defaults.title` but there is no `title` property in the `defaults` object, so I included one in this PR.
```
packages/ibm-products/src/components/InlineTip/InlineTip.tsx
packages/ibm-products/src/components/SteppedAnimatedMedia/SteppedAnimatedMedia.tsx
```
Storybook, locally in vscode
=> refactor: migrate `Inlinetip` and `SteppedAnimatedMedia` to TypeScript

packages/core/.storybook/main.js, packages/core/package.json, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.stories.js, packages/ibm-products/src/components/SidePanel/SidePanel.stories.js, yarn.lock
Contributes to #4920 
After https://github.com/carbon-design-system/ibm-products/pull/4919 did not resolve our Netlify issues, it got me thinking that the likely problem is the size of our built storybook assets. For example, our built entry point `main.js` was previously sitting around `~36mb`. Turning on `storyStoreV7` and figuring out the issues that were preventing us from using that functionality in storybook decreased the size to `~8mb`. Hoping that this decrease in size will allow Netlify build again.
This enables code splitting per component if you inspect `storybook-static` after building with these changes. There's more info [here](https://storybook.js.org/blog/storybook-on-demand-architecture/) discussing in more details the performance benefits of `storyStoreV7`.
``` …
```
=> build: turn on `storyStoreV7` setting to optimize the performance of our built storybook assets

packages/core/.storybook/main.js
Closes #4921 
This is a follow up PR to https://github.com/carbon-design-system/ibm-products/pull/4937 which enabled `storyStoreV7`. This addition uses the `lazyCompilation` and `fsCache` settings in `.storybook/main.js`. There is an article [here](https://storybook.js.org/blog/storybook-lazy-compilation-for-webpack/) discussing in more detail the performance improvements. We previously couldn't use it because it requries `storyStoreV7`.
Below are some screenshots of storybook startup times with and without this setting:
_Without file system cache or lazy compilation_  -- **1.45 min**
_With file system cache or lazy compilation_  -- **13 sec**
`packages/core/.storybook/main.js`
Made sure storybook still loads and builds as expected
=> perf: use `lazyCompilation` and `fsCache` to increase storybook start times

packages/ibm-products/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.tsx
Contributes to #4265
This PR converts `NoDataEmptyState` to TypeScript and adds `NoTagsEmptyState`
- TS interface
=> feat(NoTagsEmptyState): convert to .tsx

packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js, packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.js
Contributes to #4956
Allow column to be disabled when configure
Storybook
=> feat: column customization should allow only disable column #4956

packages/ibm-products/src/components/Datagrid/Datagrid.stories.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.js, packages/ibm-products/src/components/Datagrid/_storybook-styles.scss
Contributes to #4965
<TableCell /> takes provided classname
storybook
=> fix: support provided classname for TableCell #4965

packages/ibm-products/src/components/CoachmarkOverlayElement/CoachmarkOverlayElement.tsx
Contributes to #4493
This PR converts `CoachmarkOverlayElement` to TypeScript
- TS interface
=> feat(CoachmarkOverlayElement): convert to .tsx

packages/ibm-products/src/components/FullPageError/FullPageError.js
Last week's release failed because of `FullPageError` and my guess is that it is related to this linting error about the prop types not being alphabetized.
`FullPageError.js`
Linting error was removed.
=> fix(FullPageError): alphabetize prop types

packages/ibm-products/src/components/Coachmark/utils/enums.ts, packages/ibm-products/src/components/CoachmarkBeacon/CoachmarkBeacon.stories.js, packages/ibm-products/src/components/CoachmarkBeacon/CoachmarkBeacon.tsx
Contributes to #4496
This PR converts `CoachmarkBeacon` to TypeScript.
It also begins the conversion of Coachmark enums to TypeScript
- TS interface
- Coachmark enums
=> feat(CoachmarkBeacon): convert to .tsx

config/storybook-addon-carbon-theme/package.json, config/storybook-addon-carbon-theme/telemetry.yml, packages/ibm-products-styles/package.json, packages/ibm-products/package.json, packages/ibm-products/telemetry.yml, yarn.lock
Instrument current packages with [JS scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)
***@carbon/storybook-addon-theme***
- Update `@ibm/telemetry-js` version to 1.5.0
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)  config to `telemetry.yml`
***@carbon/ibm-products-styles***
- Update `@ibm/telemetry-js` version to 1.5.0
***@carbon/ibm-products***
- Update `@ibm/telemetry-js` version to 1.5.0
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)  config to `telemetry.yml`
N/A
=> feat: instrument current packages with js scope

packages/cdai/package.json, packages/cdai/telemetry.yml, packages/ibm-products/package.json, packages/ibm-products/telemetry.yml, packages/security/package.json, packages/security/telemetry.yml, yarn.lock
Instrument current packages with [JS scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)
***@carbon/ibm-cloud-cognitive-cdai***
- Update `@ibm/telemetry-js` version to 1.5.0
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope) config - tokens only -  to `telemetry.yml`
***@carbon/ibm-products***
- Update `@ibm/telemetry-js` version to 1.5.0
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)  config to `telemetry.yml`
***@carbon/ibm-security***
- Update `@ibm/telemetry-js` version to 1.5.0
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)  config to `telemetry.yml`
N/A
=> feat: instrument v1 packages with JS scope

packages/ibm-products-styles/src/components/InterstitialScreen/_interstitial-screen.scss, packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.js, packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.stories.js
Carousel element moving to first step on resize in InterstitialScreen - which is expected behavior... but the navigation and the step indicator was out of sync.
Contributes to [4970](https://github.com/carbon-design-system/ibm-products/issues/4970)
- Added a scroll callback which sets prog step back to 0 on resize
- Modified the story to be more clear on what step you are on 
- Updated the stylesheet to use carousels scss - to get the base styles.
Storybook
=> fix: added a scroll callback which sets prog step back to 0 on resize

e2e/components/TagSet/TagSet-test.avt.e2e.js
Closes #5004 
Adds default AVT test coverage for TagSet component.
```
e2e/components/TagSet/TagSet-test.avt.e2e.js
```
Ran playwright tests locally
=> test(TagSet): add default avt test coverage

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/release-v1.yml, .github/workflows/update-v1.yml, README.md
Contributes to #4932 
This PR renames all instances of `main_v1` in our workflows/docs to `v1`. The only remaining piece to this is actually renaming the branch within our repo, I believe any PRs that are open and targeting `main_v1` will automatically change to target `v1`.
After renaming within our repo, we can run a v1 prerelease to make sure everything still works as expected after all of the renaming.
```
.github/workflows/codeql.yml
.github/workflows/release-v1.yml
.github/workflows/update-v1.yml
README.md
```
=> chore: rename `main_v1` to `v1`

e2e/components/AboutModal/AboutModal-test.avt.e2e.js, package.json
Closes #4660 
Adds e2e AVT default state coverage for the `AboutModal` component. I also added a script in our package.json to run the AVT tests locally.
```
e2e/components/AboutModal/AboutModal-test.avt.e2e.js
package.json
```
Ran `yarn avt` to check that new test passes
=> test(AboutModal): add default avt test and add avt script to help test

packages/ibm-products-styles/src/components/CoachmarkOverlayElements/_coachmark-overlay-elements.scss, packages/ibm-products-styles/src/components/Guidebanner/_guidebanner.scss
Contributes to [5067](https://github.com/carbon-design-system/ibm-products/issues/5067)
Novice to pro components using the internal Carousel component are not including the carousel scss file in their scss
added `@use '../Carousel/carousel';` to the guidebanner.scss and _coachmark-overlay-elements.scss
storybook
=> fix: added use statement to pull in base styles for carousel

packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.jsx
Noticed that Datagrid filter flyout stories were not loading because of a missing import, likely after the `vite` changes.
`Flyout.stories.jsx`
Flyout filter story pages now load as expected
=> fix: import shared filterProps data for flyout example

packages/core/.storybook/preview.js
This PR reverts the default storybook theme to `g10`, this was unintentionally changed as part of the move to `vite` when we swapped out `storybook-addon-carbon-theme` for a theme switcher included as part of `@storybook/addon-essentials`.
`packages/core/.storybook/preview.js`
Ran storybook locally to make sure it defaults to `g10`
=> fix(storybook): revert default theme to g10

.github/CODEOWNERS
Contributes to #4980 
Updates our `CODEOWNERS` file to specify the review team as the ones to get notified.
```
.github/CODEOWNERS
```
=> chore: setup reviewer team for PRs

cspell.json, e2e/components/CreateModal/CreateModal-test.avt.e2e.js
Contributes to #4662 
Created file: `e2e/components/CreateModal/CreateModal-test.avt.e2e.js`
`yarn avt`
=> test(CreateModal): add default state AVT check

packages/ibm-products/src/components/Coachmark/Coachmark.tsx, packages/ibm-products/src/components/Coachmark/CoachmarkDragbar.tsx, packages/ibm-products/src/components/Coachmark/CoachmarkHeader.tsx, packages/ibm-products/src/components/Coachmark/CoachmarkOverlay.tsx, packages/ibm-products/src/components/Coachmark/CoachmarkTagline.tsx, packages/ibm-products/src/components/Coachmark/utils/enums.ts
Contributes to #5095
This PR converts `Coachmark` to TypeScript. Will unblock #4494 
one thing to note is the hard coded drag handle string in `CoachmarkDragbar.tsx`, this will need updating once our i18n strategy for strings is figured out.
one other thing is the `overlayRef` prop type declaration in `Coachmark.tsx`, it may need a second look
- TS interface
- Coachmark enums
=> feat(Coachmark): convert to .tsx

packages/ibm-products/src/components/WebTerminal/WebTerminalContentWrapper.tsx
Contributes to #4278 
Converted packages/ibm-products/src/components/WebTerminal/WebTerminalContentWrapper.js to packages/ibm-products/src/components/WebTerminal/WebTerminalContentWrapper.tsx
=> refactor(WebTerminalContentWrapper): add typescript types

cspell.json, e2e/components/HTTPErrorOther/HTTPErrorOther-test.avt.e2e.js
Contributes to #5077 
Create file: `e2e/components/HTTPErrorOther/HTTPErrorOther-test.avt.e2e.js`
`yarn avt`
=> test(HTTPErrorOther): add default state AVT check

cspell.json, e2e/components/TagOverflow/TagOverflow-test.avt.e2e.js
Contributes to #5005 
Created e2e/components/TagOverflow/TagOverflow-test.avt.e2e.js
Added `tagoverflow` to cspell.js as it was blocking this commit
`yarn avt`
=> test(TagOverflow): add default state avt test

cspell.json, e2e/components/FullPageError/FullPageError-test.avt.e2e.js
Closes #5010 
Created `e2e/components/FullPageError/FullPageError-test.avt.e2e.js`
`yarn avt`
=> test(FullPageError): add default state avt test

packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.stories.jsx, packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheetBody.js, packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheetHeader.js, packages/ibm-products/src/components/DataSpreadsheet/hooks/useMoveActiveCell.js
Contributes to #5098 
Allows `DataSpreadsheet` stories to load again, there were some issues with calling some functions before they were initialized.
```
packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheetBody.js
packages/ibm-products/src/components/DataSpreadsheet/hooks/useMoveActiveCell.js
```
Verified locally in storybook that the stories load as expected again
=> fix(DataSpreadsheet): initialize functions before calling them

cspell.json, e2e/components/ExportModal/ExportModal-test.avt.e2e.js
Closes #5088 
Adds avt default state test coverage for the `ExportModal` component.
```
cspell.json
e2e/components/ExportModal/ExportModal-test.avt.e2e.js
```
Ran avt tests locally, `yarn avt`
=> test(ExportModal): add avt test coverage default state

cspell.json, e2e/components/APIKeyModal/APIKeyModal-test.avt.e2e.js, packages/ibm-products/src/components/APIKeyModal/APIKeyModal.stories.jsx
Contributes to #4661 
Create file: `e2e/components/APIKeyModal/APIKeyModal-test.avt.e2e.js`
`yarn avt`
=> test(APIKeyModal): add default state AVT check

cspell.json, e2e/components/NotificationsPanel/NotificationsPanel-test.avt.e2e.js
Closes #5059 
Created `e2e/components/NotificationsPanel/NotificationsPanel-test.avt.e2e.js`
`yarn avt`
=> test(NotificationsPanel): add default state avt test

packages/core/.storybook/carbon.scss, packages/ibm-products/src/components/AboutModal/_storybook-styles.scss, packages/ibm-products/src/components/PageHeader/_storybook-styles.scss
Closes #5157 
This PR addresses the style inconsistencies we've seen pop up after the move to `vite`. This happened because we've already included the full Carbon styles and then in some cases component styles are imported from `_storybook-styles.scss` files as well which ends up taking precedence and override other styling. For example, in the case of `AboutModal` the button styles are imported in `_storybook-styles.scss` but as well already included when we include `@use '@carbon/styles';` in `packages/core/.storybook/index.scss`.
```
packages/core/.storybook/carbon.scss
packages/ibm-products/src/components/AboutModal/_storybook-styles.scss
packages/ibm-products/src/components/PageHeader/_storybook-styles.scss
```
Verified with the stories that had been having style issues
=> style: remove component level style imports from `_storybook-styles.scss`, already included

packages/core/.storybook/preview.js, packages/ibm-products/src/components/ButtonMenu/ButtonMenu.stories.jsx, packages/ibm-products/src/components/ComboButton/ComboButton.stories.jsx
Closes #5080 
This PR replaces all `ActionableNotification` with `StaticNotification` as it is more appropriate given the current usage.
```
packages/core/.storybook/preview.js
packages/ibm-products/src/components/ButtonMenu/ButtonMenu.stories.jsx
packages/ibm-products/src/components/ComboButton/ComboButton.stories.jsx
```
Storybook
=> refactor: replace actionable notification with static

cspell.json, e2e/components/ImportModal/ImportModal-test.avt.e2e.js
Closes #5089 
Adds default state AVT e2e testing coverage for the `ImportModal`. I found an alternative approach to what @devadula-nandan shared during our team huddle for waiting for an animation/transition to end which seems to work well, and resolved the issues I was having earlier with this test having color contrast violations.
```
cspell.json
e2e/components/ImportModal/ImportModal-test.avt.e2e.js
```
`yarn avt`
=> test(ImportModal): add default state avt test

packages/ibm-products/src/components/SidePanel/SidePanel.tsx
Closes #5142 
Show the title border bottom only when `animateTitle` is `false`
Storybook
=> fix(sidepanel): resolve border bottom always showing

cspell.json, e2e/components/InterstitialScreenView/InterstitialScreenView-test.avt.e2e.js
Closes #5064
Add default state AVT check for InterstitialScreenView
Created `e2e/components/InterstitialScreenView/InterstitialScreenView-test.avt.e2e.js`
yarn avt
=> test(interstitialscreenview): Add default state AVT check

cspell.json
Closes #
We've been having to add to the cspell.json file when working on the AVT e2e tests because cspell doesn't like that the component names in the storybook id/urls aren't camel case. This PR adds avt tests to be ignored by cspell so we don't keep running into conflicts.
- add `*.avt.e2e.js` to ignore path field of cspell
=> chore(cspell): ignore all avt tests

cspell.json, e2e/components/InterstitialScreenViewModule/InterstitialScreenViewModule-test.avt.e2e.js
Closes #5065
Add default state AVT check for InterstitialScreenViewModule
Created `e2e/components/InterstitialScreenViewModule/InterstitialScreenViewModule-test.avt.e2e.js`
yarn avt
=> test(InterstitialScreenViewModule): add default state AVT check

packages/ibm-products/src/components/Carousel/Carousel.tsx, packages/ibm-products/src/components/CoachmarkOverlayElements/CoachmarkOverlayElements.tsx
Closes #4492
This PR converts `CoachmarkOverlayElement` to TypeScript
* file extension
* TS interface
=> feat(CoachmarkOverlayElements): convert to .tsx

e2e/components/OptionsTile/OptionsTile-test.avt.e2e.js
Closes #4668 
default state avt test
created a new test file : e2e/components/OptionsTile/OptionsTile-test.avt.e2e.js
This is an animated collapsible component. I am taking a screenshot of the component by disabling animation using playwright screenshot option, before running `expect(page).toHaveNoACViolations`. This will fix text contrast violation.
yarn avt
=> test(OptionTile): add default state avt test

packages/ibm-products/src/components/CoachmarkButton/CoachmarkButton.tsx
Closes #4495
This PR converts `CoachmarkButton` to TypeScript
* file extension
* TS interface
=> feat(CoachmarkButton): convert to .tsx

.github/workflows/add-triage-label.yml
Closes #5198 
If an issue is opened without using one of the issue templates it is possible for it to not receive the `status: needs triage` label. This action will catch those issue and apply the triage label whenever an issue is opened or reopened in our repo.
```
.github/workflows/add-triage-label.yml
```
Tested in [example repo](https://github.com/matthewgallo/ibm-products-vite-template/commit/333df2b850579fa2de8d1cf5a34c3d53e8237f15) with [test issue](https://github.com/matthewgallo/ibm-products-vite-template/issues/7).
=> feat: adds triage label when issue opened or reopened

packages/ibm-products/src/components/Card/Card.js
Closes #5281 
turns out the `header-container` class is already in use and because it was applied here it caused a visual bug. this just renames that class to something else.
here is the offending class
```
.#{$block-class}__header-container {
display: flex;
flex-direction: row;
align-items: center;
justify-content: space-between;
}
```
after fix:
=> fix: remove previously used class name

cspell.json, packages/ibm-products/src/components/Datagrid/Datagrid.docs-page.js, packages/ibm-products/src/components/Datagrid/Datagrid.stories.jsx, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
Closes #4685 
This PR adds a `onVirtualScroll` property that returns data around what rows are currently visible within the virtualized datagrid (where only the rows that need to be visible are rendered to the DOM).
The structure sent in the callback looks like the following and comes from the `VariableSizeList` component's `onItemsRendered` prop. We are just simply providing a way for consumers to receive this data now.
```
{
overscanStartIndex: 0,
overscanStopIndex: 12,
visibleStartIndex: 1,
visibleStopIndex: 10
}
```
```
cspell.json
packages/ibm-products/src/components/Datagrid/Datagrid.stories.jsx
```
Storybook
=> feat(Datagrid): add `onVirtualScroll` property to send back data around currently visible rows in virtualized Datagrids

packages/ibm-products/src/global/js/utils/StoryDocsPage.js
Closes #5301 
This enables custom docs to render as expected. It was previously always pulling in the component description because of the `autodocs` tag. Using the `Markdown` component when we have a custom doc block description seems to resolve this issue.
```
packages/ibm-products/src/global/js/utils/StoryDocsPage.js
```
Tested against Datagrid docs page, making sure that the component description is _not_ repeated throughout the doc file
=> fix(storybook): use markdown component to render custom docs

packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx, packages/ibm-products/src/global/js/hooks/useFocus.js
Closes #5152 
Adds back the expected behavior of `selectorPrimaryFocus` when `hasCloseIcon` is also provided. The new `useFocus` hook did not account for the `selectorPrimaryFocus` prop so it always focused the close icon even when `selectorPrimaryFocus` has a value.
```
packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
packages/ibm-products/src/global/js/hooks/useFocus.js
```
Storybook
=> fix(Tearsheet): properly focus specified element with new hook

packages/ibm-products/src/components/CreateInfluencer/CreateInfluencer.tsx
After pr #5086 gets merged, we would notice an empty p tag being rendered for `secondaryLabel`, if it is passed as an empty string or undefined. as shown below
this pr would fix that issue.
packages/ibm-products/src/components/CreateInfluencer/CreateInfluencer.tsx
storybook, dev tools.
=> fix(CreateInfluencer): removed empty p tag render

packages/ibm-products/src/components/ExpressiveCard/ExpressiveCard.tsx
Closes #
```
Type error: Type 'CarbonIconType' is not assignable to type '() => void | object'.
Target signature provides too few arguments. Expected 1 or more, but got 0.
> 20 |           pictogram={category.icon}
|           ^
```
Use `CarbonIconType`
=> fix(ExpressiveCard): use CarbonIconType for pictogram

.github/workflows/release.yml
Running into an issue with the telemetry config generator step in the release where if there are no changes to commit and push in the `telemetry.yml`, it will error out.
- added a git porcelain check for the step - thanks @kennylam for the code snippet!
I created a test branch (I had to edit the release file a bit - commented out the publishing and ci-check steps, and set my own git config so I could test the telemetry step) and ran the workflow on my fork
=> chore(release): add git porcelain check

e2e/components/InlineTip/InlineTip-test.avt.e2e.js
Closes #4666 
add default state avt for InlineTip component
e2e/components/InlineTip/InlineTip-test.avt.e2e.js
yarn playwright test e2e/components/InlineTip/InlineTip-test.avt.e2e.js
=> test(InlineTip): add default state avt check

packages/ibm-products/src/components/Guidebanner/Guidebanner.tsx, packages/ibm-products/src/components/Guidebanner/GuidebannerElement.tsx, packages/ibm-products/src/components/Guidebanner/GuidebannerElementButton.tsx, packages/ibm-products/src/components/Guidebanner/GuidebannerElementLink.tsx
_(This is the clean version of #5141)_
Contributes to #4487, #4488, #4489, #4490
This PR converts `Guidebanner`, `GuidebannerElement`, `GuidebannerElementButton`, and `GuidebannerElementLink`  to TypeScript.
- TS interface
=> feat(Guidebanner): convert to .tsx

packages/ibm-products-styles/src/components/StringFormatter/_string-formatter.scss
Closes #5314 
Scopes the popover styles in `_string-formatter.scss` to the StringFormatter block class so we don't unintentionally change popovers that aren't associated with the string formatter.
```
packages/ibm-products-styles/src/components/StringFormatter/_string-formatter.scss
```
Confirmed locally in Storybook that there are no visual changes in `StringFormatter`
=> fix(StringFormatter): scope popover to string formatter block class

e2e/components/EditUpdateCards/EditUpdateCards-test.avt.e2e.js, packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.stories.jsx
Closes #5212 
Created e2e/components/EditUpdateCards/EditUpdateCards-test.avt.e2e.js
e2e/components/EditUpdateCards/EditUpdateCards-test.avt.e2e.js
packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.stories.jsx
=> test(EditUpdateCards): add default state AVT check

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js
Closes #[5272](https://github.com/carbon-design-system/ibm-products/issues/5272)
When passing a custom classname to the header props, the classname was coming through as `undefined` and not being applied to the column header `<th>` element. It comes through as `undefined` as `header.getHeaderProps()` doesn't return any `className` field.
Reference the `className` from `header` object directly.
Tested in the `Basic usage` story where we are passing in the custom classname `test-column` in the story
=> fix(datagrid): pass classname from header props directly

packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/Datagrid/styles/_useStickyColumn.scss
Closes #5327 
v1 pr to add the border to the sticky column header with the right token
packages/ibm-products/src/components/Datagrid/styles/_useStickyColumn.scss
storybook
=> fix(Datagrid): v1 added border right with the correct token

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js
Closes #5240 
This PR displays the column headers for empty virtualized/infinite scroll Datagrids. The column headers typically are rendered as part of `<DatagridVirtualBody />` because there is special sizing that is required but when there is no data this presents a problem because the headers are not displayed. This renders them normally if we have a `withVirtualScroll` Datagrid that is empty.
```
packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
```
Storybook
=> fix(Datagrid): show column headers for empty infinite scroll

packages/core/.storybook/preview.js, packages/ibm-products/src/components/PageHeader/PageHeader.tsx
Closes #4979 
When we moved the `ActionBar` from internal to canary it caused issues in the PageHeader because it wasn't being enabled (which is required for _all_ canary components), whether they are used within our `@carbon/ibm-products` components or elsewhere.
The bug can be reproduced locally by removing the [following two lines](https://github.com/carbon-design-system/ibm-products/blob/main/packages/core/.storybook/preview.js#L18-L19) in `packages/core/.storybook/preview.js` . Explicitly enabling the `ActionBar` within the `PageHeader` component fixed this issue.
[This stack blitz reproduces the issue](https://stackblitz.com/edit/github-ywsqfp?file=package.json,src%2FExample%2FExample.jsx).
```
packages/ibm-products/src/components/PageHeader/PageHeader.tsx
```
Removed enabling of …
=> fix(PageHeader): enable canary `ActionBar` inside of `PageHeader`

packages/ibm-products-styles/src/components/Datagrid/styles/_useStickyColumn.scss
Closes #5327 
replaced the border of frozen columns with right tokens
packages/ibm-products-styles/src/components/Datagrid/styles/_useStickyColumn.scss
storybook
=> fix(Datagrid): replaced border tokens with the right ones

e2e/components/ExpressiveCard/ExpressiveCard-test.avt.e2e.js
Closes #5001
add e2e test for `ExpressiveCard`
`yarn run avt`
=> test(ExpressiveCard): add @avt test for default state

packages/ibm-products/src/components/Coachmark/Coachmark.tsx
Closes #5381 
This fixes issues in SSR apps as `HTMLElement` is available client side only, causing SSR apps to crash because of it's current usage in `Coachmark` prop types. We faced a very similar issue before with the `Tearsheet`, see [here](https://github.com/carbon-design-system/ibm-products/pull/3621).
```
packages/ibm-products/src/components/Coachmark/Coachmark.tsx
```
All PR checks pass
=> fix(Coachmark): ssr issues with `instanceOf(HTMLElement)`

packages/ibm-products-styles/src/components/Datagrid/styles/_useInlineEdit.scss, packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditButton/InlineEditButton.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js, packages/ibm-products/src/components/Datagrid/useInlineEdit.js, packages/ibm-products/src/components/Datagrid/utils/getInlineEditColumns.js, packages/ibm-products/src/components/Datagrid/utils/makeData.js
Closes #5378 
What I changed was that when user adds condition for `isDisabled` and set it to true, it will make the column look disabled. Otherwise the column when it is not editable it will be a static text cell. This will resolve 5378 while retaining a use case where if user wanted it to actually be disabled, they can do so
=> fix(Datagrid): add disable column support

e2e/components/ProductiveCard/ProductiveCard-test.avt.e2e.js
Closes #5002
add e2e test for `ProductiveCard`
`yarn run avt`
=> test(ProductiveCard): add default state AVT test

packages/ibm-products/src/components/Guidebanner/Guidebanner.tsx
Closes #5419 
This fixes the AVT failure coming from `Guidebanner` that is causing avt PR checks to fail.
`packages/ibm-products/src/components/Guidebanner/Guidebanner.tsx`
Ran `yarn avt` locally
=> fix(GuideBanner): address avt failure

packages/core/.storybook/WithFeatureFlags/index.js
After the feature flag PR was merged, I noticed in the editable cell Datagrid stories that the focus was lost after attempting to edit a cell. This appears to be from the forced rerender that I added which we actually do not need, everything works as expected after removing that piece from the `WithFeatureFlags` component.
```
packages/core/.storybook/WithFeatureFlags/index.js
```
Storybook
=> fix(FeatureFlags): remove forced rerender, causing focus issues

packages/ibm-products/src/components/WebTerminal/WebTerminal.tsx
Closes #5416
added `forwards` to the exit animation, to prevent animation reset upon completion.
packages/ibm-products/src/components/WebTerminal/WebTerminal.tsx
storybook
=> fix(WebTerminal): fixes exit animation glitchy behaviour

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSimpleBody.tsx, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.tsx, packages/ibm-products/src/components/Datagrid/useDatagrid.ts
Closes #5176 
Changed `packages/ibm-products/src/components/Datagrid/useDatagrid.js` to `packages/ibm-products/src/components/Datagrid/useDatagrid.ts`
Storybook
`yarn test`
=> refactor(useDatagrid): implement typescript types

packages/ibm-products/scripts/build.js, packages/ibm-products/src/index.js, packages/ibm-products/src/index.ts
Closes #5468 
Adds missing imports of `feature-flags` file as well as an update in build script to mark `feature-flags.js` as a side effect, in order for it to be included in our build output.
```
packages/ibm-products/scripts/build.js
packages/ibm-products/src/index.js
packages/ibm-products/src/index.ts
```
Confirmed that `feature-flags.js` was included in `es` and `lib` after running build script.
=> fix(FeatureFlags): add missing imports and update build script

scripts/example-gallery-builder/update-example/index.js
Closes #5423 
This change fixes a bug in the example gallery update script. It previously attempted to call `fs.fmSync` which does not exist rather than `fs.rmSync` as intended.
```
scripts/example-gallery-builder/update-example/index.js
```
Applied this change and was able to successfully run `yarn update-gallery-config` which failed previously
=> fix: address bug in update gallery script

packages/ibm-products/src/components/SidePanel/SidePanel.tsx
Closes #5400
`packages/ibm-products/src/components/SidePanel/SidePanel.tsx`
Storybook
=> fix(SidePanel): remove default slide-in focus trap

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.tsx, packages/ibm-products/src/components/Datagrid/_storybook-styles.scss
Closes #5431 
fixes the sticky header (not sticking) issue, by bringing back this line `header.getHeaderProps().className` as `headerProps.className` from this pr #3957 
also removed 
```
.test-column {
z-index: 10;
}
```
from packages/ibm-products/src/components/Datagrid/_storybook-styles.scss
which was added in #4967 
as i observed this
https://github.com/carbon-design-system/ibm-products/assets/47176249/3bc3b968-8416-46e7-8412-ba70c16f13d0
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.tsx
storybook
=> fix(Datagrid): sticky header column

packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.jsx, packages/ibm-products/src/components/Datagrid/useNestedRows.js
Closes #5260
This PR provides a way to have rows expanded by default (when they're not included as part of `initialState.expandedRowIds`). By adding `defaultExpanded: true` to the row, the `useNestedRows` hook/plugin will toggle the expansion state so that if it is a new row and should be expanded by default, this is now possible.
There is still an issue opened from @flannanl around expansion states being not kept after rerendering, but there is a [separate issue open for this](https://github.com/carbon-design-system/ibm-products/issues/4911).
```
packages/ibm-products/src/components/Datagrid/useNestedRows.js
```
Storybook
=> feat(Datagrid): add default expansion state to `useNestedRows`

packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
Closes #5402 
Closes #5428 
Closes #5433 
fixes the negative value in datagrid column customization tearsheet heading.
fixes disabled column being deselected (when deselect all checkbox is clicked)
fixes selectable column coming from `useSelectRows` being removed if deselect all is clicked from column customization 
packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
visually through storybook
for third issue i have imported and added `useSelectRows` to Column Customization Usage Story and verified in storybook
=> fix(Datagrid): column customization negative selection value and disabled column deselection

packages/ibm-products/src/components/Datagrid/useNestedRows.js
Closes #4972 
made the width dynamically change, instead of giving margin-right = -50 to fix overlapping issue.
also if any cell is resized below 50px (minimum width), the difference is added to margin right to fix the layout of the row
packages/ibm-products/src/components/Datagrid/useNestedRows.js
storybook
=> fix(Datagrid): implemented nestedRow dynamic width

packages/ibm-products/src/components/Datagrid/useFiltering.ts
Closes #5193 
Converted `packages/ibm-products/src/components/Datagrid/useFiltering.js` to `packages/ibm-products/src/components/Datagrid/useFiltering.ts`
=> refactor(useFiltering): add typescript types

packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx
Closes #5410 
[OptionsTile]: animation flicker when collapsing options tile
root cause : after the animation is finished , isOpen is still true until onFinish callback is triggered.For that minute duration , collapsed content will again show causing the flickering.
To avoid this , isOpen is set to false after the 90% of animation completion.
Local storybook
=> fix(OptionTile): animation flicker when collapsing options tile

packages/ibm-products/src/components/Datagrid/types/index.ts, packages/ibm-products/src/components/Datagrid/useExpandedRow.ts
Closes #5180 
Add Typescript types to useExpandedRow
Changed `packages/ibm-products/src/components/Datagrid/useExpandedRow.js `to `packages/ibm-products/src/components/Datagrid/useExpandedRow.ts`
- Storybook
- Yarn test
=> refactor(useExpandedRow): add typescript types

packages/ibm-products/package.json, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.tsx, packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/TearsheetWrapper.js, packages/ibm-products/src/global/js/hooks/usePortalTarget.js
Closes #5468
This PR resolves issues with feature flags specifically for webpack builds. https://github.com/carbon-design-system/ibm-products/pull/5469 fixed most of the issues however, the `feature-flags.js` file was still being tree shook by webpack even though it is listed in our `package.json`.
I tested through some trial and error by publishing our package separately under my own npm account and then created a test app using webpack. I discovered that importing the `feature-flags.js` file from the file that uses it prevents webpack from tree shaking the file so this resolves the issue.
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.tsx
packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/Tearsheet …
```
=> fix: import feature flags to prevent them from being tree shook away for webpack builds

packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.tsx, packages/ibm-products/src/components/DataSpreadsheet/hooks/useSpreadsheetOutsideClick.js, packages/ibm-products/src/components/DataSpreadsheet/types/index.ts
Closes #5370
Added a check for when we are focused out of the table to then make sure the last edited cell persists what user had edited
Storybook
https://github.com/carbon-design-system/ibm-products/assets/10100397/53370ef8-323a-4fe0-82e8-45d3d6111c25
=> fix(Dataspreadsheets): when focus out of spreadsheet, persist edited cell

packages/ibm-products/src/components/Datagrid/useInlineEdit.tsx
Closes #5192 
Converted packages/ibm-products/src/components/Datagrid/useInlineEdit.js to packages/ibm-products/src/components/Datagrid/useInlineEdit.tsx
=> refactor(useInlineEdit): add typescript types

packages/ibm-products/src/components/Datagrid/Datagrid.mdx, packages/ibm-products/src/components/Datagrid/Datagrid.stories/CustomizeColumnStory.js, packages/ibm-products/src/components/Datagrid/Extensions/ClickableRow/ClickableRow.stories.jsx, packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.docs-page.js, packages/ibm-products/src/components/Datagrid/Extensions/EditableCell/EditableCell.docs-page.js, packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.docs-page.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Filtering.docs-page.js, packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.jsx, packages/ibm-products/src/components/Datagrid/Extensions/RowActionButtons/RowActionButtons.docs-page.js, packages/ibm-products/src/components/Datagrid/Extensions/RowHeightSettings/RowHeightSettings.stories.jsx, packages/ibm-products/src/components/Datagrid/Extensions/Slug/Slug.stories.jsx
Closes #5273 
Contributes to #5016 
Remove the "reset to default" documentation from Storybook as we do not have any design documentation around that feature and it has not been implemented.
Also remove the codesandbox/stackblitz links for non-existent Datagrid extension stories
- Remove "reset to default" documentation from 
```
- packages/ibm-products/src/components/Datagrid/Datagrid.mdx
- packages/ibm-products/src/components/Datagrid/Datagrid.stories/CustomizeColumnStory.js
- packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.docs-page.js
```
- Add `omitCodedExample` prop to the `StoryDocsPage` component for
```
components/Datagrid/Extensions/ClickableRow/ClickableRow.stories.jsx
components/Datagrid/Extensions/ColumnCustomization/ColumnCusto …
```
=> docs(storybook): remove storybook doc and codesandbox example

packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.tsx
Closes #
https://github.com/carbon-design-system/ibm-products/issues/5330
If previous state wasn't in edit mode, then don't append the new line. I checked the storybook before this change and there wasn't a way to do new line through any commands that I found. So this doesn't regress anything. Thanks!
Storybook
https://github.com/carbon-design-system/ibm-products/assets/10100397/62512d95-c05b-4839-8a5b-9444de88cc40
=> fix(Dataspreadsheets): don't append new line when we hit enter

e2e/components/SearchBar/SearchBar-test.avt.e2e.js
Closes [#5217](https://github.com/carbon-design-system/ibm-products/issues/5217)
Added avt test file for SearchBar component
`yarn avt`
=> test(SearchBar): add default avt testing

e2e/components/BigNumbers/BigNumbers-test.avt.e2e.js
Closes #5206
Added default avt test for BigNumbers
Ran `yarn avt`
=> test(BigNumbers): add default avt test

packages/ibm-products/src/components/index.js
Closes #5579
Properly exports StatusIndicatorStep.
```
packages/ibm-products/src/components/index.js
```
Exported with all other components 😄
=> fix: export status indicator step component

.github/workflows/release-base.yml, packages/ibm-products/package.json
Closes #5576
This change will update avt reports during release workflows so that we have up to date reports that can be imported from `@carbon/ibm-products/.playwright/report.json` and used to track accessibility status from our website ([work in progress here](https://github.com/carbon-design-system/carbon-for-products-website/pull/24)).
```
.github/workflows/release-base.yml
```
This should match a similar process as seen in `@carbon/react`.
=> fix: include avt report in release workflow

packages/ibm-products/src/components/PageHeader/PageHeader.tsx
Closes #5499 
This PR removes the console warning when using the `PageHeader`. This happens because now that the `ActionBar` is a canary component we have to enable it which normally emits a console warning, in this case we want to opt out of receiving warnings.
```
packages/ibm-products/src/components/PageHeader/PageHeader.tsx
```
Storybook
=> fix(PageHeader): silence warnings from enabling ActionBar

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterProvider.js
Closes #5594
This fixes an issue where if the `id` and `value` for checkbox or multiselect filters are different an error gets thrown if you attempt to remove the filter tag via the close icon.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterProvider.js
```
Updated filter props in `Flyout.stories.jsx` to locally reproduce and check that this change fixes the issue
=> fix(Datagrid): address issue when id and value of filter are different

.github/ISSUE_TEMPLATE/bug-report.yaml
This is an update to the bug issue template so that it will no longer default to "Severity 1" for all issues reported. This also borrows from Carbon core to point to the descriptions of severities as well.
=> chore(issue-template): added better description and default to "none" for severity of bugs

docs/guides/security-component-migration.md, docs/guides/v2.md, examples/carbon-for-ibm-products/FullPageError/src/Example/Example.jsx, packages/ibm-products/src/components/FullPageError/FullPageError.mdx, packages/ibm-products/src/components/HTTPErrors/HTTPError403/HTTPError403.stories.jsx, packages/ibm-products/src/components/HTTPErrors/HTTPError404/HTTPError404.stories.jsx, packages/ibm-products/src/components/HTTPErrors/HTTPErrorOther/HTTPErrorOther.stories.jsx
Closes #4402 
adds documentation and fixes example for FullPageError
docs/guides/security-component-migration.md
docs/guides/v2.md
examples/carbon-for-ibm-products/FullPageError/src/Example/Example.jsx
packages/ibm-products/src/components/FullPageError/FullPageError.mdx
storybook, markdown preview.
=> chore(FullPageError): add docs and fix example

packages/ibm-products-styles/src/components/OptionsTile/_options-tile.scss, packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx
Closes #5560
Change selectors for the OptionTile's summary and chevron elements to use BEM modifiers.
change the selectors for the CSS rules applicable to summary and chevron to use BEM modifiers, instead of looking at parent elements to determine the open and closing states.
The effects of the fix are visual, so (manually) compared how the chevron looks like and behaves during opening/closing, verified that the summary is visible on a nested options tile when it is collapsed.
=> fix(OptionsTile): fix styling of summary and chevron when nesting OptionsTile

packages/ibm-products/src/components/EditTearsheet/EditTearsheet.test.js, packages/ibm-products/src/components/EditTearsheet/EditTearsheet.tsx, packages/ibm-products/src/components/EditTearsheet/preview-components/MultiFormEditTearsheet.js
Closes #4520 
Provide indication and prevent consecutive submit button clicks as long as prev onRequestSubmit  is processing.
1. Following submit button click, submit button is disabled with loading indicator until the onRequestSubmit processing completes.
2. Modify story to emulate a 1 sec processing to see the change
3. Added unit test
Manual tests via storyboard 
Added unit test
https://github.com/carbon-design-system/ibm-products/assets/147585390/d41f4d6b-f4a2-40c0-b8e9-b328ac041fdc
=> fix(EditTearsheet): prevent submit while processing and add indication if submitting

packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.tsx
Closes #5617
This change properly sets the cell editor value so that when entering edit mode for cells within the first column (index 0) the correct value is applied.
```
packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.tsx
```
Storybook
=> fix(DataSpreadsheet): address issue with active cell value

packages/ibm-products-styles/src/components/ConditionBuilder/_condition-builder.scss, packages/ibm-products-styles/src/components/ConditionBuilder/styles/_conditionBuilderCondition.scss, packages/ibm-products-styles/src/components/ConditionBuilder/styles/_conditionBuilderItem.scss, packages/ibm-products/src/components/ConditionBuilder/ConditionBlock/ConditionBlock.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderActions/ConditionBuilderActions.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderAdd/ConditionBuilderAdd.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderButton/ConditionBuilderButton.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderConnector/ConditionConnector.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContext/ConditionBuilderProvider.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContext/translationObject.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItem.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemDate/ConditionBuilderItemDate.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemNumber/ConditionBuilderItemNumber.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemOption/ItemOptionForValueField.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemText/ConditionBuilderItemText.js, packages/ibm-products/src/components/ConditionBuilder/ConditionGroupBuilder/ConditionGroupBuilder.js, packages/ibm-products/src/components/ConditionBuilder/utils/handleKeyboardEvents.js, packages/ibm-products/src/components/ConditionBuilder/utils/util.js
Contributes #4916 , #5640 
- Implementation to show content as '**incomplete**' when user close the popover without selecting any values
- Edge case issue when user delete all plain condition keeping only subgroups in a group
- Mange tab index and focus
- Accessibility fixes
Local storybook
=> feat(conditionBuilder): accessibility and generic issue fixes

packages/core/.storybook/manager-head.html, packages/core/.storybook/preview.js
Ever since the SB8 upgrade, there have been scrollbars visible on the `iframe` that we didn't have before. I made some updates to storybook `preview.js` to remove them (they were being caused from the border that we apply to the story).
```
packages/core/.storybook/preview.js
```
Storybook
=> chore: remove sb iframe scrollbars

packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
Closes #5624 
This addresses the issues described in #5624. It adds the same functionality added in [this PR](https://github.com/carbon-design-system/ibm-products/pull/5264), which fixed the `selectorPrimaryFocus` behavior but for stacked tearsheets.
```
packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
```
Storybook
=> fix(Tearsheet): fix behavior of `selectorPrimaryFocus` for stacked tearsheets

packages/ibm-products/src/components/GetStartedCard/GetStartedCard.tsx
Closes #5675
Update GetStartedCard to use types
updated the GetStartedCard file
Storybook
=> refactor(GetStartedCard): update to typescript

packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js
Closes #5649 
fixes the focus going to below cell after we hit enter to save the cell
packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js
storybook
=> fix(Datagrid): EditableCell shifting focus to the below cell after edit

packages/ibm-products/src/components/PageHeader/PageHeader.stories.jsx
The navigation tabs used in PageHeader are incorrectly demonstrated causing accessibility issues to be reported
This PR addresses that
=> fix: navigation tab usage in story

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/Datagrid/styles/_datagrid.scss, packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.tsx
Closes #5682 
due to the presence of `div` instead of `th` at coordinates (1,1) in the table for all the mentioned variants in the issue, the screen reader reads the header ahead by 1.
also below format is inconsistent across browsers (chrome has no issues, but firefox reads header ahead by 1)
```
<div>
<th>
</th>
</div>
```
this pr fixes them.
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.tsx
voiceover in storybook, mozilla, chrome
=> fix(datagrid): screen reader misreads datagrid table headers

packages/ibm-products/src/components/ActionBar/ActionBar.tsx, packages/ibm-products/src/components/ActionBar/ActionBarItem.tsx, packages/ibm-products/src/components/ActionBar/ActionBarOverflowItems.tsx
Closes #5674 
add types to actionbar
Update ActionBar, ActionBarItem, and ActioinBarOverflowItems to using typescript
storybook
=> refactor(action-bar): convert to typescript

.github/workflows/release-base.yml
Closes #
When no changes have been implemented since the latest release candidate, the `conventional-graduate` lerna flags are needed to trigger a full release regardless if there have been no changes
=> chore(release): add lerna conventional graduate/prerelease flags

packages/ibm-products/src/components/UserAvatar/UserAvatar.tsx
Closes #5672 
Add Typescript types to UserAvatar
=> refactor(UserAvatar): convert to typescript

packages/ibm-products/src/components/PageHeader/PageHeaderUtils.js
Closes #4427
`headerOffset` is used to ensure the PageHeader works correctly if the component is not at the top of the viewport. The conditional for calculating a header offset was incorrect.
Previously it checked whether the offset value was zero. This could only be true if the header was already at the top of the viewport or it could not obtain a reference to the `offsetTopMeasuringRef`. In either case there would be no need to calculate the offset anyway.
By inverting the conditional, headerOffset will now be calculated (i.e. set to non-zero) if the offset component used to identify the PageHeader's position within the viewport if actually offset from the top.
=> fix(PageHeader): correct conditional for non zero offsets

packages/ibm-products/src/components/Datagrid/useInitialColumnSort.js, packages/ibm-products/src/components/Datagrid/useSortableColumns.tsx
Closes #5569
fixes bug where cycling through the column sort options on datagrid wouldn't allow you to go back to no sort
=> fix(Datagrid): datagrid sort reset

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.tsx
Closes #4579 
fixes a bug where a datagrid using infinite scrolling when hidden by something like a carbon `Tab` the width was getting set to 0. this fix simply checks to make sure the datagrid is on screen before applying a new width
=> fix: datagrid hidden virtual body width

.gitignore
Addresses missing piece from https://github.com/carbon-design-system/ibm-products/issues/5576
Because the playwright results for `packages/ibm-products` are included in our `gitignore`, the results are never included in our published releases. This is problematic in that we won't be able to use up to date playwright avt coverage results in the website. I've removed it from our `gitignore` so that we can pull the results from our package instead of including it just as a local file for the website (see [here](https://github.com/carbon-design-system/carbon-for-products-website/blob/main/src/components/A11yStatus/test_avt_report.json)).
```
.gitignore
```
Ran build locally
=> build(playwright): remove playwright results from gitignore

packages/ibm-products/src/components/CoachmarkOverlayElements/CoachmarkOverlayElements.tsx, packages/ibm-products/src/components/CoachmarkStack/CoachmarkStack.tsx, packages/ibm-products/src/components/CoachmarkStack/CoachmarkStackHome.tsx
Closes #4491 
Related #5097 
This PR converts `CoachmarkStack` and `CoachmarkStackHome` to TypeScript
* file extension
* TS interface
=> feat(CoachmarkStack): convert to .tsx

packages/ibm-products/src/components/Card/Card.tsx, packages/ibm-products/src/components/ProductiveCard/ProductiveCard.stories.jsx, packages/ibm-products/src/components/ProductiveCard/ProductiveCard.tsx
Closes #5399
No option to edit tooltip text on ProductiveCard with Overflow menu
Added `iconDescription` attribute to ProductiveCard and passes the same as prop to CardHeader.
Storybook
=> fix(ProductiveCard): with overflow tooltip issue

packages/ibm-products/src/components/RemoveModal/RemoveModal.stories.jsx, packages/ibm-products/src/components/RemoveModal/RemoveModal.test.js, packages/ibm-products/src/components/RemoveModal/RemoveModal.tsx
Closes #2289 
Update the Remove Modal to use ReactNode
Changed the typing for the body from `string` to `ReactNode`. 
- Added a test to check that a `Link` react node exists in the modal when added. 
- Added a new story in storybook which includes a `Link` react node in the body of text, linking to the carbon design homepage. Note: the naming of the story might want some work, and for my use case, I am looking at using Links, but are there other potential components that should be tested here?
=> feat(RemoveModal): update body to use ReactNode

packages/ibm-products/src/components/FeatureFlags/index.tsx
Closes #5671 
Converts `FeatureFlags` to TypeScript, also realized we didn't _have_ to do this one because it's released currently as unstable. But it didn't require too many changes 😄 
```
packages/ibm-products/src/components/FeatureFlags/index.tsx
```
Component and hooks still function as expected in storybook, no type errors
=> refactor(FeatureFlags): convert to typescript

packages/ibm-products/src/global/js/utils/story-helper.js
Addresses _most_ cases from https://github.com/carbon-design-system/ibm-products/issues/5837
Currently, all auto-generated guideline links for components and patterns are leading to 404 pages as they…:
- use an uppercase first characters instead of lowercase
- add an unwanted "s" suffix
Before
```
https://pages.github.ibm.com/cdai-design/pal/Componentss/side-panel/usage
```
After
```
https://pages.github.ibm.com/cdai-design/pal/components/side-panel/usage
```
- Transform kind (`Components | Patterns`) to lowercase
- Remove unwanted "s" suffix
Local storybook
=> fix: correct auto-generated guidelines links

packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx
Closes #5702 
Changes size prop to optional on ts prop declarations
- packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx
=> fix(options-tile): size prop optional

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.jsx, packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.jsx, packages/ibm-products/src/components/Datagrid/utils/DatagridActions.js
Closes #5000
Datagrid filter icon at the right most end of the screen causes scroll bar on hover. 
Issue caused by the tooltip
Added `align` prop in `filter flyout` and `filter panel` as part of `filter props`. 
Storybook
=> fix(datagrid): filter tooltip causes horizontal scroll

packages/ibm-products/src/components/Coachmark/Coachmark.test.js, packages/ibm-products/src/components/CoachmarkBeacon/CoachmarkBeacon.test.js, packages/ibm-products/src/components/CoachmarkOverlayElement/CoachmarkOverlayElement.test.js, packages/ibm-products/src/components/CoachmarkOverlayElements/CoachmarkOverlayElements.test.js
Coachmark accessibility tests are suddenly failing, which is not allowing us to kick off the full release. This PR disables those tests so we can get the release through for now.
- ibm-products/src/components/Coachmark/Coachmark.test.js
- ibm-products/src/components/CoachmarkBeacon/CoachmarkBeacon.test.js
- ibm-products/src/components/CoachmarkOverlayElement/CoachmarkOverlayElement.test.js
- ibm-products/src/components/CoachmarkOverlayElements/CoachmarkOverlayElements.test.js
- Ran `yarn ci-check` locally and everything passes
=> test(Coachmark): disable coachmark accessibility tests 

packages/ibm-products/src/components/Datagrid/useSortableColumns.tsx
Closes #5079 
Instead of losing the column header focus after sorting, now user will be able to sort in opposite direction without pressing the Tab again ( just needs to press Enter to sort in opposite direction).
=> fix(Datagrid): sortable column focus issue

.github/workflows/ci.yml, package.json, yarn.lock
[Running into an issue in the release](https://github.com/carbon-design-system/ibm-products/actions/runs/10455189263/job/28950754349) where lerna is trying to find the `stylelint-config-ibm-products@npm: *` and is failing. The other private packages are referenced directly with their package versions, so changing to the same for the `stylelint-config-ibm-products` package as well to see if that will work.
Will keep an eye out to see if lerna updates the `stylelint-config-ibm-products` version in root `package.json` as the reason why it was changed to `*` was because it was not getting updated by lerna.|
Also add the release branch to the `ci.yml` workflow so we can get ci-checks running on PRs based against the release branch
- `package.json`
- `ci.yml`
- `yarn.lock`
=> chore(stylelint): use version for stylelint config package

packages/ibm-products/src/components/Datagrid/useFiltering.ts, packages/ibm-products/src/components/Datagrid/utils/FilteringUsage.js
Closes #5742 
This PR adds a new filter type to Radio buttons. The radio button will now search for the `exactText` react-table function when filtering rather than using `.includes()`
- packages/ibm-products/src/components/Datagrid/useFiltering.ts
- packages/ibm-products/src/components/Datagrid/utils/FilteringUsage.js
Ran the same scenario as the issue and got it to work.
https://github.com/user-attachments/assets/8e92393e-5f71-49a5-8357-c007204f1426
=> feat(datagrid): adds radio filter

packages/ibm-products/src/components/Card/Card.tsx
Closes #5864
disabled variant is not interpreted as disabled from JAWS.
set `aria-disabled` attribute to the `disabled` prop value in Card.
Storybook screen reader
=> fix(getstartedcard): disable vairant not intrepreted as disabled in JAWS

packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx
Closes #5854 
fixes string format for the child of the `<Tag>` component, which fixes the title attribute.
packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx
storybook
=> fix(TagSet): fix string formatting

packages/ibm-products/src/components/APIKeyModal/APIKeyModal.types.ts, packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx
Closes #5700 
Makes the `portalTarget` property optional, as expected. I also found it was marked as required in `APIKeyModal` which I fixed in this PR as well.
```
packages/ibm-products/src/components/APIKeyModal/APIKeyModal.types.ts
packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx
```
Locally, verified within vscode
=> fix(Tearsheet): update `portalTarget` type

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.tsx
Closes #5768 
call `resetAfterIndex() `when there is a row height change that will reset the cache of `react-window
`
storybook
=> fix(DataGrid): row size change issues with virtual scrolling enabled

packages/ibm-products/src/components/CreateFullPage/CreateFullPageStep.tsx, packages/ibm-products/src/components/CreateFullPage/index.ts
Closes #5701 
This PR changes the `hasFieldSet` prop to optional and exports `CreateFullPageStepProps`
- packages/ibm-products/src/components/CreateFullPage/CreateFullPageStep.tsx
- packages/ibm-products/src/components/CreateFullPage/index.ts
=> fix(create-full-page-step): update `hasFieldSet` type and export `CreateFullPageStepProps`

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/EditInPlace/_edit-in-place.scss
Closes #5779 
fixes an issue where `EditInPlace` inside of a `td` was having experiencing a visual bug when focused. replacing `outline` with `border` allows the cell to appropriately size the component.
=> fix: editinplace replace outline with border

packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js
Contributes #5782
Skip the condition builder tests for now to pass CI checks
changed `describe` to  `xdescribe`
yarn test
=> fix(Conditionbuilder): add await for accessibility test

packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js
Closes #5912 
This PR removes the `renderRegularCell` function that was spreading `inputProps` onto a `span` element, resulting in the bug described in #5912. That element isn't serving any purpose so we can safely remove it.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js
```
Storybook
=> fix(Datagrid): remove unused span with `inputProps`

e2e/components/ConditionBuilder/ConditionBuilder-test.avt.e2e.js
Closes #5932
Add default state AVT check for Condition Builder
added `e2e/components/ConditionBuilder/ConditionBuilder-test.avt.e2e.js`
yarn avt
=> test(ConditionBuilder): add default state AVT for Condition Builder

packages/ibm-products/src/components/ExpressiveCard/ExpressiveCard.stories.jsx, packages/ibm-products/src/components/ProductiveCard/ProductiveCard.stories.jsx
Closes #5863 
this helps to alleviate some issues Raghu was experiencing while testing cards. when the button is focused with VO in the link button example VO was reading like `link. ghost button.` which made it unclear as to what the element being focused was. a button or a link? this just rewords some of the props so they look like more real world examples to make our examples more clear to assistive technology.
=> fix: reword props in card stories

packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx
Closes #5852 
This PR removes the focus of the EditInPlace after pressing Enter or the Escape key.
`packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx`
Modified storybook story to reflect the code sandbox props
https://github.com/user-attachments/assets/29621692-3efc-4c88-9293-6b49327c1fb5
=> fix(EditInPlace): removes focus when pressing esc or enter key

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products/src/components/ProductiveCard/ProductiveCard.stories.jsx, packages/ibm-products/src/components/ProductiveCard/_storybook-styles.scss
Closes #5862 
makes the graph on the productive card, screen readable.
since the graph rendered in the productive card is just a div without any children, setting `alt` or `aria-label` didn't work, so I had to take this approach.
also scoped storybook styles
packages/ibm-products/src/components/ProductiveCard/ProductiveCard.stories.jsx
JAWS on Windows 11 VM
Voiceover on Mac
=> fix(ProductiveCard): makes graph screen readable, story only.

.github/workflows/ci.yml, scripts/get-changelog.js
Closes #5967
Adjusting the release changelog script to ignore the version bump commit and not include it in the changelog.
example:
```
- chore(Conditionbuilder): typescript migration (#5841)
- chore(release): v2.47.0 (#5866) <-------- do not want this to be included
```
- `scripts/get-changelog.js`
ran changelog script locally
=> chore: update changelog script to ignore version bump commit 

config/jest-config-ibm-cloud-cognitive/setup/matchers/toHaveNoAxeViolations.js, packages/ibm-products/src/components/AboutModal/AboutModal.test.js, packages/ibm-products/src/components/CreateFullPage/CreateFullPage.test.js, packages/ibm-products/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.test.js, packages/ibm-products/src/components/Tearsheet/Tearsheet.test.js
Updates toHaveNoAxeViolations and fixes a small number of use cases.
The function was creating a new Promise which is not necessary, refactored.
Not entirely sure the async/await is doing much in the tests that were refactored, but with async tests the accessible checks need to be waited for when there are multiple uses of the accessible matchers.
Ran the tests.
=> fix: update toHaveNoAxeViolations and remove skips

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
Closes #5998
Since [] !== [], need to be careful when setting [] as a default value and then using it in the dependencies of useEffect() etc.
Created constant variables so that filters, reactTableFiltersState, etc. variables get the same default value every time.
Storybook
=> fix(datagrid): use same empty array every time

e2e/components/ConditionBuilder/ConditionBuilder-test.avt.e2e.js, packages/ibm-products/src/components/TagSet/TagSet.test.js, packages/ibm-products/src/components/TagSet/TagSet.tsx
Closes #5703 
This PR updates the tagset props. The initial issue is to update the typescript prop but after investigating I realized that it's better to not force the user to add a prop after 10 tags but have defaults and give the user the option to update them if they want to change the text for the labels. 
- packages/ibm-products/src/components/TagSet/TagSet.tsx
Storybook
=> fix(tagset): updates props

packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js
Closes #5986
This bug stems from the recent support for dynamic nested rows, returning `null` fixes this problem.
```
```
Tested storybook locally by using react 17.x.x.
=> fix(Datagrid): return null for older react versions

packages/ibm-products/src/components/Tearsheet/Tearsheet.stories.jsx
Closes #4989 
this updates `Tearsheet` stories to demonstrate proper nav implementation using carbon `Tabs`. the solution is to just wrap the entire thing in a `Tabs` component.
this also demonstrates a fairly more straight forward implementation approach that doesn't rely on an [array](https://github.com/carbon-design-system/ibm-products/blob/8fee17fd31732b792733a95ddf2955675e8ca5ae/packages/ibm-products/src/components/PageHeader/PageHeader.stories.jsx#L165) like in the `PageHeader` story implementation and just uses a react element.
confirmed locally that this implementation addresses the accessibility concerns
=> fix: tearsheet with nav accessibility

packages/ibm-products/src/components/TagOverflow/TagOverflow.tsx
Closes #5985 
Updated the type value of _filter_ prop as _boolean_
packages/ibm-products/src/components/TagOverflow/TagOverflow.tsx
storybook
=> fix(tagoverflow): incorrect type for filter prop

packages/ibm-products-styles/src/components/Datagrid/styles/_useSortableColumns.scss
Closes #5940
Inherited the alignment from parent for sortable columns
Storybook
=> fix(DataGrid): column headers vertically misaligned when some are sortable

packages/ibm-products/scripts/generate/templates/DISPLAY_NAME.test.js, packages/ibm-products/scripts/generate/templates/DISPLAY_NAME.tsx, packages/ibm-products/src/components/Carousel/Carousel.test.js, packages/ibm-products/src/components/Carousel/Carousel.tsx, packages/ibm-products/src/components/Coachmark/CoachmarkDragbar.tsx, packages/ibm-products/src/components/Coachmark/CoachmarkHeader.tsx, packages/ibm-products/src/components/CoachmarkOverlayElement/CoachmarkOverlayElement.tsx, packages/ibm-products/src/components/CoachmarkOverlayElements/CoachmarkOverlayElements.tsx, packages/ibm-products/src/components/CoachmarkStack/CoachmarkStackHome.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.tsx, packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.test.js, packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.tsx, packages/ibm-products/src/components/TagOverflow/TagOverflow.test.js, packages/ibm-products/src/components/TagOverflow/TagOverflow.tsx
Closes #5964 
The main landmark role is  removed from components as it is used to indicate the primary content of a document.
Removed role="main" attribute from component level and updated unit tests with data-testid attribute instead of role.
- unit test
- storybook
- `yarn generate ComponentName`
=> fix: main landmark role removed from components

packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js
Closes #5763 
Given a unique name attribute for the row height selection radio button group.
packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js
Storybook
=> fix(datagrid): unique name attribute for row settings radio buttons

packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.jsx
Closes #5935 
This PR fixes the error `a.filter is not a function`. Replaced the dropdown filter with multiselect
`packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.jsx`
Storybook
=> fix(datagrid): fixes multiselect for instant update bug

packages/ibm-products/src/components/PageHeader/PageHeaderUtils.js
Closes #5896 
remove small gap that was appearing when the `collapseTitle` prop in `PageHeader` was enabled
=> fix: pageheader gap

packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx, packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.tsx, packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
Closes #5704 
changes the actions prop to optional in Tearsheet.
actions prop in TearhseetNarrow, and TearsheetShell are optional already. made the typings consistent.
packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx
packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.tsx
packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
vs code IntelliSense
=> fix(Tearsheet): changed actions prop to optional

packages/ibm-products/src/components/TagSet/TagSet.tsx, packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx
Closes #5407 and also #5354
i'm guessing something changed on the carbon side because using floating ui and `autoAlign` is now working with `TagSet`.
the results i'm seeing today are much different (working) compared to a previous attempt to implement. i just reused the same code from a previous PR https://github.com/carbon-design-system/ibm-products/pull/5406
verification of functionality inside the `TagSet` story
verification of functionality using the example code provided in the issue
=> fix: add floating ui to tagset

cspell.json, packages/ibm-products/src/components/Datagrid/Datagrid.stories.jsx, packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js, packages/ibm-products/src/components/Datagrid/Extensions/RowActionButtons/RowActionButtons.stories.jsx, packages/ibm-products/src/components/Datagrid/useDisableSelectRows.ts
Closes #5972
Select all button in batch actions, selects disabled rows on other pages. 
The issue is React table only provides `getRowProps` for rows that are visible for performance improvement.
And this function is needed to determine whether a row is disabled or not.
As a workaround added a new  field `nonselectablerows` to the returned props value for each row - which holds the list of disabled rows .
Storybook (Story: `Row Action Buttons Batch Actions Usage Story`)
=> fix(datagrid): selectall selects disabled rows

packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx, packages/ibm-products/src/global/js/utils/Wrap.tsx
Closes #5745 
`tabIndex: -1` for `div.c4p--tearsheet__content` element
`yarn avt`
Storybook
=> fix(tearsheet): Firefox focuses Tearsheet content div with scroll

e2e/components/SidePanel/SidePanel-test.avt.e2e.js, packages/ibm-products/src/components/SidePanel/SidePanel.stories.jsx, packages/ibm-products/src/components/SidePanel/SidePanel.tsx, packages/ibm-products/src/components/Tearsheet/Tearsheet.stories.jsx
Closes #5885 
Implemented filter focusable elements `disabled` elements and `display === 'none'`
`yarn test`
`yarn avt`
Storybook
=> fix(SidePanel): resolve focus wrap issue when first element is disabled

packages/ibm-products/src/components/TagSet/TagSet.tsx
Closes #5481 
Multiline prop functionality is not working when maxVisible prop is not provided
Set the default value of `maxVisible` to the total number of tags, if no explicit value is provided.
- Storybook
=> fix(tagset): multiline prop broken

docs/guides/publishing-releases.md
Closes #
Add some clarifying steps to the patch release 
`docs/guides/publishing-releases.md`
=> chore(release): add steps to release docs

packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx
Refs #4281.
Fix Typescript declaration of OptionsTile.onToggle.
Made onToggle optional in Typescript.  It was already optional in PropTypes.
Building locally.
=> fix(OptionsTile): onToggle should not be required

packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js
Closes #5983
Dynamic nested rows skeleton always showing regardless of dynamic prop being set
skip await  getAsyncSubRows when not defined
=> fix(Datagrid): dynamic nested rows skeleton always showing regardless of dynamic prop being set

packages/ibm-products/src/components/CreateFullPage/CreateFullPageStep.tsx
Refs #4512.
`fieldsetLegendText` should not be required when `hasFieldset` is not specified.
Basically, not specifying `hasFieldset` is the same thing as setting it to `false`.
When `hasFieldset` is not specified, make `fieldsetLegendText` optional.
Test locally.
=> fix(CreateFullPageStep): hasFieldset and fieldsetLegendText types

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
Closes #5717 
Fixes the issue where the filter tags were updating instantly when using batch actions
I changed the filter context state dispatch from useFilters to onApply button callback in the filter panel and filter flyout
https://github.com/user-attachments/assets/2d590a2a-519c-48fc-8f86-def5fb21e935
=> fix(datagrid): batch no longer updates filter tag

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
Closes #5843 
If all the columns are unchecked, Save button should not be enabled in Datagrid customise columns
storybook
=> fix(DataGrid): disable save button on customise column

packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx
Closes #5707.
Fix type of CreateFullPage.breadcrumbs
Made it an array rather than a single breadcrumb.
Tested locally.
=> fix(CreateFullPage): breadcrumbs should be array

packages/ibm-products/src/components/ExportModal/ExportModal.tsx
Closes #6014
Screen reader identifies hidden controls -  focus sentinel button
Wrapped the `Export modal` component inside a `FeatureFlags` with  `enable-experimental-focus-wrap-without-sentinels` set to true.
Storybook
=> fix(ExportModal): screen reader identifies hidden controls

packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.tsx, packages/ibm-products/src/components/Datagrid/types/index.ts, packages/ibm-products/src/components/Datagrid/useDisableSelectRows.ts
Closes #5937
Selectable row should not count disabled rows in select all button
Updated the `totalCount ` attribute being passed to `TableBatchActions` with only selectable rows count.
Storybook
=> fix(Datagrid): select all row count updated to exclude disabled rows

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/EditInPlace/_edit-in-place.scss, packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx
Closes #6082 
removes the ellipsis in `EditInPlace` to alleviate an accessibility and functional issue where you are unable to focus on the input
=> fix: remove ellipsis from EditInPlace

packages/ibm-products/src/components/ProductiveCard/ProductiveCard.tsx
Closes #5614 
fixes small bug where `primaryButtonDisabled` was not declared in the prop types for `ProductiveCard`
=> fix: add primaryButtonDisabled prop to ProductiveCard

cspell.json, packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.stories.jsx, packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx
Closes #6089 
Focus return to the trigger button on closing the Notification panel should be handled in the component not in stories for better adapter experience.
Added option to pass trigger button reference `triggerButtonref` as prop to the `Notification Panel`component and focus being returned from the component itself instead of being done in the stories.
=> fix(NotificationPanel): focus return to trigger on closing notification panel

packages/ibm-products/src/components/Datagrid/Datagrid/DraggableElement.tsx
Closes #4797
Remove redundant `aria-disabled` in customize columns items
`aria-disabled` is set to `undefined` for `li` element.
Storybook
=> fix(Datagrid): remove redundant aria disabled

packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.tsx
Contributes #3776 
remove unwanted role from condition builder non-hierarchical variant
=> fix(ConditionBuilder): correct role for NON HIERARCHICAL_VARIANT

packages/ibm-products/src/components/Datagrid/useSelectRows.tsx
Closes #5683 
returns the radio select focus, if it's lost.
packages/ibm-products/src/components/Datagrid/useSelectRows.tsx
storybook, screen reader for mac, jaws for win 11
=> fix(dataGrid): focus loss on radio select

packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx
Closes #6010 
fixes a small timing issue that was preventing the notification panel from regaining focus after closing via keyboard.
you can verify the fix by following the `Steps to reproduce the issue (if applicable)` and verifying that the focus is regained.
=> fix: notification panel keyboard close focus

packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss, packages/ibm-products/src/components/SidePanel/SidePanel.stories.jsx, packages/ibm-products/src/components/SidePanel/_storybook-styles.scss
Closes #5922
Background color for `Multiselect` doesn't match with other fields in  `Side Panel`
Updated the style file to set `Multiselect` the same style as the rest of the fields and added a `Multi select` field in the storybook stories for `Side panel`
Storybook
=> fix(SidePanel): style issue with multi select

.github/workflows/update-example-gallery.yml, packages/ibm-products/src/components/ExportModal/ExportModal.tsx
Closes #6067 
`- cron: '0 0 15 * *'`
`if: **failure()** && steps.up_to_date.outcome == 'failure'`
`GITHUB_TOKEN `
Github UI
=> fix(update-example-gallery): resolve create-pr failure issue

config/jest-config-ibm-cloud-cognitive/index.js
Closes #6139 
adds `{ts,tsx}` extensions to the test coverage analysis and cleans up some of the jest config by removing old unnecessary coverage options. this bug was originally noticed when `UserAvatar` wasn't being picked up in the reporter. in the below screen shot you can see it's included after running the updated script.
=> fix: adds typescript to coverage report

packages/ibm-products/src/components/ExportModal/ExportModal.stories.jsx, packages/ibm-products/src/components/ExportModal/ExportModal.tsx
Closes #6018
Export Modal, Focus not returning to triggering button
Passed the trigger button reference `triggerButtonRef ` as prop to `Export Modal` and added the logic focus on the button on closing the modal from there.
Storybook
=> fix(ExportModal): focus return to trigger button

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/CreateTearsheet/_create-tearsheet.scss
Closes #5613 
fixes small visual bug where `height: 100%` was preventing padding from being applied inside `.dev-prefix--c4p--tearsheet-create__content`
=> fix: createTearsheet height fix

config/jest-config-ibm-cloud-cognitive/setup/matchers/toHaveNoACViolations.js, e2e/components/Datagrid/Datagrid-test.avt.e2e.js, playwright.config.js
Adds a temporary workaround for the `target_spacing_sufficient` rule that changed to flag certain areas as violations. We can revisit this rule as there are updates in the issue. There was also a Datagrid avt test where I found that the timeout needed to be moved to account for the side panel exit animation before checking focus returning to the row.
```
config/jest-config-ibm-cloud-cognitive/setup/matchers/toHaveNoACViolations.js
e2e/components/Datagrid/Datagrid-test.avt.e2e.js
playwright.config.js
```
AVT tests from PR checks
=> fix: temp workaround for target_spacing_sufficient rule

packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx
Refs #546.
`headerActions` was defined for `TearsheetShell` but not for `Tearsheet`.
This caused Typescript errors, and you were also missing `PropTypes` validation for any plain Javascript code using `headerActions`.
Note that ideally, Tearsheet.tsx and TearsheetNarrow.tsx would not repeat the type declarations from TearsheetShell.tsx.  But that's no addressed in this PR.
Added Tearsheet `headerActions` Typescript declaration, and also added it to the `PropTypes`.
Built locally.
=> fix(Tearsheet): add missing declaration for headerActions prop

packages/ibm-products/src/components/InlineTip/InlineTip.tsx
Closes #6099 
adds optional `?` flag on media prop for InlineTip
packages/ibm-products/src/components/InlineTip/InlineTip.tsx
vs code intellisense, local.
=> fix(InlineTip): added optional ? flag on media

packages/ibm-products-styles/src/components/TagOverflow/_tag-overflow.scss, packages/ibm-products/src/components/TagOverflow/TagOverflowPopover.tsx
Closes #6002
Update TagOverflow to use OperationalTag
Replaced `Tag` with `OperationalTag`  for tag with click action.
Storybook
=> fix(TagOverflow): use operational tag

.github/workflows/ci.yml, package.json
I noticed that there were ci issues in the new web component package when the canary release action runs because playwright browsers haven't been installed. I made a change to do this before running the web component tests, so it will work in `ci.yml` and `release-canary.yml`.
```
package.json
```
Verifying all checks in this PR still pass
=> fix: install playwright browsers

package.json, packages/ibm-products-web-components/netlify.toml, packages/ibm-products-web-components/package.json
Addresses part of #6130 
Adds storybook build scripts for web component storybook to root package.json to help with Netlify setup. I also removed the `dev` script in the web components package which was no longer being used.
```
package.json
packages/ibm-products-web-components/package.json
```
Setting up similar to how we have our React storybook
=> chore: add wc storybook scripts to root package.json for netlify setup

.github/workflows/release-v1.yml
Latest v1 release action passed and published `1.73.2` after the latest changes to our `v1` branch. This PR removes the cron schedule for running our v1 releases.
```
.github/workflows/release-v1.yml
```
=> chore: remove cron schedule for v1 release action

packages/core/netlify.toml, packages/ibm-products-web-components/netlify.toml
Part of #6130 
Moved `netlify.toml` from root to `packages/core` to follow Netlify docs on monorepo setup with multiple sites. Since we currently have a `netlify.toml` at our project root, it'll always take precedence over the one in `packages/ibm-products-web-components`.
```
netlify.toml --> packages/core/netlify.toml
packages/ibm-products-web-components/netlify.toml
```
I checked against the docs Netlify has for configuring monorepos with multiple sites
https://docs.netlify.com/configure-builds/monorepos/#example-monorepo-setup
=> fix: move netlify config to `packages/core` to follow monorepo docs w/ multiple sites

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.tsx
Closes #6208 
The last column has a resizer that overflows on the right end, causing a horizontal scrollbar to appear. Previously, we used a non-resizable spacer column, which prevented this issue. Now that the spacer column is optional, disabling it allows the resizer in the last column to overflow, resulting in a horizontal scrollbar on the table. now we hide the overflow on last column.
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.tsx
storybook
=> refactor(Datagrid): fixes the resizer overflow scorllbar on last column

packages/ibm-products/src/components/EmptyStates/assets/NoDataIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/NotificationsIllustration.js
Closes #6178
moved internal fill css to fill attribute on paths in svg
packages/ibm-products/src/components/EmptyStates/assets/NotificationsIllustration.js
packages/ibm-products/src/components/EmptyStates/assets/NoDataIllustration.js
as u can see in repro if we remove the style tag from dom, the error is gone.
we are removing the style tag in this pr, which would solve the issue.
https://github.com/user-attachments/assets/c3ef37a8-41f2-4ba1-b2aa-3e017a94557d
=> fix: csp errors on 2 illustrations

config/stylelint-config-ibm-products/package.json
v1 release failed because `stylelint-config-ibm-products` version was out of sync with the tag version published on github from an earlier v2 publish that bumped the package from `0.0.35` to `0.0.36`, we've since deleted this package in our `main` branch so it should only be an issue in v1.
```
config/stylelint-config-ibm-products/package.json
```
Verified `0.0.36` already exists, https://github.com/carbon-design-system/ibm-products/releases/tag/stylelint-config-ibm-products%400.0.36
=> chore(v1): address mismatch stylelint config tag versions

packages/ibm-products-web-components/.storybook/preview-head.html
Includes plex via cdn within preview-head in storybook config, without this plex doesn't get loaded and is not used.
```
packages/ibm-products-web-components/.storybook/preview-head.html
```
Web component preview deploy
=> fix: use plex cdn to load custom font in wc storybook

packages/ibm-products/src/components/Datagrid/useFlexResize.js
Refs #5920, #5646.
Fix regression from 9bd307e4836d986383a0464e799834712f3904e0 where Datagrid keeps redrawing.  On our unit tests we get the exception:
> Too many re-renders. React limits the number of renders to prevent an infinite loop.
Added correct dependencies to useEffect().
Tested locally.
=> fix(Datagrid): useflexresize infinite redraw

packages/cdai/README.md, packages/cdai/telemetry.yml, packages/ibm-products/README.md, packages/ibm-products/telemetry.yml, packages/security/README.md, packages/security/telemetry.yml
FOR `V1` BRANCH ONLY
This PR updates the endpoint within each package's `telemetry.yml` file with the new stable endpoint for the collector. Also, this updates the wording used in the telemetry notice under each README.
For the following packages:
- CDAI
- Security
- IBM Products
Changed `telemetry.yml` endpoint to new stable endpoint, and updated wording under telemetry notice in each README
N/A
=> chore(telemetry): update endpoint and READMEs in v1

packages/ibm-products/src/components/Datagrid/index.ts, packages/ibm-products/src/components/Datagrid/types/index.ts
Refs #5257, #6115.
This fixes some (but not all) of the Typescript issues with Datagrid.
Specifically:
1. Export DataGridState type.  Maybe other types should be exported too. Note that in other places the G is not capitalized, but it is for the type.
2. onAllRowSelect() is (and should be) optional.
3. Presumably you aren't required to have a button on your empty state screens, so "emptyStateAction" should be optional.
4. "allRowsLabel" should be optional because you only need it if your table has a "Select all" checkbox.  And also because it's optional in PropTypes.
5. Properties like "page" are only necessary if your table has pagination, so make UsePaginationInstanceProps props optional.
6. UseFiltersInstanceProps defines a bunch of weird and required properties like "preFilteredRows", …
=> fix: datagrid typescript declarations

config/storybook-addon-carbon-theme/README.md, config/storybook-addon-carbon-theme/telemetry.yml, packages/ibm-products-styles/README.md, packages/ibm-products-styles/telemetry.yml, packages/ibm-products/README.md, packages/ibm-products/telemetry.yml
This PR updates the endpoint within each package's `telemetry.yml` file with the new stable endpoint for the collector. Also, this updates the wording used in the telemetry notice under each README.
For the following packages:
- IBM Products
- IBM Products Styles
- Storybook Addon Carbon Theme
Changed `telemetry.yml` endpoint to new stable endpoint, and updated wording under telemetry notice in each README
N/A
=> chore(telemetry): update endpoint and README

packages/cdai/telemetry.yml, packages/ibm-products/telemetry.yml, packages/security/telemetry.yml
Changed `https://www-api.ibm.com/ibm-telemetry/v1/telemetry` to `https://www-api.ibm.com/ibm-telemetry/v1/metrics`
N/A
=> fix(telemetry): updating URL in `v1`

packages/ibm-products/package.json, yarn.lock
Closes #6255
`carbon-components-react` lists `7.70.0` instead of `7.60.0` in one spot, which is leading to incorrect peer dependencies. Likely a typo while updating to latest versions.
Downgrade to a the latest version that exists.
CI
=> fix: v1 version mismatch

packages/ibm-products-styles/src/components/Datagrid/styles/_datagrid.scss
Closes #6254
adds missing header hover background style from v1 to v2. this was removed around 2 years ago.
i tried to find any relevant history if it was removed intentionally, but couldn't find any, so i am guessing it was an error.
storybook
=> fix(datagrid): adds missing header hover styles in v2

packages/ibm-products-web-components/src/components/side-panel/side-panel.ts
Closes #6219
Web component SidePanel: always slideIn even when slideIn is false
Updated the `side-panel.ts` file to check if `slideIn` is enabled or not before applying styles.
Storybook
=> fix(SidePanel web components): SlideIn option issue

packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js
Closes #5925 
Add support for `autoAlign` in RowResize popover in datagrid batch actions.
Pass `autoAlign ={true} `to `<RowSizeDropdown` component from DatagridAction.
<RowSizeDropdown will now accept autoAlign prop and passdown to popover
local
=> fix(Datagrid): add support for autoAlign in row resize popover

packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.test.js, packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.tsx
Closes #6264
Increased code coverage
packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.test.js
packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.tsx
=> test(InterstitialScreen): increase code coverage

packages/ibm-products/src/components/CreateFullPage/CreateFullPage.stories.jsx, packages/ibm-products/src/components/CreateFullPage/CreateFullPage.test.js, packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx, packages/ibm-products/src/components/CreateFullPage/CreateFullPageStep.tsx, packages/ibm-products/src/components/CreateInfluencer/CreateInfluencer.tsx
Closes #6030
Expose the `onChange` property of `ProgressIndicator` in the `CreateInfluencer` component.
Expose the `onPrevious` property for the `CreateFullPageStep` component.
Props updated
<table>
<thead>
<th>Component</th>
<th>Prop</th>
<th>Description</th>
</thead>
<tr>
<td>CreateFullPage</td>
<td>onClickInfluencerStep</td>
<td>Pass <i>onClickInfluencerStep</i> prop through the <i>CreateFullPage</i> component.</td>
</tr>
<tr>
<td>CreateInfluencer</td>
<td>onClickStep</td>
<td>Receiving the <i>onClickStep</i> prop and passing it into the <i>ProgressIndicator</i>'s <i>onChange</i></td>
</tr>
<tr>
<td>CreateFullPageStep</td>
<td>onPrevious</td>
<td>New prop exposed</td>
</tr>
</table>
Storybook
`yarn test`
=> feat: expose onChange and onPrevious for CreateFullPage

packages/ibm-products/src/components/FeatureFlags/FeatureFlags.test.js
Closes #6235 
removes some unnecessary usage of setting a prop explicitly to false.
i also wanted to point something out in regards to the test that was removed. this approach doesn't really work for unknown flags. consider the following:
```
function TestComponent() {
const featureFlags = useFeatureFlags();
const a = useFeatureFlag('a');
const b = useFeatureFlag('b');
checkFlags({
a: featureFlags.enabled('a'),
b: featureFlags.enabled('b'),
});
checkFlag({
a,
b,
});
return null;
}
const { rerender } = render(
<FeatureFlags a>
<TestComponent />
</FeatureFlags>
);
```
this will throw an error. `useFeatureFlag` throws an error when the props don't match the hooks. in the above example `b` is set in the hook, but it's not set as a prop to `FeatureFlags`. this causes an `flag b not found` …
=> fix: remove unnecessary props in feature flag tests

packages/ibm-products/src/components/UserAvatar/UserAvatar.stories.jsx, packages/ibm-products/src/components/UserAvatar/_storybook-styles.scss
Contributes to #6168
One last followup task to show theme handling in user avatar story.
@AlexanderMelox @anamikaanu96 Marking this as a draft first — do we think this demonstrates the theme better?
Follow approach from Carbon [`useTheme`](https://react.carbondesignsystem.com/?path=/story/components-theme--use-theme) for better demonstration of how user avatar responds to the themes.
Storybook and CI checks
=> chore: add theme to user avatar default story

packages/ibm-products-styles/src/components/EditFullPage/_index.scss, packages/ibm-products-styles/src/components/EditTearsheet/_index.scss, packages/ibm-products-styles/src/components/EditTearsheetNarrow/_index.scss, packages/ibm-products-styles/src/components/EditUpdateCards/_edit-update-cards.scss, packages/ibm-products/src/components/Carousel/_storybook-styles.scss, packages/ibm-products/src/components/SteppedAnimatedMedia/_index.scss
Seeing deprecation warnings when building my SASS
Warning: 3 repetitive deprecation warnings omitted.
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import
╷
8 │ @import './edit-tearsheet';
│         ^^^^^^^^^^^^^^^^^^
╵
node_modules/@carbon/ibm-products/scss/components/EditTearsheet/_index.scss 8:9  @use
node_modules/@carbon/ibm-products/scss/components/_index.scss 56:1               @forward
node_modules/@carbon/ibm-products/scss/index-without-carbon.scss 12:1            @use
src/index.scss 4:1
=> fix: these at imports should not exist

packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx
Closes #6266
focus issue fixed on onBlur default behaviour
=> fix(EditInPlace): focus issue on onBlur default behaviour

.github/workflows/ci.yml
This change should allow for the expected PR checks to run against release branches (ie `release/2.*`).
```
```
I can test in a follow up PR against `release/2.54.0`
=> chore: update release branch pattern in ci.yml

packages/ibm-products/src/components/AddSelect/AddSelect.tsx, packages/ibm-products/src/components/AddSelect/AddSelectBody.tsx, packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx, packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.tsx, packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
Closes #6345 
Change the `portalTarget` type from `ReactNode` to `HTMLElement`
Changed type `ReactNode` to `HTMLElement`
`yarn avt`
`yarn test`
Storybook
=> fix(tearsheet): address portalTarget type

.github/workflows/ci.yml, .github/workflows/received-pr-review.yml
Closes #6381 
Upgrades the `upload-artifact` action used in `ci.yml` and PR review workflow, support for v3 will be removed in Dec 2024.
```
.github/workflows/received-pr-review.yml
```
Compared usage for playwright upload with Core
=> chore: bump upload-artifact action to v4

.eslintignore, config/jest-config-ibm-cloud-cognitive/package.json, packages/core/package.json, packages/ibm-products-styles/package.json, packages/ibm-products-web-components/package.json, packages/ibm-products/package.json, yarn.lock
Closes #6403 and contributes to #6374 
- Update sass from 1.77.2 to 1.80.6 (we’re a few minors behind anyway)
- Update cross-spawn via resolutions
- Add `**/coverage/**` to `.eslintignore`
CI checks — `yarn ci:check:lint` for SASS updates
=> chore: update sass and cross-spawn

packages/ibm-products/src/components/APIKeyModal/APIKeyModal.stories.jsx, packages/ibm-products/src/components/APIKeyModal/APIKeyModal.test.js, packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx, packages/ibm-products/src/components/APIKeyModal/APIKeyModal.types.ts
Closes #6246 
Implement new property `launcherButtonRef`
`yarn test`
`yarn avt`
=> fix(APIKeyModal): implement focus return to generate button

packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemOption/ItemOption.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemOption/ItemOptionForValueField.tsx, packages/ibm-products/src/components/ConditionBuilder/assets/SampleData.js
Closes #6402 
- Cannot type in to the search box to filter the list.
- Dropdown auto closes after every time a checkbox is selected
- Corrected a corrupt  data for a storybook story
- Removed preventDefault from search input. This will give carbon search input behaviour , which is to clear any search text on Escape keypress rather than closing the popover.
- StopPropogation on checkbox icon click to prevent closing
local
=> fix(conditionBuilder): address issues inside conditionBuilder popover

e2e/components/EmptyState/EmptyStateV2-test.avt.e2e.js, packages/ibm-products/src/components/EmptyStates/EmptyStateV2.stories.jsx, packages/ibm-products/src/components/EmptyStates/EmptyStateV2.tsx
Closes #6324 
note to self: update this PR or code to replace the deprecation notice block in `block` with the new `deprecationNotice` prop that will be added to the `StoryDocsPage` component here https://github.com/carbon-design-system/ibm-products/pull/6419/files#diff-d1d59f3ffba9e6226e5a00cedc4dc1cf7264ae4926deb6bfd27e902febf070eeR144
=> chore: deprecate empty state v2

packages/ibm-products-web-components/src/components/tearsheet/tearsheet.stories.ts
Closes #6305
Cancel button not working as expected in Tearsheet web components. 
The issue was with story and not component.
Added click event handler for cancel button just as in react Tearsheet.
Storybook
=> fix(tearsheet web components): cancel button not working

packages/ibm-products/src/components/APIKeyModal/APIKeyModal.tsx, packages/ibm-products/src/components/AboutModal/AboutModal.tsx, packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx, packages/ibm-products/src/global/js/hooks/useFocus.js
Closes #6420 
Refactored the common useEffect logic into a single `claimFocus` common method
`yarn avt`
`yarn test`
storybook
=> refactor(useFocus): refactor repeated useEffect code

.github/workflows/update.yml
Closes #6497 
Uses same token approach as Core to open PRs so that it is opened by one of the Carbon github bots/apps. I also removed the slack integration piece since it doesn't work and wanted to do some cleanup.
```
```
Haven't been able to yet! But the same `APP_ID` and `APP_PRIVATE_KEY` secrets have been added to our repo that are also used in core and those are used to generate the token used by `peter-evans/create-pull-request`.
=> build: update dependency action to use carbon bot/app token

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/PageHeader/_page-header.scss
Closes #6415 
fixes menu button overflow issue in firefox in small screen
packages/ibm-products-styles/src/components/PageHeader/_page-header.scss
storybook, firefox
=> fix(pageHeader): menu button overflow issue on small screens

.github/workflows/update.yml
This will fix a bug in the recent changes to the dependency upgrade action so that the non-Carbon dependencies have an access token to open a PR.
```
```
For additional context, see [here](https://github.com/carbon-design-system/ibm-products/actions/runs/12147196556). You can see that the `carbon` job passed and a PR was opened successfully by the Carbon automation app/bot but the second job failed.
=> fix: add generate token step for the dependency upgrade job

e2e/components/TagSet/TagSet-test.avt.e2e.js, e2e/test-utils/simulateKeyPress.ts
Closes #6473
- Test latest accessibility-checker rulesets on various states of tag set
- Add tests for open and close states in popover/tooltip
- Add tests for open and close states in tag modal
- Review any additional states we may need to capture or add tests for : covered remove tags functionality and search functionality in the modal.
- Add keyboard navigation tests to AVT
yarn avt
=> test(Tagset): add avt tests for complex states

.github/workflows/process-pr-review-data.yml
Fixes another bug I found in the PR review label action. Because we include `setup-node` and specify a `cache` configuration, the `Post Setup Node.js` job fails because it's looking for a `.yarn/cache` directory, however since this action doesn't depend on any dependencies being installed the `cache` directory doesn't exist. I think it's safe for us to just remove the `setup-node` step.
[Example of failing job](https://github.com/carbon-design-system/ibm-products/actions/runs/12237876420/job/34134624242)
Good news is that the action looks to be working now, outside of this one issue!
```
.github/workflows/process-pr-review-data.yml
```
Manually verified in the action that we don't need to install dependencies, it's all based on results from various GH api requests.
=> fix(actions): process pr review action, remove `setup-node`

.github/workflows/process-pr-review-data.yml
I removed the checkout step as well as `setup-node` in my previous PR, this is causing [issues](https://github.com/carbon-design-system/ibm-products/actions/runs/12257930292/job/34196535636) with getting the actual action to run. Adding it back in this PR 😄 
```
.github/workflows/process-pr-review-data.yml
```
=> fix(actions): add checkout step back

packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.tsx
Closes #6457 
Initial state issue fix.
Set the initial state to root state and clear initial state on manually deleting all conditions
local
=> fix(Condition builder): initial state getting reset on re-rendering

.github/workflows/ci.yml
Run percy from netlify build script to avoid using hardcoded percy token directly in `.github/workflows/ci.yml`.
```
```
Verified snapshots were still being taken from netlify logs.
=> build: remove `vrt` from ci.yml and run directly from netlify build script

packages/ibm-products/src/components/CoachmarkOverlayElements/CoachmarkOverlayElements.test.js, packages/ibm-products/src/components/CoachmarkOverlayElements/CoachmarkOverlayElements.tsx
Closes https://github.com/carbon-design-system/ibm-products/issues/5596
This PR:
- Adds callbacks when clicking on Next and Previous buttons.
- Allows to set the current progression.
Add three optional properties to CoachmarkOverlayElements:
- onNextCallback
- onBackCallback
- currentStep
I modified the story book as follows:
Then manually checked that:
- next and back callbacks correctly logged into the console
- the progression was correctly set.
=> feat(CoachmarkOverlayElements): Add next/back callbacks and currentStep properties

packages/ibm-products/src/components/DragAndDrop/DragAndDrop.mdx
Small fix to update incorrect page title for Drag and drop example.
```
packages/ibm-products/src/components/DragAndDrop/DragAndDrop.mdx
```
Storybook
=> docs(DragAndDrop): fix docs title

packages/ibm-products/src/components/EmptyStates/assets/ErrorIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/NoDataIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/NoTagsIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/NotFoundIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/NotificationsIllustration.js, packages/ibm-products/src/components/EmptyStates/assets/UnauthorizedIllustration.js, packages/ibm-products/src/global/js/utils/useId.js
Reopened on behalf of @sean-anderson-ibm
> Closes #6606 and #6607 
> 
> Fixes `useId` use in react 17 and below, due to `useId` only being in react 18 and above. Falls back to previous method of id generation for react versions <18.
> 
> #### What did you change?
> I added a util function to change how `useId` works based on react version support and updated references to it
> #### How did you test and verify your work?
> I linked the build package to a repo using react 16, and verified the issue was no longer present.
=> fix(EmptyState): added useId handling for older react version

packages/ibm-products/package.json, packages/ibm-products/src/components/FilterSummary/FilterSummary.tsx, yarn.lock
Closes #6677 
**Attention:** This PR reverts the changes in #6462 
We reverted back to `6.5.1` since some consumers are not on React v18 and want to support v17 of React.
Ran storybook and checked components that use framer-motion
=> chore: downgrade framer motion to `6.5.1` to support React v17

packages/ibm-products-web-components/package.json, packages/ibm-products-web-components/tasks/build.js, packages/ibm-products-web-components/tools/svg-result-carbon-icon-loader.js, packages/ibm-products-web-components/tools/svg-result-carbon-icon.js, packages/ibm-products-web-components/tools/vite-svg-result-carbon-icon-loader.ts, packages/ibm-products-web-components/vite.config.ts, yarn.lock
Closes #6674 
This PR addresses the build issues described in #6674. The issue stemmed from incorrect glob patterns that are responsible for compiling and transforming icons, because the glob was incorrect we always ended up with an empty array for the icon paths, meaning that we never transformed any of the icons as expected.
```
packages/ibm-products-web-components/package.json
packages/ibm-products-web-components/tasks/build.js
packages/ibm-products-web-components/tools/svg-result-carbon-icon-loader.js
packages/ibm-products-web-components/tools/svg-result-carbon-icon.js
packages/ibm-products-web-components/tools/vite-svg-result-carbon-icon-loader.ts
packages/ibm-products-web-components/vite.config.ts
yarn.lock
```
I tested this by including an example app and importing the side panel …
=> fix(web-components): addresses issues in wc build script

packages/ibm-products-styles/src/components/ConditionBuilder/styles/_conditionBuilderItem.scss
Closes #6436 
property text in each condition should be bold
style correction
local
=> fix(conditionbuilder): property text in each condition should be bold

config/jest-config-ibm-cloud-cognitive/index.js
We'll likely want to be writing more tests in TypeScript moving forward, this PR updates our jest config to run test files with `ts` or `tsx` extensions.
```
config/jest-config-ibm-cloud-cognitive/index.js
```
Existing tests still run as expected
=> refactor(jest): support ts/tsx test files

packages/ibm-products/src/components/Datagrid/useOnRowClick.ts
Closes #6547 
Added a null check for `toggleRowSelected` callback since for some rows objects, `toggleRowSelected` is not present.
local
=> fix(Datagrid): onRowClick results in toggleRow.toggleRowSelected is not a function error in console

packages/ibm-products/src/components/BigNumbers/BigNumbers.test.js
Closes #6654
Increased code coverage for big numbers
=> test(BigNumbers): increase code coverage

packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.tsx
Closes #6444
handle step change on carousal scroll by determining current step from scroll percent and step size.
Eg: when there are 4 steps, scroll percent will be .25, .5, .75,1 respectively and stepsize will be .25
local
=> fix: step Indicator and Buttons Not Updating on Forward Scroll in InterstitialScreen 

packages/ibm-products-web-components/package.json, packages/ibm-products-web-components/tasks/build.js, yarn.lock
Closes #6736 
In order for `@rollup/plugin-typescript` to work correctly we need `tslib` as a dev dependency, turns out we just hadn't properly configured the rollup TS plugin. I also downgraded `eslint` until the rest of our monorepo is able to use v9.
```
packages/ibm-products-web-components/package.json
yarn.lock
```
I was able to confirm these changes by confirming the correct import of `__decorate` from the `tslib` library in the built versions of `side-panel` and `tearsheet` by running `yarn build` from `packages/ibm-products-web-components` and inspecting the import of `__decorate` from `tslib` directly (previously was importing from `../../node_modules/tslib` rather than from `tslib`).
=> build(web-components): move `tslib` to dev dependency

packages/ibm-products/src/components/CoachmarkFixed/CoachmarkFixed.tsx, packages/ibm-products/src/components/Datagrid/Datagrid.test.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js, packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx, packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx, packages/ibm-products/src/components/SidePanel/SidePanel.tsx, packages/ibm-products/src/components/WebTerminal/WebTerminal.tsx, packages/ibm-products/src/global/js/hooks/index.js, packages/ibm-products/src/global/js/hooks/usePrefersReducedMotion.js
Closes #6751 
This PR removes usage of `useReducedMotion` from `framer-motion` and replaces it with our own reduced motion hook that we have within our own library (`usePrefersReducedMotion`).
```
packages/ibm-products/src/components/CoachmarkFixed/CoachmarkFixed.tsx
packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx
packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx
packages/ibm-products/src/components/SidePanel/SidePanel.tsx
packages/ibm-products/src/components/WebTerminal/WebTerminal.tsx
packages/ibm-products/src/global/js/hooks/index.js
packages/ibm-products/src/global/js/hooks/usePrefersReducedMotion.js
```
Verified same behavior in storybook with reduced …
=> refactor(reduced-motion): use our own `usePrefersReducedMotion` hook

.github/workflows/triage-labeled-issues.yml
Closes #6696
Uses `tibdex/github-app-token` to generate a new token whenever this action is run, this helps us to avoid expired tokens in actions.
```
.github/workflows/triage-labeled-issues.yml
```
Verified `tibdex/github-app-token` usage across other actions
=> fix(actions): gen new token inside `triage-labeled-issues` action

e2e/components/NotificationsPanel/NotificationsPanel-test.avt.e2e.js, packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.stories.jsx
Closes #6522
Recategorize NotificationsPanel as a component in Storybook to match the website.
Also required an override to the usage docs because of a minor difference in website v. component naming — website uses “notification panel” whereas the component is already named “Notification**s**Panel.”
- Move to Components
- Update e2e links
- Fix link to usage docs
`yarn avt /NotificationPanel/`
`yarn ci-check`
Locally verify URLs.
=> chore: move Notification panel to Components in Storybook

packages/ibm-products/src/components/AddSelect/AddSelectBody.test.js, packages/ibm-products/src/components/AddSelect/AddSelectRow.js
Closes #6653 
increases coverage for `AddSelectColumn` and the `useFocus` hook in `AddSelect`
=> chore: increase addselect coverage

packages/ibm-products/package.json, packages/ibm-products/src/components/ActionBar/ActionBar.tsx, packages/ibm-products/src/components/CoachmarkStack/CoachmarkStackHome.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBlock/ConditionBlock.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.types.ts, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItem.tsx, packages/ibm-products/src/components/EditTearsheet/EditTearsheet.tsx, packages/ibm-products/src/components/PageHeader/PageHeader.tsx, packages/ibm-products/src/components/TagSet/TagSetOverflow.tsx, packages/ibm-products/src/custom-typings/index.d.ts, yarn.lock
I noticed that `framer-motion` snuck past us in the dev dependency PR. We should merge this before our code freeze to prevent it from reaching an `rc` publish.
```
yarn.lock
```
=> fix: revert framer motion version

.stylelintrc.js, packages/ibm-products-styles/src/components/NotificationsPanel/_notifications-panel.scss
Closes #6802 
We merged all css logical properties PR so now we can enable the linter to give us errors from now on.
**PR List**
- https://github.com/carbon-design-system/ibm-products/pull/6746
- https://github.com/carbon-design-system/ibm-products/pull/6768
- https://github.com/carbon-design-system/ibm-products/pull/6774
- https://github.com/carbon-design-system/ibm-products/pull/6777
- https://github.com/carbon-design-system/ibm-products/pull/6746
- Turned CSS logical property linter to true
I added physical properties and it gave errors, also using `yarn lint:styles` should fix most of the errors
=> chore: enables css logical property rule

packages/ibm-products/src/components/Tearsheet/Tearsheet.tsx, packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.tsx
Refs #4687, #4751.
Fix missing typescript declaration for launcherButtonRef. It was in the base class (TearsheetShell), but
not Tearsheet nor TearsheetNarrow.
(It was in Tearsheet and TearsheetNarrow's PropTypes, but not the typescript declaration.)
Added Typescript declaration for launcherButtonRef.
Tested locally.
=> fix(Tearsheet): missing launcherbuttonref declaration

packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItem.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemDate/ConditionBuilderItemDate.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemOption/ItemOption.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemOption/ItemOptionForValueField.tsx, packages/ibm-products/src/components/ConditionBuilder/utils/handleKeyboardEvents.js, packages/ibm-products/src/components/ConditionBuilder/utils/util.js
Closes #6788 
- For search box inside popover, clear the text inside the search box on escape key press if any search text is present. Close the popover on escape only if search box is empty. If some search text is present, user has to press escape twice to close the popover.
- Close the multiselect popover when enter is pressed . Space can be used to toggle between the selection. Implement this on every other input types. On a textarea input, press enter will close popover with entered value. Shift + enter will enable user to move to new line inside the text area.
- Use carbon Heading component as popover heading.
local storybook
=> fix(Condition Builder): accessibility violations part 1

packages/core/.storybook/manager.js, packages/core/.storybook/preview.js, packages/core/.storybook/theme.js
Closes #6822
Changed storybook font to IBM Plex sans. 
packages/core/.storybook/manager.js
packages/core/.storybook/theme.js
packages/core/.storybook/preview.js
=> fix(storybook): add fontBase

config/jest-config-ibm-cloud-cognitive/setup/matchers/toHaveNoACViolations.js, packages/ibm-products-styles/src/components/FullPageError/_full-page-error.scss, packages/ibm-products/src/components/FullPageError/FullPageError.stories.jsx, playwright.config.js
Closes #6365 
removes target spacing sufficient from playwright exclusions
fixes fullPageError report on target spacing sufficient
config/jest-config-ibm-cloud-cognitive/setup/matchers/toHaveNoACViolations.js
packages/ibm-products-styles/src/components/FullPageError/_full-page-error.scss
packages/ibm-products/src/components/FullPageError/FullPageError.stories.jsx
playwright.config.js
avt checks
=> chore: remove target spacing sufficient from playwright exclusions

e2e/components/OptionsTile/OptionsTile-test.avt.e2e.js, packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx
Closes #6529 
adds keyboard navigation avt test for `OptionsTile`. tests the correct order of focus and that the content is displayed when space is used to toggle the details accordion.
=> test: add keyboard nav avt for optionstile

packages/ibm-products-styles/src/components/GetStartedCard/_get-started-card.scss
Closes #6949
SASS raises deprecation warnings on these two lines introduced in v2.60.0 (for details, see original issue description):
`margin-block: to-rem(-50px) -$spacing-09;`
`margin-block: to-rem(-56px) -$spacing-09;`
I change this to what SASS will currently compiles it to (according to Webpack log), namely:
`margin-block: to-rem(-50px) - $spacing-09;`
`margin-block: to-rem(-56px) - $spacing-09;`
1. I look at the storybook for GetStrtedCard for the one with Pictogram and the one with Sequence in my localhost environment, and then I compare it with the deployed Storybook for Carbon v2.60.0. I did not spot any difference. My change is the one SASS currently compiles into, so if it is incorrect, then the original SASS code doesn't do what it is supposed to do anyway.
2. I check the log …
=> fix(GetStartedCard): #6949 - 2 Sass deprecation warnings

packages/ibm-products-styles/src/components/Tearsheet/_tearsheet.scss, packages/ibm-products/src/components/Tearsheet/Tearsheet.docs-page.js, packages/ibm-products/src/components/Tearsheet/Tearsheet.stories.jsx
Closes #6698 
**Issue**
The `Tearsheet` stylesheet included a CSS fix for form fields that were set to `readOnly`. This was an inherited issue from the parent `Modal` component. 
**Solution**
It seems the `Modal` styling has been fixed, and the existing CSS in the `Tearsheet` broke those changes. Removing the old fix has restored the correct styling for `readOnly` form fields.
```
packages/ibm-products-styles/src/components/Tearsheet/_tearsheet.scss
packages/ibm-products/src/components/Tearsheet/Tearsheet.stories.jsx
packages/ibm-products/src/components/Tearsheet/Tearsheet.docs-page.js
```
- Added story `firstElementReadOnly`: [Direct Storybook link](https://deploy-preview-6961--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet--tearsheet-read-only-input-fi …
=> fix(Tearsheet): undo previous "readonly" css fix

packages/ibm-products/package.json
Closes #6880
Looks like adding generate  to the telemetry-config script will fix the issue .
Updated command:
"telemetry-config": "ibmtelemetry-config  generate --id xxxx --endpoint xxxx --files ./src/components/**/*.(tsx|js|jsx)",
yarn telemetry-config
=> build: update telemetry-config script to include generate keyword

packages/ibm-products/src/global/js/hooks/usePresence.ts
Closes #7032
Adds better docs to `usePresence` since it will likely be used more now for unmounting components with animations.
```
packages/ibm-products/src/global/js/hooks/usePresence.ts
```
Docs update only
=> docs(usePresence): add more docs around hook usage

.gitignore, packages/ibm-products-web-components/package.json, packages/ibm-products-web-components/tasks/build.js, yarn.lock
Closes https://github.com/carbon-design-system/carbon/issues/18761
creates a new `es-custom` folder which will generate our components with `cds-custom-` prefix instead of `cds-`
**New**
- bump `@carbon/web-components` to latest version (v2.25.0) that includes the `es-custom` build folder
- updated build to add a post build which copies the generates `es` files and then does a find and replace to swap out all instances of `cds` with `cds-custom`
- add `es-custom` to gitignore
run yarn build and see if `es-custom` folder is generated in web components and if the components have the correct prefix
**note**
- User's will need to import two different style files. One with
```
@use '@carbon/styles' with (
$prefix: 'cds-custom' // Default prefix
);
```
and the other will be just 
```
@use …
```
=> feat(custom-element): new es build module

cspell.json, packages/ibm-products-web-components/src/components/user-avatar/user-avatar.mdx, packages/ibm-products-web-components/src/components/user-avatar/user-avatar.scss, packages/ibm-products-web-components/src/components/user-avatar/user-avatar.stories.ts, packages/ibm-products-web-components/src/components/user-avatar/user-avatar.ts
closes #7100 
RenderIcon prop changed to slot.
Based on the [suggestion](https://github.com/carbon-design-system/carbon/pull/18703#discussion_r1977846565) in Menu(carbon). Same logic applies here.
packages/ibm-products-web-components/src/components/user-avatar/user-avatar.stories.ts
packages/ibm-products-web-components/src/components/user-avatar/user-avatar.ts
cspell.json
=> fix(useravatar): renderIcon prop changed to slot

docs/guides/publishing-releases.md
Add links to Web Components package in our release guide.
- Add links to WC package on npm for prerelease, subsequent release, and stable release
Markdown preview 😛
=> chore: add WC package to release docs

packages/ibm-products/src/components/CreateFullPage/CreateFullPageStep.tsx, packages/ibm-products/src/components/CreateInfluencer/CreateInfluencer.tsx, packages/ibm-products/src/components/SimpleHeader/SimpleHeader.js
Closes #6815.
The top heading (assuming it's specified) is H1, so the subheadings should be H2, not H3, H5, or H6. 
Use `Section` and `Heading` for the heading subheadings, so they come out at the right level.
Could have hardcoded the headings to H2, but this way seems less brittle.
Also, change the subtitle to `<p>` as it is really more of a description than another heading.
Based on some of the code from #6816.
Tested from Storybook.
Note: depends on https://github.com/carbon-design-system/ibm-products/pull/7161.
=> fix(CreateFullPage): use correct heading levels

packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx
Closes #7162.
Make `OptionsTile` use heading levels in line with its hierarchy in the document, assuming the document was written correctly using `Section` and `Heading`.
Both for the main heading rendered by `OptionsTile` itself as well as headings in the content passed to `OptionsTile`.
Use `Section` and `Heading` instead of `<div>` and `<h6>`.
Based on code from #6816 but without the ability to override the level.  See also https://github.com/carbon-design-system/carbon/pull/18871, which is the same thing for TableContainer.
Tested locally.
Note: depends on #7161.
=> fix(OptionsTile): use correct heading levels

packages/ibm-products/src/components/Datagrid/useSortableColumns.tsx
Closes #6957 
sets default min width to 50, also prioritizes min width thats passed through column definition
packages/ibm-products/src/components/Datagrid/useSortableColumns.tsx
added disableSortBy for a column in sortable columns story to cross verify
=> fix: set minWidth to 50 instead of 0, prioritize column.minWidth

packages/ibm-products/src/components/EmptyStates/EmptyState.tsx, packages/ibm-products/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.tsx, packages/ibm-products/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.tsx, packages/ibm-products/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.tsx, packages/ibm-products/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.tsx, packages/ibm-products/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.tsx, packages/ibm-products/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.tsx
Closes #7011 
Small refactor to extend `ButtonProps` for empty state action (button).
Also reuse `EmptyStatePresetProps` for common props across the empty state presets.
- Extend Carbon `ButtonProps` for `EmptyStateAction`.
- Add `EmptyStatePresetProps` to reuse `EmptyStateProps` with `illustration` omitted since these are set at each preset.
Tests and CI pass
=> refactor: EmptyState TS to extend Carbon `ButtonProps`

packages/ibm-products/src/components/Tearsheet/Tearsheet.stories.jsx, packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
Fixes #7164.
As per https://www.w3.org/WAI/tutorials/page-structure/headings/, the headings inside tearsheet content must have a level relative to the tearsheet's own heading.   This PR makes that easy.
In other words, applications can write like this and the heading levels will make sense when it renders:
```jsx
<Tearsheet
...
description="This is a description for the tearsheet, providing an opportunity to   describe the flow over a couple of lines in the header of the tearsheet."
influencer={
<Section>
<Heading>Heading in influencer 1</Heading>
<p>...</p>
</Section>
<Section>
<Heading>Heading in influencer 2</Heading>
<p>...</p>
</Section>
}
...
>
<Section>
<Heading>Content Heading 1</Heading>
<p>...</p>
</Section>
<Section>
<Heading>Content heading 2</Heading>
<p>...</p>
</Section> …
```
=> fix(tearsheet): fix heading levels of content

packages/ibm-products-web-components/README.md, packages/ibm-products-web-components/package.json, packages/ibm-products-web-components/telemetry.yml, packages/ibm-products/package.json, packages/ibm-products/telemetry.yml, yarn.lock
Closes #7103 
Instruments the WC package with IBM Telemetry.
* Adds the Telemetry npm dependency, `telemetry.yml` config file with the newly issued project ID, README notice, postinstall script and `package.json` change so the `telemetry.yml` is included in the package's dist
* Updates the React packages Telemetry configuration script to include the stable collection URL
* Ran that to ensure the React prop and prop values in the React package config is up to date
N/A
=> chore: onboard wc package with telemetry

packages/ibm-products-web-components/examples/about-modal/package.json, packages/ibm-products-web-components/examples/full-page-error/package.json, packages/ibm-products-web-components/examples/side-panel/package.json, packages/ibm-products-web-components/examples/tearsheet/package.json, packages/ibm-products-web-components/examples/user-avatar/package.json
Closes #7296
Bump vite version in all Web Component examples.
Update `package.json` for each WC example
=> chore: bump vite in web component examples

.github/workflows/automerge.yml
Closes #6884 and #7314
Update `automerge.yml` to run on `ubuntu-latest`.
This was the only action not yet on `ubuntu-latest`.
`automerge.yml`
=> chore: update automerge action to ubuntu-latest

package.json, packages/ibm-products/src/components/CreateFullPage/CreateFullPage.test.js, packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx, yarn.lock
Closes #7101 
This feature enhancements allows null to be a viable step and then filtered out to reflect the progress indicator step correctly
- Added a test to test the functionality
- Storybook
=> feat(create-full-page): null as a viable step

packages/ibm-products/src/global/js/hooks/useResizeObserver.js
Closes #5729 
Adds an optional chain to remove null error
`packages/ibm-products/src/global/js/hooks/useResizeObserver.js`
=> fix(use-resize-observer): adds optional chain

packages/ibm-products-styles/src/components/NotificationsPanel/_notifications-panel.scss
Closes #7169 
Accommodate change in sticky header spacing when Do Not Disturb not included in the notifications panel header.
This definitely requires VRT but ideally should not change the snapshots. 🤞
- Move header block-end padding to Do Not Disturb toggle for better visual balance when it’s removed
- Adjust default sticky position and use `:has()` selector to adjust when the do not disturb _is_ included in the notification header
You can test this by doing either of the following:
- Use Inspect to remove the entire do not disturb toggle
- Comment out `onDoNotDisturbChange: action('Toggled "Do not disturb"')` from NotificationsPanel.stories default props
=> fix(NotificationsPanel): adjust time section labels spacing

packages/ibm-products/src/components/ConditionBuilder/ConditionBlock/ConditionBlock.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.stories.jsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.types.ts, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderAdd/ConditionBuilderAdd.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContext/ConditionBuilderProvider.tsx
Closes #7130 
This add support for a new callback prop 'onAddItem' that will be called before adding any condition , subgroup or group. 
User can prevent add if they return `{preventAdd : true}`
Added a new callback prop
```
onAddItem?: (
addItemType: 'add-condition' | 'add-subgroup' | 'add-group',
rootState: ConditionBuilderState,
group?: ConditionGroup
) => { preventAdd: boolean };
```
=> feat(conditionBuilder): add pre add callback before adding

packages/ibm-products/src/components/OptionsTile/OptionsTile.tsx
Refs #7162
It's important for the `OptionsTile` children to be inside the` <Section>`, in case they have their own subheadings.
Moved the Section to be wrapped around everything instead of just wrapped around the title.
Storybook
=> fix(optionstile): section needs to wrap around children

packages/ibm-products-web-components/examples/about-modal/package.json, packages/ibm-products-web-components/examples/full-page-error/package.json
Closes #7390 
Update `ibm-products-web-components` package version in About Modal and Full page error examples
Updated version  to `0.14.0-rc.0` in both examples             
In the existing example the problem was solved by forking the example and updating the version to `0.14.0-rc.0`.
Te same is done here.
[About Modal Stackblitz Example from the PR Branch](https://stackblitz.com/github/sangeethababu9223/ibm-products/tree/fix/stackblitz-example-version-update/packages/ibm-products-web-components/examples/about-modal?file=src%2Findex.js)
[Full Page Error Stackblitz Example from the PR branch](https://stackblitz.com/github/sangeethababu9223/ibm-products/tree/fix/stackblitz-example-version-update/packages/ibm-products-web-components/examples/full-page-error?file=src%2Findex.js)
=> fix(stackblitz examples): updated version in about modal and fullpage

packages/ibm-products/src/components/SidePanel/SidePanel.test.js, packages/ibm-products/src/components/SidePanel/SidePanel.tsx
Refs #7174 and 9bc927a75f0a3ecc90076fd270b52aa98c66d22a.
Leverage IconButton to display back button.
Also:
- Remove redundant title and aria-label from close button.
- Update tests to find buttons semantically, rather than by CSS class.
- Fix back button tooltip.  It wasn't showing up before.
Jest and storybook.
=> chore(sidepanel): leverage IconButton

e2e/components/ExpressiveCard/ExpressiveCard-test.avt.e2e.js, packages/ibm-products/src/components/Card/Card.test.js, packages/ibm-products/src/components/Card/Card.tsx, packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.tsx, packages/ibm-products/src/components/ExpressiveCard/ExpressiveCard.stories.jsx, packages/ibm-products/src/components/ExpressiveCard/ExpressiveCard.tsx, packages/ibm-products/src/components/ProductiveCard/ProductiveCard.stories.jsx, packages/ibm-products/src/components/ProductiveCard/ProductiveCard.tsx
Closes https://github.com/carbon-design-system/ibm-products/issues/3831
The Card component is used by `ExpressiveCard`, `ProductiveCard` and `GetStartedCard`. The `ExpressiveCard` and `ProductiveCard` exposes `actionIcon href`. In this PR, `actionIcon href` has been deprecated and a new `link` object has been introduced.
Note 1: There are other properties: `primaryButtonHref` and `secondaryButtonHref`, where the href string can be replaced with a link object. I haven't included those changes in this PR as these changes are not in the scope of [3831](https://github.com/carbon-design-system/ibm-products/issues/3831).
Note 2: The component `EditUpdateCards` uses `ProductiveCard`, but since `EditUpdateCards` is deprecated, I haven't added new storybook for it. I have updated the type so that …
=> feat: ExpressiveCard should have the ability to open a link in a new window

packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.test.js, packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.tsx
Closes #7319 
This feature enhancements allows null to be a viable step and then filtered out to reflect the progress indicator step correctly.
- Added a test to test the functionality
- Storybook
=> fix(CreateTearsheet): added code fix and test

.github/renovate.json5
Closes #7309 
This PR ignores major releases of the following packages:
- **@testing-library/\*\* packages** 
- `@testing-library/dom`
- `@testing-library/react`
- `@testing-library/react-hooks`
- `@testing-library/user-event`
- `@testing-library/jest-dom`
- **React packages**:
- `react`
- `react-dom`
- **Carbon packages**:
- `@carbon/react`
- `@carbon/grid`
- `@carbon/layout`
- `@carbon/motion`
- `@carbon/themes`
- `@carbon/type`
- `@carbon/feature-flags`
- `@carbon/utilities`
- `@carbon/icons`
- `@carbon/icons-helpers`
- **Miscellaneous packages**:
- `commander`
Also removes `@carbon/telemetry` since it is unused
Dependency Dashboard
=> chore(renovate): disables major upgrades for some packages

packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
Issue brought up by @wkeese 🎉 
> Hi Alexander, I’m looking at a Datagrid bug apparently from your commit https://github.com/wkeese/carbon-ibm-products/commit/fc9af2a67b1de33f8e941bea6353a67542c35af6.
> 1. Go to https://carbon-for-ibm-products.netlify.app/?path=/story/deprecated-datagrid-datagrid-filtering-panel--panel-batch&globals=viewport:basic,
> 2. Open filter panel, and check Password Strength / Normal.
> 3. -> Table filtered
> 4. Click “dismiss” button of the Normal filter tag (above the table).
> 5. Filter panel restored to original state, and all table rows displayed.
> 6. Check Password Strength / Critical in filter panel.
> 7. Click filter panel’s Cancel button
> 8. Filter panel restored to state from step 2 (Normal checked).   Expected: Nothing should be checked, because we …
=> fix(datagrid): last applied filter should be included for both panel and flyout

packages/ibm-products/src/components/EmptyStates/EmptyState.tsx, packages/ibm-products/src/components/EmptyStates/EmptyStateContent.tsx, packages/ibm-products/src/components/EmptyStates/EmptyStates.stories.jsx, packages/ibm-products/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.tsx, packages/ibm-products/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.tsx, packages/ibm-products/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.tsx, packages/ibm-products/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.tsx, packages/ibm-products/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.tsx, packages/ibm-products/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.tsx
Closes #7459.
Enhance `EmptyState` to use the right heading level automatically, rather than forcing the application to specify `headingAs`.
Note that you still need to specify `headingAs="h1"` for full-page `EmptyState`, i.e. when there is no higher-level heading above the `EmptyState`.
These changes match the heading updates I've been making to other components to use `Section` and `Heading`.
Also, fix strange code in `EmptyStateContent` that was confused about when to use `Section` and when to use `Heading`.
`EmptyState`'s wrapper node is a `Section`, and it uses `Heading` for the heading.  Unless overridden by `headingAs`.
Storybook, including a temporary change to explicitly specify `headingAs`.
=> feat(emptystate): automatically use right heading level

.percy.yml
Closes #7513 
~I'm hoping increasing the network timeout for percy will resolve some of the flaky snapshots that get flagged as visual changes.~
Next attempt is to use the `waitForSelector` in the percy config to look for `[data-carbon-theme]` since that attribute is only added after storybook has finished loading.
Percy has flagged 8 visual differences which I think may be accurate. [This PR](https://github.com/carbon-design-system/ibm-products/pull/7447/files) contained changes to the breadcrumb row height which would explain the page header snapshots. And the other snapshot that was flagged was `NotificationPanel`, but it was just the 'n months ago' text. I'll approve the Percy snapshot changes and we can monitor new PRs for any Percy flakiness.
While storybook is loading (no …
=> fix(percy): add global `waitForSelector` to validate that storybook has loaded

packages/ibm-products-web-components/src/components/about-modal/about-modal.test.ts, packages/ibm-products-web-components/src/components/full-page-error/full-page-error.test.ts, packages/ibm-products-web-components/src/components/tearsheet/tearsheet.test.ts
The vite mock for the Carbon close icon that was previously needed may be the culprit for the flaky options-tile web component test. Basically the mock will cause vite to reload the test and can cause unexpected behavior.
```
[vite] (client) ✨ new dependencies optimized: @carbon/icons/lib/close/20
[vite] (client) ✨ optimized dependencies changed. reloading
[vitest] Vite unexpectedly reloaded a test. This may cause tests to fail, lead to flaky behaviour or duplicated test runs.
For a stable experience, please add mentioned dependencies to your config's `optimizeDeps.include` field manually.
```
After removing the mock, I do not see the above warnings anymore.
```
packages/ibm-products-web-components/src/components/about-modal/about-modal.test.ts …
```
=> fix(wc-tests): remove vi mock, no longer needed, causing flaky tests

.percy.yml
Closes https://github.com/carbon-design-system/ibm-products/issues/7513 (already closed, but I noticed Percy still took a snapshot of the storybook loading spinner for `Saving` so trying a different `waitForSelector`)
I updated the `waitForSelector` value to target the `.story-wrapper` element which doesn't even get included in the DOM until the story has loaded. I'm hoping switching to this selector helps because I noticed that in one of the Percy builds, the `Saving` component received a snapshot of the storybook loader which is not what we would expect.
`.percy.yml`
Checking the percy flagged snapshots
=> test: try `.story-wrapper` for percy waitForSelector

packages/ibm-products-web-components/tools/rollup-plugin-lit-scss.js, packages/ibm-products-web-components/vite.config.ts, packages/ibm-products/.storybook/main.js
Closes #7512 
configures `sass` to stop with all the tedious messaging caused by deprecation warnings and from our carbon dependencies
in the screenshot above you can see how when you run the storybook commands that you're not inundated with large amounts of messages from sass
=> fix: supress sass deprecation warnings

packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
Closes #7521.
Most browsers automatically allow tab navigation to scrollable nodes without interactive content.  Unfortunately, Tearsheet sabotaged that behavior by explicitly setting tabIndex={-1}.
This simply removes that tabIndex setting.
Storybook.
=> fix(Tearsheet): fix keyboard scroll for non-interactive tearsheet

packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx
Refs #4922.
` onRequestSubmit()` can optionally return a `Promise` instead of a straight value.
Changed Typescript declaration for `onRequestSubmit()` to note that it can return a `Promise`.
Ran the build.
=> chore(CreateFullPage): onrequestsubmit can return a promise

packages/ibm-products-styles/src/components/AboutModal/_about-modal.scss, packages/ibm-products-styles/src/global/styles/_display-box.scss, packages/ibm-products/src/components/NotificationsPanel/_storybook-styles.scss, packages/ibm-products/src/components/NotificationsPanel/preview-components/UnreadNotificationBell.js
Closes #6878 
Includes minor changes to provide stronger RTL support, most of the components flagged in #6878 were related to layout issues from the `DisplayBox` utility component used for overflow type stories (tagset, tag overflow, etc.).
An area that I did a little bit of research around was icon mirroring between LTR and RTL. From what I've found, icon mirroring should be supported except for cases where it may change the meaning of what the icon is used for. (ie "common icons such as the fast-forward and rewind icons in media players, use the same orientation in both LTR and RTL layouts"). To demonstrate how to support this, I included the mirroring support for the notification bell in `NotificationsPanel`. Most of the icons being used are symmetrical and won't require any additional …
=> fix(rtl): minor updates to provide stronger rtl support

.github/workflows/create-release-tag-and-pr.yml, lerna.json, scripts/get-changelog.js
Closes #7437 
[Change-logs](https://github.com/carbon-design-system/ibm-products/pull/7524/files#diff-8f035289d274d6d70d7fcda70c304e870ea8163ef97c0c34e764bd38d6e389b4R6) seem to be accumulating and repeating since `v2.62.0` in all packages. Lerna used generate and update changelog.md during releases. Looks like some glitch happened after a subsequent RC release `2.62.0-rc.1`.
Now `changelog.md` is updated using a manual script `get-changelog.js` while running the workflow  `Create github tag and PR `during release. We are already using the same script for generating changelog in [release](https://github.com/carbon-design-system/ibm-products/releases) page. Now I am reusing this scripts to update `changelog.md` as well.
Updated `get-changelog.js` to include logic to write the logs to …
=> chore: change-logs repeated in all packages

.github/workflows/release-canary.yml
Closes #6729
the last several [canary release failures ](https://github.com/carbon-design-system/ibm-products/actions/workflows/release-canary.yml)show the following in the publish log
```
lerna WARN notice Package failed to publish: @carbon/ibm-products-styles
lerna ERR! E422 Error verifying sigstore provenance bundle: Failed to validate the provenance subject against the package name, version and tarball integrity. Please try re-publishing with the latest stable version of npm
```
unfortunately i'm unable to find anything with this error message specifically. right now the only thing i'm attempting to do is up update the node version used in the canary publish workflow from 20 to 24
=> fix: canary release workflow

packages/ibm-products/src/components/EmptyStates/EmptyStateContent.tsx, packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenBody.tsx, packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenFooter.tsx, packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenHeader.tsx
Closes #7587 
It appears that the Interstitial sub-components never used the `ref` from `forwardRef` when initially created, this causes warning within the console and when running tests with our library. I also removed `forwardRef` from `EmptyStateContent` which also had the same issue but we do not need to include `forwardRef` support since that is an internal component.
```
packages/ibm-products/src/components/EmptyStates/EmptyStateContent.tsx
packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenBody.tsx
packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenFooter.tsx
packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenHeader.tsx
```
Verified no longer seeing these warning/errors in console
=> fix(Interstitial): pass forwarded refs

.github/workflows/create-release-tag-and-pr.yml
Closes #7437 
We need to ensure release tag is created before running the script for generating changelog. 
I have moved up the `create-release-tag` job to run before pull request creation
Can only be tested during the next release
=> chore(release): ensure release tag is created before release PR creation

packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.tsx, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.tsx, packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.tsx, packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/handleGridKeyPress.js, packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js, packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js, packages/ibm-products/src/components/Datagrid/useOnRowClick.ts, packages/ibm-products/src/components/Datagrid/useRowExpander.js, packages/ibm-products/src/components/Datagrid/useSelectRows.tsx, packages/ibm-products/src/components/Datagrid/useSortableColumns.tsx, packages/ibm-products/src/components/EditFullPage/EditFullPage.stories.jsx, packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx, packages/ibm-products/src/components/ExportModal/ExportModal.tsx, packages/ibm-products/src/components/ScrollGradient/ScrollGradient.js, packages/ibm-products/src/components/TruncatedList/TruncatedList.tsx, packages/ibm-products/src/global/js/utils/wrapFocus.js
Closes #7641 
This is a complementary PR to #7640 but focuses on removing any usage of our local `carbon.prefix` in favor of `usePrefix()` from Carbon. The only place it still makes sense to use our locally defined Carbon prefix variable is within our test files, otherwise there will be clashes with custom prefixing.
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.tsx
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.tsx
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.tsx
packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/handleGridKeyPress.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js …
```
=> fix: remove usage of local carbon prefix in component files

packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.tsx
Closes #6859 
confirmed that this change doesn't revert the original bug fix
=> fix: adds nullish checker back into create tearsheet first step logic

cspell.json, e2e/components/NotificationsPanel/NotificationsPanel-test.avt.e2e.js, packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.test.js, packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx
Closes #7377
When clicked outside the notification panel, the focus should return to trigger button only if the clicked element is not an actionable element like a button, input, link etc.
- Modified the `useClickOutside` hook callback to check if the clicked element is an actionable element and focus return to trigger based on that.
- Added a function to check if the clicked element is actionable.
- Updated Unit test for the change.
- updated avt test to match the change.
Storybook
=> fix(notification panel): clickoutside return focus to trigger button

packages/ibm-products-web-components/.storybook/main.ts, packages/ibm-products-web-components/tsconfig.json, packages/ibm-products/.storybook/main.js, scripts/get-auto-track-script.ts
Closes #7690 
Replaces the amplitude auto-capture setup with carbon autotrack.
```
packages/ibm-products-web-components/.storybook/main.ts
packages/ibm-products-web-components/tsconfig.json
packages/ibm-products/.storybook/main.js
scripts/get-auto-track-script.ts
```
=> refactor(instrumentation): replace amplitude with autotrack

packages/ibm-products/.storybook/manager-head.html, scripts/get-auto-track-script.ts
Follow up to #7710, noticed our old setup was still hanging around which causes errors. I also messed up the syntax for the `siteId` 😅 
```
packages/ibm-products/.storybook/manager-head.html
scripts/get-auto-track-script.ts
```
- Found errors in newly deployed storybook
=> fix(Instrumentation): auto track follow ups

.percy.yml, e2e/components/NotificationsPanel/NotificationsPanel-test.avt.e2e.js
Updates urls for two avt tests from `NotificationsPanel`, these are causing avt tests to fail after the storybook IA changes. Also noticed that in our `percy.yml` config file, we were still only including snapshots within `IBM Products` directory, which doesn't exist after the storybook IA changes (this is what is causing the `vrt-runner` to fail). I've updated it to include snapshots for `Components`, `Patterns`, and `Utilities`.
```
e2e/components/NotificationsPanel/NotificationsPanel-test.avt.e2e.js
```
Will verify in this PR
=> fix(avt): update notification panel avt story urls and fix percy config issue

packages/core/src/welcome/_storybook-styles.scss, packages/ibm-products-styles/src/global/styles/_display-box.scss, packages/ibm-products/.storybook/carbon.scss
Closes #7646 
The extra import of `@carbon/styles` from the welcome page and the display box utility component were overriding the `$font-path` that is now configured in `.storybook/index.scss`. This caused the errors in the console regarding plex woff/woff2 files not loading, and also imported the entirety of Carbon's styles 2 extra times within our storybook.
```
packages/core/src/welcome/_storybook-styles.scss
packages/ibm-products-styles/src/global/styles/_display-box.scss
packages/ibm-products/.storybook/carbon.scss
```
Ran storybook locally
=> fix(stories): remove extra carbon style imports

packages/ibm-products/src/components/Card/Card.tsx
closes #7743 
adds `...rest` back into `Card`. thus highlighting our ongoing issues with composability and lack of typescript in our testing and stories 😂
=> fix: add rest props back to card overflow

README.md, packages/core/src/welcome/Welcome.js
Closes #7399 
Add Install, Styles, Usage section as in [website](https://pages.github.ibm.com/carbon/ibm-products/developing/get-started/) in repo [readme.md](https://github.com/carbon-design-system/ibm-products)
Include the missing detail in readme. `To include all Carbon index-full-carbon`
Add Get started link in storybook welcome page, this should go to packages/ibm-products/README.md
local
=> docs: update installation detail in readme and welcome story

.github/workflows/deploy-latest.yml, .github/workflows/deploy-staging.yml
Closes #6985 
`yarn storybook-wc:build` will fail with below error if run with out a full build 
```
Error: Can't find stylesheet to import.
╷
18 │ @use '@carbon/ibm-products-styles/scss/components/FullPageError' as *;
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
src/components/full-page-error/full-page-error.scss 18:1  root stylesheet
```
=> fix: perform full  build before wc story build

.github/workflows/deploy-latest.yml, .github/workflows/deploy-staging.yml
Closes #6985 
Deployement failed with authentication [error](https://github.com/carbon-design-system/ibm-products/actions/runs/16020384802/job/45195685524)
```
npm warn exec The following package was not found and will be installed: gh-pages@6.3.0
ProcessError: fatal: could not read Username for 'https://github.com/': No such device or address
```
=> fix: add authenticated remote

packages/ibm-products-web-components/src/components/page-header/_story-assets/_storybook-styles.scss, packages/ibm-products-web-components/src/components/page-header/page-header.mdx, packages/ibm-products-web-components/src/components/page-header/page-header.scss, packages/ibm-products-web-components/src/components/page-header/page-header.stories.ts, packages/ibm-products-web-components/src/components/page-header/page-header.test.ts, packages/ibm-products-web-components/src/components/page-header/page-header.ts, packages/ibm-products-web-components/vite.config.ts
Closes #7740 
Adds sticky functionality to page header web component when there is scrolling content, similar to the current page header.
```
packages/ibm-products-web-components/src/components/page-header/_story-assets/_storybook-styles.scss
packages/ibm-products-web-components/src/components/page-header/page-header.scss
packages/ibm-products-web-components/src/components/page-header/page-header.stories.ts
packages/ibm-products-web-components/src/components/page-header/page-header.ts
```
Verified in each of the page header stories
=> feat(page-header): add sticky support, web component

packages/ibm-products/src/components/InterstitialScreen/InterstitialScreenBody.tsx
Closes #7790 
Currently InterstitialScreen.Body accepts contentRenderer callback prop that will return the content to render in body.
This enhancement will add support to children prop for InterstitialScreen.Body ,if user want to go with some simple static content that doesn't need to access internal state and also offers more performance by reducing re-renders
add support for children
=> feat: add support for  children prop for InterstitialScreen.Body

packages/ibm-products-web-components/src/components/about-modal/about-modal.stories.ts, packages/ibm-products-web-components/src/components/full-page-error/full-page-error.stories.ts, packages/ibm-products-web-components/src/components/notification-panel/notification-panel.stories.ts, packages/ibm-products-web-components/src/components/options-tile/options-tile.stories.ts, packages/ibm-products-web-components/src/components/side-panel/side-panel.stories.ts, packages/ibm-products-web-components/src/components/tearsheet/tearsheet.stories.ts, packages/ibm-products-web-components/src/components/truncated-text/truncated-text.stories.ts, packages/ibm-products-web-components/src/components/user-avatar/user-avatar.stories.ts, packages/ibm-products-web-components/src/utilities/overflow-handler/overflow-handler.stories.ts
Closes #7821 
Restructures the top level categories in our web component storybook, renaming `Experimental` to `Components` and moving `Utilities` to the top level.
```
packages/ibm-products-web-components/src/components/about-modal/about-modal.stories.ts
packages/ibm-products-web-components/src/components/full-page-error/full-page-error.stories.ts
packages/ibm-products-web-components/src/components/notification-panel/notification-panel.stories.ts
packages/ibm-products-web-components/src/components/options-tile/options-tile.stories.ts
packages/ibm-products-web-components/src/components/side-panel/side-panel.stories.ts
packages/ibm-products-web-components/src/components/tearsheet/tearsheet.stories.ts
packages/ibm-products-web-components/src/components/truncated-text/truncated-text.stories.t …
```
=> docs(storybook): restructure top level categories

packages/ibm-products/src/components/ProductiveCard/ProductiveCard.docs-page.js
Closes #6728 
Adds some docs around overflow menu usage in `ProductiveCard`.
```
packages/ibm-products/src/components/ProductiveCard/ProductiveCard.docs-page.js
```
Doc update only
=> docs(ProductiveCard): add docs about overflow menu items

actions/add-review-labels/package.json
Closes #7848 
Closes #7847 
Added a `resolutions` key to the `actions/add-review-labels` packages, not sure if this will break anything related to the action itself. I went through the release notes for the packages I added and didn't notice any breaking changes that seem to apply to us. We're on the latest for the packages that are getting flagged with these security vulnerabilities so we can't upgrade them directly (`@actions/core` and `@actions/github`).
Typically we only have `resolutions` in our root `package.json` but this one is separate from our monorepo packages (`packages/*`) so it seems to still pin those packages.
```
actions/add-review-labels/package.json
```
Mend check passes in this PR
More details can …
=> fix(deps): add resolutions for `add-review-label` action

packages/ibm-products/src/components/CoachmarkBeacon/CoachmarkBeacon.tsx, packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx, packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx, packages/ibm-products/src/components/PageHeader/PageHeader.stories.jsx, packages/ibm-products/src/components/ScrollGradient/ScrollGradient.js
Refs #7043 and https://github.com/IBMa/equal-access/issues/2281.
It's no longer necessary to set `tabIndex={0}` for scrollable `<div>` or `<section>` elements.  See #7043.
You also don't need it for `<IconButton>` or `<button>`, as it's the default.
Removed various unneeded `tabIndex={0}`.
Storybook.
=> chore: remove unneeded tabIndex={0} settings

packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItem.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemDate/ConditionBuilderItemDate.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemNumber/ConditionBuilderItemNumber.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemOption/ItemOption.tsx, packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemOption/ItemOptionForValueField.tsx, packages/ibm-products/src/components/ConditionBuilder/assets/sampleInput.js, packages/ibm-products/src/components/ConditionBuilder/utils/useTranslations.js
Closes #7803,#7856,#7868
Condition builder issue fixes
- Fix story crash issue when custom component is used, which is a storybook specific issue
- When a custom operator uses the same ID as a default operator, the label displays the generic "Add operator" text instead of the configured custom label.
- Remove extra space from inout type number, when unit is not passed
- Null check for config object
local storybook
=> fix: condition builder minor issue fixes

packages/ibm-products/package.json, packages/ibm-products/src/components/PageHeader/next/PageHeader.test.js, packages/ibm-products/src/components/index.ts, yarn.lock
Chatting with a product team trying to use new page header, we discovered that it's being exported as `unstable__PageHeader` rather than `preview__PageHeader`. Export was updated in `packages/ibm-products/src/components/index.js` but not `packages/ibm-products/src/components/index.ts`. We may need to cleanup this structure later on.
I also bumped the resizer package from labs that has the esm/cjs fix.
=> fix(PageHeader): export as preview from ts exports, bump resizer

packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
Closes #7761 
addSelect getting closed while selecting any item from sort popover
include .`cds--menu` to selectorsFloatingMenus in Tearsheet
storybook
=> fix(AddSelect): modal is getting closed while trying to click and select from sort overflowmenu

packages/ibm-products-web-components/src/components/page-header/page-header-title-breadcrumb.ts, packages/ibm-products-web-components/src/components/page-header/page-header.scss, packages/ibm-products-web-components/src/components/page-header/page-header.ts
Closes #7932 
Correctly sets the sticky positioning values even when the page header content element isn't provided. This allows for the "condensed" version that some teams have inquired about. This change also allows for no scroll animation for the title breadcrumb if there is not a page header content element, in this case the title breadcrumb should be fully visible initially.
```
packages/ibm-products-web-components/src/components/page-header/page-header-title-breadcrumb.ts
packages/ibm-products-web-components/src/components/page-header/page-header.scss
packages/ibm-products-web-components/src/components/page-header/page-header.ts
```
Storybook
More details can be found in the [pull request](./CONTRIBUTING.md) …
=> feat(page-header): position updates when content element not provided

packages/ibm-products-web-components/examples/set-of-breadcrumbs/index.html, packages/ibm-products-web-components/examples/set-of-breadcrumbs/package.json, packages/ibm-products-web-components/src/components/page-header/_story-assets/overflowHandler.ts, packages/ibm-products-web-components/src/components/page-header/_story-assets/set-of-breadcrumbs.scss, packages/ibm-products-web-components/src/components/page-header/_story-assets/set-of-breadcrumbs.ts, packages/ibm-products-web-components/src/components/page-header/page-header.scss, packages/ibm-products-web-components/src/components/page-header/page-header.stories.ts
Closes #7799 
Adds an example to demonstrate how to include overflowing behavior for the breadcrumbs within the breadcrumb bar of the page header. These changes are implementation only as I've included the example that @devadula-nandan built to show this behavior, not directly included within the page header component itself.
A local `overflowHandler.ts` util was added because the one from `@carbon/utilities` does not include padding/margin spacing in the over element size calculation. Until I submit a PR to update it within core, I've included a local version that includes those values.
The changes can be viewed from [this story](https://deploy-preview-7913--ibm-products-web-components.netlify.app/?path=/story/patterns-pageheader--tab-bar-with-tabs-and-tags).
``` …
```
=> feat(page-header): add breadcrumb overflow example

cspell.json
add `scroller` word to spellcheck exclude.
This word was added in [this commit](https://github.com/carbon-design-system/ibm-products/commit/3a98acf5915b574276d94105453e8b0d4057cc0b) caused [error](https://github.com/carbon-design-system/ibm-products/actions/runs/16724649335/job/47336995205)
=> fix: add scroller word to spellcheck exclude

packages/ibm-products-web-components/src/components/interstitial-screen/interstitial-screen.stories.ts
Puts the Interstitial web component into the `Components` category with the others
=> chore(Interstitial): reorganize story category

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/Datagrid/styles/addons/_FilterPanel.scss, packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
Use correct syntax for custom CSS property.
A couple of custom CSS properties with value "320px" were incorrectly set as `<integer>` instead of `<length>`. The former should only be numbers and not contain any units, therefore should be using the latter.
I noticed this when building a separate project using [lightningcss](https://lightningcss.dev/), which is more strict than other CSS parsers. Lightningcss throws an error for these 2 references.
Compared local storybook to deployed version. Tested `SidePanel` and `Datagrid/Filtering/Panel` to ensure that nothing regressed.
=> fix(styles): use correct syntax for custom CSS props

packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx, packages/ibm-products/src/components/CreateModal/CreateModal.tsx, packages/ibm-products/src/components/CreateSidePanel/CreateSidePanel.tsx, packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.tsx, packages/ibm-products/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.tsx
Closes #7866
This fix disables this default behavior [W3 Section 8.2](https://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2) "When there is only one single-line text input field in a form, the user agent 'should' accept Enter in that field as a request to submit the form."
You can see Storybook example here:
1. [Create Full Page With Step In Error State](https://ibm-products.carbondesignsystem.com/?path=/story/patterns-prebuilt-patterns-create-flows-createfullpage--create-full-page-with-step-in-error-state). Single input field reloads the page. 
- Set focus on the input field, 
- hit the Enter key, 
- the page reloads. 
3. [Create Full Page With Header](https://ibm-products.carbondesignsystem.com/?path=/story/patterns-prebuilt-patterns-create-flows-createfullpage--create-full-page-wi …
=> fix(Create tearsheets and modals): disable ability to submit form using the Enter key

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss, packages/ibm-products-web-components/src/components/side-panel/side-panel.scss
Closes #7923
Remove box-shadow on side panel slide-in variants.
These are not overlaid but inline with existing content.
Note: In the React version, we only remove the shadow when the `slide-in` panel does not include an overlay. You can still achieve slide-over with no overlay but a shadow (or a slide-in with an overlay).
This does not appear to be the same in the WC version. In WC, the overlay is only present in a slide-over but never in a slide-in. (Although you can have a slide-over with no overlay.)
Remove shadow on `slide-in` side panel variant.
Storybook
=> fix(SidePanel): remove shadow on slide-ins

packages/ibm-products/src/components/SidePanel/SidePanel.tsx
Closes #7969 
We had a [similar issue](https://github.com/carbon-design-system/ibm-products/pull/5516/files) in the past which put the same fix. 
Merging with carbon flag is happening in f`eature-flags.js`.
=> fix(SidePanel): unable to find a feature flag with the name: 'enableSidepanelResizer'

.github/workflows/release-base.yml
This should fix the issue we're seeing during today's release action. Our storybook needs to build/create the `storybook-static` directory before we're able to startup the server to produce the avt report.
```
.github/workflows/release-base.yml
```
=> fix(release): build storybook first before running avt report

.github/workflows/release-base.yml
Removes the avt setup from within the release action for now. It is timing out since it's not run as a matrix like it is from within our `ci.yml` workflow.
```
.github/workflows/release-base.yml
```
=> chore(release): remove avt script temporarily

packages/ibm-products-styles/src/components/TagSet/_tag-set.scss
Closes #8102 
Removes style overrides
packages/ibm-products-styles/src/components/TagSet/_tag-set.scss
Storybook
=> fix(tagset): restore operational tag styles

packages/ibm-products/src/components/PageHeader/next/PageHeader.stories.js, packages/ibm-products/src/components/PageHeader/next/_storybook-styles.scss
Closes #8119 
Adds a `compact` story for new page header, no new changes needed to implement this, you just exclude the `PageHeader.Content` component and only use `PageHeader.BreadcrumbBar` and `PageHeader.TabBar`.
I also addressed an issue with how the preview was displaying from the doc page and moved the component from `Experimental/Patterns/PageHeader` to `Experimental/PageHeader` since we're classifying compound components as components, rather than patterns.
```
packages/ibm-products/src/components/PageHeader/next/PageHeader.stories.js
packages/ibm-products/src/components/PageHeader/next/_storybook-styles.scss
```
Storybook
our …
=> feat(PageHeader): add compact story, fix preview styles in storybook docs page

packages/ibm-products-web-components/package.json, yarn.lock
Closes N/A
For a bit of context, I'll give a brief rundown of how `@ibm/telemetry-js` works. 
When any repo using carbon packages is doing its `npm install`, all carbon packages are being installed at once. To avoid them running our `postinstall` collection script at the same time and affecting CI performance, we make it so the first package that runs the script will become an IPC server. All others will become IPC clients, and send over their "work to do" over to the server. The server then processes all the package's sequentially, in order to avoid using up too many resources. 
However, if the package that becomes a server is using any version of telemetry that is not `v1.10.0` or higher, then it won't have the code required to run the Web Components scope for data collection. In other …
=> fix(telemetry): bump version

packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap, packages/ibm-products-styles/src/components/TagOverflow/_tag-overflow.scss, packages/ibm-products-styles/src/components/TagSet/_tag-set.scss
Closes #8189 
just some small styling issues for the show more link in `TagSet` and `TagOverflow`
also removes some styles for the `:visited` state because they weren't being used. today i learned `:visitied` has certain css restrictions for privacy reasons
=> fix: update popover link in tagset and overflow

config/jest-config-ibm-cloud-cognitive/package.json, packages/ibm-products-styles/package.json, packages/ibm-products/package.json, yarn.lock
Pinning `chalk` because of the recent npm malware attacks. This is a package used internally within our monorepo that we honestly don't rely on heavily and should consider removing entirely. Before we do so, we can pin to the version we're currently using (the impacted version was already published over, but just to be extra safe we'll pin for now).
Pinned `chalk` versions
Updated lock file
PR checks run as expected
=> chore(deps): pin `chalk` package

yarn.lock
Resolves a security issue, added a resolution to trigger a lock file update. After removing the resolution the version of `tmp` in our lock file remains at `0.2.5` (documented as a safe version [here](https://github.com/advisories/GHSA-52f5-9888-hmc6)) so I removed the resolution.
`yarn.lock`
N/A
=> chore: bump tmp version in lock file

config/jest-config-ibm-cloud-cognitive/package.json, config/jest-config-ibm-cloud-cognitive/setup/setupFilesAfterEnv.js, packages/ibm-products-styles/package.json, packages/ibm-products/package.json, packages/ibm-products/scripts/generate/index.mjs, packages/ibm-products/scripts/import.js, yarn.lock
Closes #8290 
Removes the `chalk` package from our repo, was used across a handful of places for various component generation scripts and jest setup. Everything was replaced with a more native approach so that we don't have to rely on that dependency anymore.
```
config/jest-config-ibm-cloud-cognitive/package.json
config/jest-config-ibm-cloud-cognitive/setup/setupFilesAfterEnv.js
packages/ibm-products-styles/package.json
packages/ibm-products/scripts/generate/index.mjs
packages/ibm-products/scripts/import.js
yarn.lock
```
Ran scripts locally, will also verify in PR checks
=> refactor(scripts): remove chalk dep

packages/ibm-products/src/components/PageHeader/next/PageHeader.test.js, packages/ibm-products/src/components/PageHeader/next/PageHeader.tsx
Closes #8257
Uses the `Section` and `Heading` components so that the title in the page header receives a more appropriate heading level.
- `packages/ibm-products/src/components/PageHeader/next/PageHeader.tsx`
- `packages/ibm-products/src/components/PageHeader/next/PageHeader.test.js`
Verified in browser that the heading level is using the correct semantic level
=> fix(PageHeader): use section and heading components for heading levels

packages/ibm-products-web-components/.storybook/_container.scss, packages/ibm-products/.storybook/index.scss
Closes #7998
Uses background theme token for the storybook doc previews so that we don't end up in mixed theme states.
```
packages/ibm-products-web-components/.storybook/_container.scss
packages/ibm-products/.storybook/index.scss
```
Verified locally across both storybooks
=> chore(storybook): use theme tokens for sb doc previews
