carbon-design-system/ibm-products

- .prettierignore
- packages/core/.storybook/main.js
- packages/security/package.json
- packages/security/src/ComboButton/ComboButton.stories.js
- packages/security/src/ComboButton/_index.scss
- packages/security/src/ComboButton/index.js
- packages/security/src/index.js
**New**
Add entry points for `packages/security`
**Changed**
Apply Prettier formatting to Storybook source files
**Removed**
Storybook source files from `.prettierignore`
> build(main): add entry points, permit Storybook formatting

- packages/security/src/ICA/ICA.stories.js
- packages/security/src/ICA/_index.scss
- packages/security/src/ICA/index.js
**New**
Add ICA component and basic story
> docs(storybook): add ICA component

- .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
**New**
Add issue template for feature requests or enhancements
> docs(issue-template): add component issue template

- packages/security/src/Decorator/Decorator.stories.js
- packages/security/src/Decorator/_index.scss
- packages/security/src/Decorator/index.js
Resolves #36
**New**
- Add `Decorator` component and styles
- Add basic `Decorator` story with knobs
> feat(decorator): export component, add story

- packages/experimental-package/src/components/ExampleComponent/ExampleComponent.stories.js
Adds event handler for demonstration purposes to the experimental example component
> feat: add event handler to experimental example

- packages/experimental-package/src/components/PageHeader/PageHeader.js
- packages/experimental-package/src/components/PageHeader/PageHeader.stories.js
- packages/experimental-package/src/components/PageHeader/README.md
- packages/experimental-package/src/components/PageHeader/_storybook-styles.scss
- packages/experimental-package/src/components/PageHeader/index.js
Working on #59
Adds a skeleton for the pageHeader component.
> feat: skeleton pass of pageHeader

- packages/experimental-package/package.json
- packages/experimental-package/src/components/PageHeader/PageHeader.js
- packages/experimental-package/src/components/PageHeader/PageHeader.stories.js
- packages/experimental-package/src/components/PageHeader/_index.scss
- packages/experimental-package/src/components/PageHeader/_page-header.scss
- packages/experimental-package/src/components/PageHeader/_storybook-styles.scss
- packages/experimental-package/src/components/PageHeader/index.js
- packages/experimental-package/src/global/styles/_carbon-settings.scss
- yarn.lock
Closes #
removed files.
M       packages/experimental-package/package.json
A       packages/experimental-package/src/components/PageHeader/_index.scss
A       packages/experimental-package/src/components/PageHeader/_page-header.scss
M       packages/experimental-package/src/components/PageHeader/_storybook-styles.scss
M       packages/experimental-package/src/components/PageHeader/index.js
M       packages/experimental-package/src/components/_index.scss
M       packages/experimental-package/src/global/styles/_carbon-settings.scs …
> feat: flesh out structure of page header

- packages/experimental-package/src/components/PageHeader/PageHeader.stories.js
- packages/experimental-package/src/components/PageHeader/_storybook-styles.scss
Add stories for PageHeader that correspond to the examples in the design issue #59.
> feat: add stories for PageHeader

- packages/core/package.json
- packages/experimental-package/package.json
- packages/experimental-package/src/components/PageHeader/PageHeader.stories.js
- packages/experimental-package/src/components/PageHeader/_storybook-styles.scss
- yarn.lock
A       .yarn/offline-mirror/@carbon-grid-10.15.0.tgz
M       packages/core/package.json
M       packages/experimental-package/package.json
M       packages/experimental-package/src/components/PageHeader/_storybook-styles.scss
M       yarn.lock
**New**
- More stories
**Changed**
- Improved stories
> feat: improve PageHeader stories

- packages/experimental-package/src/components/PageHeader/PageHeader.stories.js
Progresses: #59
Adds a degenerate story to demo/test the behaviour of the PageHeader with long strings and large numbers of various items.
**New**
- New degenerate story
> Add story for PageHeader with many items and long strings

- packages/experimental-package/src/components/PageHeader/_page-header.scss
Part of #59 
A single file update to make the page a little more responive
> feat: adjust responsive behavior

- packages/experimental-package/src/components/PageHeader/ActionBarItem.js
- packages/experimental-package/src/components/PageHeader/PageHeader.js
- packages/experimental-package/src/components/PageHeader/PageHeader.mdx
- packages/experimental-package/src/components/PageHeader/PageHeader.stories.js
- packages/experimental-package/src/components/PageHeader/PageHeaderCopy.stories.js
Progresses #59
Miscellaneous updates to the docs for PageHeader
M       packages/experimental-package/src/components/PageHeader/ActionBarItem.js
M       packages/experimental-package/src/components/PageHeader/PageHeader.mdx
M       packages/experimental-package/src/components/PageHeader/PageHeaderCopy.stories.js
> Updates to the PageHeader documentation

- packages/experimental-package/src/components/PageHeader/PageHeader-test.js
Progresses #59
A couple of initial enzyme tests for the Pageheader
A       packages/experimental-package/src/components/PageHeader/PageHeader-test.js
**New**
- Enzyme tests for PageHeader
> Add enzyme tests for PageHeader

- packages/experimental-package/src/components/PageHeader/PageHeader.js
- packages/experimental-package/src/components/PageHeader/_page-header.scss
Relates to  #59
Some minor tweaks to the heading scroll, think I need to move the height stuff into state variables but will do so in a separate PR.
M       packages/experimental-package/src/components/PageHeader/_page-header.scss
> feat: further heading scroll tweaks

- packages/experimental-package/src/components/PageHeader/PageHeader.js
- packages/experimental-package/src/components/PageHeader/_page-header.scss
Part of #59
Refactor height measurements into state and comment on each useEffect.
Reviewed behaviour in storybook, ran tests and linter.
> chore: refactor heights into state

- packages/experimental-package/src/components/PageHeader/PageHeader.js
- packages/experimental-package/src/components/PageHeader/_page-header.scss
Part of  #59
A number of refinements made by observing the behaviour of each of the pageHeader stories when the page scrolls.
M       packages/experimental-package/src/components/PageHeader/_page-header.scss
Reviewed in storybook
> feat: refine pageHeader

- packages/experimental-package/src/components/RemovalModal/RemovalModal.js
- packages/experimental-package/src/components/RemovalModal/RemovalModal.mdx
- packages/experimental-package/src/components/RemovalModal/RemovalModal.stories.js
Adds an MDX file for `RemovalModal` and updates some of the proptypes and documentation
removed files.
M       packages/experimental-package/src/components/RemovalModal/RemovalModal.js
A       packages/experimental-package/src/components/RemovalModal/RemovalModal.mdx
M       packages/experimental-package/src/components/RemovalModal/RemovalModal.stories.js
**New**
- MDX documentation for `RemovalModal`
> Removal modal mdx

- CODEOWNERS
Resolves https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/149#issuecomment-711265603
> docs(CODEOWNERS): update CODEOWNER naming

- packages/experimental/src/components/RemovalModal/RemovalModal.mdx
- packages/experimental/src/components/RemovalModal/RemovalModal.stories.js
Contributes to #61 
Small docs update to align more closely with carbon.
M       packages/experimental/src/components/RemovalModal/RemovalModal.mdx
**Changed**
- RemovalModal.mdx
I added in some helpful links to point towards Carbon related documentation since the `RemovalModal` component is essentially just a Carbon `Modal`. I'm not sure exactly what additional documentation would benefit this specific component that isn't covered in any of the additional links I've added.
> fix: small RemovalModal docs update

- packages/experimental/src/components/PageHeader/PageHeader.js
- packages/experimental/src/components/PageHeader/PageHeader.stories.js
- packages/experimental/src/components/PageHeader/_page-header.scss
Various updates based on review with design
- Simplifies spacing under last row
- Adds pre-collapse option for title and breadcrumb row
- Adds option to keep both breadcrumb and tabs
- Address some spacing and font size issues.
- Moves action bar items far right
- Makes line under action bar items full width
removed files.
M       packages/experimental/src/components/PageHeader/PageHeader.stories.js
M       packages/experimental/src/components/PageHeader/_page-header.scss
> feat: various review updates

- packages/cdai/package.json
- packages/cdai/src/components/IdeSaving/IdeAutoSave.js
- packages/cdai/src/components/IdeSaving/IdeAutoSave.spec.js
- packages/cdai/src/components/IdeSaving/IdeManualSave.js
- packages/cdai/src/components/IdeSaving/IdeManualSave.spec.js
- packages/cdai/src/components/IdeSaving/IdeSaving.stories.js
- packages/cdai/src/components/IdeSaving/README.md
- packages/cdai/src/components/IdeSaving/_IdeAutoSave.scss
- packages/cdai/src/components/IdeSaving/_IdeManualSave.scss
- packages/cdai/src/components/IdeSaving/_storybook.scss
- packages/cdai/src/components/IdeSaving/index.js
- packages/cdai/src/index.js
- Add Saving component from CDAI
- move some dependencies to devDependencies as per recent discussion
> feat: add saving component

- .github/ISSUE_TEMPLATE/new-component-or-pattern-template.md
This currently does not work/appear. Adds frontmatter and a request for an RTL story.
M       .github/ISSUE_TEMPLATE/new-component-or-pattern-template.md
> Update the issue template for creating new components

- packages/experimental/src/components/PageHeader/PageHeader.js
- packages/experimental/src/components/PageHeader/_page-header.scss
Contributes to #5 
Review revisions that do not require additional measurement code. 60% title width 75% nav.
Also addresses broken title animation.
M       packages/experimental/src/components/PageHeader/_page-header.scss
> chore: more page header stuff

- packages/experimental/src/components/Tearsheet/TearsheetShell.js
- packages/experimental/src/components/Tearsheet/TearsheetShell.stories.js
- packages/experimental/src/components/Tearsheet/_index.scss
- packages/experimental/src/components/Tearsheet/_tearsheet.scss
- packages/experimental/src/components/_index.scss
Contributes to #183 
The TearsheetShell component is the first step to adding tearsheets. It handles the modal behaviour, sizing and positioning of tearsheets.
A       packages/experimental/src/components/Tearsheet/TearsheetShell.js
A       packages/experimental/src/components/Tearsheet/TearsheetShell.stories.js
A       packages/experimental/src/components/Tearsheet/_index.scss
A       packages/experimental/src/components/Tearsheet/_tearsheet.scss
M       packages/experimental/src/components/_index.scss
**New**
- TearsheetShell component and basic stories.
> Create TearsheetShell component

- packages/cdai/src/components/IdeRemove/IdeRemove.cucumber.js
- packages/cdai/src/components/IdeRemove/IdeRemove.feature
- packages/cdai/src/components/IdeRemove/IdeRemove.js
- packages/cdai/src/components/IdeRemove/IdeRemove.spec.js
- packages/cdai/src/components/IdeRemove/IdeRemove.stories.js
- packages/cdai/src/components/IdeRemove/README.md
- packages/cdai/src/components/IdeRemove/_IdeRemove.scss
- packages/cdai/src/components/IdeRemove/__snapshots__/IdeRemove.spec.js.snap
- packages/cdai/src/components/IdeRemove/_storybook.scss
- packages/cdai/src/components/IdeRemove/index.js
- packages/cdai/src/components/IdeRemove/test_assets/testProps.js
- packages/cdai/src/index.js
- packages/cdai/src/index.scss
Moved IdeRemove component from CDAI
> feat: ide-remove

- .github/workflows/release.yml
**New**
Enforce `actions/checkout` to use administrator token
> build(release): add token to manage protected branch

- packages/cdai/src/components/IdeCard/README.md
- packages/cdai/src/components/IdeCreate/README.md
- packages/cdai/src/components/IdeEmptyState/README.md
- packages/cdai/src/components/IdeHTTPErrors/README.md
- packages/cdai/src/components/IdeHome/README.md
- packages/cdai/src/components/IdeImporting/README.md
- packages/cdai/src/components/IdeNavigation/Navigation/README.md
- packages/cdai/src/components/IdeNavigation/PageContent/README.md
- packages/cdai/src/components/IdeNavigation/PageHeader/README.md
- packages/cdai/src/components/IdeNavigation/README.md
- packages/cdai/src/components/IdeRemove/README.md
- packages/cdai/src/components/IdeSaving/README.md
update contributors in CDAI readme files
> fix: update readmes

- .kodiak.toml
**New**
Add basic Kodiak configuration to manage merging and updating of approved PRs
> build(kodiak): add Kodiak configuration

- packages/experimental/src/components/Tearsheet/Tearsheet.stories.js
- packages/experimental/src/components/Tearsheet/TearsheetNarrow.stories.js
- packages/experimental/src/components/Tearsheet/_storybook-styles.scss
Contributes to #183 
Improves the Tearsheet stories.
M       packages/experimental/src/components/Tearsheet/Tearsheet.stories.js
M       packages/experimental/src/components/Tearsheet/TearsheetNarrow.stories.js
M       packages/experimental/src/components/Tearsheet/_storybook-styles.scss
> Improve Tearsheet stories

- packages/babel-preset-ibm-cloud-cognitive/CHANGELOG.md
- packages/cdai/CHANGELOG.md
- packages/cdai/src/component_helpers/Clipboard.js
- packages/cdai/src/component_helpers/Clipboard.spec.js
- packages/cdai/src/components/IdeAPIKeyGeneration/IdeAPIKeyGeneration.cucumber.js
- packages/cdai/src/components/IdeAPIKeyGeneration/IdeAPIKeyGeneration.feature
- packages/cdai/src/components/IdeAPIKeyGeneration/IdeAPIKeyGeneration.js
- packages/cdai/src/components/IdeAPIKeyGeneration/IdeAPIKeyGeneration.spec.js
- packages/cdai/src/components/IdeAPIKeyGeneration/IdeAPIKeyGeneration.stories.js
- packages/cdai/src/components/IdeAPIKeyGeneration/README.md
- packages/cdai/src/components/IdeAPIKeyGeneration/_IdeAPIKeyGeneration.scss
- packages/cdai/src/components/IdeAPIKeyGeneration/__snapshots__/IdeAPIKeyGeneration.spec.js.snap
- packages/cdai/src/components/IdeAPIKeyGeneration/_storybook.scss
- packages/cdai/src/components/IdeAPIKeyGeneration/index.js
- packages/cdai/src/components/IdeAPIKeyGeneration/test_assets/testProps.js
- packages/cdai/src/index.js
- packages/cdai/src/index.scss
- packages/cloud-cognitive/CHANGELOG.md
- packages/core/CHANGELOG.md
- packages/experimental/CHANGELOG.md
- packages/jest-config/CHANGELOG.md
- packages/rollup-config/CHANGELOG.md
- packages/security/CHANGELOG.md
contribute last remaining component across from CDAI
> feat: add cdai apikey component

- packages/cdai/package.json
start publishing cd&ai components
> chore: start publishing cdai components

- packages/experimental/src/components/TagSet/TagSet.js
- packages/experimental/src/components/TagSet/TagSet.stories.js
- packages/experimental/src/components/TagSet/_storybook-styles.scss
- packages/experimental/src/components/TagSet/_tag-set.scss
Contributes to #32 and #59 
Add show all to tags overflow. Needs work to address modal glitch.
M       packages/experimental/src/components/TagSet/TagSet.js
M       packages/experimental/src/components/TagSet/TagSet.stories.js
M       packages/experimental/src/components/TagSet/_tag-set.scss
> feat: add show all to tag-set

- packages/cdai/src/components/IdeButton/_IdeButton.scss
- packages/cdai/src/components/IdeImporting/IdeImporting.scss
missed 2 from https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/231
> fix: use tilde for node_module imports 2

- .github/stale.yml
**Changed**
Update Probot: Stale label to reflect https://github.com/carbon-design-system/ibm-cloud-cognitive/labels/status%3A%20wontfix
> build(stale): update assigned label

- packages/core/scripts/build.js
Resolves https://github.com/carbon-design-system/ibm-cloud-cognitive/security/code-scanning/2
> build: fix code scanning alert

- .github/ISSUE_TEMPLATE/new-component-or-pattern-template.md
- .github/PULL_REQUEST_TEMPLATE.md
**New**
Add guidance for verifying any new production dependencies.
> docs(templates): add dependency guidance

- packages/core/.storybook/index.scss
- packages/core/.storybook/preview.js
- packages/storybook-addon-carbon-theme/README.md
Update the readme and a bit of a tidy
removed files.
M       packages/core/.storybook/index.scss
M       packages/core/.storybook/preview.js
M       packages/storybook-addon-carbon-theme/README.md
> chore: add scss to storybook addon readme

- packages/experimental/src/components/AboutModal/_about-modal.scss
- packages/experimental/src/components/BreadcrumbWithOverflow/_breadcrumb-with-overflow.scss
Contributes to #148
Use correct carbon color token on about modal scroll gradient
> fix: use correct carbon token for about modal gradient

- packages/experimental/src/components/ExportModal/ExportModal.js
- packages/experimental/src/components/ExportModal/ExportModal.stories.js
- packages/experimental/src/components/ExportModal/_export-modal.scss
Contributes to #31 
adds story updates to export modal including radio selections, loading messaging, error messaging, success messaging. also includes update to improve name validation UX.
removed files.
M       packages/experimental/src/components/ExportModal/ExportModal.js
M       packages/experimental/src/components/ExportModal/ExportModal.stories.js
M       packages/experimental/src/components/ExportModal/_export-modal.scss
> fix: additional stories and selection for export

- packages/cdai/src/globals/scss/_carbon-settings.scss
fixes some style issues with some CDAI components: IdeCard, IdeHome and IdeHTTPErrors
> fix: missing grid scss

- packages/cdai/package.json
update to https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/280
> fix: move to peerDependencies

- packages/experimental/src/components/PageHeader/PageHeader.js
- packages/experimental/src/components/PageHeader/PageHeader.stories.js
- packages/experimental/src/components/PageHeader/_page-header.scss
Contributes to #59
feat: remove content switcher option from header
fix: align tags left when no tabs
feat: add line between breadcrumb and tabs
M       packages/experimental/src/components/PageHeader/PageHeader.stories.js
M       packages/experimental/src/components/PageHeader/_page-header.scss
> feat: review updates for page header

- packages/cdai/src/components/IdeSlideOverPanel/IdeSlideOverPanel.js
- packages/cdai/src/components/IdeSlideOverPanel/IdeSlideOverPanel.stories.js
Port of the visibility fix in IdeComponents:
https://github.ibm.com/cloud-integration-design/ide-components/pull/311
> fix: migrate focus trap fix for slideover

- packages/experimental/src/components/PageHeader/PageHeader.js
Contributes to #59
The last merge popped a column outside of its container.
removed files.
m. packages/experimental/src/components/PageHeader/PageHeader.js
> fix: merge issue in breadcrumb dom

- packages/cdai/package.json
> release: v1

- packages/cdai/package.json
- packages/cdai/src/components/IdeFilter/IdeFilter.js
- packages/cdai/src/components/IdeFilter/_IdeFilter.scss
- packages/cdai/src/components/IdeSaving/IdeAutoSave.js
- packages/cdai/src/components/IdeSaving/IdeAutoSave.spec.js
- packages/cdai/src/components/IdeSaving/_IdeAutoSave.scss
- packages/experimental/package.json
use @carbon/icons-react instead
> chore: stop using carbon-icons

- packages/experimental/src/components/APIKeyModal/APIKeyModal.stories.js
- packages/experimental/src/components/APIKeyModal/_api-key-modal.scss
Contributes to #56 
fixes modal body padding
M       packages/experimental/src/components/APIKeyModal/APIKeyModal.stories.js
M       packages/experimental/src/components/APIKeyModal/_api-key-modal.scss
> fix: apikey modal body padding

- packages/cdai/src/components/IdeCreate/_ide-create.scss
> fix: increase zindex in header

- packages/experimental/src/components/APIKeyModal/APIKeyModal.js
- packages/experimental/src/components/APIKeyModal/APIKeyModal.stories.js
- packages/experimental/src/components/APIKeyModal/_api-key-modal.scss
- packages/experimental/src/components/ImportModal/ImportModal.js
- packages/experimental/src/global/js/utils/wait.js
Contributes to #56 
Various design updates that address all the issues in this comment https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/56#issuecomment-756064399
M       packages/experimental/src/components/APIKeyModal/APIKeyModal.js
M       packages/experimental/src/components/APIKeyModal/APIKeyModal.stories.js
M       packages/experimental/src/components/APIKeyModal/_api-key-modal.scss
> ApiKeyModal design feedback updates

- packages/experimental/src/components/APIKeyModal/APIKeyModal.js
- packages/experimental/src/components/APIKeyModal/APIKeyModal.stories.js
- packages/experimental/src/components/APIKeyModal/_api-key-modal.scss
- packages/experimental/src/components/APIKeyModal/_storybook-styles.scss
Contributes to #56 
address design feedback from https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/56#issuecomment-760348210. specifically custom step validation.
M       packages/experimental/src/components/APIKeyModal/APIKeyModal.js
M       packages/experimental/src/components/APIKeyModal/APIKeyModal.stories.js
M       packages/experimental/src/components/APIKeyModal/_api-key-modal.scss
M       packages/experimental/src/components/APIKeyModal/_storybook-styles.scss
> fix: design feedback updates for apikeymodal

- .github/CONTRIBUTING.md
- README.md
**New**
- Point to Carbon's contributing guide for tips on preparing PRs
- Emphasise community messaging in `README.md`
> docs(CONTRIBUTING): add additional guidance

- README.md
Consolidates the build and run steps together in a single section on the README
> fix: update readme with build steps

- .github/CONTRIBUTING.md
**New**
Add guidance on improving review comprehension
> docs(contributing): update PR submission guidelines

- packages/experimental/src/components/PageHeader/PageHeader.js
- packages/experimental/src/components/PageHeader/_page-header.scss
- packages/experimental/src/global/js/utils/unwrap-if-fragment.js
Contributes to #59
- Remvoe runtime error when no action bar
- Correct use of prefix in the scss file
- Correct space under header when no action Bar items
- Stick page actions to the top when no action bar
M       packages/experimental/src/components/PageHeader/_page-header.scss
M       packages/experimental/src/global/js/utils/unwrap-if-fragment.js
> fix: further page header review updates

- packages/experimental/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js
- packages/experimental/src/components/BreadcrumbWithOverflow/_breadcrumb-with-overflow.scss
- packages/experimental/src/components/BreadcrumbWithOverflow/_storybook-styles.scss
Contributes to #59 and #181
Copies styling from here to make progress https://github.com/carbon-design-system/carbon/pull/7085
Left some TODOs to remove when 7085 is included in a Carbon build
removed files.
mpackages/experimental/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js 
m packages/experimental/src/components/BreadcrumbWithOverflow/_breadcrumb-with-overflow.scss 
m packages/experimental/src/components/BreadcrumbWithOverflow/_storybook-styles.scss
> fix: styling of breadcrumb with overflow

- CODEOWNERS
Changes code owners to the development team
> Change code owners to development team

- packages/cdai/src/components/IdeEmptyState/IdeEmptyState.js
- packages/cdai/src/components/IdeEmptyState/_IdeEmptyState.scss
Changes:
----
New external link icon for the  IdeEmptyState external link
> External link icon

- packages/experimental/src/components/index.js
export ContextHeader component for easy consumption
> fix: add export

- packages/experimental/src/global/js/utils/uuidv4.js
- packages/experimental/src/global/js/utils/uuidv4.spec.js
Our ID generator had no test and failed without a definition window.
M       packages/experimental/src/global/js/utils/uuidv4.js
A       packages/experimental/src/global/js/utils/uuidv4.spec.js
> fix: crypto for ssr and add test

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/component-or-pattern.md
- .github/ISSUE_TEMPLATE/dev-issue.md
- .github/ISSUE_TEMPLATE/new-component-or-pattern-template.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/REVIEWERS_GUIDELINES.md
Closes #348
Contributes to #363
Update to some documentation and adding REVIEWERS_GUIDELINES and dev-issue template.
Documentation only.
Documentation only.
> chore: update issue templates

- .github/ISSUE_TEMPLATE/component-or-pattern.md
- .github/REVIEWERS_GUIDELINES.md
Formatting to please prettier.
Ran prettier.
> fix: prettier formatting

- packages/experimental/src/components/SidePanel/SidePanel.js
- packages/experimental/src/components/SidePanel/SidePanel.stories.js
- packages/experimental/src/components/SidePanel/_side-panel.scss
Contributes to #64 
This PR addresses some design changes that were requested, in addition to adding a `labelText` prop that displays above the side panel title, the `primaryActions` now accept a loading property as well that will render the `<InlineLoading />` component.
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/64#issuecomment-781345336
All test for the side panel component still pass
> fix(SidePanel): added design changes and added new labelText prop

- packages/experimental/src/components/Card/Card.mdx
Contributes to #382
updates the card component docs
> fix: update card docs

- .github/CODE_GUIDELINES.md
- packages/experimental/scripts/generate/templates/_STYLE_NAME.scss
- packages/experimental/src/components/ExampleComponent/_example-component.scss
Contributes to #393 
Brings the Javascript files for the ExampleComponent and the CLI templates in line with our code guidelines.
ExampleComponent js, template js, and CODE_GUIDELINES.md
Ran a build and ran storybook.
> Update example component and CLI scss

- packages/experimental/src/components/WebTerminal/WebTerminal.js
Closes #457
Update WebTerminal as per other components.
WebTerminal.js
Ran storybook
> update WebTerminal to fix the Storybook failures

- .github/CODE_GUIDELINES.md
- packages/core/.storybook/index.scss
- packages/experimental/scripts/generate/templates/DISPLAY_NAME.js
- packages/experimental/scripts/generate/templates/DISPLAY_NAME.test.js
- packages/experimental/scripts/generate/templates/_storybook-styles.scss
- packages/experimental/src/components/ExampleComponent/ExampleComponent.js
- packages/experimental/src/components/ExampleComponent/ExampleComponent.test.js
- packages/experimental/src/components/ExampleComponent/_example-component.scss
- packages/experimental/src/components/ExampleComponent/_storybook-styles.scss
Contributes to #393
ExampleComponent and CLI templates and CODE_GUIDELINES.MD
Ran a build and ran storybook.
> Further updates to ExampleComponent and CLI for standards

- packages/experimental/scripts/generate/index.js
- packages/experimental/src/global/js/package-settings.js
Closes #460
Updates the generate cli to add the new component to components/index.js and global/js/package-settings.js
packages/experimental/scripts/generate/index.js - to amend the script
packages/experimental/src/global/js/package-settings.js - to add a comment targetted by the script
Tried out the CLI
> chore: improve generate cli

- packages/experimental/scripts/generate/templates/DISPLAY_NAME.stories.js
- packages/experimental/scripts/generate/templates/_STYLE_NAME.scss
- packages/experimental/src/components/AboutModal/AboutModal.js
- packages/experimental/src/components/AboutModal/AboutModal.mdx
- packages/experimental/src/components/AboutModal/AboutModal.stories.js
- packages/experimental/src/components/AboutModal/AboutModal.test.js
- packages/experimental/src/components/AboutModal/_about-modal.scss
- packages/experimental/src/components/AboutModal/_index.scss
- packages/experimental/src/components/AboutModal/_storybook-styles.scss
- packages/experimental/src/components/ExampleComponent/ExampleComponent.stories.js
Closes #393
AboutModal component files
Ran build and ran storybook. Added tests for remaining guidelines items and verified all tests run ok.
> Apply code guidelines to AboutModal

- packages/experimental/src/__tests__/index-all-disabled.test.js
- packages/experimental/src/__tests__/index-all-enabled.test.js
- packages/experimental/src/__tests__/index.test.js
- packages/experimental/src/components/Notifications/Notifications.js
- packages/experimental/src/components/SidePanel/SidePanel.js
- packages/experimental/src/components/TagSet/TagSet.js
- packages/experimental/src/components/WebTerminal/WebTerminal.js
Contributes to #364
The index tests are currently just testing ExampleComponent. Extended these to test all components. This uncovered some rendering and property issues that needed to be fixed at the same time.
index-all-disabled.test.js, index-all-enabled.test.js, index.test.js and settings.test.js
Also:
- WebTerminal, SidePanel and Notifications: in some circumstances these don't render anything. A React functional component wishing to render nothing needs to return `null`.
- TagSet: various errors were occurring when no children were supplied.
- Notifications: an error was occurring when no data was supplied.
Ran tests, and also checked modified components in storybook.
> Extend the index tests to all components

- package.json
Contributes to #462
Removed unnecessary rimraf from yarn clean script
package.json only
ran `yarn clean` :-)
> Clean up yarn clean

- packages/cloud-cognitive/src/global/js/package-settings.js
- packages/cloud-cognitive/src/index-all-disabled.js
- packages/cloud-cognitive/src/index-all-enabled.js
- packages/cloud-cognitive/src/index.js
Contributes to #148
package settings
ran tests
> Add AboutModal to released component list

- packages/cloud-cognitive/src/components/HTTPErrors/HTTPError403/HTTPError403.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPError404/HTTPError404.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPErrorOther/HTTPErrorOther.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPErrors.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPErrors.test.js
- packages/cloud-cognitive/src/components/HTTPErrors/_http-errors.scss
- packages/cloud-cognitive/src/components/HTTPErrors/_index.scss
- packages/cloud-cognitive/src/components/HTTPErrors/_storybook-styles.scss
- packages/cloud-cognitive/src/components/HTTPErrors/assets/HTTPErrorSvg403.js
- packages/cloud-cognitive/src/components/HTTPErrors/assets/HTTPErrorSvg404.js
- packages/cloud-cognitive/src/components/HTTPErrors/assets/HTTPErrorSvgOther.js
Contributes to #502 
I made some changes to the HTTPErrors components to follow the review guidelines.
HTTPError components
Double checked storybook to make sure none of the components broke
And ensure that all tests pass with `jest /HTTPErrors/`
> chore(HTTPErrors): add pre review changes

- packages/cloud-cognitive/src/components/Notifications/Notifications.js
- packages/cloud-cognitive/src/components/Notifications/Notifications.test.js
- packages/cloud-cognitive/src/components/Notifications/_notifications.scss
- packages/cloud-cognitive/src/components/Notifications/useClickOutside.js
Contributes to #507 
Preps Notifications component for release review
Notifications component
Verified everything in storybook still works and tested via `jest /Notifications/`
> chore(Notifications): prep component for release review

- packages/cloud-cognitive/src/components/UserProfileImage/UserProfileImage.js
Contributes to #69
Updated UserProfileImage because we've revised the Canary mechanism while it was being written :-)
Canary.js
Build, ran tests, ran storybook.
> update UserProfileImage with revised Canary mechanism

- packages/cloud-cognitive/src/components/Notifications/Notification.stories.js
- packages/cloud-cognitive/src/components/Notifications/Notifications.js
- packages/cloud-cognitive/src/components/Notifications/_storybook-styles.scss
Contributes to #523 
This fixes a bug that I found in the Notifications component where new notifications added to the component were not getting sorted properly (they would just get added to the end of the "today" group). Now the notifications of each group get sorted chronologically.
`Notifications.js`
`Notifications.stories.js`
`Notifications/_storybook-styles.scss`
Add the ability to create new notifications within storybook and verified that they get added in the right place.
> fix(Notifications): new notifications get sorted as expected now

- packages/cdai/src/components/IdeSlideOverPanel/IdeSlideOverPanel.stories.js
Remove IDESlideOverPanel browser console error from story
Added id to textinput and textarea components in story
Ran up storybook
> fix: ideStoryError

- packages/cloud-cognitive/src/components/ExampleComponent/ExampleComponent.js
Contributes to #363
Nuffink
Didn't
> feat: new release for experimental wrapper

- packages/experimental/config-experimental-commonjs.js
- packages/experimental/index-commonjs.js
- packages/experimental/package.json
Contributes to #363
fix exports
files in experimental
doing that now mate
> ensure es and lib entry points forward respective settings

- packages/cloud-cognitive/package.json
- packages/experimental/package.json
Contributes to #366
package.json, but the main thing is the feat tag in the commit.
> A technical PR to sync up the experimental and cloud-cognitive versions on a new feature version

- packages/cloud-cognitive/src/components/Notifications/Notifications.js
- packages/cloud-cognitive/src/components/Notifications/Notifications.test.js
Contributes to #507 
During the review of the StatusIcons component, I learned of the requirement to have the `blockClass` as a className on the outer most element of the component. This PR addresses that.
`Notifications.js`
`Notifications.test.js`
Verified that the blockClass was added and updated tests.
> chore(Notifications): add blockClass to outermost containing element

- packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/_breadcrumb-with-overflow.scss
- packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
Contributes to #59 #189 
Fixes some breakpoint behaviour either side of 692 breakpoint
Styles for breadcrumb and page header
Verified behaviour in storybook
> fix: pageheader styles either side of md breakpt

- .github/VARIANT_COMPONENT_GUIDELINES.md
Adds documentation to describe the new base & variant component pattern
for https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/525
> feat: adds variant component guidelines

- packages/cloud-cognitive/src/components/Card/Card.js
- packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.stories.js
- packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.stories.js
- packages/cloud-cognitive/src/components/ProductiveCard/_storybook-styles.scss
> Card design feedback

- packages/cloud-cognitive/src/components/Card/Card.js
- packages/cloud-cognitive/src/components/Card/_card.scss
- packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.js
- packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.stories.js
- packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.js
- packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.stories.js
- packages/cloud-cognitive/src/components/ProductiveCard/_productive-card.scss
- packages/cloud-cognitive/src/components/ProductiveCard/_storybook-styles.scss
Contributes to https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/382#issuecomment-813592978 & https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/382#issuecomment-813605208
please note the usage of `stylelint-disable` i was unable to use a carbon token with a negative value. i tried all the different ways i could think of to get it to evaluate to a negative value, but to no avail. if you know how to get a negative number using a carbon token please let me know.
> fix: card design feedback

- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.js
- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.test.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.js
- packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Contributes to #555
Tearsheet files
Ran tests
> Updates to Tearsheet from review

- packages/cloud-cognitive/src/components/_Canary/Canary.js
Contributes to #578
fixes out dated canary instruction
> fix: out dated canary instruction

- README.md
> docs(codesandbox): fix `README` CodeSandbox link

- .github/ISSUE_TEMPLATE/bug-report.md
> docs(codesandbox): fix bug report CodeSandbox link

- packages/cloud-cognitive/src/components/Card/Card.js
- packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.stories.js
- packages/cloud-cognitive/src/components/ProductiveCard/_productive-card.scss
Contributes to #382 
adds additional design feedback to card and card stories
> fix: more card design feedback

- .github/CODE_GUIDELINES.md
> Update code guidelines with more details of tests and global component requirements

- packages/cloud-cognitive/src/components/ActionSet/ActionSet.js
- packages/cloud-cognitive/src/components/ActionSet/ActionSet.test.js
- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.js
- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.stories.js
- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.test.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.stories.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js
- packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
- packages/jest-config/index.js
Contributes to #555
Add tests for ActionSet, plus a few adjustments to ActionSet. Rename 'height' prop of Tearsheet to 'verticalPosition'.
ActionSet and Tearsheet
Ran build, test, storybook.
> Additional review findings for Tearsheet and ActionSet

- .github/REVIEWERS_GUIDELINES.md
> Update review guidelines with global reqs plus post-review steps

- packages/cloud-cognitive/src/components/ImportModal/ImportModal.js
- packages/cloud-cognitive/src/components/ImportModal/_import-modal.scss
Contributes to #617 and #504
some styling updates for import modal
> fix: import modal style updates

- packages/cloud-cognitive/src/components/TagSet/TagSet.js
- packages/cloud-cognitive/src/components/TagSet/TagSetModal.js
- packages/cloud-cognitive/src/components/TagSet/TagSetOverflow.js
Refactor TagSet in prep for release review of page header
Extracted the modal and overflow parts of the tagset to components
Using storybook
> chore: refactor TagSet

- packages/cloud-cognitive/src/components/ExportModal/ExportModal.js
- packages/cloud-cognitive/src/components/ExportModal/ExportModal.test.js
- packages/cloud-cognitive/src/components/ExportModal/_export-modal.scss
- packages/cloud-cognitive/src/components/_index.scss
- packages/cloud-cognitive/src/components/index.js
> fix: added testing for export release review

- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
- packages/cloud-cognitive/src/global/js/utils/props-helper.js
Update page header action bar item usage to match update action bar
- Changed page header usage in story
- Updated main test case and added test case for coping with the outdated format
- Added deprecatePropUsage 
Ran storybook and jest for the page header.
> fix: page header action bar usage

- .github/VARIANT_COMPONENT_GUIDELINES.md
- packages/cloud-cognitive/src/components/ActionSet/ActionSet.js
- packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.js
- packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.js
- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.js
- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.stories.js
- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.test.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js
- packages/cloud-cognitive/src/global/js/utils/props-helper.js
- packages/cloud-cognitive/src/global/js/utils/props-helper.test.js
Contributes to #546
Just moved common code down into TearsheetShell using David's method to block unwanted props, so that we only have to make changes in one place.
Tearsheet files, and extended stripUnwantedProps function.
ran build, tests, storybook
> Tearsheet refactor

- .github/CODE_GUIDELINES.md
- packages/cloud-cognitive/src/components/AboutModal/AboutModal.stories.js
Contributes to #638
Review AboutModal stories to ensure all props make sense in the control panel. Also updated code guidelines to capture some of the important points.
AboutModal stories and code guidelines.
ran storybook
> About modal stories

- packages/cloud-cognitive/src/components/ActionBar/ActionBar.js
- packages/cloud-cognitive/src/components/ActionBar/ActionBar.test.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
- packages/cloud-cognitive/src/components/TagSet/TagSet.js
- packages/cloud-cognitive/src/components/TagSet/TagSet.test.js
- packages/cloud-cognitive/src/components/TagSet/TagSetModal.js
- packages/cloud-cognitive/src/components/TagSet/TagSetOverflow.js
- packages/cloud-cognitive/src/components/_index.scss
- packages/cloud-cognitive/src/components/index.js
- packages/cloud-cognitive/src/global/js/package-settings.js
Added tests to TagSet and tidies up some code.
- Removed some guff from ActionBar
- Moved TagSet to internal
- maxVisibleTags -> maxVisible to match other similar
- changed sizing tags array to work with tests
- simplified filteredModalTag construction.
- make use of ToolTip.onChange in TagSetOverflow simplifying implementation
Tests and storybook.
> fix: add tag set tests n tidy

- packages/cdai/src/components/IdeCard/_IdeCard.scss
fixes https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/654
> fix: increase specificity

- package.json
- packages/cloud-cognitive/src/components/APIKeyDownloader/APIKeyDownloader.test.js
- packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.js
- packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.test.js
- packages/cloud-cognitive/src/components/Card/Card.js
- packages/cloud-cognitive/src/components/Card/Card.test.js
- packages/cloud-cognitive/src/components/ExportModal/ExportModal.js
- packages/cloud-cognitive/src/components/ExportModal/ExportModal.test.js
- packages/cloud-cognitive/src/components/ExpressiveCard/ExpressiveCard.test.js
- packages/cloud-cognitive/src/components/ProductiveCard/ProductiveCard.test.js
- packages/cloud-cognitive/src/components/Saving/Saving.test.js
Contributes to #615 #647 #634 
Adds and improves testing for `ApiKeyModal` `ExportModal` and `Card`
> fix: adds and improves testing to several components

- packages/cloud-cognitive/src/components/_index.scss
@andrea-gm fixes unstyled ContextHeader in storybook (and for users!)
> Add ContextHeader styles to package roll-up

- packages/cloud-cognitive/src/components/ActionSet/ActionSet.js
- packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js
per comments made by @davidmenendez on #697 
ActionSet, Tearsheets, SidePanel
ran storybook
> Improve docgen when wrapping underlying components eg Button

- packages/cdai/package.json
- packages/cdai/src/components/ContextHeader/ContextHeader.js
- packages/cdai/src/components/ContextHeader/ContextHeader.stories.js
- packages/cdai/src/components/ContextHeader/ContextHeader.test.js
- packages/cdai/src/components/ContextHeader/_context-header.scss
- packages/cdai/src/components/ContextHeader/_index.scss
- packages/cdai/src/components/ContextHeader/_storybook-styles.scss
- packages/cdai/src/components/ContextHeader/index.js
- packages/cdai/src/index.js
- packages/cdai/src/index.scss
copy ContextHeader to CDAI components so we can consume as non-experimental
> CDAI context header

- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
Closes #630
Changes the collapse button to only appear if requested by the consumer.
Page Header
CI Check and storybook.
> feat: show collapse button if requested

- packages/cloud-cognitive/src/components/RemoveDeleteModal/RemoveDeleteModal.js
- packages/cloud-cognitive/src/components/RemoveDeleteModal/RemoveDeleteModal.stories.js
- packages/cloud-cognitive/src/components/RemoveDeleteModal/RemoveDeleteModal.test.js
- packages/cloud-cognitive/src/components/RemoveDeleteModal/_remove-delete-modal.scss
- packages/cloud-cognitive/src/components/Saving/Saving.test.js
contributes to #738 and #708
refactors `RemoveDeleteModal` to use a composed modal for more flexibility as well as numerous updates and fixes to get the component ready for release review. also made a small update to a test in `Saving`
> Remove delete release cleanup

- README.md
- packages/experimental/src/esm/config-experimental.js
> A couple of extra bits of clean-up for the revised canary mechanism

- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
- packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
- packages/cloud-cognitive/src/components/TagSet/TagSet.js
Contributes to #657
Fixes a number of issues from design review
- Spacing under breadcrumb/action bar to 05
- Vertical alignment of tabs and tags
- Tab position from left of stage to 16px
- Added the option to supply expand collapse 
- Spacing 07 when only page title
Storybook and ci-check
> fix: issues raised in page header design review

- packages/cloud-cognitive/src/components/ExportModal/ExportModal.js
- packages/cloud-cognitive/src/components/ExportModal/ExportModal.stories.js
- packages/cloud-cognitive/src/components/ExportModal/ExportModal.test.js
adds `onClose` and `preventCloseOnClickOutside` to `ComposedModal`
> fix: forgot to add onclose to export modal

- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
Improves test coverage of page header to 95% from 83%.
- Added Istanbul where resize test is required.
- Added tests as required
Ran tests and checked coverage.
> chore: improve page header test coverage

- packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js
Fixes the console error output when running tests for this component. Setting state in the timeout was causing state to be changed after it was unmounted so I just removed the setTimeout and set the step to 0.
Storybook and ran tests (no more error output)
> fix(CreateTearsheet): fix console error in tests from timeout issue

- packages/cloud-cognitive/src/components/HTTPErrors/HTTPError403/HTTPError403.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPError403/HTTPError403.stories.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPError404/HTTPError404.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPError404/HTTPError404.stories.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPErrorContent.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPErrorOther/HTTPErrorOther.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPErrorOther/HTTPErrorOther.stories.js
- packages/cloud-cognitive/src/components/HTTPErrors/HTTPErrors.test.js
Contributes to #502 
Addresses the changes requested from the HTTPError release review.
`HTTPError403.js`
`HTTPError404.js`
`HTTPErrorOther.js`
`HTTPErrorContent.js`
`HTTPError403.stories.js`
`HTTPError404.stories.js`
`HTTPErrorOther.stories.js`
`HTTPError.test.js`
> fix(HTTPErrors): addresses review findings

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/ExportModal/_export-modal.scss
- packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.mdx
- packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.stories.js
- packages/cloud-cognitive/src/components/RemoveModal/_remove-modal.scss
> fix: remove and export modal fixes

- packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
- packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js
Contributes to #845 
Brings SidePanel test coverage back up to 100%.
`jest /SidePanel/ --coverage`
> chore(SidePanel): add prop type validator test

- packages/cloud-cognitive/src/components/CreateSidePanel/CreateSidePanel.js
- packages/cloud-cognitive/src/components/CreateSidePanel/CreateSidePanel.stories.js
- packages/cloud-cognitive/src/components/CreateSidePanel/CreateSidePanel.test.js
- packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
- packages/cloud-cognitive/src/components/SidePanel/SidePanel.stories.js
- packages/cloud-cognitive/src/components/SidePanel/SidePanel.test.js
- packages/cloud-cognitive/src/components/SidePanel/_index.scss
- packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
- packages/cloud-cognitive/src/components/SidePanel/constants.js
- packages/cloud-cognitive/src/components/SidePanel/index.js
Contributes to #849 
Addresses the items found during the SidePanel component release review.
`SidePanel/SidePanel.js`
`SidePanel/SidePanel.stories.js`
`SidePanel/SidePanel.test.js`
`SidePanel/_index.scss`
`SidePanel/_side-panel.scss`
`SidePanel/constants.js`
`SidePanel/index.js`
`CreateSidePanel.js`
`CreateSidePanel.stories.js`
`CreateSidePanel.test.js`
> fix(SidePanel): make review fixes for release

- packages/cloud-cognitive/src/__tests__/settings.test.js
- packages/cloud-cognitive/src/settings.js
Make some Carbon tokens available from our settings package.
settings.js
Tests to check availability of tokens and values
> feat: simplified carbon token value in js

- packages/cloud-cognitive/src/components/TagSet/TagSet.js
- packages/cloud-cognitive/src/components/TagSet/TagSet.stories.js
- packages/cloud-cognitive/src/components/TagSet/TagSet.test.js
- packages/cloud-cognitive/src/components/TagSet/TagSetModal.js
- packages/cloud-cognitive/src/components/TagSet/TagSetOverflow.js
- packages/cloud-cognitive/src/components/TagSet/_index.scss
- packages/cloud-cognitive/src/components/TagSet/_storybook-styles.scss
- packages/cloud-cognitive/src/components/TagSet/_tag-set.scss
- packages/cloud-cognitive/src/components/TagSet/index.js
- packages/cloud-cognitive/src/components/index.js
Contributes to #801 
Updates as per review
- fix: verify child type
- fix: change use of heading to title
- fix: link role
- fix: search case
- feat: change block class of tag-set-overflow
- fix: use own block class in tagset modal
- feat: add TagSet to index.js
- fix: add to tagset to index.js
- fix: copyright corrections and addition
- fix: replace use of 2px with token
- fix: remove unnecessary scss preprocessing
- fix: apply height modal adjustment only for md+
Ran Storybook, tests and ci-check.
> Issue801 tag set review

- CODEOWNERS
Add code owners for `packages/security`
> docs(CODEOWNERS): add code owners for Security

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
Contributes to #773
per grid design document
tearsheet styles
ran storybook
> Make tearsheets full screen at sm and md breakpoints

- README.md
- packages/cloud-cognitive/README.md
Updates README.md for repo and packages/cloud-cognitive
README.md - adjusted the badge location.
packages/cloud-cognitive/README.md - adjusted badge location and added contributors.
> Update package contributors

- .github/CODE_GUIDELINES.md
> chore: tiny fix to code guidelines

- packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to #849 
Addresses design review changes from #849, specifically around the positioning of the back button icon.
Storybook
> fix(SidePanel): fix back button positioning

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.stories.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js
- packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
closes #659
tearsheet styles and stories
Ran storybook and tests
> Wrap tearsheet description at 60% and clamp to two lines

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/_index-released-only.scss
- packages/cloud-cognitive/src/global/js/package-settings.js
Contributes to #849 
All side panel review items have been addressed, this PR will mark SidePanel as released.
✅  the flags for the components in package-settings.js should be changed to true.
✅  the component SCSS should be included in /src/components/_index-released-only.scss.
✅  run the tests, recreating snapshots (using -u), and check in the updated public CSS snapshot. NB it is sufficient to run yarn jest styles -u to complete the snapshot updates.
> chore(SidePanel): mark as released

- packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.js
- packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.stories.js
- packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.test.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
Contributes to #976 
- Remove use of children 
- Enforce key in buttons shape
- Adjust PageHeader as a result.
CI-Check, test and storybook.
> feat: remove child support from button set with overflow

- packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.js
- packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.stories.js
- packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.test.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
Contributes to #976
Switched back to using Button.propTypes.kind instead of redeclaring kind array.
Storybook and test
> fix: revert to button kind

- examples/cloud-cognitive/ccs-base-react-16/src/reportWebVitals.js
- examples/cloud-cognitive/ccs-base-react-17/src/reportWebVitals.js
- packages/cloud-cognitive/CHANGELOG.md
- packages/cloud-cognitive/src/components/CreateFullPage/_storybook-styles.scss
- packages/cloud-cognitive/src/components/ImportModal/ImportModal.js
- packages/cloud-cognitive/src/components/LoadingBar/LoadingBar.js
- packages/cloud-cognitive/src/components/LoadingBar/_loading-bar.scss
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.mdx
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
- packages/cloud-cognitive/src/components/PageHeader/_storybook-styles.scss
This PR fixes a few more spelling errors, or excludes them from cspell.
Several files. Please check carefully that I've not changed anything that shouldn't be changed.
run tests, build, storybook.
> More spelling fixes

- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeaderDemo.data.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeaderUtils.js
- packages/cloud-cognitive/src/components/PageHeader/_index.scss
- packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
- packages/cloud-cognitive/src/components/PageHeader/_storybook-styles.scss
- packages/cloud-cognitive/src/components/PageHeader/index.js
Contributes to #996
Update copyright headers and correct available space ??= operator.
Storybook.
> fix: correct available space default assignment, and update copyright headers in source files

- .github/ISSUE_TEMPLATE/question.md
Change question template to refer to @carbon/ibm-cloud-cognitive components.
> Update question template to correct repo name

- packages/cloud-cognitive/src/components/PageHeader/PageHeader.mdx
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js
Contributes to #996
PageHeader.stories.js
Ran storybook. That's kind of the way, really.
> chore: reorganise PageHeader stories

- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
Contributes to #996 
Correction to page header title when using new breadcrumbs property
Added title to the new format of breadcrumbs.
Tests and storybook
> fix(PageHeader): title breadcrumb

- packages/cloud-cognitive/src/components/ActionBar/ActionBar.js
- packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js
- packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.test.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeaderDemo.data.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeaderUtils.js
Contributes to #996 
Get coverage to 100% for PageHeader and related components.
Added some Istanbul ignores to ActionBar, BradcrumbWithOverflow, ButtonSetWithOverflow, PageHeader
Ran tests and storybook.
> chore: page header tests 100 percent code coverage

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/ButtonSetWithOverflow/_button-set-with-overflow.scss
- packages/cloud-cognitive/src/components/_index-released-only.scss
- packages/cloud-cognitive/src/components/index.js
- packages/cloud-cognitive/src/global/js/package-settings.js
Release page header
- Changed flag for PageHeader and removed a spurious one for ActionBarItem in package-settings.js and components/index.js
- Added PageHeader scss to /src/components/_index-released-only.scss.
- ran the tests, recreating snapshots
storybook and test
> feat: release page header

- packages/cloud-cognitive/src/components/APIKeyModal/APIKeyDownloader.js
- packages/cloud-cognitive/src/components/APIKeyModal/APIKeyDownloader.test.js
- packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.test.js
Contributes to #954 
updated testing for apikey
> fix: update apikeymodal prop testing

- packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.stories.js
removes warning from apikey story
> fix: apikey story fix

- packages/cloud-cognitive/package.json
Resolves https://ibm-casdesign.slack.com/archives/C013ZTX0N6B/p1627494496145700
Add remaining Carbon packages as peer dependencies.
> feat(deps): add Carbon packages as peer dependencies

- packages/cloud-cognitive/package.json
- packages/core/.storybook/manager.js
Contributes to #1092 
Display current package version in Storybook.
> docs(storybook): add current version

- packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js
- packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.stories.js
- packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js
- packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepWithSectionsTearsheet.js
Contributes to #1085 
Fix args issue in CreateTearsheet stories.
`CreateTearsheet/CreateTearsheet.stories.js`
`CreateTearsheet/preview-components/MultiStepTearsheet.js`
`CreateTearsheet/preview-components/MultiStepWithSectionsTearsheet.js`
`CreateTearsheet/CreateTearsheet.js`
Storybook
> fix(CreateTearsheet): stories should receive args as expected now

- packages/cloud-cognitive/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.stories.js
Contributes to #1101 
Updated CreateTearsheetNarrrow story input validation to match Carbon guidelines.
`CreateTearsheetNarrow.stories.js`
Storybook
> chore(CreateTearsheetNarrow): update story input validation

- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeaderUtils.js
- packages/cloud-cognitive/src/components/PageHeader/_storybook-styles.scss
- packages/cloud-cognitive/src/global/js/hooks/index.js
- packages/cloud-cognitive/src/global/js/hooks/useWindowScroll.js
- packages/cloud-cognitive/src/global/js/utils/scrollableAncestor.js
Closes to #1067
- Fixed offset measurement which only worked if the page had not scrolled more than PageHeader height.
- Updated page header offset calculation to work within a scrollable element (not just window).
- Verified that scrolling beyond PageHeader height adjusting the width no longer caused the offset error.
- Verified that scrolling worked within a element other than the window
- Ran tests
> feat: fix offset and add element based scroll

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/ExportModal/_export-modal.scss
- packages/cloud-cognitive/src/components/ImportModal/_import-modal.scss
Contributes to #1181 & #1179 
adds some small css updates
> Import export updates

- packages/cloud-cognitive/src/components/SidePanel/SidePanel.mdx
Addresses https://ibm-cloud.slack.com/archives/G01PUCL3V8R/p1630532692032900
Fixes the broken preview of the side panel in storybook docs.
fyi @andrea-gm 
`SidePanel.mdx`
Storybook
> fix(SidePanel): update storyname in mdx doc file

- packages/cloud-cognitive/src/components/Cascade/Cascade.js
- packages/cloud-cognitive/src/components/Cascade/Cascade.test.js
- packages/cloud-cognitive/src/components/Cascade/_cascade.scss
- packages/cloud-cognitive/src/components/Cascade/_index.scss
- packages/cloud-cognitive/src/components/Cascade/_storybook-styles.scss
> fix: release review updates

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js
- packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.test.js
- packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheetDivider.js
- packages/cloud-cognitive/src/components/CreateTearsheet/_create-tearsheet.scss
- packages/cloud-cognitive/src/components/CreateTearsheet/index.js
- packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepWithSectionsTearsheet.js
- packages/cloud-cognitive/src/components/_index-released-only.scss
- packages/cloud-cognitive/src/components/index.js
- packages/cloud-cognitive/src/global/js/package-settings.js
Contributes to #1211 
Addresses feedback from @SimonFinney regarding the CreateTearsheet release.
`packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.js`
`packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheet.test.js`
`packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheetDivider.js`
`packages/cloud-cognitive/src/components/CreateTearsheet/_create-tearsheet.scss`
`packages/cloud-cognitive/src/components/CreateTearsheet/index.js`
`packages/cloud-cognitive/src/components/index.js`
`packages/cloud-cognitive/src/global/js/package-settings.js`
> fix(CreateTearsheet): updates based on release review

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/_index-released-only.scss
- packages/cloud-cognitive/src/global/js/package-settings.js
- packages/core/story-structure.js
> fix: cascade release

- .github/ISSUE_TEMPLATE/bug-report.md
Contributes to https://ibm-casdesign.slack.com/archives/G01PUCL3V8R/p1631117985004800
Update CodeSandbox bug report link to reflect directory structure.
> docs: update CodeSandbox bug report link

- packages/security/package.json
Contributes to https://github.com/carbon-design-system/ibm-security/issues/973
- Add `sideEffects` to package.json
Local test build and consumption.
> fix(security): add sideEffects for tree shaking

- packages/cloud-cognitive/src/components/APIKeyModal/APIKeyModal.js
Contributes to #1257 
technically `navigator.clipboard.writeText` is an asynchronous function and even though it wasn't causing issues locally not using `await` it appears to be an issue in certain environments. so now when a user clicks on the copy button it will check to make sure that copy works and consumes the promise. if there's an error caused by copying an error message will now appear. i also added an additional optional `onCopy` prop for users to provide their own copy function in case they don't want to or can't use the built in copying function.
no additional testing has been added because i have to first ensure this fixes the problem in codesandbox.
> fix: adds additional check for copy

- examples/cloud-cognitive/example-gallery/src/gallery-config/index.js
- scripts/example-gallery-builder/index.js
Contributes to #1274
Sort of fixes the example gallery thumbnails, although does not seem to run on pre-commit.
> Fix example gallery 

- packages/core/story-structure.js
story-structure.js
ran storybook
> fix: ensure story order matches PAL site

- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/global/js/utils/props-helper.js
PropTypes.oneOf takes an array, not a string.
> Silence warning in prop-types

- package.json
Corrects pre-commit script
main package.json
Tested committing a change
> fix: correct pre-commit for example gallery

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/ActionBar/ActionBar.js
- packages/cloud-cognitive/src/components/ActionBar/ActionBarOverflowItems.js
- packages/cloud-cognitive/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.js
- packages/cloud-cognitive/src/components/ButtonMenu/ButtonMenu.js
- packages/cloud-cognitive/src/components/ButtonSetWithOverflow/ButtonSetWithOverflow.js
- packages/cloud-cognitive/src/components/PageHeader/PageHeader.js
- packages/cloud-cognitive/src/components/PageHeader/_page-header.scss
Fixes z-index issues with breadcrumb, pageActions (when in  breadcrumb) and actionBar overflow. 
- CI Check
- Tests
- Storybook
> fix: overflwo z-indexes in page header

- examples/cloud-cognitive/example-gallery/src/App.scss
- examples/cloud-cognitive/example-gallery/src/GalleryCard.scss
Contributes to #1278
Styling updates to example gallery.
Make dummy cards the correct width (last row spaced properly).
Changed the thumbnail image to cover as it looks neater.
Changed the card title position.
Fix background only first page.
Prevent page jump on search removing scroll bar.
In browser testing.
> chore: tidy example gallery styling

- packages/cloud-cognitive/src/components/EditSidePanel/EditSidePanel.stories.js
- packages/cloud-cognitive/src/components/SidePanel/SidePanel.stories.js
> chore: replace deprecated icon Delete20 with TrashCan20

- packages/cloud-cognitive/src/components/Toolbar/Toolbar.test.js
- packages/cloud-cognitive/src/components/Toolbar/ToolbarButton.js
- Contributes to #67 
- Related to #1469 
Refactor `Toolbar` tests to improve readability and provide utility for testing variant accessibility.
> test: refactor `Toolbar` tests

- packages/cloud-cognitive/src/components/AddSelect/AddSelect.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelect.test.js
- packages/cloud-cognitive/src/components/AddSelect/_add-select.scss
- packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.stories.js
- packages/cloud-cognitive/src/components/SingleAddSelect/SingleAddSelect.stories.js
Contributes to #1578 
adds selection functionality to `AddSelect`
> fix: adds selection functionality to add select

- packages/cloud-cognitive/src/components/SidePanel/SidePanel.stories.js
Contributes to #1568 
Added danger buttons to SidePanel stories.
`SidePanel.stories.js`
Storybook
> chore(SidePanel): #1568 add danger to side panel stories

- packages/cloud-cognitive/src/components/AddSelect/AddSelect.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelect.test.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectBreadcrumbs.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectList.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectSidebar.js
Breaks up `AddSelect` into several smaller components-
* `AddSelectSidebar`
* `AddSelectBreadcrumbs`
* `AddSelectList`
> fix: breakup add select into multiple components

- packages/cloud-cognitive/src/components/ActionSet/ActionSet.stories.js
- packages/cloud-cognitive/src/components/ActionSet/_storybook-styles.scss
- packages/cloud-cognitive/src/global/js/utils/DisplayBox.js
Use nice new extent indicator instead of weird shadowy box thing.
ActionSet stories
Ran storybook
> chore(ActionSet): use extent indicator in stories

- packages/cloud-cognitive/src/components/AddSelect/AddSelect.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectColumn.js
- packages/cloud-cognitive/src/components/AddSelect/_add-select.scss
- packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.stories.js
Contributes to #1713
adds overflow and individual column filtering support to multi select with hierarchy. screenshot for reference-
> fix: add select multi select filtering

- packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js
Contributes to #1724 
Replaces the use of `event.keyCode` with `event.key`.
`DataSpreadsheet.js`
Storybook
> chore(DataSpreadsheet): use event.key in replace of keyCode

- packages/cloud-cognitive/src/components/AddSelect/AddSelectColumn.js
- packages/cloud-cognitive/src/components/AddSelect/_add-select.scss
Contributes to #1752 
this PR begins the work to implement the sort and filter functionality for add select columns. there's no current functionality built in to this. this just lays the groundwork with the initial html framework, so for the sake of this PR you can ignore the fact the values for the overflow dropdown's aren't being dynamically created. the next step is figuring out how to generate the dropdown items.
> fix: adds the filter and sort buttons to add select columns

- packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.js
- packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.test.js
Contributes to #1492 
Address missing test coverage
InlineEdit.test.js
Ran `yarn test:c4p --coverage`
> fix(InlineEdit): test coverage update

- package.json
Fix build issue caused by below v1 versions not updating as part of release.
Changed to "*" as per "stylelint-config-ibm-products".
> fix: component usage version in package

- packages/cloud-cognitive/src/components/AboutModal/_about-modal.scss
- packages/cloud-cognitive/src/components/ActionSet/_action-set.scss
- packages/cloud-cognitive/src/components/AddSelect/_add-select.scss
- packages/cloud-cognitive/src/components/CreateModal/_create-modal.scss
- packages/cloud-cognitive/src/components/CreateModal/_storybook-styles.scss
- packages/cloud-cognitive/src/components/ExportModal/_export-modal.scss
- packages/cloud-cognitive/src/components/ModifiedTabs/_modified-tabs.scss
- packages/cloud-cognitive/src/components/NotificationsPanel/_notifications-panel.scss
- packages/cloud-cognitive/src/components/RemoveModal/_remove-modal.scss
- packages/cloud-cognitive/src/components/TagSet/_tag-set.scss
- packages/cloud-cognitive/src/components/Tearsheet/_tearsheet.scss
- packages/security/src/components/LayoutModules/ListItemModule/_index.scss
Replace use of bx in style files
Remaining instances of 'bx' found in .scss file in the packages folder.
Storybook, build and test.
> chore: remove bx from style files

- packages/cloud-cognitive/src/components/AddSelect/AddSelectList.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectSidebar.js
- packages/cloud-cognitive/src/components/AddSelect/_add-select.scss
- packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.stories.js
Contributes to #1859 
adds icon support for add select rows
> fix: add select icon support

- cspell.json
- netlify.toml
Contributes to #1871 
As discussed [here](https://github.com/netlify/build-image/issues/612#issuecomment-925772672), this is a potential work around for us to resolve our netlify build time out issues that we've been experiencing.
`netlify.toml`
`cspell.json`
Hopefully the branch deploy/netlify logs from this PR will give us some insight into this approach
> chore: test yarn netlify configuration

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/ExportModal/_export-modal.scss
> fix: show export modal close icon

- packages/cloud-cognitive/src/components/AddSelect/AddSelect.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelect.test.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectFilter.js
- packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.js
- packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.mdx
- packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.stories.js
- packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.test.js
- packages/cloud-cognitive/src/components/SingleAddSelect/SingleAddSelect.js
- packages/cloud-cognitive/src/components/SingleAddSelect/SingleAddSelect.mdx
- packages/cloud-cognitive/src/components/SingleAddSelect/SingleAddSelect.stories.js
- packages/cloud-cognitive/src/components/SingleAddSelect/SingleAddSelect.test.js
some cleanup and starts adding documentation for proptypes and the mdx files. there's still some todo's left, but i'll complete it in a follow up PR.
> chore: add select documentation

- packages/cloud-cognitive/src/components/AddSelect/AddSelectColumn.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectSort.js
- packages/cloud-cognitive/src/components/AddSelect/add-select-utils.js
- packages/cloud-cognitive/src/components/AddSelect/hooks/useItemSort.js
Contributes to #1964
extracts existing add select sorting functionality so that it can be reused for global sorting.
> chore: add select extract sorting

- packages/cloud-cognitive/src/components/AddSelect/AddSelect.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectColumn.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectFilter.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectSort.js
- packages/cloud-cognitive/src/components/AddSelect/_add-select.scss
- packages/cloud-cognitive/src/components/AddSelect/add-select-utils.js
- packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.stories.js
Contributes to #1964 
adds global sort functionality and some additional cleanup
> fix: global sort functionality for add select

- packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetBody.js
After changing the `cellSize` prop in storybook, the active cell placement becomes incorrect. To fix this, I just made sure that when `cellSize` changes, the placement of the active cell is updated along with all of the selection areas.
`DataSpreadsheetBody.js`
Storybook (changing the `cellSize` control in storybook is the easiest way to test this, by comparing the interaction that can be seen from this preview deploy vs the current storybook site).
> fix(DataSpreadsheet): update active cell location after cellSize change

- packages/cloud-cognitive/src/components/AddSelect/AddSelectSidebar.js
fixes small bug in the sidebar
> fix: add select sidebar bug

- docs/reviews/RELEASE_REVIEW_GUIDELINES.md
- package.json
- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/_index-released-only.scss
- packages/cloud-cognitive/src/global/js/package-settings.js
> feat: inline edit release

- packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
Contributes to #2023 
We need to check to make sure `window` exists before accessing it for ssr applications.
`SidePanel.js`
We've made similar fixes in other components that have had the same issue
> fix(SidePanel): check if window exists for reduced motion logic

- packages/cloud-cognitive/src/components/SidePanel/SidePanel.stories.js
- packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
Contributes to #2020 
Update SidePanel story and styles for C11
Fix grid on SlideIn story and correct icon sizing.
Use `c4p-settings` namespace in styles and fix linting issues.
Storybook
> chore: update SidePanel

- .github/workflows/release.yml
Make comment to release.yml schedule
`release.yml`
> chore: add comment to release.yml

- packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.js
- packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.test.js
Contributes to #2071
Updates aria label and skips accessibility test
- Adds aria label for RemoveModal
- Skips test due to Carbon changes
Ran tests
> chore: update RemoveModal accessibility

- packages/cloud-cognitive/src/components/TagSet/TagSet.test.js
Contributes to #2071
Fix test in TagSet for v11
Fix undefined length for tagTypes
Ran tests
> chore: update TagSet test

- .github/workflows/sync-main.yml
Contributes to #2134
Add workflow from #2151 to `main` branch
Cherry picked the commit to branch based off `main`
#2151
> chore: add action to sync v11 with main

- packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js
- packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.stories.js
- packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.test.js
- packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetHeader.js
- packages/cloud-cognitive/src/components/DataSpreadsheet/utils/handleMultipleKeys.js
Partially contributes to #1976 
Addresses some of @janhassel review comments.
```
packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.stories.js
```
Storybook
> fix(DataSpreadsheet): add missing aria labels and update arialabelled-by

- packages/cloud-cognitive/src/components/AddSelect/AddSelectBody.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectBody.test.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectList.js
Contributes to #2077
fixes a bug that was being caused when the user submitted or closed the add select component. basically the problem was being caused by the internal state not resetting when the component closed.
> fix: reset state on submit or close

- packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js
- packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheetBody.js
Addresses @janhassel's feedback around voice over usage with the spreadsheet component.
`DataSpreadsheet.js`
`DataSpreadsheetBody.js`
> chore(DataSpreadsheet): add aria-owns for voice over support

- packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.js
- packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.test.js
> fix: inline edit newline fix v11

- packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.js
- packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.stories.js
adds a few stories for inline edit v2
> fix: add inline edit v2 stories

- packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.js
- packages/cloud-cognitive/src/components/InlineEditV2/_inline-edit-v2.scss
Contributes to #2375 
addresses the two small issues in the design review for inline edit v2
> fix: design review fixes

- packages/cloud-cognitive/src/components/InlineEdit/InlineEdit.js
- packages/cloud-cognitive/src/components/InlineEdit/index.js
- packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.js
- packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.stories.js
- packages/cloud-cognitive/src/components/InlineEditV2/InlineEditV2.test.js
- packages/cloud-cognitive/src/components/InlineEditV2/_index.scss
- packages/cloud-cognitive/src/components/InlineEditV2/_inline-edit-v2.scss
- packages/cloud-cognitive/src/components/InlineEditV2/_storybook-styles.scss
> fix: various updates from release review

- packages/cloud-cognitive/src/components/AddSelect/add-select-utils.js
> fix: add select filter fix

- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterProvider.js
- packages/cloud-cognitive/src/components/FilterSummary/FilterSummary.js
- packages/cloud-cognitive/src/components/FilterSummary/FilterSummary.stories.js
- packages/cloud-cognitive/src/components/FilterSummary/_filter-summary.scss
- packages/cloud-cognitive/src/components/FilterSummary/_index.scss
- packages/cloud-cognitive/src/components/FilterSummary/_storybook-styles.scss
- packages/cloud-cognitive/src/components/FilterSummary/index.js
- packages/cloud-cognitive/src/components/_index.scss
- packages/core/story-structure.js
This adds FilterSummary component
> feat: adds FilterSummary

- README.md
- packages/cloud-cognitive/README.md
Quick fix to CI badges to use updated syntax
Use status badge from CI workflow instead of query.
> chore: fix CI badges

- README.md
- packages/cloud-cognitive/README.md
Quick fix to CI badges to use updated syntax
Use status badge from CI workflow instead of query.
> chore: fix CI badges v11

- packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.js
- packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.stories.js
- packages/cloud-cognitive/src/components/RemoveModal/RemoveModal.test.js
> fix: adds primaryButtonDisabled prop to RemoveModal  v11

- packages/cloud-cognitive/src/components/Card/Card.js
> fix: card action bug fix

- .all-contributorsrc
- README.md
- cspell.contributors.txt
- cspell.html.txt
Adds @jagathgj as a contributor for code on v11 branch
README.md
.all-contributorsrc
Cspell
Verified in Markdown preview
> docs: add jagathgj as contributor for code

- examples/carbon-for-ibm-products/example-gallery/src/GalleryCard.scss
- examples/carbon-for-ibm-products/example-gallery/src/_carbon-settings.scss
- examples/carbon-for-ibm-products/example-gallery/src/_carbon.scss
Removes some unnecessary example gallery SCSS.
Tested locally and on codesandbox.
> chore: simplify example gallery scss

- packages/cloud-cognitive/src/components/index.js
This PR exports useFiltering from index.js
> fix: exports useFiltering (v11)

- packages/cloud-cognitive/src/components/Datagrid/useFiltering.js
- packages/cloud-cognitive/src/components/Datagrid/utils/DatagridActions.js
Exports FilterFlyout from datagridState
> feat(Datagrid): exports FilterFlyout from datagridState (v11)

- packages/cloud-cognitive/src/components/Datagrid/styles/_useExpandedRow.scss
Contributes to #2502 
Expanded row content align issue fixed
Updated spacing token
storybook
> fix(Expandable rows): spacing updated

- packages/cloud-cognitive/src/components/MultiAddSelect/MultiAddSelect.mdx
- packages/cloud-cognitive/src/components/SingleAddSelect/SingleAddSelect.mdx
- yarn.lock
> chore: add select docs update

- .github/ISSUE_TEMPLATE/accessibilty-review.md
- cspell.html.txt
Contributes to #2232
Adds a new issue template for accessibility review.
Added new issue template.
> chore: add accessibility review template

- .github/ISSUE_TEMPLATE/accessibilty-review.md
- cspell.html.txt
Contributes to #2232
Adds a new issue template for accessibility review.
Added new issue template.
> chore: add accessibility review template v11

- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.js
- packages/cloud-cognitive/src/components/Tearsheet/Tearsheet.stories.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetNarrow.stories.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js
- packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.stories.js
v11 port of #2617 
See original PR for details.
> docs(tearsheet): update "portalTarget" prop name in stories (v11)

- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js
Contributes to #2649 
Filter left panel & filter flyout: add "Any" option to Radio buttons and Dropdowns and make the default selected
`addons/Filtering/FilterFlyout.js`
`addons/Filtering/FilterPanel.js`
Storybook
> fix(DataGrid): any option in filter panel v11

- packages/cloud-cognitive/src/components/OptionsTile/_options-tile.scss
> fix(options-tile): add safe area around toggle

- packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridContent.js
- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js
- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterProvider.js
- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/hooks/index.js
- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/utils.js
- packages/cloud-cognitive/src/components/Datagrid/utils/DatagridActions.js
This PR takes the combined logic from filter flyout and panel and merges them into a hook so that the code stays DRY.
> feat(Datagrid): Extracts Filtering logic into useFilters hook (v11)

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/EmptyStates/_empty-state.scss
> fix(empty-state): update type tokens

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/HTTPErrors/_http-errors.scss
> fix(http-errors): update type tokens

- .github/workflows/sync-commit.yml
> chore: test default GitHub token

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/ActionSet/_action-set.scss
- packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.js
> fix(create-full-page): update button sizes

- packages/cloud-cognitive/src/components/Tearsheet/TearsheetShell.js
> fix(tearsheet-shell): use `Layer` for `wide` only

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPage.stories.js
- packages/cloud-cognitive/src/components/CreateFullPage/CreateFullPageStep.js
- packages/cloud-cognitive/src/components/CreateFullPage/_create-full-page.scss
> fix(create-full-page): fix grid usage examples

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
- packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
> fix(side-panel): fix icon button alignment

- packages/cloud-cognitive/src/components/AddSelect/AddSelectBreadcrumbs.js
- packages/cloud-cognitive/src/components/AddSelect/AddSelectList.js
- packages/cloud-cognitive/src/components/AddSelect/_add-select.scss
the v10 version of https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2709
> fix: add select keyboard accessibility fixes

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/SidePanel/SidePanel.js
- packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
* fix(side-panel): fix icon button alignment
* chore(side-panel): remove unused class
---------
Contributes to #2810
> fix(side-panel): fix icon button alignment (#2814)

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/CreateTearsheet/CreateTearsheetStep.js
- packages/cloud-cognitive/src/components/CreateTearsheet/_create-tearsheet.scss
- packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js
- packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepWithIntro.js
> fix(create-tearsheet): fix grid usage examples

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/SidePanel/_side-panel.scss
> fix(side-panel): fix close button hover state

- packages/cloud-cognitive/src/global/js/utils/story-helper.js
Contributes to https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2755
Documentation at https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2799
> feat(storybook): new fn getSelectedCarbonTheme

- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js
- packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss
Contributes to #2700 
Adds support for i18n and changes overflow-y from scroll to auto in the table container
> feat(Datagrid): adds i18n support and change overflow-y

- packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
> fix(Datagrid): filtering number empty tag bug (v11)

- packages/cloud-cognitive/src/__tests__/__snapshots__/styles.test.js.snap
- packages/cloud-cognitive/src/components/UserProfileImage/_user-profile-image.scss
Contributes to #2839 
improves the focus state of the user profile image. visual change approved by shaun and marwa
> fix: user profile image focus v11

- .all-contributorsrc
- README.md
- cspell.contributors.txt
Add @lily-peng and @mgallo25 as contributors for code.
This was requested by elycheea [in this comment](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2756#issuecomment-1516309259) and [in this comment](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2900#issuecomment-1516325679)
> docs: add lily-peng and mgallo25 as contributors for code

- packages/cloud-cognitive/README.md
- packages/cloud-cognitive/src/components/ExampleComponent/ExampleComponent.js
- packages/cloud-cognitive/src/components/ExampleComponent/ExampleComponent.stories.js
- packages/cloud-cognitive/src/components/ExampleComponent/ExampleComponent.test.js
- packages/cloud-cognitive/src/components/ExampleComponent/useExample.js
- packages/cloud-cognitive/src/global/js/package-settings.js
- packages/cloud-cognitive/src/global/js/utils/test-helper.js
- packages/core/.storybook/index.scss
- packages/core/.storybook/preview.js
Contributes to #2747
The same faetures as PR 2748 but without the DataGrid feature flag bit, just update the example component.
Merged feature flag examples down from V2.
Storybook
> feat: feature flagging in v1 with example

- packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products/src/components/AddSelect/AddSelectBody.js
- packages/ibm-products/src/components/AddSelect/AddSelectColumn.js
- packages/ibm-products/src/components/AddSelect/AddSelectRow.js
- packages/ibm-products/src/components/AddSelect/_add-select.scss
Contributes to https://github.ibm.com/CDAI-design/pal/issues/1172
addresses a number of styling issues brought up during migration review. a few things are still left to do, but this is a start.
> fix: various style fixes for add select for the v2 migrations

- packages/cloud-cognitive/package.json
- yarn.lock
DataGrid has an undeclared dependancy on lodash, this PR adds it.
> fix: add missing lodash dependency

- .github/workflows/release.yml
> fix: release action for v1

- .github/workflows/release.yml
Attempt to correct release.yml
> Main v1 release action

- .github/workflows/ci.yml
Figured this one out with @matthewgallo on zoom.
Taking that as a review.
> fix: ci disable security and cdai check

- .github/workflows/release.yml
- config/babel-preset-ibm-cloud-cognitive/CHANGELOG.md
- config/babel-preset-ibm-cloud-cognitive/index.js
- config/babel-preset-ibm-cloud-cognitive/package.json
- config/cli/CHANGELOG.md
- config/cli/package.json
- config/jest-config-ibm-cloud-cognitive/CHANGELOG.md
- config/jest-config-ibm-cloud-cognitive/index.js
- config/jest-config-ibm-cloud-cognitive/package.json
- config/storybook-addon-carbon-theme/CHANGELOG.md
- config/storybook-addon-carbon-theme/package.json
- config/stylelint-config-ibm-products/CHANGELOG.md
- config/stylelint-config-ibm-products/index.js
- config/stylelint-config-ibm-products/package.json
- lerna.json
- packages/component-usage-report/package.json
- yarn.lock
The build is still failing, probably need to ensure we update lerna and perhaps other dependencies too.
> fix: bring config & version numbers up to those in v1

- packages/ibm-products/src/components/ImportModal/ImportModal.js
> fix: reset import modal state on close

- config/storybook-addon-carbon-theme/CHANGELOG.md
Update the change log to note V1 release.
> fix: storybook addon change log

- packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products/src/components/AddSelect/_add-select.scss
- packages/ibm-products/src/components/CreateFullPage/_create-full-page.scss
- packages/ibm-products/src/components/CreateModal/_create-modal.scss
- packages/ibm-products/src/components/CreateSidePanel/_create-side-panel.scss
- packages/ibm-products/src/components/CreateTearsheet/_create-tearsheet.scss
- packages/ibm-products/src/components/CreateTearsheet/_storybook-styles.scss
- packages/ibm-products/src/components/CreateTearsheetNarrow/_create-tearsheet-narrow.scss
- packages/ibm-products/src/components/DataSpreadsheet/_data-spreadsheet.scss
- packages/ibm-products/src/components/Datagrid/_storybook-styles.scss
- packages/ibm-products/src/components/EditSidePanel/_edit-side-panel.scss
- packages/ibm-products/src/components/EditTearsheet/_edit-tearsheet.scss
- packages/ibm-products/src/components/EditTearsheet/_storybook-styles.scss
- packages/ibm-products/src/components/ImportModal/_import-modal.scss
- packages/ibm-products/src/components/NotificationsPanel/_notifications-panel.scss
- packages/ibm-products/src/components/OptionsTile/_storybook-styles.scss
- packages/ibm-products/src/components/PageHeader/_page-header.scss
- packages/ibm-products/src/components/Saving/_saving.scss
- packages/ibm-products/src/components/SidePanel/_side-panel.scss
- packages/ibm-products/src/components/TagSet/_tag-set.scss
- packages/ibm-products/src/components/Tearsheet/_tearsheet.scss
- packages/ibm-products/src/components/Toolbar/Toolbar.test.js
- packages/ibm-products/src/components/UserProfileImage/_user-profile-image.scss
Contributes to #3028 
Replace v10 type and theme tokens
Replaced v10 tokens with v11 tokens as in the following reference [https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md)
Updated breaking test in `Toolbar/Toolbar.test.js`
Storybook
> fix: update type and theme tokens

- packages/ibm-products/package.json
- yarn.lock
Contributes to #3166 
Swap `@carbon/react` peer dependency to allow `minor` and not just `patch` changes
- Change from `~` to `^` for @carbon/react peer dependency
- cloned repo
- yarn && yarn test
> chore: update package.json

- packages/ibm-products/src/global/js/hooks/useResizeObserver.js
Contributes to #3172 
based on https://github.com/carbon-design-system/ibm-products/pull/3176
> fix: infinite perspective issue

- packages/core/src/component-playground/components/Tearsheet/TearsheetWide.js
- packages/ibm-products/src/components/APIKeyModal/APIKeyModal.js
- packages/ibm-products/src/components/AboutModal/AboutModal.test.js
- packages/ibm-products/src/components/ActionBar/ActionBar.js
- packages/ibm-products/src/components/CreateFullPage/CreateFullPage.js
- packages/ibm-products/src/components/CreateFullPage/CreateFullPage.test.js
- packages/ibm-products/src/components/CreateModal/CreateModal.js
- packages/ibm-products/src/components/CreateModal/CreateModal.mdx
- packages/ibm-products/src/components/CreateModal/CreateModal.test.js
- packages/ibm-products/src/components/CreateSidePanel/CreateSidePanel.js
- packages/ibm-products/src/components/CreateSidePanel/CreateSidePanel.mdx
- packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.js
- packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.test.js
- packages/ibm-products/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.js
- packages/ibm-products/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.test.js
- packages/ibm-products/src/components/EditSidePanel/EditSidePanel.js
- packages/ibm-products/src/components/ExportModal/ExportModal.test.js
- packages/ibm-products/src/components/ImportModal/ImportModal.test.js
- packages/ibm-products/src/components/Tearsheet/Tearsheet.test.js
- packages/ibm-products/src/components/Tearsheet/TearsheetShell.js
- packages/ibm-products/src/components/WebTerminal/WebTerminal.test.js
Contributes to #3177
v1 port of @lee-chase’s work on #3179 
- Add aria-labels to components with a11y issues.
- Update stories and tests
Ran tests
> fix: improve a11y tests

- packages/ibm-products/src/components/InlineTip/InlineTip.mdx
Update documentation after review from content designer. All Novice to Pro components will be updated to reflect latest IBM content guidelines.
Guidebanner `mdx` file only.
Requires sign off from content designer Lynn Harding.
> docs(InlineTip): Update doc after review

- packages/ibm-products/src/components/Guidebanner/Guidebanner.mdx
Update documentation after review from content designer. All Novice to Pro components will be updated to reflect latest IBM content guidelines.
Guidebanner `mdx` file only.
Requires sign off from content designer Lynn Harding.
> docs(Guidebanner): Update doc after review

- packages/ibm-products/src/components/NonLinearReading/NonLinearReading.mdx
Update documentation after review from content designer. All Novice to Pro components will be updated to reflect latest IBM content guidelines.
NonLinearReading `mdx` file only.
Requires sign off from content designer Lynn Harding.
> docs(NonLinearReading): Update doc after review

- .github/workflows/codeql.yml
- .github/workflows/pr.yml
Cleanup workflow yml files after all of the `merge_group` additions 😅
> fix: remove duplicate merge_group and remove from title validation

- .github/workflows/add-to-merge-queue.yml
Attempt to fix permissions issue in merge queue workflow
> chore: move merge queue permissions

- examples/carbon-for-ibm-products/react-16-example/yarn.lock
- examples/carbon-for-ibm-products/react-17-example/yarn.lock
Closes #3390 #3391 #3392 #3393 
Bump semver from 6.3.0 to 6.3.1 and word-wrap from 1.2.3 to 1.2.5 in react 16 and 17 examples
> chore(deps): bump semver to 6.3.1 and word-wrap to 1.2.5 

- .github/workflows/dco.yml
This adds the DCO workflow. I also added the DCO token to the repo secrets.
There's not a good way to test actions until they're in main 😕
> ci(dco): add dco workflow

- packages/ibm-products/src/components/NonLinearReading/NonLinearReading.js
- packages/ibm-products/src/components/NonLinearReading/NonLinearReading.test.js
- packages/ibm-products/src/components/NonLinearReading/_non-linear-reading.scss
Contributes to #3423 (review issue) and #2857 (failing accessibility test)
- **3423** Update code and styling to meet accessibility guidelines.
- **2857** Confirm that previous failing test `await expect(container).toBeAccessible(componentName)`, which was previously commented out, now passes.
- Updated JS to include `aria` features.
- Updated SCSS for better hover and focus outlines.
> fix(NonLinearReading): accessibility review changes

- packages/ibm-products/src/components/Checklist/Checklist.js
- packages/ibm-products/src/components/Checklist/Checklist.stories.js
- packages/ibm-products/src/components/Checklist/ChecklistChart.js
Contributes to #3456
Reviewed code and styling to meet accessibility guidelines.
Very little. Most of the accessibility features were added in the original PR while I was learning to implement accessibility features. Minor change to replace bespoke `ariaLabelledBy` chart prop with standard `aria-labelledby` attribute to take advantage of `<ChecklistChart {...rest} />` instead.
> fix(Checklist): accessibility review changes

- packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js
Contributes to #3241 
fixes additional bug where clicking inside the dropdown closed the dropdown
> fix: datagrid row height click

- packages/ibm-products/src/components/Checklist/ChecklistChart.js
Contributes to https://github.ibm.com/security/novice-to-pro-components/issues/193
Minor design update
Just the colors for the Checklist donut colors, light and dark themes.
> fix(Checklist): update checklist donut chart colors

- packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js
Contributes to #2042 
Add spacebar usage of checkbox for the column customsation.
Datagrid column customisation.
Storbyook
> fix: checkbox in column customisation

- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js
- packages/ibm-products/src/components/Datagrid/utils/DatagridPagination.js
> fix: datagrid pagination fixes v1

- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.js
- packages/ibm-products/src/components/Datagrid/_datagrid.scss
- packages/ibm-products/src/components/Datagrid/utils/DatagridActions.js
Contributes to #3442 
address issues from the datagrid actions release review
> fix: datagrid actions review fixes

- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.js
- packages/ibm-products/src/components/Datagrid/_datagrid.scss
> chore: toolbar review fixes

- packages/ibm-products/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products/src/components/StatusIcon/StatusIcon.js
- packages/ibm-products/src/components/StatusIcon/_status-icon.scss
Contributes to #2850 
`in-progress`, `pending`, and `running` icons updated for `StatusIcon` component
updated icon imports and scss
storybook
> fix(status icon): updated icons

- packages/ibm-products/src/components/Datagrid/Datagrid.docs-page.js
- packages/ibm-products/src/components/Datagrid/useSortableColumns.js
Contributes to #3445 
removes some optional hardcoded strings and cleans up a bit of redundant code
> chore: datagrid sort review updates

- packages/ibm-products/src/components/Datagrid/Datagrid.stories.js
- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js
- packages/ibm-products/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
Contributes to #3508 
Addresses some of the items that came up during the design review for "Row height/settings" extension.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js
packages/ibm-products/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
```
Storybook and made sure all Datagrid tests still pass
> chore(Datagrid): row settings design review fixes (v1)

- packages/ibm-products/src/components/Datagrid/Datagrid.stories.js
- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js
- packages/ibm-products/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
Contributes to #3508 
Addresses some of the items that came up during the design review for "Row height/settings" extension.
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeDropdown.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/RowSize/RowSizeRadioGroup.js
packages/ibm-products/src/components/Datagrid/styles/addons/_RowSizeDropdown.scss
```
Storybook and made sure all Datagrid tests still pass
> chore(Datagrid): row settings design review fixes

- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js
Contributes to #3737
Fixes a column resize bug in the Datagrid where if you resized a column focusable items outside of the Datagrid seemed to lose focus. There was some extra logic in the resize end action to prevent this behavior.
While working on this issue, I discovered that we don't need to handle all of the custom logic to handle mouse events with resizing, `react-table` will still take care of that even if we want custom control over the key events so that we have keyboard support with resizing columns. Because of this, I was able to remove some code from `DatagridHeaderRow.js`.
```
```
Storybook
> fix(Datagrid): address resize end issues

- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.js
- packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js
- packages/ibm-products/src/components/Datagrid/useSelectRows.js
> fix: datagrid batch actions release review fixes

- packages/ibm-products/src/components/Datagrid/Datagrid.docs-page.js
- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
- packages/ibm-products/src/components/Datagrid/styles/_datagrid.scss
- packages/ibm-products/src/components/Datagrid/useInfiniteScroll.js
- packages/ibm-products/src/components/Datagrid/useParentDimensions.js
- packages/ibm-products/src/components/Datagrid/useResizeTable.js
- packages/ibm-products/src/components/Datagrid/useSkeletonRows.js
Contributes to #3468 
Review fixes after reviewing `useInfiniteScroll`, refactored virtualized data test.
```
packages/ibm-products/src/components/Datagrid/useInfiniteScroll.js
packages/ibm-products/src/components/Datagrid/useParentDimensions.js
packages/ibm-products/src/components/Datagrid/useResizeTable.js
packages/ibm-products/src/components/Datagrid/useSkeletonRows.js
```
Storybook, confirmed test passed after refactoring
> chore(Datagrid): review changes from `useInfiniteScroll`/virtual review

- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridToolbar.js
- packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js
- packages/ibm-products/src/components/Datagrid/useSelectRows.js
> fix: batch actions review fixes v1

- packages/ibm-products/src/components/AddSelect/AddSelectBody.test.js
- packages/ibm-products/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.js
- packages/ibm-products/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.js
- packages/ibm-products/src/components/EmptyStates/assets/ErrorIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NoDataIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NoTagsIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NotFoundIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NotificationsIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/UnauthorizedIllustration.js
Contributes to #3731 
was originally addressed in https://github.com/carbon-design-system/ibm-products/pull/3741 but because that refactor is still under review we decided to split out this fix to get it out sooner
> fix: empty state accessibility update

- packages/ibm-products/src/components/AddSelect/AddSelectBody.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.js
- packages/ibm-products/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.js
- packages/ibm-products/src/components/EmptyStates/assets/ErrorIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NoDataIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NoTagsIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NotFoundIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NotificationsIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/UnauthorizedIllustration.js
> fix: empty state accessibility fix v1

- .github/workflows/release-preminor.yml
- .github/workflows/release-scheduled.yml
Hopefully fixes release workflow.
> fix: release workflow

- .github/workflows/release-preminor.yml
- .github/workflows/release.yml
Progress! But it seems we forgot to put the `publish` back in after `lerna publish`. 😅 Should have caught it in the original PR.
🙏 🤞
> fix: lerna publish

- packages/ibm-products/src/components/Datagrid/Datagrid.stories/StickyActionsColumnStory.js
- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Extensions/RowActionButtons/RowActionButtons.stories.js
- packages/ibm-products/src/components/Datagrid/useFlexResize.js
solves issue of the actions column not floating to the right of the spacer. this PR will check for an actions column and if found will move it to the end after the spacer.
> fix: move spacer and actions to the end

- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.js
- packages/ibm-products/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.js
Contributes to #3731 
missed applying a title in the no data illustration
> fix: no data empty state title

- cspell.html.txt
- packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
- packages/ibm-products/src/components/SidePanel/SidePanel.js
- packages/ibm-products/src/components/SidePanel/SidePanel.stories.js
Contributes to #3752
https://github.com/carbon-design-system/carbon-for-ai/issues/16
Add AI slug and background
Side Panel to accommodate the slug
Storybook
> feat: Side panel ai enhancements

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
- packages/ibm-products/src/components/SidePanel/SidePanel.js
Side panel erroring in storybook complaining that `getActionsContainerElement` is used before initialisation.
- Moved function higher before usage.
- Also tweaks close and slug position to fixed from absolute to help web component version.
Ran storybook and checked scroll
> fix: published side panel error

- .github/workflows/release-v1.yml
- .github/workflows/release.yml
- config/storybook-addon-carbon-theme/package.json
- packages/ibm-products-styles/package.json
- packages/ibm-products/package.json
Contributes to #3748 
Finally doing this even though the steps really were as simple as Taylor described 🙈 https://github.com/carbon-design-system/ibm-products/issues/3748#issuecomment-1802190991
Add workflow permissions Ensure workflow permissions include `id-token: write` and `contents: write`
Add `provenance: true` to publishConfigs
GitHub actions are hard to test but perhaps we can do a prerelease after merge??
> chore: publish packages with provenance

- packages/ibm-products/src/components/ExportModal/ExportModal.stories.js
Contributes to #3944
Add dropdown menu for validExtensions & preformattedExtensions
`packages/ibm-products/src/components/ExportModal/ExportModal.stories.js`
Storybook
> chore(ExportModal): add dropdown menu for validExtensions & preformattedExtensions

- packages/ibm-products-styles/src/components/Guidebanner/_guidebanner.scss
- packages/ibm-products/src/components/Guidebanner/Guidebanner.js
- packages/ibm-products/src/components/Guidebanner/Guidebanner.stories.js
Contributes to #3903
New prop `withLeftGutter`
> fix(Guidebanner): allow adding 1rem space on the left

- cspell.json
- packages/ibm-products/src/components/Guidebanner/Guidebanner.js
- packages/ibm-products/src/components/Guidebanner/Guidebanner.stories.js
- packages/ibm-products/src/components/Guidebanner/_guidebanner.scss
Contributes to #3903
Is related to `v2` PR #3965 
New prop `withLeftGutter`
> fix(Guidebanner): allow adding 1rem space on the left, v1

- packages/ibm-products-styles/src/components/InlineTip/_inline-tip.scss
- packages/ibm-products/src/components/InlineTip/InlineTip.js
- packages/ibm-products/src/components/InlineTip/InlineTip.stories.js
Contributes to #3904
Is related to `v2` PR #3978  
New prop `withLeftGutter`
> fix(InlineTip): allow adding 1rem space on the left, v2

- cspell.json
- packages/ibm-products/src/components/InlineTip/InlineTip.js
- packages/ibm-products/src/components/InlineTip/InlineTip.stories.js
- packages/ibm-products/src/components/InlineTip/_inline-tip.scss
Contributes to #3904 
Is related to `v2` PR #3969 
New prop `withLeftGutter`
> fix(InlineTip): allow adding 1rem space on the left, v1

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products-styles/src/components/SidePanel/_side-panel.scss
Contributes to #3896 
Refactor some SASS
- Removed duplicate generated SCSS for placement.
> chore: move sass out of loop

- packages/ibm-products-styles/src/components/Datagrid/styles/_datagrid.scss
- packages/ibm-products/src/components/WebTerminal/WebTerminal.js
Contributes to #4007 
fixes an on hover issue and apparently formats a bunch of code
> fix: datagrid empty state hover background color

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products/src/components/APIKeyModal/APIKeyModal.stories.js
Contributes to #3973 
Updates control for generateSuccessBody
`packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap`
`packages/ibm-products/src/components/APIKeyModal/APIKeyModal.stories.js`
Storybook
> chore(APIKeyModal): control dropdown for generateSuccessBody

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products/src/components/ImportModal/ImportModal.stories.js
Contributes to #4014 
Add dropdown menu for accept control
`packages/ibm-products/src/components/ImportModal/ImportModal.stories.js`
`packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap`
Storybook
> chore(ImportModal): Add dropdown control for accept

- packages/ibm-products/src/components/RemoveModal/RemoveModal.stories.js
Contributes to #4020 
Remove uneeded portalTarget control
`packages/ibm-products/src/components/RemoveModal/RemoveModal.stories.js`
Storybook
> chore(RemoveModal): Remove unneeded portalTarget control

- packages/ibm-products/src/components/Toolbar/Toolbar.stories.js
Contributes to #4029 
Add boolean control for vertical control
`packages/ibm-products/src/components/Toolbar/Toolbar.stories.js`
Storybook
> chore(Toolbar): add boolean control for vertical

- packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
> fix: close filter flyout on cancel

- packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.js
- packages/ibm-products/src/components/InterstitialScreen/_interstitial-screen.scss
Bugs found / adjustments while adding the component to V2
- Fixed a comment to be a little more readable
- Added component description
- Added blockClass to bring pairity with V2 version
- Added css rule to keep paging in the carousel in line
- Prevent the close on click outside of the modal
> fix(InterstitialScreen): bugfix/changes from adding component

- cspell.json
- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridContent.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useShouldDisableButtons.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/utils.js
- packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.js
- packages/ibm-products/src/components/Datagrid/useFiltering.js
- packages/ibm-products/src/components/Datagrid/utils/filterPropsForTesting.js
- packages/ibm-products/src/components/FilterSummary/FilterSummary.js
- packages/ibm-products/src/components/FilterSummary/FilterSummary.test.js
Contributes to #3942 
Increases test coverage to at least 80% for Datagrid related filtering files/components.
```
cspell.json
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useShouldDisableButtons.js
packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/utils.js
packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.j …
```
> test(Datagrid): increase filtering test coverage (v1)

- scripts/example-gallery-builder/update-example/index.js
- scripts/example-gallery-builder/update-example/templates-react-16/package.json
- scripts/example-gallery-builder/update-example/templates-react-17/package.json
- scripts/example-gallery-builder/update-example/templates/package.json
Changes how the gallery package.json files are augmented.
The three template package.json file and the scripts/example-gallery-builder/update-example/index.js
Ran the script.
> fix: gallery update

- packages/ibm-products/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.js
- packages/ibm-products/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.js
- packages/ibm-products/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.js
- packages/ibm-products/src/components/EmptyStates/assets/ErrorIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NoDataIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NoTagsIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NotFoundIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/NotificationsIllustration.js
- packages/ibm-products/src/components/EmptyStates/assets/UnauthorizedIllustration.js
Fixes failed release.
`yarn lint`
> chore: lint empty states

- packages/core/.storybook/manager-head.html
- packages/core/package.json
Closes carbon-design-system/carbon#15657
Add compliance footer to Storybook
Reviewed in Storybook, CI checks pass
> feat: add compliance footer in v2 Storybook

- packages/core/.storybook/manager-head.html
Closes carbon-design-system/carbon#15638
Add compliance footer to Storybook
Reviewed in Storybook, CI checks pass
> feat: add compliance footer in v1 Storybook

- packages/core/story-structure.js
> fix: empty state v2 storybook fix

- examples/carbon-for-ibm-products/gallery-examples.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.js
- packages/ibm-products/src/components/Datagrid/useInfiniteScroll.js
- packages/ibm-products/src/components/Datagrid/useSelectRows.js
Contributes to #4234 
This is a v1 PR for the [fixes](https://github.com/carbon-design-system/ibm-products/pull/4216) that @prathapsimha contributed to the Datagrid, addressing some issues with SSR and Datagrid.
```
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.js
packages/ibm-products/src/components/Datagrid/useInfiniteScroll.js
```
Storybook
> fix(Datagrid): ssr datagrid fixes (v1)

- package.json
Contributes to #4043
the current `spellcheck` command is out of date and not working. this fixes it
> fix: update to spellchecker

- packages/core/src/welcome/Welcome.js
- packages/ibm-products/src/components/Coachmark/CoachmarkTagline.js
- packages/ibm-products/src/components/CoachmarkStack/CoachmarkStackHome.js
- packages/ibm-products/src/components/ExampleComponent/ExampleComponent.stories.js
- packages/ibm-products/src/components/ExampleComponent/ExampleComponent.test.js
- packages/ibm-products/src/components/FullPageError/preview-components/UiShell.js
- packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.js
- packages/ibm-products/src/components/TooltipTrigger/TooltipTrigger.stories.js
Changed imports from `'@carbon/icons-react'` to `'@carbon/react/icons'`
Visually inspected components in storybook
Ran tests locally
> fix: Updated all icon imports

- cspell.packages.txt
- packages/core/.storybook/manager-head.html
Contributes to carbon-design-system/carbon#15657
Closes carbon-design-system/carbon#15656
- Improve compliance footer use with Storybook.
- Add common.js and Tealium
Storybook, cspell
Verified in browser
> chore: fix compliance footer and add common.js

- packages/ibm-products-community/package.json
> fix: update publish config in community package to public

- packages/ibm-products/src/components/AboutModal/AboutModal.tsx
- packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js
Contributes to #4254 
Adds typescript support to AboutModal
```
packages/ibm-products/src/components/AboutModal/AboutModal.js -> packages/ibm-products/src/components/AboutModal/AboutModal.tsx
```
> feat(AboutModal): add typescript types

- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridEmptyBody.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridHeaderRow.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRefBody.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSimpleBody.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.js
> fix: remove false role from datagrid

- packages/ibm-products-styles/src/components/Datagrid/styles/_datagrid.scss
- packages/ibm-products-styles/src/components/Datagrid/styles/_useStickyColumn.scss
- packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.stories.js
Contributes to #4338
Update the class to overwrite the data table class 
update Scss 
Using storybook
17-4eac-a7d3-6679ca7e0050)
> feat: the frozen column doesn't follow the hover color on DataGrid #4338

- packages/ibm-products/src/components/EditInPlace/EditInPlace.js
> fix: add aria label to edit in place

- packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js
> fix: datagrid select all toggle rows not disabled

- packages/ibm-products/src/components/Datagrid/Datagrid.stories.js
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js
> fix: removes disabled rows from select all v1

- packages/ibm-products/src/components/CreateModal/CreateModal.tsx
Contributes to #4258 
Adds TypeScript types to CreateModal component.
```
packages/ibm-products/src/components/CreateModal/CreateModal.tsx
```
Storybook
> refactor(CreateModal): convert to typescript

- packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/CustomizeColumnsTearsheet.js
> fix: remove sorting in custom column tearsheet v1

- packages/ibm-products/src/components/SidePanel/SidePanel.js
- packages/ibm-products/src/components/SidePanel/SidePanel.test.js
- packages/ibm-products/src/global/js/hooks/useFocus.js
Contributes to #4228 
Fix focus trap issue in side panel
Used `useFocus` hook
Storybook
> fix(sidepanel): resolve focus trap issue

- packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx
Contributes to #4498 
converted packages/ibm-products/src/components/EditInPlace/EditInPlace.js to packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx
packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx
> refactor(EditInPlace): add typescript types

- packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js
> fix: add datagrid stateReducer row prop check

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.tsx
Contributes to #4261 
Converted packages/ibm-products/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.js to packages/ibm-products/src/components/CreateTearsheetNarrow/CreateTearsheetNarrow.tsx
> refactor(CreateTearsheetNarrow): add typescript types

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products/src/components/HTTPErrors/HTTPError404/HTTPError404.tsx
Contributes to #4270 
converted packages/ibm-products/src/components/HTTPErrors/HTTPError404/HTTPError404.js to packages/ibm-products/src/components/HTTPErrors/HTTPError404/HTTPError404.tsx
> refactor(HTTPError404): add typescript types

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products/src/components/HTTPErrors/HTTPError403/HTTPError403.tsx
Contributes to #4269 
Converted packages/ibm-products/src/components/HTTPErrors/HTTPError403/HTTPError403.js to packages/ibm-products/src/components/HTTPErrors/HTTPError403/HTTPError403.tsx
> refactor(HTTPError403): add typescript types

- cspell.html.txt
- package.json
- packages/ibm-products-styles/src/components/Coachmark/_coachmark-tagline.scss
- packages/ibm-products-styles/src/components/Guidebanner/_guidebanner.scss
- packages/ibm-products-styles/src/components/InlineTip/_inline-tip.scss
- packages/ibm-products/src/components/Decorator/Decorator.mdx
- packages/ibm-products/src/components/DecoratorBase/DecoratorBase.mdx
- packages/ibm-products/src/components/DecoratorDualButton/DecoratorDualButton.mdx
- packages/ibm-products/src/components/DecoratorLink/DecoratorLink.mdx
- packages/ibm-products/src/components/DecoratorSingleButton/DecoratorSingleButton.mdx
- packages/ibm-products/src/components/Nav/Nav.js
- packages/ibm-products/src/components/Nav/Nav.stories.js
- packages/ibm-products/src/components/Nav/Nav.test.js
- packages/ibm-products/src/components/Nav/NavList.js
Closes #4804 
fixes remaining cspell issues and adds `--quiet` to the spellcheck script to make it easier to read
> fix: spellcheck fixes and quiet flag

- package.json
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContext/DataConfigs.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContext/DataTreeContext.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContext/Translations.js
- packages/ibm-products/src/components/ConditionBuilder/assets/SampleData.js
fixes a few spelling errors that weren't caught with cspell in conditions builder
> fix: spells

- packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.js
Contributes to #4465 
Fixed the working of includeStep on first step
> fix(CreateTearsheet): includeStep fix on first step

- packages/ibm-products/src/components/InterstitialScreenView/InterstitialScreenView.tsx
Contributes to #4485 
Converted packages/ibm-products/src/components/InterstitialScreenView/InterstitialScreenView.js to packages/ibm-products/src/components/InterstitialScreenView/InterstitialScreenView.tsx
> refactor(InterstitialScreenView): add typescript types

- packages/ibm-products-styles/src/components/Datagrid/styles/_useSortableColumns.scss
Contributes to #4954
update scss to add background color 
using storybook
Before 
After
> feat: fix sortable header transparent issue #4954

- packages/ibm-products/src/components/TruncatedList/TruncatedList.tsx
Contributes to #4291 
Converted packages/ibm-products/src/components/TruncatedList/TruncatedList.js to packages/ibm-products/src/components/TruncatedList/TruncatedList.tsx
> refactor(TruncatedList): add typescript types

- packages/ibm-products/src/components/InlineTip/InlineTipLink.tsx
> refactor(InlineTipLink): implement typescript types

- packages/ibm-products/src/components/Carousel/Carousel.tsx
- packages/ibm-products/src/components/Carousel/CarouselItem.tsx
Contributes to #4947
This PR converts `Carousel` and `CarouselItem` to TypeScript
this will also unblock related tickets https://github.com/carbon-design-system/ibm-products/issues/4492 https://github.com/carbon-design-system/ibm-products/issues/4490 and InterstitialScreen TS conversion (no ticket yet)
- TS interface
> feat(Carousel): convert to .tsx

- e2e/components/StatusIcon/StatusIcon-test.avt.e2e.js
Contributes to #5060 
Created the file `e2e/components/StatusIcon/StatusIcon-test.avt.e2e.js`.
`yarn avt`
> test(StatusIcon): add default state AVT check

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products-styles/src/components/_index-released-only-with-carbon.scss
- packages/ibm-products-styles/src/components/_index-released-only.scss
- packages/ibm-products/carbon.yml
- packages/ibm-products/src/global/js/package-settings.js
Closes #5137 
This PR releases the `Checklist` component as stable.
- Added checklist styles to release only scss files
- Updated styles snapshot (`yarn test:c4p:snapshot`)
- Updated `package-settings.js`
- Added entry in `carbon.yml`
> feat(Checklist): release as stable

- e2e/components/EditInPlace/EditInPlace-test.avt.e2e.js
Closes #5009
Created e2e/components/EditInPlace/EditInPlace-test.avt.e2e.js
`yarn avt`
> test(EditInPlace): default state avt check

- e2e/components/Checklist/Checklist-test.avt.e2e.js
Closes #5061 
Created `e2e/components/Checklist/Checklist-test.avt.e2e.js`
`yarn avt`
> test(Checklist): add default state avt test

- e2e/components/UserProfileImage/UserProfileImage-test.avt.e2e.js
Contributes to #5078 
Created `e2e/components/UserProfileImage/UserProfileImage-test.avt.e2e.js` file
`yarn avt`
> test(UserProfileImage): add default state AVT check

- cspell.json
- e2e/components/UnauthorizedEmptyState/UnauthorizedEmptyState-test.avt.e2e.js
Contributes to #5074 
Created file: `e2e/components/UnauthorizedEmptyState/UnauthorizedEmptyState-test.avt.e2e.js`
`yarn avt`
> test(UnauthorizedEmptyState): add default state AVT check

- e2e/components/EmptyState/EmptyState-test.avt.e2e.js
Contributes to #4665 
Created `e2e/components/EmptyState/EmptyState-test.avt.e2e.js`
`yarn avt`
> test(EmptyState): add default state AVT check

- packages/ibm-products/src/components/CoachmarkFixed/CoachmarkFixed.tsx
Contributes to #4494
This PR converts `CoachmarkFixed` to TypeScript.
- TS interface
> feat(CoachmarkFixed): convert to .tsx

- .github/PULL_REQUEST_TEMPLATE.md
Updates the PR template we have so that it can close issues, as opposed to the current verbiage we have of `Contributes to`.
> chore: update pr template to close issue

- .github/ISSUE_TEMPLATE/accessibility-issue.yaml
Add the triage status label to the a11y template
> chore(a11y-template): add need triage status label

- e2e/components/Tearsheet/Tearsheet-test.avt.e2e.js
- packages/ibm-products/src/components/Tearsheet/Tearsheet.stories.jsx
Closes #4672 
Add default AVT testing to `Tearsheet` component.
`yarn avt`
> test(tearsheet): add default avt test

- e2e/components/DelimitedList/DelimitedList-test.avt.e2e.js
Closes #5209
Created e2e/components/DelimitedList/DelimitedList-test.avt.e2e.js
> test(DelimitedList): add default state AVT test

- e2e/components/DescriptionList/DescriptionList-test.avt.e2e.js
Closes #5210 
Created e2e/components/DescriptionList/DescriptionList-test.avt.e2e.js
> test(DescriptionList): add default state AVT test

- e2e/components/EmptyState/EmptyStateV2-test.avt.e2e.js
Closes #5214 
Created e2e/components/EmptyState/EmptyStateV2-test.avt.e2e.js
> test(EmptyStateV2): add default state AVT test

- e2e/components/Decorator/Decorator-test.avt.e2e.js
Closes #5208 
Created e2e/components/Decorator/Decorator-test.avt.e2e.js
> test(Decorator): add default state AVT test

- e2e/components/EditInPlace/EditInPlace-test.avt.e2e.js
- e2e/components/EditTearsheet/EditTearsheetForm-test.avt.e2e.js
Closes #5213 
Created e2e/components/EditTearsheet/EditTearsheetForm-test.avt.e2e.js
> test(EditTearsheetForm): add default state AVT check

- packages/ibm-products-styles/src/components/ConditionBuilder/styles/_conditionBuilderCondition.scss
- packages/ibm-products-styles/src/components/ConditionBuilder/styles/_conditionBuilderItem.scss
- packages/ibm-products/src/components/ConditionBuilder/ConditionBlock/ConditionBlock.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderAdd/ConditionBuilderAdd.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderButton/ConditionBuilderButton.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItem.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemDate/ConditionBuilderItemDate.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemNumber/ConditionBuilderItemNumber.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemOption/ConditionBuilderItemOption.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemText/ConditionBuilderItemText.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemTime/ConditionBuilderItemTime.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionConnector/ConditionConnector.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionGroupBuilder/ConditionGroupBuilder.js
- packages/ibm-products/src/components/ConditionBuilder/utils/checkForHoldingKey.js
- packages/ibm-products/src/components/ConditionBuilder/utils/handleKeyboardEvents.js
- packages/ibm-products/src/components/ConditionBuilder/utils/util.js
Contributes to #4577 
Keyboard accessibility implementation for sentence variant
Listened to keydown event and handled the keyboard navigation based on [W3C](https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/layout-grids/) guidelines
Locally
> feat(conditionBuilder): keyboard accessibility for sentence variant

- e2e/components/StatusIndicator/StatusIndicator-test.avt.e2e.js
- e2e/components/StatusIndicator/StatusIndicatorStep-test.avt.e2e.js
Closes #5221 , #5223
Created e2e/components/StatusIndicator/StatusIndicator-test.avt.e2e.js , e2e/components/StatusIndicator/StatusIndicatorStep-test.avt.e2e.js
e2e/components/StatusIndicator/StatusIndicator-test.avt.e2e.js 
e2e/components/StatusIndicator/StatusIndicatorStep-test.avt.e2e.js
> test(StatusIndicator): add default state AVT check

- e2e/components/EditAndUpdate/EditFullPage-test.avt.e2e.js
Closes #5211 
Created e2e/components/EditAndUpdate/EditFullPage-test.avt.e2e.js
> test(EditFullPage): add default state AVT check

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/sync-commit.yml
- config/storybook-addon-carbon-theme/README.md
- packages/ibm-products/src/global/js/utils/story-helper.js
- scripts/example-gallery-builder/gallery-config.js
- scripts/example-gallery-builder/index.js
Updates workflow files to use new `v1` branch name.
```
.github/workflows/codeql.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/sync-commit.yml
config/storybook-addon-carbon-theme/README.md
packages/ibm-products/src/global/js/utils/story-helper.js
scripts/example-gallery-builder/gallery-config.js
scripts/example-gallery-builder/index.js
```
This PR 😄
> fix: update v1 branch name across workflow files

- e2e/components/Toolbar/Toolbar-test.avt.e2e.js
Closes [#5219](https://github.com/carbon-design-system/ibm-products/issues/5219)
add e2e test for `Toolbar`
`yarn run avt`
> test(Toolbar): add default state AVT test

- packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.tsx
- packages/ibm-products/src/components/ProductiveCard/ProductiveCard.tsx
Closes #4505 
Add Typescript types to ProductiveCard
file extension
TS interface
> refactor(ProductiveCard): add Typescript types to ProductiveCard

- e2e/components/PageHeader/PageHeader-test.avt.e2e.js
Closes #5003
add e2e test for `PageHeader`
`yarn run avt`
> test(PageHeader): add default state avt test

- packages/ibm-products/src/components/Datagrid/types/index.ts
- packages/ibm-products/src/components/Datagrid/useInfiniteScroll.ts
Closes #5177 
`packages/ibm-products/src/components/Datagrid/useInfiniteScroll.ts`
Storybook
`yarn test`
> refactor(useInfiniteScroll): implement typescript types

- packages/ibm-products/src/components/Datagrid/types/index.ts
- packages/ibm-products/src/components/Datagrid/useSortableColumns.tsx
Closes #5182 
`packages/ibm-products/src/components/Datagrid/useSortableColumns.tsx`
Storybook
`yarn test`
> refactor(useSortableColumns): implement types

- packages/ibm-products/src/components/Datagrid/useSelectAllToggle.tsx
Closes #5190 
Converted `packages/ibm-products/src/components/Datagrid/useSelectAllToggle.js` to `packages/ibm-products/src/components/Datagrid/useSelectAllToggle.tsx`
> refactor(useSelectAllToggle): add typescript types

- packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js
Closes #
https://github.com/carbon-design-system/ibm-products/issues/5427
Add validator so when we leave cell we can determine if we want the change to apply or not. 
Story book
https://github.com/carbon-design-system/ibm-products/assets/10100397/53974074-8181-4857-b33c-59883d72a146
> fix(Datagrid): cell persistency issue fixed with validator

- package.json
- yarn.lock
Closes #5455 
Includes fixes for Mend issue, adding `ws` to resolutions resolves this.
`package.json`
`yarn.lock`
Checks in this PR should all pass
> chore: address mend issue

- packages/ibm-products/src/components/DataSpreadsheet/DataSpreadsheet.tsx
Closes #5526 
Fix condition check, see issue videos on why this condition check changed
Story book, original use case still works. Won't know absolute fix until next version release since issue seems to be coming through due to how the importing of the component is happening.
> fix(dataspreadsheet): Change condition check (fix regression)

- packages/core/.storybook/main.js
- packages/core/package.json
- yarn.lock
Closes #5414 
look at storybook
> chore: add a11y tab to storybook

- e2e/components/Nav/Nav-test.avt.e2e.js
- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products/src/components/HTTPErrors/HTTPError403/HTTPError403.stories.jsx
- packages/ibm-products/src/components/HTTPErrors/HTTPError403/HTTPError403.tsx
- packages/ibm-products/src/components/HTTPErrors/HTTPError404/HTTPError404.stories.jsx
- packages/ibm-products/src/components/HTTPErrors/HTTPError404/HTTPError404.tsx
- packages/ibm-products/src/components/HTTPErrors/HTTPErrorOther/HTTPErrorOther.stories.jsx
- packages/ibm-products/src/components/HTTPErrors/HTTPErrorOther/HTTPErrorOther.tsx
- packages/ibm-products/src/components/HTTPErrors/HTTPErrors.test.js
- packages/ibm-products/src/components/HTTPErrors/_storybook-styles.scss
Closes #4083 
added deprecation notice and annotation
packages/ibm-products/src/components/HTTPErrors/HTTPError403/HTTPError403.stories.jsx
packages/ibm-products/src/components/HTTPErrors/HTTPError403/HTTPError403.tsx
packages/ibm-products/src/components/HTTPErrors/HTTPError404/HTTPError404.stories.jsx
packages/ibm-products/src/components/HTTPErrors/HTTPError404/HTTPError404.tsx
packages/ibm-products/src/components/HTTPErrors/HTTPErrorOther/HTTPErrorOther.stories.jsx
packages/ibm-products/src/components/HTTPErrors/HTTPErrorOther/HTTPErrorOther.tsx
packages/ibm-products/src/components/HTTPErrors/_storybook-styles.scss
storybook
> chore(HTTPErrors): add depr notice and annotation

- e2e/components/SidePanel/SidePanel-test.avt.e2e.js
- packages/ibm-products/src/components/SidePanel/SidePanel.tsx
> chore: adds additional sidepanel avt tests

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products-styles/src/components/Datagrid/_datagrid.scss
Closes #5567 
By default the pagination should be taking the same color as table, so I have removed the extra code for overriding the background color for pagination
> fix(Datagrid): pagination color fix

- packages/ibm-products-styles/src/components/ConditionBuilder/_condition-builder.scss
- packages/ibm-products-styles/src/components/ConditionBuilder/styles/_conditionBuilderItem.scss
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderAdd/ConditionBuilderAdd.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemNumber/ConditionBuilderItemNumber.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemText/ConditionBuilderItemText.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItemTime/ConditionBuilderItemTime.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionGroupBuilder/ConditionGroupBuilder.js
- packages/ibm-products/src/components/ConditionBuilder/utils/handleKeyboardEvents.js
- packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.jsx
Contributes #4916
- Handle keyboard navigation for tree variant
- Handle focus for close icon on removal of conditions
Local storybook
> feat(ConditionBuilder): handle keyboard navigation for tree variant

- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.stories.jsx
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContext/translationObject.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionGroupBuilder/ConditionGroupBuilder.js
- packages/ibm-products/src/components/ConditionBuilder/assets/sampleInput.js
- packages/ibm-products/src/components/ConditionBuilder/utils/handleKeyboardEvents.js
- packages/ibm-products/src/components/ConditionBuilder/utils/util.js
Contributes #5494 ,#4916
- Added test cases for sentence variant
- Added test cases for tree  variant
- Changed _Add_ _Condition_ label to sentence case
- Code refining in `ConditionBuilderContent.js`
- Close button focus issue
- Pending to commit: testcases for keyboard navigation
storybook, test coverage report
> feat(ConditionBuilder): adding test cases and issue fixes

- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js
Closes #5494 
test case for keyboard accessibility
storybook, test coverage report
> feat(conditionBuilder): unit test cases for keyboard navigation

- packages/ibm-products-styles/src/components/ConditionBuilder/_condition-builder.scss
- packages/ibm-products-styles/src/components/ConditionBuilder/styles/_conditionBuilderCondition.scss
- packages/ibm-products-styles/src/components/ConditionBuilder/styles/_conditionBuilderItem.scss
- packages/ibm-products/src/components/ConditionBuilder/ConditionBlock/ConditionBlock.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderAdd/ConditionBuilderAdd.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderButton/ConditionBuilderButton.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderConnector/ConditionConnector.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContent/ConditionBuilderContent.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderContext/translationObject.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItem.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionGroupBuilder/ConditionGroupBuilder.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionPreview/ConditionPreview.js
- packages/ibm-products/src/components/ConditionBuilder/utils/handleKeyboardEvents.js
Contributes #5706, #5739, #5740, #5748, #5749, #5752, #5751
Design review changes from Tomer
storybook
> feat(ConditionBuilder): design review changes 1

- config/jest-config-ibm-cloud-cognitive/CHANGELOG.md
- config/jest-config-ibm-cloud-cognitive/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/ibm-products-community/CHANGELOG.md
- packages/ibm-products-community/package.json
- packages/ibm-products-styles/CHANGELOG.md
- packages/ibm-products-styles/package.json
- packages/ibm-products/CHANGELOG.md
- packages/ibm-products/package.json
- yarn.lock
Updates main branch with changelog and version bumps in release branch from code freeze
> chore(release): v2.47.0-rc.0

- packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js
Closes #5834 
fixed string filtering logic
packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js
storybook
> fix(Datagrid): column custimisation search filter truncation

- config/jest-config-ibm-cloud-cognitive/CHANGELOG.md
- config/jest-config-ibm-cloud-cognitive/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/ibm-products-community/CHANGELOG.md
- packages/ibm-products-community/package.json
- packages/ibm-products-styles/CHANGELOG.md
- packages/ibm-products-styles/package.json
- packages/ibm-products/CHANGELOG.md
- packages/ibm-products/package.json
- yarn.lock
Automated release PR for v2.47.0
**Checklist**
> chore(release): v2.47.0

- packages/ibm-products-styles/src/components/ConditionBuilder/styles/_conditionBuilderItem.scss
Closes #5835
restructured the css styles that caused warning
local
> fix(conditionBuilder): _conditionBuilderItem.scss causing sass warnings

- .github/workflows/stale.yml
Closes #5913 
This PR updates the time stalebot takes to close out stale issues and also updates the frequency this workflow is run.
```
.github/workflows/stale.yml
```
> chore: update stalebot config

- e2e/components/APIKeyModal/APIKeyModal-test.avt.e2e.js
- e2e/components/AboutModal/AboutModal-test.avt.e2e.js
- e2e/components/ExportModal/ExportModal-test.avt.e2e.js
- e2e/components/FullPageError/FullPageError-test.avt.e2e.js
- e2e/components/HTTPError403/HTTPError403-test.avt.e2e.js
- e2e/components/HTTPError404/HTTPError404-test.avt.e2e.js
- e2e/components/HTTPErrorOther/HTTPErrorOther-test.avt.e2e.js
- e2e/components/Saving/Saving-test.avt.e2e.js
- e2e/components/Toolbar/Toolbar-test.avt.e2e.js
- packages/core/.storybook/preview.js
- packages/ibm-products/src/components/APIKeyModal/APIKeyModal.stories.jsx
- packages/ibm-products/src/components/AboutModal/AboutModal.stories.jsx
- packages/ibm-products/src/components/ExportModal/ExportModal.stories.jsx
- packages/ibm-products/src/components/FullPageError/FullPageError.stories.jsx
- packages/ibm-products/src/components/HTTPErrors/HTTPError403/HTTPError403.stories.jsx
- packages/ibm-products/src/components/HTTPErrors/HTTPError404/HTTPError404.stories.jsx
- packages/ibm-products/src/components/HTTPErrors/HTTPErrorOther/HTTPErrorOther.stories.jsx
- packages/ibm-products/src/components/Saving/Saving.stories.jsx
- packages/ibm-products/src/components/Toolbar/Toolbar.stories.jsx
Closes #5827
[Storybook] Organize component and patterns based on new IA #5827
local storybook
> chore: storybook Organize component and patterns based on new IA

- .github/workflows/stale.yml
Contributes to #5913
We updated the timing but missed the stalebot message in #5914. 🙈 
Update the stalebot message to reflect the updated timing.
> chore: update stalebot message

- docs/guides/publishing-releases.md
Closes #
Update the release docs in hopes the steps are more clear - there's some repetition but I think it's more straight forward that way
- docs/guides/publishing-releases.md
> docs(release): update release docs

- docs/guides/publishing-releases.md
Add another step for manually change release label from `prerelease` to `latest`.
Add detail to `publishing-releases.md`
Markdown previews
> chore: update release docs

- e2e/components/AboutModal/AboutModal-test.avt.e2e.js
- packages/ibm-products/src/components/AboutModal/AboutModal.stories.jsx
- packages/ibm-products/src/components/AboutModal/AboutModal.tsx
Closes #4209 
Handling focus using the `useFocus` hook.
1. Implemented `useFocus()` hook
2. Feature flag `enable-experimental-focus-wrap-without-sentinels`
```
<FeatureFlags
flags={{
'enable-experimental-focus-wrap-without-sentinels': true,
}}
>
```
3. Implemented **AVT** test
1. `yarn avt`
2. `yarn test`
3. Storybook
> fix(AboutModal): implement useFocus()

- packages/ibm-products/src/components/Datagrid/Datagrid.stories.jsx
- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.tsx
- packages/ibm-products/src/components/Datagrid/Datagrid/addons/stateReducer.js
Closes #5898 
this pr adds the intended behaviour to the component.
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSelectAll.tsx
storybook, checked locally combining `batch actions` and `pagination` story
> fix(Datagrid): select all checkbox to select current page

- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js
- packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js
Includes the fix for https://github.com/carbon-design-system/ibm-products/issues/5995 as a patch for `2.49.1`.
> fix(Datagrid): return null for older react versions, patch release changes for `2.49.1`

- packages/ibm-products/src/components/ExportModal/ExportModal.tsx
Closes #6020 
Status message has been updated to convey communication effectively to screen reader users.
> fix(ExportModal): update status message

- config/stylelint-config-ibm-products/package.json
Follow up to #6220 
```
config/stylelint-config-ibm-products/package.json
```
> chore: bump stylelint-config

- e2e/components/CreateFlows/CreateTearsheet-test.avt.e2e.js
- packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.test.js
- packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx
Closes #6164 
Make sure to focus the next element if the specific element is not available
Storybook
> fix(Tearsheet): resolve focus issue

- package.json
Fix formatting issues, preventing release action from running as expected.
`package.json`
N/A
> chore: fix formatting issues

- packages/ibm-products/src/components/EmptyStates/EmptyState.tsx
- packages/ibm-products/src/components/EmptyStates/EmptyStateV2.tsx
- packages/ibm-products/src/components/EmptyStates/ErrorEmptyState/ErrorEmptyState.tsx
- packages/ibm-products/src/components/EmptyStates/ErrorEmptyState/index.ts
- packages/ibm-products/src/components/EmptyStates/NoDataEmptyState/NoDataEmptyState.tsx
- packages/ibm-products/src/components/EmptyStates/NoDataEmptyState/index.ts
- packages/ibm-products/src/components/EmptyStates/NoTagsEmptyState/NoTagsEmptyState.tsx
- packages/ibm-products/src/components/EmptyStates/NoTagsEmptyState/index.ts
- packages/ibm-products/src/components/EmptyStates/NotFoundEmptyState/NotFoundEmptyState.tsx
- packages/ibm-products/src/components/EmptyStates/NotFoundEmptyState/index.ts
- packages/ibm-products/src/components/EmptyStates/NotificationsEmptyState/NotificationsEmptyState.tsx
- packages/ibm-products/src/components/EmptyStates/NotificationsEmptyState/index.ts
- packages/ibm-products/src/components/EmptyStates/UnauthorizedEmptyState/UnauthorizedEmptyState.tsx
- packages/ibm-products/src/components/EmptyStates/UnauthorizedEmptyState/index.ts
- packages/ibm-products/src/components/EmptyStates/index.ts
Closes #6046 
This PR exports all types in Emptystates
Export types, changed all index.js -> index.ts
> feat(empty-states): exports types

- packages/ibm-products-styles/src/components/UserAvatar/_carbon-imports.scss
- packages/ibm-products-styles/src/components/UserAvatar/_user-avatar.scss
- packages/ibm-products/src/components/UserAvatar/UserAvatar.mdx
- packages/ibm-products/src/components/UserAvatar/UserAvatar.tsx
Closes #6168
Addressed released review fixes.
Also regarding "focus ring" I discussed with Marion Hekeler(@marion-bruells) she mentioned it should work only on tabbing.
packages/ibm-products/src/components/UserAvatar/UserAvatar.tsx
packages/ibm-products-styles/src/components/UserAvatar/_user-avatar.scss
packages/ibm-products/src/components/UserAvatar/UserAvatar.mdx
packages/ibm-products-styles/src/components/UserAvatar/_carbon-imports.scss
> fix(UserAvatar): release review fixes

- packages/ibm-products/src/components/ActionBar/ActionBar.tsx
- packages/ibm-products/src/components/PageHeader/PageHeader.tsx
Closes #5946 
Change import statement
Storybook
`yarn test`
> fix(PageHeader): change type import

- e2e/components/Datagrid/Datagrid-test.avt.e2e.js
- packages/ibm-products/src/components/Datagrid/Datagrid.docs-page.js
- packages/ibm-products/src/components/Datagrid/Datagrid.stories.jsx
- packages/ibm-products/src/components/Datagrid/Datagrid.test.js
- packages/ibm-products/src/components/Datagrid/Datagrid/Datagrid.tsx
- packages/ibm-products/src/components/Datagrid/Extensions/AiLabel/AiLabel.stories.jsx
- packages/ibm-products/src/components/Datagrid/Extensions/ClickableRow/ClickableRow.stories.jsx
- packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.jsx
- packages/ibm-products/src/components/Datagrid/Extensions/EditableCell/EditableCell.stories.jsx
- packages/ibm-products/src/components/Datagrid/Extensions/ExpandableRow/ExpandableRow.stories.jsx
- packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Flyout.stories.jsx
- packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.jsx
- packages/ibm-products/src/components/Datagrid/Extensions/NestedRows/NestedRows.stories.jsx
- packages/ibm-products/src/components/Datagrid/Extensions/RowActionButtons/RowActionButtons.stories.jsx
- packages/ibm-products/src/components/Datagrid/Extensions/RowHeightSettings/RowHeightSettings.stories.jsx
- packages/ibm-products/src/global/js/utils/StoryDocsPage.js
- packages/ibm-products/src/global/js/utils/test-helper.js
> chore: datagrid deprecation notice

- packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.tsx
Closes #6443 
onClose is already triggered by onClose of compose modal.
local
> fix(InterstitialScreen): onclose callback triggered twice

- .github/workflows/ci.yml
- .github/workflows/update-example-gallery.yml
> chore: update actions/cache for workflows

- packages/ibm-products/src/components/StatusIcon/StatusIcon.test.js
Closes #6651
Code coverage is now 100%.
```
packages/ibm-products/src/components/StatusIcon/StatusIcon.test.js
```
```
yarn coverage statusicon
```
> chore(StatusIcon): update code coverage

- package.json
adds a fix to auto fix stylelint errors
> chore: add fix flag to stylelint

- packages/ibm-products-styles/src/components/NotificationsPanel/_notifications-panel.scss
- packages/ibm-products-styles/src/components/WebTerminal/_web-terminal.scss
- packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.tsx
- packages/ibm-products/src/components/WebTerminal/WebTerminal.tsx
Closes #6872 
moves the styles to scss and removed any effects applying styles.
also used motion tokens as per carbon motion standards
notifications panel, web terminal
storybook
> fix: glitches on open

- packages/ibm-products-web-components/src/components/user-avatar/user-avatar.scss
- packages/ibm-products-web-components/src/components/user-avatar/user-avatar.stories.ts
- packages/ibm-products-web-components/src/components/user-avatar/user-avatar.ts
Closes #6790 
Now the user avatar background color will dynamically change according to the storybook theme.
packages/ibm-products-web-components/src/components/user-avatar/user-avatar.ts
> feat(userAvatar): backgroundcolor change based on theme

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products-styles/src/components/UserAvatar/_user-avatar.scss
Closes #6944 
As per the [PR discussion](https://github.com/carbon-design-system/ibm-products/pull/6918) need to remove `data-carbon-theme` related styles from UserAvatar.
> fix(useravatar): remove data-carbon-theme related style

- actions/add-review-labels/package.json
- package.json
- yarn.lock
> fix: add @octokit security resolutions

- scripts/get-changelog.js
Closes #6994 
Add Web Component package updates to changelog
`get-changelog.js`
```
node ./scripts/get-changelog.js -f v2.60.0 -t v2.61.0-rc.0 >> changelog.txt
```
Which generated ... (`@carbon/ibm-products` and `@carbon/ibm-products-styles` changelogs omitted).
```
- feat(userAvatar): backgroundcolor change based on theme (#6918)
- feat(useravatar): create useravatar web component (#6823)
- feat(storybook): add text direction toolbar item (#6855)
- fix(useravatar): variable change (#6856)
- build(deps): update Carbon 11 compatible versions to latest (#6912)
```
> chore: add web components to changelog

- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilderItem/ConditionBuilderItem.tsx
Closes #7071 
correct tooltip for custom operator
storybook
> fix(ConditionBuilder): correct tooltip for custom operator

- packages/ibm-products-web-components/src/components/tearsheet/tearsheet.stories.ts
- packages/ibm-products-web-components/src/components/tearsheet/tearsheet.test.ts
- packages/ibm-products-web-components/src/components/tearsheet/utils.ts
Closes #7222
Created a util.ts file to store all reusable functions for Storybook.
packages/ibm-products-web-components/src/components/tearsheet/utils.ts
packages/ibm-products-web-components/src/components/tearsheet/tearsheet.stories.ts
packages/ibm-products-web-components/src/components/tearsheet/tearsheet.test.ts
> fix(tearsheet): added utils.ts

- .github/workflows/ci.yml
Closes #7116 
need to confirm this works before disabling in netlify
> chore: add vrt script back into ci.yml

- packages/ibm-products-styles/src/components/PageHeader/_page-header.scss
Closes #6575 
Removed unused styles from _page-header.scss
packages/ibm-products-styles/src/components/PageHeader/_page-header.scss
Storybook
> fix(pageheader): remove unused styles

- packages/ibm-products-styles/src/__tests__/__snapshots__/styles.test.js.snap
- packages/ibm-products/src/components/Tearsheet/TearsheetNarrow.tsx
Closes #7484 
`actions` prop for the NarrowTearsheet didn't support "label" fieldl
Modified the actions prop to match the Tearsheet actions prop, which was `TearsheetAction[]`.
Storybook, tests, ran snapshot
> refactor(TearsheetNarrow): modified `actions` prop on narrow tearsheet to match tearsheet.

- .github/workflows/release-canary.yml
adds some additional environment variables to the canary release script to try to help debug ongoing issues
https://docs.npmjs.com/generating-provenance-statements
> fix: try updating canary release environment variables

- packages/ibm-products/src/components/ActionBar/ActionBarItem.test.js
- packages/ibm-products/src/components/AddSelect/AddSelectBody.test.js
- packages/ibm-products/src/components/AddSelect/AddSelectBreadcrumbs.test.js
- packages/ibm-products/src/components/BreadcrumbWithOverflow/BreadcrumbWithOverflow.test.js
- packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js
- packages/ibm-products/src/components/CreateFullPage/CreateFullPage.test.js
- packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx
- packages/ibm-products/src/components/CreateTearsheet/CreateTearsheet.test.js
- packages/ibm-products/src/components/Decorator/Decorator.test.js
- packages/ibm-products/src/components/DecoratorBase/DecoratorBase.test.js
- packages/ibm-products/src/components/DecoratorDualButton/DecoratorDualButton.test.js
- packages/ibm-products/src/components/DecoratorLink/DecoratorLink.test.js
- packages/ibm-products/src/components/DecoratorSingleButton/DecoratorSingleButton.test.js
- packages/ibm-products/src/components/FilterPanel/FilterPanelAccordion/FilterPanelAccordion.test.js
- packages/ibm-products/src/components/FilterPanel/FilterPanelAccordionItem/FilterPanelAccordionItem.test.js
- packages/ibm-products/src/components/HTTPErrors/HTTPErrors.test.js
- packages/ibm-products/src/components/InterstitialScreen/InterstitialScreen.test.js
- packages/ibm-products/src/components/NotificationsPanel/NotificationsPanel.test.js
- packages/ibm-products/src/components/OptionsTile/OptionsTile.test.js
- packages/ibm-products/src/components/SidePanel/SidePanel.test.js
- packages/ibm-products/src/components/StatusIndicator/StatusIndicator.test.js
- packages/ibm-products/src/components/TagOverflow/TagOverflow.test.js
- packages/ibm-products/src/components/UserAvatar/UserAvatar.test.js
- packages/ibm-products/src/components/UserProfileImage/UserProfileImage.test.js
Closes #7426 , #7427
Added valid matcher for expect() in 23 test files 
Updated the test to check for the complete class name instead of a partial match using classList.contains. ( only found this in CreateFullPage.test.js)
Fixed the behaviour of CreateFullPage component, it was not working as expected when initialStep > StepLength  && initialStep<=0
packages/ibm-products/src/components/ActionBar/ActionBarItem.test.js
packages/ibm-products/src/components/AddSelect/AddSelectBody.test.js
packages/ibm-products/src/components/AddSelect/AddSelectBreadcrumbs.test.js
packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js
packages/ibm-products/src/components/CreateFullPage/CreateFullPage.test.js
packages/ibm-products/src/components/Decorator/Decorator.test.js …
> test: add valid matcher for expect()

- e2e/components/NotificationsPanel/NotificationsPanel-test.avt.e2e.js
Fixes avt test fail issue in Notification panel. Updating avt test added in https://github.com/carbon-design-system/ibm-products/pull/7707
> fix(notification pnale): avt test issue

- packages/ibm-products/src/components/PageHeader/next/PageHeader.stories.js
- packages/ibm-products/src/components/index.js
Exports new page header as `preview_PageHeader` as discussed during today's triage.
Component export
N/A
> fix(PageHeader): export as preview

- packages/ibm-products-web-components/package.json
- packages/ibm-products-web-components/telemetry.yml
- yarn.lock
These changes enable IBM Telemetry to collect usage data of the web components in the `carbon/ibm-products-web-components` package.
- added script in the web component package's package.json to update the telemtry.yml file
- updated the telemetry.yml file
- updated `@ibm/telemetry-js` dependency to `v1.10.0`
- updated `@ibm/telemetry-js-config-generator` dependency to `v2.1.0`
- manually tested new script
- [N/A] ~Updated documentation and storybook examples~
- [N/A] ~Wrote passing tests that cover this change~
- [N/A] ~Addressed any impact on accessibility (a11y)~
- [N/A] ~Tested for cross-browser consistency~
> feat(telemetry): add wc scope

- packages/ibm-products/src/components/Coachmark/next/Coachmark/CoachmarkBubble/CoachmarkBubble.tsx
Closes #8023 
Added of ref usage in CoachmarkBubble
> fix(CoachmarkBubble): usage of ref

- packages/ibm-products-web-components/src/components/checklist/checklist-group.ts
- packages/ibm-products-web-components/src/components/checklist/checklist-item.ts
- packages/ibm-products-web-components/src/components/checklist/checklist.scss
- packages/ibm-products-web-components/src/components/checklist/checklist.stories.ts
Part of #8133 
- Adds some of the missing styles in Checklist web component
- Updates checklist story to showcase all the 5 task statuses
Storybook
> fix(checklist): update styles

- .github/workflows/code-connect.yml
- packages/ibm-products-web-components/figma.config.json
- packages/ibm-products/figma.config.json
Closes #8386
Adds the configuration so that we can start picking up web component code connect work.
```
.github/workflows/code-connect.yml
packages/ibm-products-web-components/figma.config.json
packages/ibm-products/figma.config.json
```
> feat(code-connect): add web component code connect config setup
